OBJECTS = char2hol.o cjchar.o das2b.o fdfld.o gbfas.o gtfld.o gtprm.o\
gtrsp.o hol2char.o ia22h.o ia2hx.o ias2b.o ib2as.o\
ibin.o ichcm.o ichcm_ch.o ichmv.o ifams.o ifill.o ifill_ch.o iflch.o\
ih22a.o ihx2a.o ir2as.o iscn_ch.o iscnc.o iscns.o\
jchar.o mcoma.o pchar.o gtprm2.o ichmv_ch.o ras2b.o id2as.o

lnfch.a: $(OBJECTS)

include ../include.mk
