#!/bin/bash
set -e
#
if ! [ $(id -u) = 0 ]; then
   echo "This script must be run as root."
   exit 1
fi
#
echo "********************************************************************"
echo "*  This is the INSTALLATION script for a AUID account              *"
echo "********************************************************************"
echo "CAUTION: This script will automatically modify some of your directories."
echo "On /home, am existing user home directory will renamed to user.FSCOPY"
badans=true
while [ "$badans" = "true" ]
do
  echo -n "Enter exisiting user to update (return to exit): " 
  read ans
  case "$ans" in
    prog) echo "Can't update prog "
           ;;
    oper) echo "Can't update oper "
           ;;
    *)    if  [ x$ans = x ]; then
	    exit
          elif  [ -e /home/$ans.FSCOPY -o -L /home/$ans.FSCOPY ]; then
	    echo "/home/$ans.FSCOPY exisits, user apparently already updated"
	  elif ! [ -e /home/$ans -o -L /home/$ans ]; then
	    echo "User $ans does not have a directory on /home"
	  else
           badans=false
          fi
  esac
done
#
cd /home
mv $ans $ans.FSCOPY
#
cd /usr2/fs/st.default/auid
find . -print|cpio -pmdu /home/$ans
chown -R $ans.$ans /home/$ans
chmod -R u+rwx,go+r,go+x /usr2/oper
#
echo "Done."
