#!/usr/bin/perl
# Usage: popen_fix file

if ($#ARGV < 0) {
    print "\n  Usage: popen_fix files\n\n";
    print "    Changes procedues files with sy=popen '... 2>&1' to drop the final 2>&1.\n\n";
    print "    'files' are the files to be fixed\n\n";
    print "    The original files are renamed with a '.bak' extension\n\n";
    exit -1;
}


$float_pattern='([+-]?)(?=\d|\.\d)\d*(\.\d*)?';

FILE: foreach $name (@ARGV) {

    $bak = $name . ".bak";
    $out = $name;
    if (!-e $name) {
	die "Can't find $name Quitting.\n";
    }

# rename the original if we can and open the files

    if (-e $bak) {
	die "Backup-file $bak already exists, giving up.\n";
    }

    rename ($out,$bak) ||die "renaming $out to $bak failed: $!, giving up.\n";
 
    if(!open(BAK,$bak)) {
	print "Failed to open $bak: $!\n";
	if(!rename($bak,$out)) {
	    print "Unable to rename $bak to $out: $!\n";
	    die "Please fix whatever the problem is and rename it yourself.\n";
	} else {
	    die "I renamed $bak to $out for you.\n";
	}
    }
    
    if(!open(OUT,">" . $out)) {
	print "Failed to open $out: $!\n";
	if((!close(BAK)) || (!rename($bak,$out))) { 
	    print "Unable to rename $bak to $out: $!\n";
	    die "Please fix whatever the problem is and rename it yourself.\n";
	} else {
	    die "I renamed $bak to $out for you.\n";
	}
    }


#process

    $line=0;
    $change=0;
    while(<BAK>) {
	$line++;
# we only fix sy=go commands, even commented out
	if(!/^[" ]*sy= *popen '.* 2>&1'/i) {
	    print OUT;
	    next;
	}
	$change=1;
	chomp;
#these patterns will fix most common cases
	if(/^([" ]*sy= *popen '.*) 2>&1('.*)$/i) {
	    print OUT "$1$2\n";
	} 
    }
    $rename=0;
    if(!close(OUT)) {
	$rename=1;
	print "Warning: Unable to close to $out: $!\n";
    }
    if(!close(BAK)) {
	$rename=1;
	print "Warning: Unable to close to $bak: $!\n";
    }

    if($rename || $change == 0) {
	if(!rename($bak,$out)) { 
	    print "Warning: Unable to rename '$bak' to '$out': $!\n";
	    if($rename) {
		print "Warning: Please fix whatever the problem is and rename it yourself,\n";
		print "Warning: probably using 'mv $bak $out'\n";
	    } else {
		print "Warning: It appears that $out did not need any changes,\n";
		print "Warning: but to be safe you should probably \"";
		print "Warning: use 'mv $bak $out'\n";
	    }
	} elsif($rename) {
	    print "Warning: I renamed '$bak' to '$out' for you.\n";

	}
    }
}
