OBJECTS = test.o frmaux4.o
#
F77= gf77
FFLAGS = -c -g
LIBES = ../fslb/fslb.a ../lnfch/lnfch.a ../newlb/newlb.a\
../flib/flib.a ../fclib/fclib.a\
../clib/clib.a ../fmpsee/fmpsee.a ../rtelb/rtelb.a -lrtx
#
../bin/test: $(OBJECTS)
	gf77 -g -o test $(OBJECTS) $(LIBES)
