LIBS = ../vis/vis.a ../clib/clib.a
OBJECTS= gnfit.o fit2.o fpoly.o  scaler.o unscaler.o inine.o incne.o \
dppco.o dppfa.o dppin.o dppsl.o ftau.o

LDLIBS += $(FLIBS)

../bin/gnfit: $(OBJECTS) $(LIBS)

include ../include.mk
