OBJECTS= get_buf.o put_buf.o read_fscom.o read_init.o put_buf_ch.o\
read_quikr.o run_prog.o setup_fscom.o wait_prog.o write_fscom.o\
write_init.o write_quikr.o clrcl.o wait_relt.o\
susp.o rmpar.o rn_take.o rn_put.o rn_test.o kbreak.o\
send_break.o clear_prog.o put_bufi.o get_arg.o\
suspend.o go_suspend.o

flib.a: $(OBJECTS)

include ../include.mk
