OBJECTS = setcl.o
LIBS = ../fslb/fslb.a ../lnfch/lnfch.a ../newlb/newlb.a\
../flib/flib.a ../fclib/fclib.a ../clib/clib.a ../poclb/poclb.a\
../clib/clib.a ../fmpsee/fmpsee.a ../rtelb/rtelb.a

LDLIBS += $(FLIBS)

../bin/setcl: $(OBJECTS) $(LIBS)

include ../include.mk
