C@GTFLD
      SUBROUTINE GTFLD(IAS,IC1,IC2,IFC,IEC)
C     SCAN A STRING FOR A SERIES OF CHARACTERS SEPARATED BY BLANKS
C
C   INPUT VARIABLES:
      integer*2 IAS(*)
      integer ic1,ic2
C       INPUT STRING WITH CHARACTERS
C     IC1 - FIRST CHARACTER TO USE IN IAS
C     NCH - NUMBER OF CHARACTERS IN IAS FOLLOWING IC1
C     IC2 - LAST CHARACTER IN IAS TO USE
C
C   OUTPUT VARIABLES:
      integer ifc,iec
C     IFC - FIRST NON-BLANK CHARACTER IN IAS
C     IEC - LAST NON-BLANK CHARACTER IN IAS
C
C   LOCAL VARIABLES:
      integer i,oblank
      data oblank/O'40'/
C
C
C     FIRST INITIALIZE
C
      IFC = 0
      IEC = 0
      IF (IC1.GT.IC2) RETURN
C
C     SCAN FOR THE FIRST NON-BLANK
C
      DO 100 I=IC1,IC2
        IF (JCHAR(IAS,I).NE.oblank) GOTO 101
100     CONTINUE
      RETURN
C       THERE ARE ONLY BLANKS
101   IFC = I
      IEC = I
      IF (IEC.LT.IC2) GOTO 190
      IC1 = IC2 + 1
      RETURN
C
C     NOW SCAN FOR THE NEXT BLANK
C
190   DO 200 I=IFC+1,IC2
        IF (JCHAR(IAS,I).EQ.oblank) GOTO 201
200   CONTINUE
      IEC = IC2
C       STRING ENDS WITH NON-BLANK
      IC1 = IC2 + 1
      RETURN
201   IEC = I-1
      IC1 = I
C       UPDATE FIRST CHARACTER NUMBER IN STRING
      RETURN
      END
