LIBS = ../rclco/rcl/rcl_cmd.o ../rclco/rcl/rcl_pkt.o ../rclco/rcl/rcl_sysn.o\
../rclco/rcl/rcl_util.o ../poclb/poclb.a ../clib/clib.a ../rtelb/rtelb.a 

OBJECTS = rclcn.o rclcn_das.o

../bin/rclcn: $(OBJECTS) $(LIBS)

include ../include.mk
