OBJECTS= cnvrt.o datan2z.o equn.o fln.o flt0.o gmodl.o\
gtchr.o gtdbl.o gtdc.o gtra.o gtrel.o igeta.o\
igtbn.o iptdc.o iptra.o jr2as.o kcrt.o keof.o\
kfild.o kfmp.o kgant.o kidnam.o kif.o kopn.o\
koutp.o kpant.o kread.o kreof.o kwrit.o refr.o\
sider.o po_put_i.o po_put_c.o fmpwrite2.o sider2.o\
equn2.o gtdbl.o jd2as.o fln1.o flt1.o igthx.o ihxw2as.o

polb.a: $(OBJECTS)

include ../include.mk
