LIBS = ../poclb/poclb.a ../clib/clib.a ../poclb/poclb.a ../rtelb/rtelb.a -lm
OBJECTS = rdtcn.o FFT.o rdbe_freqz.o rt_nonfinite.o rtGetInf.o rtGetNaN.o

../bin/rdtcn: $(OBJECTS) $(LIBS)

include ../include.mk
