//
// Copyright (c) 2020-2023 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= Converting to a 64-bit System
Version 1.10.0 - December 2023

//:hide-uri-scheme:
:sectnums:
:sectnumlevels: 4
:experimental:

:toc:
:toclevels: 4

:sectnums!:
== Document revision history

Click the *Details* toggle below to unhide/hide the history.

[%collapsible]
====

* 1.10.0 -- Reorganize to put reference copies in their own directory
first, them make working copies; minor cleanup
* 1.9.1 -- Add *NOTE* about not renaming _/usr2/log_
* 1.9 -- Remove extraneous `log-old` from `chmod a-w ...`
* 1.8 -- Improve customization of home directories; put Document revision history in a collapsible block
* 1.7 -- Note other formats for `_st-version_`
* 1.6 -- Transfer logs directly to a reference copy
* 1.5 -- Use _root_ on the old system to copy files if possible
* 1.4 -- Add revision history
* 1.3 -- Rewrite to include FSL11 and make useful for more situations
* 1.2 -- Add using ssh-keygen
* 1.1 -- Cleanup
* 1.0 -- Add unlongify TIP
* 0.8 -- Fix typos
* 0.7 -- Font improvements
* 0.6 -- Simplify 64-bit upgrade path
* 0.4 -- Simplify 64-bit upgrade path
* 0.3 -- Initial version

====

:sectnums:
== Introduction

This document covers converting to a 64-bit system architecture from
an existing FS _10.<x>_ installation on a 32-bit system. It is also
used as part of the upgrade path to go directly to a 64-bit system
while upgrading to FS _10.0_.

The approach here can also be used to transfer an existing 64-bit (or
32-bit) FS installation to a new system without changing OS
(including architecture) and FS version. For that case, in place of
the <<Install a 64-bit system>> step make sure you have the same OS
(including architecture) and FS version installed on your new system
as on your existing system and then omit the
<<Update station programs for 64-bit>> step.

If you are moving to a different OS, you may need to use a different
FS version and update your station files and software for the new OS
and FS version. For FSL11, a pointer to the instructions for this are
included in its installation guide and in the
<<Install a 64-bit system>> step below.

The process in this document assumes you will be installing to a new
system. This will allow you to set up the new system without
disturbing your operational system.

== Convert to using a 64-bit system

IMPORTANT: All operations, except where noted, are performed on the
new system.

Please follow the steps below.

=== Install a 64-bit system

Install a 64-bit (or 32-bit, but 64-bit is recommended) system on a
different (hopefully new) computer. We recommend FSL11, which is based
on Debian _Bullseye_ and tuned for FS use. The FSL11 installation
guide can be found at https://nvi-inc.github.io/fsl11/. That process
installs FS _10.2_. After that instead of the directions in the
current document, you should follow the directions in the appendix
<<../releases/10/2/10.2.adoc#_transferring_an_existing_fs_installation_to_fsl11,Transferring
an existing FS installation to FSL11>> of the
<<../releases/10/2/10.2.adoc#,FS 10.2 Update Notes>> document. Those
instructions include, by reference, a subset of the ones in the
current document.

NOTE: If you are following these directions as part of installing FS
_10.0_ on FSL10, that will still work, but we recommend using FS
_10.2_ on FSL11 instead.

You can install a non-FSL__x__ Linux distribution. However, we can't
provide as much support in that case. The FSL11 distribution is tuned
to provide a complete platform for running the FS. For other
distributions you may have to make adjustments for several things that
an FSL11 installation provides, including:

- which packages are installed
- required user accounts and groups
- backup methods

=== Login as root on the new system

Login as _root_ on the new system.

=== Rename default directories

NOTE: This step assumes you have installed a base FS, either along
with FSL11 or using your own methods. If the latter, and the normal
default FS directories were not created, you can skip this step.

. Rename the existing default station specific FS related directories
on the new system to get them out of the way:

      cd /usr2
      mv control   control.DEFAULT
      mv sched     sched.DEFAULT
      mv proc      proc.DEFAULT

. If you use the _/usr2/tle_files_ directory on your old system, you
should rename the one on the new system:

      cd /usr2
      mv tle_files tle_files.DEFAULT

. If your station software is in _/usr2/st-0.0.0_ on your old system,
you should rename the one on the new system:

      cd /usr2
      mv st-0.0.0  st-0.0.0.DEFAULT

NOTE: The _/usr2/log_ directory is not renamed since it will not be
replaced with a copy of the directory from the old system.

=== Create directory for reference copies

It can be useful to have a reference copy of certain parts of the old
system. In particular, you may want to preserve copies of the
operational directories: _control_, _log_, _proc_, and _sched_; the
last version of the station software; the home directories of _oper_
and _prog_; old reference copies from previous updates; it may also be
useful to preserve _/etc_. For this reason, the file transfer is
organized around making reference copies and then making new working
copies for items where that is appropriate. If you prefer, you can
skip making reference copies and copy the operational directories of
_control_, _log_, _proc_, and _sched_ directly to _/usr2_ on the new
system.

You can make a directory on _/usr2_ (usually the largest partition and
one with ample room) to hold the reference copies. This might be,
e.g., _/usr2/old_FSL9_, if your previous system was FSL9. You should
use whatever naming scheme is appropriate for your situation. The
current step and the following one use _/usr2/old_FSL9_ as an example.
You should substitute the appropriate directory for your system.

You can create the reference directory structure with:

  mkdir -p /usr2/old_FSL9/usr2

=== Transfer files

Your station specific FS related files can be transferred from the old
system using any convenient method. If both systems are on the network
this can be particularly easy. The following example sub-steps use
this approach. You should replace the `_old_` host name in the
examples with your old system's host name. These commands must be
executed as _root_, and except where noted, from the new system.

As an example, the sub-steps below use _/usr2/old_FSL9_ as the
directory to hold the files from your system. You should substitute
the appropriate directory for your system (see the previous step
(<<Create directory for reference copies>>).

TIP: If you want to copy-and-paste the example _scp_ commands below as
is (this is possible for most of them), you can add an alias `old` for
your old system in the _/etc/hosts_ file.

[TIP]
====

You may need to provide the appropriate password for each _scp_
command below. If so, you can simplify the process by copying your new
system's _root_ public SSH keys to the old machine _oper_ and _prog_
accounts with _ssh-copy-id_ first. If _root_ doesn't have an ID yet,
you will get an error like:

 /usr/bin/ssh-copy-id: ERROR: No identities found

In that case, you can generate a key with _ssh-keygen_
(leaving the passphrase empty is recommended) and try _ssh-copy-id_
again.

====

CAUTION: It is assumed that the new installation is on new hardware
with disks more than large enough to accommodate all the data being
transferred. However, if you installed the new Linux on old hardware
with small disks, there may be a space issue.

WARNING: The instructions below assume that the old system you are
using has a standard FS configuration in terms of symbolic links and
directories. If your system is different, you will need to adjust what
you do accordingly, but you may still find the outline of sub-steps
useful.

IMPORTANT: These instructions assume that you can login to the old
system as _root_ using _ssh_. Allowing this is a security risk and
should only be permitted temporarily for these command. If you are not
able to allow it, you can use the _oper_ and _prog_ (or other)
accounts as appropriate to transfer the files. In that case, there is
risk that some files may not be copied due to ownership/permission
issues. You may need to take other steps to copy those files.

. Transfer operational directories:

.. Transfer _control_, _log_, _proc_, and _sched_, from your `_old_`
system:

+

[subs="+quotes"]
....
cd /usr2/old_FSL9/usr2
scp -pqr _old_:/usr2/control .
scp -pqr _old_:/usr2/log .
scp -pqr _old_:/usr2/proc .
scp -pqr _old_:/usr2/sched .
....
+

NOTE: Your _log_ directory could be large and take a significant
amount of time to transfer.

.. Transfer _tle_files_:
+

If you use the _/usr2/tle_files_ directory on your `_old_` system, you
can also transfer it:

+

[subs="+quotes"]
....
cd /usr2/old_FSL9/usr2
scp -pqr _old_:/usr2/tle_files .
....

+

. Make "`starter`" working copies of the operational directories
(except _log_):

 cd /usr2
 cp -a old_FSL9/usr2/control .
 cp -a old_FSL9/usr2/proc .
 cp -a old_FSL9/usr2/sched .

+

and possibly:

 cd /usr2
 cp -a old_FSL9/usr2/tle_files .

. Fix the ownership/permissions of the working copies you made:

    /usr2/fs/misc/fix_perm
+
Answer `*y*` to confirm.
+

NOTE: If you don't have a _/usr2/tle_files_ directory, you will get a
message that there is no such directory. That is benign unless you
expect such a directory to be there.

. Transfer your station software directory (and make a working copy).
This is usually the target directory pointed to by the _/usr2/st_
symbolic link. On your old system, you can find its name with:

  ls -l /usr2/st
+

In the rest of this sub-step, the target `st-_version_` will be used.
You should replace `_version_` with your version string. For example,
use `_1.0.0_`, to make a target `_st-1.0.0_`. (You may need to adjust
these commands if you have a different format for `st-_version_`,
perhaps `_st-git_`.) If your target is `_st-0.0.0_` you should rename
the default on the new system first as described in the
<<Rename default directories>> step above.

+

All the sub-steps below are executed on the new system:

.. Copy the target from the `_old_` system to the new system:

+

[subs="+quotes"]
....
cd /usr2/old_FSL9/usr2
scp -pqr __old__:/usr2/st-_version_ .
....

.. Create a local working copy

+

[subs="+quotes"]
....
cd /usr2
cp -a old_FSL9/usr2/st-_version_ .
....

.. Set the _/usr2/st_ symbolic link to point to the target directory:

+

[subs="+quotes"]
....
cd /usr2
ln -fsn st-_version_ st
....

.. Set its ownership to prevent users other than _prog_ from modifying
it:

+
[subs="+quotes"]
....
cd /usr2
chown -R prog.rtx st-_version_
chmod -R go-w st-_version_
....

+

. Copy your _oper_ and _prog_ directories to the new system. This
sub-step is optional. The FSL11 installation made default home
directories for these users on _/usr2_. If you had not customized
content for the users on the old system, you could just use the
versions on the new system. Still it may be useful to have a copy of
your old directories on the new system for reference, especially if
you realize later that there were additional programs and files you
want to use on the new system. You can accomplish the transfers as
_root_ using:

+

[subs="+quotes"]
....
cd /usr2/old_FSL9/usr2
scp -pqr _old_:/usr2/oper .
scp -pqr _old_:/usr2/prog .
....

. Transfer other files.

+

You may need or want copies of other directories. These might include
_/etc_; _/usr/local/sbin_ and _/usr/local/bin_ (for RAID and AUID
scripts); reference copies of even older installations (possibly
_/usr2/old_FSL8_ and others); other directories from _/usr2_. For
example:

+
[subs="+quotes"]
....
cd /usr2/old_FSL9
scp -pqr _old_:/etc .
rsync -avz --mkpath _old_:/usr/local/sbin usr/local/sbin
rsync -avz --mkpath _old_:/usr/local/bin usr/local/bin
scp -pqr __old__:/usr2/old_FSL8 .
...
....

+

and:

+
[subs="+quotes"]
....
cd /usr2/
scp -pqr __old__:/usr2/old_FSL8 .
...
....

. Set the permissions of the reference directory.

+

You should probably set the entire directory to _not_ have write
permission:

  cd /usr2
  chmod -R a-w old_FSL9


=== Customize files on the new system

There are several things you may need to adjust on the new system.
These include:

.. Customize the _oper_ and _prog_ home directories on the new system
to include any features you want from the old system.

+

This would typically include updating the default _~/.profile_,
_~/.bashrc_, _~/.bash_aliases_, and _~/bin_. If you were previously
using _tcsh_ (the default for FSL9 and earlier) and are now changing
to _bash_ (the default for FSL10 and later), you will need to
translate customized settings from your _~/.login_ and _~/.cshrc_
files.

.. Install additional Debian packages

+

You may need to install packages for your new system that you had
installed on the old system.

.. Copy/merge additional configuration files, such as:

    /etc/hosts
    /etc/hosts.allow
    /etc/hosts.deny
    /etc/ntp.conf

.. Update station software

+

If you are moving to a new FS and FSL__x__ version, any needed changes
are covered in the FS update notice. If you are converting to 64-bit,
instructions can be found in the following steps.

=== Login as prog on the new system

The following steps up to <<Reboot>> should be executed as _prog_ on
the new system.

=== Update station programs for 64-bit

This step is for modifying your station programs in _/usr2/st_. There
are two possible issues, conversion of FORTRAN code and conversion of
C code.

NOTE: If you are not converting from 32- to 64-bit, you should skip
this step and go directly to the <<Make local software>> step below.

==== Conversion of FORTRAN code

If you don't have any FORTRAN station code or you have already
converted it to _f95_, skip this sub-step.

Use of _f95_ is necessary on 64-bit systems. If you have station
programs in FORTRAN, please email Ed so he is aware.

You will need to adapt your __Makefile__s
to use the same compiler options as the FS, which can be
found in _/usr2/fs/include.mk_.
As a first cut, it may work to add the following two lines
to your __Makefile__s for FORTRAN programs:

    FFLAGS  += -ff2c -I../../fs/include -fno-range-check -finit-local-zero -fno-automatic -fbackslash
    FLIBS   += -lgfortran -lm

==== Conversion of C code

If you don't have any C station code, you can skip this sub-step.

If you have C station code, it should work as written unless you have
declared integers that interface to the FS as `long` (this was
actually a common practice due to the example code that been
provided). For a start at fixing those, please see
https://github.com/dehorsley/unlongify.  The following sub-steps
describe how to install and use the _unlongify_ tool.

===== Install go language

If you haven't already, you will need to first install the _go_
language. If you are using FSL11, you can install the _go_ language in
one of two ways listed below:

. <<Option A - Installing golang package>>
. <<Option B - Installing latest go language>>

We recommend the first way for those that are only using _go_ for the
_unlongify_ tool. After installing the _go_ language, continue the
<<Conversion of C code>> instructions starting at
<<Configure prog account for go language>> sub-step below.

====== Option A - Installing golang package

You can use the Debian package management system to install _go_.
This will give you an older version of _go_ that is perfectly adequate
for the task at hand and is supported by the normal security update
mechanism. To install it this way, as _root_ use:

  apt-get install golang

====== Option B - Installing latest go language

You can install the latest version of _go_, but this is outside the
normal security update mechanism. In this case, you will need to
manage your own updates, which may not be suitable for an operational
environment. If you use this method it is recommended that you sign-up
for _go_ language announcements so that you will be informed when a
security update is available. You can sign-up at
https://groups.google.com/forum/#!forum/golang-announce.

Another alternative is to delete the latest _go_ (`*rm -rf
/usr/local/go*`) after you have made _unlongify_. You can
always re-install it if you need it again.

Both the initial install and updates are handled by the
_fsadapt_ script, as _root_:

  cd /root/fsl11
  ./fsadapt

In the first window select _only_ the option (i.e., only that line has a `*`):

  goinst    Install (or 'Update') Go programming language

Then press kbd:[Enter] while `OK` is highlighted. On the next screen, press kbd:[Tab]
to highlight `Cancel` and then press kbd:[Enter].

===== Configure prog account for go language

Once you have the _go_ language installed, you need to define the
`GOPATH` environment variable and include it in _prog_'s path. The
default _~prog/.profile_ file includes two commands (commented out by
default) to accomplish these things:

 #export GOPATH=~/go
 #PATH="$GOPATH/bin:/usr/local/bin/go:$PATH"

You will need to uncomment these two lines and then logout
and log back in again as _prog_ or, in a current login session
for _prog_, re-execute the file:

....
. ~/.profile
....

===== Install unlongify

Then you should be able to execute the installation step given
at the URL above (as _prog_):

  cd
  go get github.com/dehorsley/unlongify

===== Use unlongify

Please read the _README.md_ file, which is displayed at the URL above.
Alternatively, it can be viewed at
_~/prog/go/src/github.com/dehorsley/unlongify/README.md_ where it was
installed by the above command. Please pay particular attention to the
`Note` about system calls.

TIP: The _unlongify_ program attempts to process all _*.h_ and _*.c_
files in the path specified as its argument. If it encounters a file
with a syntax error, an error message will be printed and processing
will stop. Presumably, this would not happen for files that are in
active use, e.g., are referred to in __Makefile__s. However, there may
be code with issues in files that are not currently used. If an error
occurs, the messages should help you identify files with issues, which
can moved (re)moved or corrected as appropriate. Thanks to Carlo
Migoni (Sardinia) for reporting this and spurring the addition of file
names to the error messages.

=== Make local software

IMPORTANT: If you are installing a 64-bit system as part of upgrading
to FS _10.0_, you should return to the FS update instructions at this
point.

If _/usr2/st/Makefile_ is set-up in the standard way, you can do this with:

       cd /usr2/st
       make rmdoto rmexe all

Once your code __make__s successfully, you can continue, but you may
need to debug it in the <<Test the FS>> step below.

=== Reboot

IMPORTANT: Reboot the computer. This is important for initializing
shared memory for the new version.

=== Login as oper on the new system

The remaining steps assume you are logged in as _oper_ on the new
system.

=== Test the FS

NOTE: You may need to debug your station code as part of this.
