//
// Copyright (c) 2020-2021 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= DRAFT FS Document Font Conventions
Version 0.4 - January 2021

:sectnums:

== Introduction

This document covers font and other typographic conventions for FS HTML
documents using _asciidoctor_ source.

== Conventions

=== Terminology

* All top-level document sections are referred to as _sections_.

* All sections below the top-level are referred to as _sub-sections_.

* All steps at the top-level of instructions are referred to as
_steps_.

* All steps below the top-level are referred to as _sub-steps_.

NOTE: Steps often occur as sub-sections. If a section, or sub-section,
is a step, or sub-step, it should referred to as a step, or sub-step,
as appropriate.

=== In-line text

The default body font is used for all text, except:

* _italics_ are used for names (filenames, filename extensions,
directory paths, libraries, programs, accounts, UNIX commands,
versions, nodes, domain names, websites, URLs, URIs, email addresses,
etc., but not people, FSx, or FSLx), emphasis, and the first use of
technical terms.

* `monospace` is used for data (code, program input/output, contents
of files, UNIX command options, FS commands, etc.), fixed parts of
items that would be italic when there are replaceable elements
present, and explicit command/option examples.

* `*monospace bold*`  for explicit input/commands to be entered by the
user.

* `_monospace italic_` (no bold) for replaceable items, including in
explicit input/commands to be entered by the user.

=== Code blocks

Code (data) blocks are usually all simple monospace, but italics may
be useful in some cases for replaceable items.

=== Links

The anchor text in all links is normal body text for simplicity. The
text used depends on the reference:

** External URLs -- These are references to web pages outside of the
FS. The anchor text should be the full URL. Shorter anchor text can be
used if explained; this is useful for repetitive forms.

** Other FS documents -- These are references to other FS documents.
The anchor text should be the full title of the document.  The
surrounding text should identify it as a document.

** Sections (or steps that appear as sections) in other FS documents
-- The anchor text should be the full section/step title. The
surrounding text should identify it as a section or sub-section (or
step or sub-step) and include a link to the document.

** References to other anchors in other FS documents -- The anchor
text should show content related text. The surrounding text should
identify it as something other than a section/step (perhaps _change_
if appropriate) and include links to its section/step and document.

** References to sections/steps of the current document -- The anchor
text should be the full section/step title. The surrounding text
should identify it as a section or sub-section (or step or sub-step).
Including whether it is _above_ and _below_ is helpful.

** References to other anchors in the current document -- The anchor
text should show content related text. The surrounding text should
identify it as something other than a section/step (perhaps _change_
if appropriate) and include a link to its section/step.

=== Document titles

Document titles use normal important word capitalization.  Upper case
is used for acronyms and technical terms that are normally upper case.
There are no special fonts in document titles.

=== Section and sub-section titles

The first word and proper names in sections and sub-section titles
start with capital letters. Upper case is used for acronyms and
technical terms that are normally upper case. Other words are all
lower case.

There are no special fonts in section and sub-section titles for
simplicity. Such formatting may also trigger different results for
different _asciidoctor_ versions.

=== General guidelines for admonitions

These are not firm distinctions.

TIP: Advice

NOTE: Non-essential, supplemental,  information

CAUTION: Could cause a minor issue

WARNING: Could cause a major issue

IMPORTANT: Will result in a major issue

== Source examples

=== Italics 

  Use single underscores around _words_ to be in italics; double underscores for __char__acters.

Results in:

Use single underscores around _words_ to be n italics; double underscores for __char__acters.

=== Monospace

  Use single backticks around `words` to be in monospace; double backticks for ``char``acters.

Results in:

Use single backticks around `words` to be in monospace; double backticks for ``char``acters.

=== Monospace bold

  Use single backticks and asterisks around `*words*` to be in monospace bold; double backticks and single asterisks for ``*char*``acters.

Results in:

Use single backticks and asterisks around `*words*` to be in monospace bold; double backticks and single asterisks for ``*char*``acters.

=== Monospace italic
 
  Use single backticks and underscores around `_words_` to be in monospace italics; double backticks and single underscores for ``_char_``acters.

Results in:

Use single backticks and underscores around `_words_` to be in
monospace italics; double backticks and single underscores for
``_char_``acters.

=== Curved quotes

 Add backticks inside '`quotes`' to make them "`curved.`"

Results in:

Add backticks inside '`quotes`' to make them "`curved.`"

=== Code blocks

Code blocks are created by indenting text, or preceding and following it with four periods.

=== Italics in code blocks

    [subs="+quotes"]
    ....
    login: _account_
    ....

Results in:

[subs="+quotes"]
....
login: _account_
....

=== Admonitions

Admonitions are created by starting a line with the admonition in
capital letters followed by a colon and space.

For admonitions with complex content, a _block_ can be made by putting
the capitalized admonition in square brackets, then on the next line
four equal signs, then ending the block with a line of four equal
signs.

....
[TIP]
====
Suggestion:

. Step
. Another step
====
....

Results in:

[TIP]
====
Suggestion:

. Step
. Another step
====

== Workarounds

This section covers some ad hoc workarounds for issues with _asciidoctor_.

=== Effect of references to sections in other documents on italics

In some cases a reference to a section header in a different document, e.g.,:

  <<beta2.adoc#_update_control_files,Update control files>>

may fail to link properly if there are italicized words (implemented
as single underscores on each side of the word) later in the same
paragraph.

There are two possible fixes. The first is preferred.

. Change the single underscores around all the following words to be
italicized in the same paragraph to be double underscores.
+

This treats them as _characters_ to be italicized, which is
syntactically correct, if somewhat typographically redundant. This is
the preferred approach since it stays within the normal syntax.

. Change the `\#\_` in the reference to `#\_`.
+

While more compact typographically, this is not preferred because it
is outside the normal syntax. And although it fixes the link, single
underscores for italics will then not work for words that follow in
that paragraph.

See also: https://github.com/asciidoctor/asciidoctor/issues/3278
