//
// Copyright (c) 2020-2023 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= FS 10.2 to Latest Commit Update Notes
Version 4.9 - February 2023

:sectnums:
:stem: latexmath
:sectnumlevels: 4
:experimental:

:toc:

== Introduction

The document covers updating from FS _10.2_ to the _latest commit_ on
its branch. The latest commit is experimental. We make every effort to
keep the latest commit usable, but any commit that is not tagged for
release is not intended for operations. The intended use of this
document is to collect update information, as it becomes available,
before the next release.

IMPORTANT: Commits that are not tagged for release may have
significant issues including: not building, crashing, and
incompatibilities with operational observation schedule files. Such
commits are intended for testing only. _Let the user beware._

CAUTION: It is expected that those using the latest commit are experts
and will manage the differences for updating to the next official
release themselves. No specific documentation will be provided. What
commit was last updated to will determine what needs to be done. It
might work to verify that all the steps in the latest version of this
document, appropriately adjusted and renamed as the update from the old
release to the new release, were completed. However, this may not be
complete. _Let the user beware._

This document is up to date with the `10.2.0` commit. Due to small
increments, such as updating this document, that may not be the
literal last commit, but the differences should be small unless you
happen to `pull` between a significant change and this document being
updated.

== Upgrading from 10.2 to the latest commit

IMPORTANT: Since there are no commits beyond the `10.2.0` commit yet,
there is nothing to do and you should ignore his entire document. The
instructions below are placeholders.

You must have already upgraded to _10.2.0_ according to the
<<10.2.0.adoc#,FS 10.2 Update Notes>> document before installing
this update.

=== Fetch the latest commit

IMPORTANT: Since there are no commits beyond the `10.2.0` commit yet,
there is nothing to do and you should ignore skip this entire
document. The instructions below are placeholders.

There are two alternatives:

. If you are using FSL9, FSL10, or another system that supports
connections to _github_ and you are using _git_ (as is recommended)
then as _prog_ execute:

 cd /usr2/fs-git
 git checkout main
 git pull

. If you are using FSL8, or otherwise unable to use _git_:

+

IMPORTANT: Since there are no commits beyond the `10.2.0` commit yet,
there is nothing to do and you should ignore skip this entire
document. The instructions below are placeholders.

+

Please follow the steps, through the step that includes the option to
set the _/usr2/fs_ link, in the
<<../../misc/release_model.adoc#_installing_from_an_archive,Installing
from an archive>> subsection in the
<<../../misc/release_model.adoc#,Release Model>> document. Please note
that:

+
[square]

* For FSL8, you will need the *TIP* in the `*wget*` step.

* For the __tag__ in the `*wget*` and `*tar*` commands, use the short
SHA for the commit, `98ccc361`.

* After extracting the archive, change the name of the output
directory to use the latest feature release and the short SHA of the
commit, like _fs-10.2.0-98ccc361_, which will then be used in the
following `*cd*` command. For example (for the _source_ directory,
kbd:[Tab] completion is your friend):

 mv fs-98ccc361ea9f18d719f158f7c70c96edadb32607 fs-10.2.0-98ccc361
 cd /usr2/fs-10.2.0-98ccc361

* You will end the "`installing from an archive`" with the step
setting the link for __/usr2/fs__ by running *`make install`*.

=== Update your station code.

Except if noted otherwise, these steps should all be performed as
_prog_.

This step is not needed at this time.

=== Reboot

IMPORTANT: This will make sure the FS server is stopped and shared
memory is reallocated.

This step is not needed at this time.

=== Additional steps

Except if noted otherwise, these steps should all be performed as
_oper_.

There are no additional steps yet.

=== Review changes

Please see the <<Changes since 10.2.0>> section below for the details
of the changes since that release.

== Changes since 10.2.0

There are separate subsections with summaries of the changes in the FS
and _drudg_.

Clickable links such as https://github.com/nvi-inc/fs/issues/36[#36]
connect to specific issues reported at
https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

Each change is listed as a numbered title, then usually a few summary
sentences, followed by a _toggle_:

[%collapsible]
====
Details are shown here.
====

that can be clicked on to toggle showing (or not showing) the details.
In this way, you can view the summary as a list and only reveal the
details of items that interest you. The summary sentences and/or the
details toggle may be omitted if they would not add any new
information, usually because it is already covered in the numbered
title item and/or the details are very brief.

=== FS changes

There are no FS changes yet.

=== drudg changes

There are no _drudg_ changes yet.
