//
// Copyright (c) 2020-2023 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= FS 10.2-alpha1 Update Notes
Version 5.1 - March 2023

:sectnums:
:stem: latexmath
:sectnumlevels: 4
:experimental:

:toc:

== Introduction

This document covers the steps needed to update from FS _10.1_ to
_10.2_ (latest patch is _10.2.0_) and the changes in the new version.
Installing the new version (see the <<Upgrading from 10.1>> section
below) is much simpler than the update to _10.1_.

IMPORTANT: Despite the next paragraph, _alpha_ and _beta_ releases are
not intended for operations.

FS _10.2_ has been tested for a few configurations but not all
possible ones. You should test it carefully before using it for
operations. Please email Ed if you encounter problems so that we can
resolve them.

The changes in the FS and _drudg_ for _10.2_ are covered in the
<<Changes since 10.1>> section below. The most significant changes
are:

* Support for FSL11. The FSL11 distribution is based on Debian
_bullseye_ and is the latest FSL__x__ Linux distribution. The
installation instructions for FSL11 can be found at:
https://nvi-inc.github.io/fsl11/.

* Support for experiment names (session codes) of 16 characters or
less. This enables use of the new IVS 12-character session codes.

* The _plotlog_ utility, for examining data in the log files, has been
expanded and updated. The changes include support for RDBEs, DBBC3s,
and recorder performance statistics.

== Upgrading from 10.1

You must have already upgraded to _10.1_ according to the
<<../1/10.1.0.adoc#,FS 10.1.0 Update Notes>> document before
installing this update.

NOTE: You can make a _fresh_ install of _10.2_ on an FSL11 system
using the FSL11 installation document, once it is available.  Testers
of previous development commits for FS support of FSL11 can follow the
instructions here.

=== Fetch 10.2

There are two alternatives:

. If you are using FSL9, FSL10, FSL11, or another system that supports
connections to _github_ and you are using _git_ (as is recommended)
then as _prog_ execute:

 cd /usr2/fs-git
 git fetch
 git checkout 10.2.0-alpha1

. If you are using FSL8 or are otherwise unable, or prefer not, to use
_git_:

+

Please follow the steps, through the step that includes the option to
set the _/usr2/fs_ link, in the
<<../../misc/release_model.adoc#_installing_from_an_archive,Installing
from an archive>> subsection in the
<<../../misc/release_model.adoc#,Release Model>> document. Please note
that:

+
[disc]

* For FSL8, or if you are otherwise unable to connect to _github_, you
will need the *TIP* in the `*wget*` step.

* For the __tag__  use `10.2.0-alpha1`.

* You will end using the "`installing from an archive`" procedure with
the step setting the link for __/usr2/fs__ by running *`make
install`*.

=== Set new environment variables

There are two alternatives:

. For FSL11, no new environment variables need to be set, skip to the
next step <<Make the FS>>.

. For FSL__x__ Linux distributions FSL10 and earlier, set the
environment variables `FS_F95_NO_ALLOW_ARGUMENT_MISMATCH` (even if not
using _f95_) and `FS_PYTHON_VERSION`.  Some other non-FSL__x__
distributions may need one or both set as well.

.. Update login _rc_ files:

+

+

There are two alternatives:

... If your _prog_ login shell is _bash_, add the following to
_~prog/.profile_:

 export FS_F95_NO_ALLOW_ARGUMENT_MISMATCH=1
 export FS_PYTHON_VERSION=2

... If your _prog_ login shell is _tcsh_, add the following to
_~prog/.login_:

 setenv FS_F95_NO_ALLOW_ARGUMENT_MISMATCH 1
 setenv FS_PYTHON_VERSION 2

.. Logout of _prog_ and back in

=== Make the FS

As _prog_:

 cd /usr2/fs
 make clean rmdoto rmexe all >& /dev/null
 make -s

No output from the last command indicates a successful _make_.

=== Update your station code.

This step can _probably_ deferred for now, if it is needed at all. If
you do need to make this change, it will not become necessary until
you receive schedule files with more than six characters in the name
(before the _.skd_ or _.vex_ extension) or you otherwise want to use
_.snp_, _.prc_, or _.log_ files with names before the "`dot`" (_._) of
more than eight characters. It will probably be some time before
schedules with longer names become available. However it is better to
not put off updating your software too long. There is a reasonable
chance that your software may not need any changes.

CAUTION: You may be asked by a coordinating center or scheduler if
your station can handle the longer names. You should _not_ answer
"`yes`" until you have made the necessary changes or verified that no
changes are needed.

There are two issues to address, shared memory variables and the
_lognm_ program:

. Use of shared memory variables.

+

If your station software uses the C shared memory variables: `LLOG`,
`LLPRC`, `LSKD`, `LSTP`, `LNEWPR`, `LNEWSK`, or `LEXPER`, you should
update to use `LLOG2`, `LLPRC2`, `LSKD2`, `LSTP2`, `LNEWPR2`,
`LNEWSK2` or `LEXPER2` instead, respectively.

+

Likewise, if you use the corresponding FORTRAN _fscom_dum.i_ variables
via the `++fs_get_++__variable__`/`++fs_set_++__variable__()` routines
in _newlb/prog.c_, you will need to change to use the new variables
and routines.

+

The old variables all have a length of `8`. The new variables have a
length defined by the `MAX_SKD` parameter (currently with a value of
`18`) in _include/params.h_ ++(C)++ and _include/params.i_ (FORTRAN).

+

NOTE: These strings in these variables are blank padded, not
terminated with a `null` byte.

+

The old variables are still available and should work fine until you
use _.snp_, _.prc_, or _.log_ file names with more than eight
characters before the "`dot`" (_._), in which case the values in the
old variables will be truncated versions.

. Use of the _lognm_ program

+

If you use the _lognm_ program, you should make sure the callers can
handle log names up to `18` characters in length.

+

The _lognm_ program returns a string no longer than the actual length
of the log name. There should be no issues for log names of eight
characters or less even if you have not made any adjustments to handle
longer names.

If you update your station code, you will need to re__make__ it. If
_/usr2/st/Makefile_ is set-up in the standard way, you can do this
with (as _prog_):

 cd /usr2/st
 make rmdoto rmexe all

=== Additional steps

. Optionally, update your NTP configuration.

+

This change will make the output of the `check_ntp` procedure and the
contents of _/etc/ntp.conf_ file easier to read. Instructions are
included for how to remove display of NTP related FQDNs and IP
addresses in the log, if that is an issue for your site.

+

If you want to make this change, it can be deferred to a convenient
time. The instructions can be found in the
<<Update NTP Configuration>> appendix.

=== Reboot

IMPORTANT: This will make sure the FS server is stopped and shared
memory is reallocated.

=== Review changes

Please see the <<Changes since 10.1>> section below for the details
of the changes since that release.

== Changes since 10.1

There are separate subsections with summaries of the changes in the FS
and _drudg_.

Clickable links such as https://github.com/nvi-inc/fs/issues/36[#36]
connect to specific issues reported at
https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

Each change is listed as a numbered title, usually with a few summary
sentences, followed by a *Details* _toggle_, like:

[%collapsible]
====
Details are shown here.
====

that can be clicked on to toggle showing (or not showing) the details.
In this way, you can view the summary as a list and only reveal the
details of items that interest you. The summary sentences and/or the
details toggle may be omitted if they would not add any new
information, usually because it is already covered in the numbered
title item, summary, and/or the details are very brief.

=== FS changes

. <<FSL11,FSL11>>:[[FSL11]] Support FSL11

+
--

The code was updated for FSL11 (Debian _Bullseye_). The FSL11
distribution is latest FSL__x__ Linux distribution. The installation
instructions can be found at: https://nvi-inc.github.io/fsl11/. The
primary changes in the FS to support FSL11 are:

[disc]
* Making typographic changes to be compatible with the new _f95_
compiler version.

* Adding _python3_ versions of existing _python_ scripts.

--
+

Users of pre-FSL11 systems will need to set some environment variables
for _prog_ before compiling. These are described in the installation
instructions (above) as well as in the "`Details`" collapsible section
below.

+

[%collapsible]
====

.. Remove  use of `stime()`

+

+

In FSL11, `stime()` is not available for newly linked applications. It
would need to be replaced with `clock_settime()`. It was not replaced
because the functionality it was used for, setting the system time,
hasn't been available to non-_root_ users since the FS was ported to
Linux (FS9), circa 1995. The FS must _never_ be run by _root_.

.. New required environment variables for pre-FSL11 systems.

+

Two new environment variables, `FS_F95_NO_ALLOW_ARGUMENT_MISMATCH` and
`FS_PYTHON_VERSION`, were added to assist with compilation on
pre-FSL11 systems. They only need to set once in _prog_'s login `rc`
files on these systems. Their use is explained in the next two items.

.. <<f95,f95>>:[[f95]] Changes for new _f95_ compiler version

+

The _f95_ compiler, version _6.3.0_, in FSL11 has stricter
requirements for the use of octal, hexadecimal, and binary constants
and for argument type agreement in calls to functions and subroutines
than in previous FSL__x__ versions. The changes made were:

... Reformat octal and hexadecimal constants

+

Hexadecimal, octal, and binary constants can only be used in `data`
statements or in the intrinsic function `int()`. There is a compiler
option, `-fallow-invalid-boz`, to relax this requirement. However, it
does not cover the case of actual arguments to a function at this
time. There are many of those, so it was decided to just change all
non-`data` statement use of these constants to parameters. They were
wrapped in `int()` in the `parameter` statements. The parameter names
were chosen so the constants could be globally replaced in the FORTRAN
code without overflowing the 72-character line limit. Existing octal
and hexadecimal constants in `parameter` statements were wrapped in
`int()`. The FS code did not have any binary constants.

+

This change can cause the symbol table for _f2c_ (used by _fort77_
when it is the compiler) to overflow. The symbol table size for that
case was increased by adding the option `-Nn1604`.

... Add use of `-fallow-argument-mismatch` compiler option.

+

Argument type mismatches are common in the code, particular for when
Hollerith data is being handled and sometimes `interger*4` and
sometimes `integer*2` arrays are passed as the same argument for
functions and subroutines. Since this error is benign and there was an
option to ignore it (and it worked), it was used.

+

+

For _f95_ in previous FSL__x__ versions, this option is not accepted
(or needed). To allow compilation on these older systems, use of an
environment variable `FS_F95_NO_ALLOW_ARGUMENT_MISMATCH` was added. If
it is set to `1`, the complier option is not used. Some other
non-FSL__x__ distributions may need the variable set as well. For
these older systems, this needs to be set once in _prog_'s login `rc`
files then it is necessary to re-login into the _prog_ account before
compiling.

+

+

For FS installations that are using the _fort77_ complier, it is still
recommended that the variable be set to `1`. That way the
configuration will be forward compatible with a possible change to
_f95_.

... Remove mixing of `integer*4` and `integer*2` as arguments for
intrinsic `and()`.

.. Changes for _python3_.

+

FSL11 has limited support for _python2_, in particular there is no
`numpy` The two largest _python_ programs in the FS, _gnplt_ and
_logpl_ require `numpy`. Since most of the work converting was for
these two programs, it seemed best if they all were converted. There
is not expected to by any _python2_ in the next Debian release,
_bookworm_.

+

The older _python2_ version are still included in case they are
needed. For older systems that are unable to use the _python3_
versions (this includes FSL10 and older FSL__x__ systems), an
environment variable `FS_PYTHON_VERSION` was added. If it is set to
`2`, the _python2_ versions are linked. For these older systems, this
needs to be set once in _prog_'s login `rc` files then it is necessary
to re-login into the _prog_ account before compiling.

+

It may be that on some of these older systems (this includes FSL10 and
older FSL__x__ systems), the _python3_ versions of the scripts could
be used if more Debian packages for missing _python3_ modules are
installed. This has not been tested. If you try this, please let Ed
know your results. In the meantime. the original _python2_ scripts are
available.

+

The programs effected are: _logpl_, _gnplt_, _monpcal_, _be_client_,
_s_client_, and _rdbemsg_. The _python3_ source code is in directories
with the same name. The _python2_ source code can be found in
directories with the same name, but with `-python2` appended. It is
expected that the _python2_ and _python3_ versions will be maintained
in parallel for the foreseeable future.

+

Four steps were used to convert the code to _python3_:

... Run code through the _2to3_ utility.

+

This utility makes many of the typographic changes needed going from
_python2_ to _python3_. It can installed, as _root_, with:

  apt-get install 2to3

... Run the code through the _reindent_ utility.

+

+

This utility will re-indent a script using 4-space indents and no hard
tabs. It can be installed, with:

.... First, as _root_:

   apt-get install pip

.... Then as _prog_ (in _bash_):

  cd ~
  pip3 install reindent
  PATH="~/.local/bin:$PATH"

+

+

TIP: The `PATH=...` statement needs to be re-executed for each new
login or new _bash_ shell.

... Change the _shebang_ lines to use _python3_

+

The _python3_ variant must be explicitly referenced for FSL11.

... Fix runtime issues that were discovered during testing

+

We believe we have found all of these, but perhaps not. The most
common paths through the code were exercised, but there maybe some
obscure paths, particularly in _logpl_ and _gnplt_ that may still have
problems. Please report any issues you find to Ed. It should be easy
to post (and install) a patch that will fix them.

+

+

The fixes made so far include:

+
[disc]

* Wrap the third argument of `range()` in `int()`

* Change the `import` from `idlelib.TreeWidget` to `idlelib.tree`

* Replace the use of `popen2` with `subprocess` and use text encoding
for sub-process I/O

* Fix archaic use of `strip()`

* Use `encode()`/`decode()` for socket I/O

* Change `isAlive()` to `is_alive()` for threads

* Use `key=functools.cmp_to_key()` for (time) sort.

* Set `rcond=-1` in `linalg.lstsq()` to preserve old behavior

* Use `median()` rather than divide-by-two to find the median of a
sorted list.

+

+

[NOTE]
=====

The installation of _2to3_, _pip_, and _reindent_ can be reversed (if
nothing else is installed in _~prog/.local_) with:

.. As _root_:

   apt-get purge 2to3
   apt-get purge pip

.. As _prog_ (be careful with this command in case other things than
_reindent_ are installed in _~prog/.local_):

  rm -rf /usr2/prog/.local

=====

====

+

. <<Names,Names>>:[[Names]] Support names of 18 characters or less for
the `schedule`, `proc`, and `log` commands.

+

With the last two characters of the names usually taken up by the
two-character station code, this allows experiment names to be 16
characters or less. This provides support for the IVS Master File _v2_
"`session code`" lengths of 12 characters or less. The _fsvue_ and
_logex_ programs were not updated for this change.


+

[%collapsible]
====

This change is largely transparent to the users. The four visible
effects are:

[disc]
* The length  and/or location of the `SCHED=...` and `LOG=...` fields
in the `System Status Monitor` display (_monit2_) were changed. The
`SCHED=..` field now occupies the space previously used by both
`SCHED=...` and `LOG=...`. The `LOG=...` field is now in the lower
right where the `HEAD PASS # ...` field was previously located.

* The display of procedure libraries for the `pfdl` command in _pfmed_
now shows only three libraries per line. A key was also added to
describe the prefix letters.

* The `log=...` command now traps a log name that is too long.
Previously, it just truncated longer names to eight characters.

* The _lognm_ script will put out log names up to 18 characters in
length, previously the maximum was eight.

The _fsvue_ and _logex_ programs were no updated for this change. If
you are using these programs, we will look into updating them, please
contact Ed. If they were working before, they should continue to work
for names of eight characters or less.

Internally, new variables were appended to shared memory for the
schedule, schedule procedure, station procedure, and log file names
and the experiment (schedule) name. The old variables are still
present and hold up to the first eight characters of longer names.
This is intended to make the changes backward compatible for station
programs (such as _antcn_ and _telegraf_) that are pinned to the FS
_10.0_ memory layout until they can be updated for the new variables.
Of course, longer names will appear truncated in the downstream
programs until they have been updated.

====

. Improve _plotlog_

+

The default plot device for X11 displays was changed to be useful.
Added recorder performance statistics. The plotting of clock data was
expanded. Plots of wind speed and direction were added. Plotting CDMS
data was added. T~sys~ plots for DBBC3s and RDBEs were added.
Phase-cal tone plots for RDBEs were added. Plots of LSB Mark IV
decoder phase-cal data were added. Phases outside [-180°,+180°] are
now automatically marked as bad, but can be included with the `-Y`
option. Clock and cable values outside (-10,+10) seconds are now
automatically marked as bad, but can be included with the `-C` option.
Plots of Wettzell style `/rx/` data were added. Bad points are now
displayed as open circles and slightly off the upper (or right) edge
of the plots. Any values in time plots that did not decode are now
consistently displayed at the upper edge of the plots. Plotting of
phase differences attempts to provide better vertical plot limits if
the differences cluster around ±180°. Support for the _giza_ plot
library was added. Bad horizontal tick marks in some `-p` plots were
fixed. Some command line options were changed.  The `-h` (help) output
was improved. The version was bumped to _2.2_.  Some improvements were
made in the code.

+

[%collapsible]
====

.. Change the plot device for X11 displays to `/xw` (closing
https://github.com/nvi-inc/fs/issues/183[#183]).

+

If the `DISPLAY` variable is set and no other plot device was
specified, the program assumes it should plot on the X11 display. The
old default X11 plot device, `/xterm`, didn't work. That device
apparently worked for some pre-FSL8 distribution. For as far back as
FSL8 `/xterm` seems to be available, but doesn't work. So this has
probably been a problem since at least 2009. _plotlog_ was introduced
(using `/xterm`) in FS _9.8.0_ (July 2005) with commit
52398939d5f867b2e7ab4e18f8886babda6dfaae. FSL5 (_woody_) was probably
active at that time. `/xw` now seems to be a good choice in FSL8 and
later.

.. Add recorder performance statistics

+

Time plots were added for:

+
--
[disc]

* Delay in recorder starting (seconds)

+

NOTE: This does not include any delay for the schedule running late.

* Shortness of recording length (seconds)

+

NOTE: For non-Mark 6 recording, this may include some delay for the
schedule running late.

* Missing bytes (count)

--
+

All information is inferred from the `scan_name=...` command, the
command that starts the recording (`disk_record=on` or
`mk6__x__=record=...`), and the results of `scan_check`. The FS,
_cplane_ (Mark 6), and _jive5b_ forms of `scan_check` are supported.

+

Thanks to Jon Quick (HartRAO) for suggestions about what information
to report.



.. Expand clock plotting.

+

The clock plotting was expanded to plot all data collected by commands
with names that contain `fmout`, `gps`, and `maser`. Additionally,
RDBE `dot2pps` and `dot2gps` data from multicast and `dbe_pps_offset`
and `dbe_gps_offset` commands are plotted. The DBBC3 `pps2dot` data
from multicast and the `mcast_time` command are plotted. For the RDBE
and DBBC3, if both command stream and multicast versions are
available, only the multicast is plotted unless the `-B` option is
used, which will include both.

+

Opposite signed versions of the same offset (e.g. `gps-fmout` and
`fmout-gps`) are no longer combined in one plot (with appropriately
adjusted signs). Keeping them separate makes the plots more
representative of the log contents.

+

Thanks to Karine Le Bail and Rüdiger Haas (both at Onsala) for
arranging to produce experiment logs with `mcast_time` data for
testing.

.. Add plotting of wind speed and direction.

+

If fields for these data are present in the `wx/` log entries they
will be plotted. This is in contrast to temperature, pressure and
humidity, which are always plotted if `wx/` entires are present.
Missing values for any fields are shown as "`out-of-range`" (near the
top-edge of the corresponding plot).

.. Add plotting of CDMS data.

+

As with `cable/` data, the default is to plot the values as the change
in one-way delay in picoseconds, relative to the first valid value
found in the log. Also as with `cable/`, the `-r` option can be used
to plot the raw values instead. Values greater than `999998.5`, which
only occurs for error conditions, are marked as "`bad`".

.. Add plotting of RDBE and DBBC3 T~sys~ values from multicast.

+

By default, only the data from the first encountered detector (other
than channel `00` for RDBEs) from each IF band is plotted. The `-m`,
and `-M`, options can be used to select, and deselect, different sets
of detectors based on regular expressions. This is similar in function
to the `-g`/`-G` options (the latter, formerly the `-e` option),
except `-m`/`-M` only apply to RDBE and DBBC3 T~sys~ data and are
applied as they are read-in instead of when they are plotted. This
makes them a bit faster since there are typically many values
involved.

.. Add plotting of RDBE phase-cal data from multicast

+

By default, only the first encountered tone from each IF is plotted.
The `-d`, and `-D`, options can be used to select, and deselect,
different sets of tones based on regular expressions. This is similar
in function to the `-g`/`-G` options (the latter, formerly the `-e`
option), except that `-d`/`-D` are only applied to RDBE phase-cal
tones and are applied as they are read-in instead of when they are
plotted. This makes them a bit faster since there are typically many
values involved.

+

The `-j` (T~sys~ normalization) and `-k` options are not supported for
RDBE phase-cal yet.

+

The (new) `-v` option plots phase differences between tones in the
same RDBE IF channel.

.. Add plotting of the first encountered LSB phase-cal tone per
converter for the Mark IV decoder (and K5TS) output.

+

This is in addition to the already supported first encountered USB
tone per converter.

+

For phase difference plots (options `-lanw`) when both USB and LSB
tones are present, the differences for only one tone per converter are
plotted. If USB and LSB is present for an individual converter, the
difference between the side-bands is plotted after the differences for
pairs of different converters.

.. Mark phases outside [-180°,+180°] as bad by default.

+

This can useful for Mark IV decoder communication errors. All phase
can be included with the new `-Y` option.

.. Mark clock and cable values outside (-10,10) seconds as bad by
default.

+

These are generally not useful values, but can be included if needed
with the new `-C` option. Normally they only occur if a counter is
being used and a bad value is returned.

.. Add support for Wettzell's style of `/rx/` data.

+

The most useful fields for plotting in Wettzell's `/rx/` data are of
the form `_number_[_units_]` where `_number_` is a floating point
number and `_units_` is one of `dB`, `dBm`, `degC`, or `MHz`. By
default, _plotlog_ will only plot what seems to be the most
interesting of these, which are the `degC` fields in any record and
the `dBM` fields in the `IF__xx__` records (the `dBM` and `MHz` fields
in the `lo__x__` records, and the `dB` fields in the `IF__xx__`
records, are usually static). The `-W` option can be used to plot all
the `_number_[_units_]` fields.

+

It is assumed that only one field of a given `units` type exists per
log entry type. The latter is determined by the first field of the log
entry, typically `lo__x__` or `IF__xx__`, for a given `_x_` or `_xx_`.
For example, `loa`, `lob`, `IFAH`, `IFAV` are all different types for
this purpose. If there is more than one field with a given `units`
type in a log entry type, the plot for that type combination will be
garbled. As of this writing there are no known cases of this.

.. Display bad points as open circles and move them slightly off the
top (or right) plot edge.

+

Displaying them as open circles makes it clearer that they are
different than the "`good`" points which are closed circles. Moving
them slightly off the top (or right) edge improves their visibility
and eliminates ambiguity about which plot they are part of in stacked
plots.

.. Always display values that don't decode at the upper edge of time
plots.

+

Previously for some data types, specifically `cable`, `rx`, `sx`, `sk`
and `fmout-gps`, samples were omitted if they did not decode as
floating point numbers. Now they are displayed at the upper edge of
the plot, as occurs for other data types, so their presence is
visible. The only cases where samples are completely omitted now is
when the form of the entry is too garbled to be identified or the
command is missing (possibly because it timed-out). These two
situations may be noticeable if the plot for a data type is missing
entirely or is sparser than expected.

.. Plotting of phase differences attempts to provide better vertical
plot limits if the differences cluster around ±180°.

+

If there is a gap in the phase differences of 180° or more and there
is some data in both the bottom and top of the [-180°,+180°] range,
the data is adjusted to be around +180°. This doesn't fix all overly
large vertical scales, but it improves the worst ones.

.. Add support for the _giza_ plot library.

+

The _pgperl_ package provided by some Linux distributions (for example
FSL11) may use the _giza_ plotting library instead of _pgplot_.
Unfortunately, _giza_ is not yet a fully compatible replacement for
_pgplot_. Several differences have been noticed, so far, in _giza_
version `1.2.0` (which is used by FSL11):

+
--
[disc]

* The default line-width is thicker. It appears to actually be what
would be line-width `2` in _pgplot_. It appears that the line-widths
are off by one (see the next item as well).

* Setting the line-width accepts `0`, which gives the same width as
`1`, the minimum, in _pgplot_. However, line-width `0` causes the plot
borders to not appear for device `/xw`.

* The closed circle graph marker `17` is significantly less distinct.

* The open circle graphs markers, symbols `20` through `27` (and some
others), have thicker lines than in _pgplot_. For `20` and `21`, it is
difficult to make out that they are open.

* Graph markers are clipped if they are on the edge of a plot instead
of allowing them to spill over. This makes them harder to see.

* Automatic spacing of vertical tick marks is overly dense.

* Requested horizontal tick spacings are only approximately respected.

* The environment variables `PGPLOT_BACKGROUND` and
`PGPLOT_FOREGROUND` for setting the plot colors are not respected.

--
+

If the script detects that _giza_ is in use, it will adjust the
line-width, except for plot device `/xw`, and use a larger open circle
for "`bad'" points. The resulting plots are usable, but not as good as
with _pgplot_. These adjustments can be disabled, individually, with
`-Z` option if they cause a problem or if a later version of _giza_
has better agreement with _pgplot_. If _giza_ is not detected, the
`-Z` option can be used for force the adjustments. Please see the `-h`
output for more details.

+

One advantage of _giza_ is that a PDF file is available as an output
device.

.. Fix bad horizontal ticks for `-p` option.

+

Previously except for the last page, there was an extra set of
horizontal tick marks in the bottom plot on each page. Additionally,
the horizontal tick labels on these pages were for the extra set of
ticks. This has been fixed. There is no extra set of tick marks and
the labels are correct.

.. Change the command line options.

+

In addition to adding the `-B`, `-C`, `-d`/`-D`, `-m`/`-M`, `-W`,
`-Y`, and `-Z` options as mentioned above, the following changes were
made:

... The old `-e` option was moved to `-G` (now paired with `-g`) for
parallel construction with `-D`/`-d` and `-M`/`-m` and to make room
for the new `-e` option.

... The new `-e` option can be used to specify the rack type as
`dbbc3` or `rdbe`, This can be useful for DBBC3 and RDBE log snippets
that don't contain an `equip` line near the start. This only affects
DBBC3 and RDBE T~sys~, and RDBE phase-cal, processing.

... The new `-l` option can used to specify the location, which is
only used in the plot titles. This can be useful for log snippets that
don't contain a `location` line.

... The new `-S` option can be used to require a leading slash before
the command name for `wx/`, `cable/`, and `cdms/` entries. For example
with `-S`, the search string for `wx/` entries is `/wx/`. This is
useful, for example, if there are non-data entry of the form `wx/` and
the data entries are of the form, `/wx/.` The program accepts the form
without the leading `/` because that is what some stations produce for
the data entries and that will match for stations that do use as a
leading `/`. This option is only to help for stations with non-data
entries that do not have the leading `/` and data entries with the
leading `/`.

... The old `-v` (version) option was moved to `-V` to make room for
the new `-v` option, which plots phase differences between phase-cal
tones within an RDBE IF.

.. Improve the `-h` help output.

+

... A suggestion for a file name extension for the `/vps` device was
added.

... The explanation of the `-2` option was improved.

... How to set the background and foreground plot colors was added.

+

+

This can be used to change the background/foreground colors to
white/black from black/white. The latter are used by default for the
X11 display with some FSL__x__.

... An explanation was added that out-of-range phase values in the
`-p` plots are placed near the right-hand edge of the plots.

... Add explanation of option philosophy:

+

+

Generally, the philosophy is that if no options are specified the
script should something that is likely to be useful. Options can be
added to tune the behavior for different situations. Scripts or
aliases can be used if any options are needed routinely.

.. Bump version number to _2.2_.

.. Improve the code

+

A few internal improvements were made:

... The efficiency of finding the `location` log record was improved
by only parsing for it if it has not been found before (and was not
specified by `-l`). As a result, only the first one encountered (or
the `-l` value) is used now.

... The help output was changed to a multi-line string for easier
maintenance.

... The order of options in the `Getopts` call was alphabetized.

... Removing DOS end-of-lines (to help with files that were
transferred via machines with such end-of-lines) was improved so that
it did not need to be handled in each search string.

====

. Change the order of commands for DBBC3 syncing.

+

The sequence of commands for syncing the DBBC3 were changed in the
<<../1/dbbc3_ops.adoc#_sync_time,Sync time>> section of the
<<../1/dbbc3_ops.adoc#_alternate_core3h_board_configuration_method,Alternate
Core3H board configuration>> appendix of the <<../1/dbbc3_ops.adoc#,FS
10.1 DBBC3 Operations Manual>>.

+

[%collapsible]
====

There is now a `pps_sync` command both before and after the `timesync`
commands. Despite this improvement using this method is still not
recommended.

Thanks to Sven Dornbusch (MPIfR) for providing the best sequence of
commands.

====

. Fix _plog_ to support sending multiple files to BKG (closes
https://github.com/nvi-inc/fs/issues/186[#186]).

+

[%collapsible]
====

Due to a bug, _plog_ was unable to send multiple files to BKG in one
invocation. The result was that none were sent.

Thanks to Kiah Imai (KPGO) for reporting this and testing the fix.

====

. <<shutdown,Server shutdown>>[[shutdown]]: Shutdown display server
on `terminate` (closes
https://github.com/nvi-inc/fs/issues/176[#176]).

+

When the display server is in use, terminating the FS now also
shutdowns the server. An interlock was introduced to prevent
termination if it would also stop active _autoftp_ and/or _fs.prompt_
instances.

+

[%collapsible]
====

Previously, if the display server was in use, it continued running in
background when the FS was terminated; now it will shutdown. Not
shutting down was introduced in commit
`85b24dc67111d82371c3fd0b850b19174840e0e4`, and first released in FS
_10.0.0_, as part of a larger scheme to serve client web pages. In the
short-term, that plan is not being followed through on and the change
had some negative impacts for local use. Manually stopping the server
was required in certain cases:

[disc]

* If _antcn_, or another local program opens an X11 application, say
for example, for a dialog box to let the operator select the antenna,
the application will appear on that display. If later an operator on a
different display wants to restart the FS, the server would have to be
stopped before restarting the FS for the X11 application to appear on
the new display.

* To update the environment variables used by the FS

* To change the user that owns the FS processes

Manually stopping the server is no longer required in these, or any
other, cases.

A small downside of this change is that if the FS is terminated and
restarted in quick succession, there may be a socket conflict (while
the old server instance cleans up) that prevents the restart. This can
be handled by waiting a moment and trying to restart again.

An implication of stopping the server is that any running _autoftp_
and _fs.prompt_ processes will also be terminated. This is
undesirable, especially in the case of _autoftp_ since any active data
transfers would be terminated. To avoid this, an interlock was
introduced. When the server is in use and any _autoftp_ or _fs.prompt_
instances are active, termination will be prevented with explanatory
error messages. If it is necessary terminate, an override parameter,
`force`, can be used:

 terminate=force

To keep things simple, the previous override parameter,
`disk_record_ok`, for terminating if disk recording is active has been
eliminated and that functionality is now included in the `force`
parameter as well. See `*help=terminate*` for more explanation.

The interlock for preventing termination if _pfmed_ is active was
moved to be before the interlocks that can be overridden with `force`.
It is not possible to override the _pfmed_ interlock and there is no
point using `force` if termination will be blocked by _pfmed_ anyway.

The <<../../../misc/env_vars.adoc#_runtime_variables,Runtime
variables>> section of the <<../../../misc/env_vars.adoc#,FS
Environment Variables>> document was updated to reflect this change.

The <<../0/fsserver_changes.adoc#,FS 10.0.0 Server changes>> document
was updated to reflect this change.

====

. Fix crashes for DBBC2 communication errors (closing
https://github.com/nvi-inc/fs/issues/191[#191]).

+

[%collapsible]
====

There was an error in class number handing of communicating with a
DBBC2 (the FS refers to the device as a "`DBBC`"). It occurred in the
periodic checking of the DBBC2 personality and version number. Crashes
only seemed to happen when the DBBC2 is in a bad state, and then after
about ++~35++ `ch -810 Communication error for DBBC.` errors. There
should no longer be any crashes even if the DBBC2 is in the bad state.
Rebooting the DBBC2 may fix the bad state. That is a good thing to do
since calibration data may be lost and other problems may occur while
it is in the bad state.

This fix is also included in patch releases _10.0.1_ and _10.1.1_.

Thanks to Eskil Varenius (Onsala) for reporting this problem and
testing the fix.

====

. Fix using a DBBC IF channel as a detector in _fivpt_ and _onoff_
with continuous calibration (closing
https://github.com/nvi-inc/fs/issues/190[#190]).

+
[%collapsible]
====

The DBBC (i.e., the DBBC2) does not provide separate cal-on and
cal-off TPIs for an IF detector when continuous calibration is in use.
Implementing something useful in the FS for this case had been
overlooked.  Unfortunately, the FS produced unusable T~ant~
measurements in _fivpt_ and nonsensical T~sys~ values for those
detectors in _fivpt_ and _onoff_.

This was improved by (i) internally treating that detector as having a
T~cal~ value of `-100` (i.e., assuming there is no noise diode for
this detector) and (ii) using the unswitched power. This results in
_fivpt_ T~ant~ and estimated peak values being printed in percent of
system temperature in _fivpt_ and T~sys~ for that detector as `-100`
in _onoff_.  If the T~cal~ defined in the _.rxg_ file was already
negative, that value is used instead.

If the IF channel is not corrupted by RFI, this makes it usable for
pointing measurements. It use should still be avoided for gain
calibration measurements for other reasons, primarily having a very
broad bandpass, but in some cases not having a center frequency that
_onoff_ can calculate accurately. Additionally, the value of the
"`DBBC IF power conversion factors`" in _equip.ctl_ may not have
accurate values.

Thanks to Jon Quick (HartRAO) for reporting the existing poor
behavior, pointing out that something useful could be done, and
testing the improvement.

====

. Add _streamlog_ utility (closes
https://github.com/nvi-inc/fs/issues/64[#64]).

+

The _streamlog_ utility is a script that outputs log entries as they
are written. It can be used by itself or with other programs that
filter for specific log entries. It will provide the most complete
output when the display server is enabled, but should also be useful
when it is not.

+

[%collapsible]
====

By default, if the FS is already running, the script will output log
entries to `stdout` (for simple interactive use, this is the user's
terminal) as they are generated. A small number of entries may be lost
when the FS is started. When the display server is not enabled, a
small number of entries may be lost when the active log is changed.

The script has four command line options. Generally speaking they
should _not_ be used with _streamlog_ in _stpgm.ctl_. The options are:

.. `-d` -- display stream

+

This option is only available if the display server is enabled. It
outputs the display server stream instead of the log stream. The
display stream is what is displayed in the log display window by the
FS client. There are several differences between what is is shown in
the log display window and what goes in the log. The most significant
of these are:

+
[disc]

* The log display output uses a shorter time-tag field.

* Some output lines are suppressed in the log display window because
they would be overwhelming and would generally not be helpful for
interactive use.

* Some FS error messages are not shown in the log display window
because the operator has suppressed them with the `tnx` command.

* The log display window includes some output that is not in the log,
specifically the FS startup and termination messages and some program
error messages.

.. `-h` -- help output

.. `-s` -- scroll-back

+

When the display server is enabled and the script is started and/or
the FS is started, any log entries in the scroll-back buffer will also
be output. This may reduce the number of lines that might be lost when
the FS is started.

+

If the display server is not enabled, up to 20 (a little more than the
number of lines in the typical log header) old log lines will be
output when the script is started, the active file log is changed, or
the FS is started. This may result in some lines being output more
than once. It may reduce the number of lines that will be missed
during these transitions.
`
.. `-w` -- wait for FS start

+

Wait for the FS to start and/or continue to wait for the FS to be
restarted if it is terminated.

[NOTE]
=====

The limitations and considerations for why these options should _not_
be used in _stpgm.ctl_ are:

[disc]
* The '-d' option can be used in _stpgm.ctl_ if the display server is
in use. However, it would be safer to use the log output (no `-d`)
instead. If it is used without the display server enabled, it will
crash the FS immediately after start-up.

* The `-h` option is not useful in _stpgm.ctl_. Its use will cause the
FS to crash immediately after start-up.

* The `-s` option can be used in _stpgm.ctl_ but is of marginal value.
It may reduce the number of lines that might be lost at FS start-up.
With the display server not enabled, it may reduce the number of lines
lost at the transition to a new log.

* The `-w` option is not useful in _stpgm.ctl_ and will cause problems
in some cases if the display server is not enabled. It is best to
avoid it entirely in _stpgm.ctl_.

=====

Thanks to Dave Horsley (Hobart) for coming up with the idea for this
script, the initial version, and many of the incremental improvements.

====

. Improve _logpl_

+

An error was fixed that caused incorrect plots for the data from some
paired commands. The help output was improved.

+

[%collapsible]
====

.. Fix plotting of data from paired commands (closing
https://github.com/nvi-inc/fs/issues/182[#182]).

+

_logpl_ can plot data from paired commands. The first command of a
pair (its description in _logpl.ctl_ starts with a `$`) is associated
with the second of the pair (its description ends with `$`). _logpl_
selects the data to plot based on the first command. The next
following instance of the second command has the value to be plotted.
This can be useful for situations where one command identifies what is
being sampled (e.g., a BBC defined by `pcalports=`) and the data
values come from a second command (e.g., amplitude or phase for a
single sideband from `decode4/pcal`).

+

The problem arises if the corresponding second command is missing
(perhaps due to a time-out) before the next instance of the first
command. In that case, _logpl_ thinks the next occurring second
command should be used, even if the intervening first command
identifies different data. The result is that data from two different
selections may appear on one plot. That makes a mess.

+

This was fixed by invalidating the match of a first command if another
instance of it occurs, but with a different string value. This
prevents a match on the second command of a pair if the first command
of that pair with a different string has occurred since the original
first command with the right string.

.. Improve Help contents for the Main screen

+

The description of the three bottom buttons in the Plot Details box
was improved. This was primarily to say that the deleting of
individual points is with a double right-click instead of a
left-click. Other small improvements were made.

====

. Improve recommended NTP configuration

+

Change the `check_ntp` procedure to not use the `-n` option of _ntpq_.
Make aliases in _/etc/hosts_ for all NTP servers for easier reading of
`ntpq -p`.  Use aliases in _/etc/ntp.conf_ for easier viewing and
maintenance. Add information on how to redact server FQDNs and IP
addresses from log.

+

[%collapsible]
====

The recommended NTP configuration can be found in _misc/ntp.txt_. The
"`items`" listed in the following descriptions are where the change is
covered in that file.

..  Change the `check_ntp` procedure to not use the `-n` option of
_ntpq_

+

This allows descriptive names, instead of IP addresses, to be
displayed for servers by _ntpq_. Item `6a`.

+

The example _.prc_ files were updated to agree.

.. Make aliases in _/etc/hosts_ for all NTP servers for easier reading
of `ntpq -p`.

+

This defines descriptive aliases for `ntpq -p` to display. Item `6d`.

.. Use aliases in _/etc/ntp.conf_ for easier viewing and maintenance.

+

With the aliases defined in _/etc/hosts_, this avoids the need to use
IP addresses, which are harder to recognize. Without the defined
aliases, using IP addresses was necessary to avoid problems when there
is DNS outage. Item `2b`.

.. Add information on how to redact server FQDNs and IP addresses from
log.

+

If site IT policies prohibit public dissemination of FQDNs and IP,
this information can be used to keep that information out of the log
files, which are often uploaded to publicly accessible servers. Item
`6e`.

.. Make other minor wording improvememts.

====

. Include `rdbe30_mon.py`

+

This script, written by Russ McWhirter (Haystack), is very useful for
evaluating RDBE functionality. Russ has graciously agreed to allow it
to be distributed with the FS to simplify making it available to
stations that have RDBEs.

+

[%collapsible]
====

The (original) _python2_ version is available as
_/usr2/fs/misc/rdbe30_mon.py2_.  The _python3_ version is available as
_/usr2/fs/misc/rdbe30_mon.py_.

.. Some of its features are:

* When started, it opens four windows: `Command List`, `Command Log`,
`Monitor`, and `Plots`. The windows may be closed individually, but
closing the `Monitor` window will cause the program to exit. The
default positions of the windows can be set with command line options
(see below).

* Command line options:

+
[circle]

** `-h __multicast_host__`

** `-p __multicast_port__`

** `-H __RDBE_host__`

** `-P __RDBE_port__`

** `--command`, `--log`, `--monitor`, and `--plot` to set the X11
display geometry of the corresponding windows. Only the position of
the window should be set, e.g., `+0+0`, as the value for the option.

* An enable/disable plotting checkbox and a Phase-cal offset (MHz)
entry box on the `Plots` window. The plots shown are in order (from
the top):

+
[circle]

** Raw data
** FFT of raw date
** Histogram of raw data
** Time domain Extracted PCal (Complex)
** FFT of Extracted Pcal: Amplitude
** FFT of Extracted Pcal: Phase
** Count difference for Tcal: IF0, IF1

* The commands in the `Command List` window can be edited. Pressing
kbd:[F1], or right clicking, on a command will cause it to be sent to
the RDBE.

* Files:

+

+

These files are created in the current working directory. The value of
_<RDBE_ADDR>_ is the IP address of the RDBE.

** __rdbe30_monrc_<RDBE_ADDR>.db__ -- holds the geometry of the
windows between invocations of the script. Geometry values from
command line options override these.

** __rdbe30_mon_cmd_<RDBE_ADDR>.log__ -- holds a  record of the
commands sent to the RDBE and the responses.

** __rdbe30_mon_dat_<RDBE_ADDR>.log__ -- holds a record of the
multicast data received from the RDBE. This file can become quite
large.

.. Installation

... Install the `matplotlib` appropriate for your system's _python_
version, if not already included. This will need to be done by _root_.

+
[disc]

* Usually for _python2_:

  apt-get install python-matplotlib

* Usually for _python3_:

  apt-get install python3-matplotlib

... IMPORTANT: For the remainder of these instructions make sure you
are in the _oper_ account, switching if necessary.

... Copy the version that is correct for your system (for _python2_,
use `.py2` instead of `.py`) to your _~oper/bin_ directory.

 cp /usr2/fs/misc/rdbe30_mon.py ~oper/bin

... Place a line for each RDBE in your _clpgm.ctl_ control file. For
example, for RDBE-A (for _python2_, use `.py2` instead of `.py`):

 mona   d popen 'cd /tmp;rdbe30_mon.py -h 224.0.2.10 -p 20021 -H rdbea 2>&1' -n rdbemona

+

Substitute the correct multicast address (`-h`) and port (`-p`) for
your device. For other RDBEs, copy that line and make appropriate
changes (for example for RDBE-B: `mona` -> `monb`, `rdbea` -> `rdbeb`,
`rdbemona` -> `rdbemonb`, change the multicast address and port).

+

+

The `cd /tmp` in the line causes the script's files to be written to
(and read from) _/tmp_; so they won't clutter up other directories.
They will also be automatically deleted each time the system is
rebooted. You can place them in a different directory if you want to
preserve them.

+

+

TIP: You can control the initial placement of the windows by adding the
`--command`, `--log`, `--monitor`, and `--plot` options with
appropriate placement geometry values.

+

+

NOTE: The RDBE host address alias, in this example `rdbea`, must be
defined in _/etc/hosts_.

.. Running the script

+

IMPORTANT: The script should not be left running during operations. If
the plotting function is enabled, it is CPU intensive.

+

You can run the script from the operator input window, e.g., for
RDBE-A:

  client=mona

+

Exit the program by closing the `Monitor` window

.. The following changes were needed for the _python3_ version:

* Change `import` of `NavigationToolBar2TkAgg` to
`NavigationToolBar2Tk`

* Change log file output to buffered

* Use `draw()` instead of `show()`

* Use data `encode()`/`decode()` for socket I/O

* Select real part of complex array for plotting to eliminate warning

* Remove use of `buffer()` to linearise an array.

====

. Make miscellaneous improvements (some internal) to _pfmed_.

+

The visible improvements are largely making the terminology in program
messages related to procedure libraries consistent, but some bugs were
fixed too. The internal improvements are mostly to make the handling
of FORTRAN `character` variables in subroutines work for arbitrary
length variables passed in as arguments.

+

[%collapsible]
====

The visible changes include:

[disc]
* In program messages, the term "`active`", as opposed to "`open`", is
always used for the procedure library that _pfmed_ is currently
working on.

* In program messages, the term "`library`", as opposed to "`file`",
is always used for a procedure library, except for some file oriented
error messages. Error messages in _boss_ related to procedure
libraries were also made consistent.

* The FS `help` command pages for the `schedule` and `proc` commands
were updated to be consistent with the above terminology.

* A "`key`" was added to the end of the `pfdl` command output to
describe the prefix letters before the library names (`>`, active in
_pfmed_; `A`, the current FS schedule library; `S`, the current FS
station library, always `station`). These prefix letters now displayed
correctly.

* Fix `pfst` command to trap the "`old`" library not existing.
Previously, it would be created as an empty library.

* Fix `pfst` command to allow copying of the library that is the
active library in _pfmed_. This was broken for _gfortan_ which allows
a file to be open to only one unit, but worked for _fort77_ (which
uses _f2c_). It now works independently of the compiler being used.
This had previously been fixed for the `st` command in commit
`ec03102e02ee2525243dfc3fba57981c6781f139` for FS _9.13.1_ in August
2019.

* Improve detection of the FS being active if it is started while
_pfmed_ is running, which is apparently okay. There may still be some
race conditions for this situation.

* Improved the error message for _pfmed_ already being in use.

* A missing error message for no procedure library being active was
restored.

The internal changes include:

[disc]
* Making `character` arguments of subroutine independent of the actual
length of the passed variable. This was very helpful for making the
change in the procedure library name lengths.

* Make the lengths of character variables consistent with their usage
for procedure names, procedure library names, and file extensions.
This was very helpful for making the change in the procedure library
name lengths.

* Improve the code for the `ds` command. This included fixing
`character` subroutine arguments to be adjustable, removing Hollerith
use of `character` variables, and cleaning-up edges cases for the
bubble-sort.

* Make the same terminology consistency improvements ("`active`" and
"`library`") in the code and comments that are visible to the user.

====

. Make miscellaneous small bug fixes and improvements

+

[%collapsible]
====

.. Fix `-help` command line option for _gnplt_ (closing
https://github.com/nvi-inc/fs/issues/184[#184]).

+

This option was fixed to provide a synopsis of the command line
arguments instead of failing entirely.

+

Thanks to Jon Quick (HartRAO) for reporting this bug.

.. Fix _gnplt_ error message for the GUI crashing to mention `gnplt`
rather than `LogPlotter`.

.. Remove redundant class number clearing, which only occurred after
an error, when setting the AGC in _onoff_ for DBBC2s and DBBC3s.

+

The could potentially have caused clearing of a class number that was
already in use for something else. The chances of a problem were
pretty low.

.. Demote `if` and `setup_proc` commands from being _immediate_
execution commands (closing
https://github.com/nvi-inc/fs/issues/189[#189]).

+

If entered interactively, they would execute immediately even if there
was a time block on the operator command stream. This was not an issue
for the schedule stream, where they were normally used, since that
stream doesn't have the functionality of immediate execution commands
and in a schedule they are normally used in procedures. As a result,
the old behavior was benign for schedules.

.. Change description (title) for `cable` in the default _logpl.ctl_
file to not include `length`.

+

_logpl_ plots the raw `cable` data, not converted to length.

.. Improve the help page for `cont_cal` for the DBBC3

+

The only polarity values that should be used are `0` and `2`.

+

Thanks to Sven Dornbusch (MPIfR) for this clarification.

.. Improve `help` page for the `setup_proc` command,

+

Minor wording improvements.

.. Improve the description of the `use_setup_proc` _drudg_ option in
the
<<../1/dbbc3_ops.adoc#_minimizing_the_use_of_setup_procedures,Minimizing
the use of setup procedures>> appendix of the
<<../1/dbbc3_ops.adoc#,FS 10.1 DBBC3 Operations Manual>> document.

.. Improve the description of the `thread__suffix__` procedure in the
<<../1/dbbc3_ops.adoc#_thread_procedure,Thread Procedure>> appendix of
the <<../1/dbbc3_ops.adoc#,FS 10.1 DBBC3 Operations Manual>> document.

+

This included adding a description of the `ds` added to the
`datastream` label for the file name and that it stays lowercase all
the way to the file name.

.. Set the home directory permissions for AUID accounts to `0750`.

.. Add documents <<../1/10.1.1.adoc#,FS 10.1.1 Update Notes>> and
<<../0/10.0.1.adoc#,FS 10.0.1 Update Notes>> for new patches releases.

.. Modify document <<../1/10.1.0.adoc#,FS 10.1.0 Update Notes>> to
_not_ change default branch to _main_ when preserving the old
repository if it was cloned around June 5, 2022 or later.

+

In this case, the default is already _main_.

.. Add a *TIP* for managing directory names of FS installations from
archives in the
<<../../misc/release_model.adoc#_installing_from_an_archive,Install
from an archive>> subsection of the
<<../../misc/release_model.adoc#,Release Model>> document.

+

Making a copy as a new directory before making any local changes can
make it easier to track changes and which version is in use.

.. Add a *TIP* for how to avoid losing your place in a *Details*
toggle for a FS or _drudg_ change list item when following a link
(basically: right-click and open a new tab). This was added to the
<<../1/10.1.0.adoc#improve_presentation,Improve presentation>> FS
change sub-item (if that link doesn't work in your browser, the *TIP*
is copied below) of the <<../1/10.1.0.adoc#,FS 10.1.0 Update Notes>>
document.  The *TIP* added is:

+

****

TIP: An alternative to avoid this is to right click the link, then
open it in a new tab, and then click on that tab. To return to the
original document, you can close the new tab or click on the original
document's tab, whatever you prefer.

****

.. Add explanation of how to navigate to a link in *Details* toggle in
a different document, if the browser doesn't support going to it
directly. This was added to the
<<../1/10.1.0.adoc#improve_presentation,Improve presentation>> FS
change sub-item (if that link doesn't work in your browser, the text
is copied below) of the <<../1/10.1.0.adoc#,FS 10.1.0 Update Notes>>
document.  The text added is:

+

****

* Links that point into a *Details* toggle in a different document do
not work in all browsers. To help with that, if the relevant text is
small it is reproduced within an embedded sidebar block (grey
background). Otherwise, a second link to the title of the item with
the toggle is provided along with instructions to follow the link
(probably opening it in a new tab would be best), open the toggle, and
then search for the anchor text of the original link.

****

.. Add explanation for generating an _ssh_ key for _scp_ commands when
converting to 64-bit.

+

The <<../../../misc/64-bit_conversion.adoc#,Converting to a 64-bit
System>> document was updated.

.. Update instructions in the _making_gh-pages.txt_ file for the
current default branch, _main_.

====

=== drudg changes

_drudg_ opening message date is `2023-02-21`.

. Make typographic changes for the new _f95_ version in FSL11.

+

[%collapsible]
====

These are similar to changes described in the <<f95,f95>> FS change
item (if that link doesn't work in your browser, click on this link
instead: <<FSL11,FSL11>>, open the *Details* toggle below that
location by clicking on it, go `Back` in the browser, and finally
click on the original link). There were only a few octal constants
outside of `parameter` statements and these were in simple assignment
statements. All octal constants were wrapped in `int()`. There were no
`and()` statements with mixed sized ``integer``s. There were no
hexadecimal or binary constants at all.

====

. Accept input schedule files (_.skd_ and _.vex_) with up to 16
characters before the dot (`.`) for the extension.

+

This change was made to agree with <<Names,Names>> FS change item
above.

. Prepend `ds` to the _name_ (second) parameter in the
`datasteram=add,{thread},*` command in the single-thread-per-file
`thread__suffix__` SNAP procedure for VDIF recording.

+

[%collapsible]
====

The command now reads: `datastream=add,ds{thread},*`. This change is
intended to be forward compatible with emerging file naming
conventions for recorded data. For more information on the
`thread__suffix__` SNAP procedure, see the
<<../1/dbbc3_ops.adoc#_thread_procedure,Thread Procedure>> appendix of
the <<../1/dbbc3_ops.adoc#,FS 10.1 DBBC3 Operations Manual>> document.

====

. Make miscellaneous small bug fixes and improvements

+

[%collapsible]
====

.. Improve _skdrut/errormsg.f_ to avoid problems with bounds checking
by not hard-coding the `character` argument's length.

.. Fix _skdrut/trimlen.f_ to prevent problems with bounds checking if
the string is blank.

.. Fix _drudg/snap.f_ to use the experiment name internal to the file
rather than from the filename.

.. Fix _drudg/strip_path.f_ to check for enough space to store the
file name.

====

[appendix]

= Update NTP Configuration

Although the use of NTP on the FS computer is strongly encouraged for
most situations, this entire appendix is optional.

The recommended NTP configuration is described in _misc/ntp.txt_. If
you have not implemented it before, you can use the information there
to do so.

As of FS _10.2_ the recommendations have been improved. If you have
previously used those recommendations, this appendix describes how to
update your implementation for the improvements. You should review the
directions below, and the contents of _misc/ntp.txt_ to which they
refer, before deciding what to do. The "`items`" listed in the
following descriptions are where the change is covered in that file.

. As _root_:

.. Add aliases for all your NTP servers to _/etc/hosts_. Item `6d`.

.. Change your _/etc/ntp.conf_ file to use the aliases in _/etc/hosts_.
Item `2b`.

.. Restart _ntpd_.

+

For _init.d_ systems, FSL9 and earlier, you can use:

 /etc/init.d/ntp restart

+

For _systemd_ systems, FSL10 and later:

 systemctl restart ntp

+

Rebooting is an option for restarting NTP on any system.

.. Verify NTP operation (any user can do this)

... Check to make sure you get the expected servers listed by `ntp
-p`.

+

If not, you may need to recheck you definition of aliases in
_/etc/hosts_ and their use in _/etc/ntp.conf_;

... Check that the `remote` for each server is an alias.

+

+

+

If not, you may need to adjust your _/etc/hosts_ file.

. As _oper_:

.. Update your `check_ntp` procedure to not use the `-n`
option of _ntpq_. Item `6a`.

+

You can also expand the list of servers that are displayed by
adjusting the _grep_ command in the procedure. The details are covered
in item `6a`.

.. Optionally, redact FQDNs and IP addresses from the output of
`check_ntp`. Item `6e`.

+

Some sites may have IT policies that require this, but it may be
prudent for everyone to implement it,

.. Verify the output of `check_ntp`.

... Make sure the `remote` field is the  alias, not the IP address,
for each server.

+

+

If not, you may not have removed the `-n` option from `ntpq  -np` to
make it `ntpq -p`.

... If you intended to redact IP addresses from the output, make sure
no IP addresses appear, but instead the string `REDACTED`. You can
compare to `ntpq -p` run from a shell, which will not have `REDACTED`.

+

+

+

If you still get IP addresses from `check_ntp`, then you may need to
fix the use of the filter in item `6e`.
