//
// Copyright (c) 2020-2025 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= FS 10.2 to Latest Commit Update Notes
Version 1.7 - July 2025

:sectnums:
:stem: latexmath
:sectnumlevels: 4
:experimental:

:toc:

== Introduction

The document covers updating from FS _10.2_ to the _latest commit_ on
its branch. The latest commit is experimental. We make every effort to
keep the latest commit usable, but any commit that is not tagged for
release is not intended for operations. The intended use of this
document is to collect update information, as it becomes available,
before the next release.

IMPORTANT: Commits that are not tagged for release may have
significant issues including: not building, crashing, and
incompatibilities with operational observation schedule files. Such
commits are intended for testing only. _Let the user beware._

CAUTION: It is expected that those using the latest commit are experts
and will manage the differences for updating to the next official
release themselves. No specific documentation will be provided. What
commit was last updated to will determine what needs to be done. It
might work to verify that all the steps in the official release update
notes were completed. However, that may not be complete. _Let the user
beware._

This document is up to date with the
`6be435f6120bca47231cbf968a4b5b730b7e8f7a` (`6be435f6`) commit. Due to
small increments, such as updating this document, that may not be the
literal last commit, but the differences should be small unless you
happen to `pull` between a significant change and this document being
updated.

== Upgrading from 10.2 to the latest commit

//IMPORTANT: Since there are no commits beyond the `10.2.0` commit yet,
//there is nothing to do and you should ignore his entire document. The
//instructions below are placeholders.

You must have already upgraded to _10.2.0_ according to the
<<10.2.0.adoc#,FS 10.2 Update Notes>> document before installing
this update.

=== Fetch the latest commit

//IMPORTANT: Since there are no commits beyond the `10.2.0` commit yet,
//there is nothing to do and you should ignore skip this entire
//document. The instructions below are placeholders.

There are two alternatives:

. If you are using FSL9, FSL10, FSL11, or another system that supports
connections to _github_ and you are using _git_ (as is recommended)
then as _prog_ execute:

 cd /usr2/fs-git
 git fetch
 git checkout -q 6be435f6

. If you are using FSL8, or otherwise unable to use _git_:

+

//IMPORTANT: Since there are no commits beyond the `10.2.0` commit yet,
//there is nothing to do and you should ignore skip this entire
//document. The instructions below are placeholders.

+

Please follow the steps, through the step that includes the option to
set the _/usr2/fs_ link, in the
<<../../misc/release_model.adoc#_installing_from_an_archive,Installing
from an archive>> subsection in the
<<../../misc/release_model.adoc#,Release Model>> document. Please note
that:

+
[disc]

* For FSL8, you will need the *TIP* in the `*wget*` step.

* For the __tag__ in the `*wget*` and `*tar*` commands, use the short
SHA for the commit. For example, for commit under discussion here,
`6be435f6120bca47231cbf968a4b5b730b7e8f7a`, use `6be435f6`.

* After extracting the archive, change the name of the output
directory to use the latest feature release and the short SHA of the
commit, like _fs-10.2.0-76-g6be435f6_ (note the _g_ before the short
SHA), which will then be used in the following `*cd*` command. For
example (kbd:[Tab] completion is your friend for the long SHA):

 cd /usr2
 mv fs-6be435f6120bca47231cbf968a4b5b730b7e8f7a fs-10.2.0-66-g6be435f6
 cd /usr2/fs-10.2.0-76-g6be435f6

* You will end the "`installing from an archive`" with the step
setting the link for __/usr2/fs__ by running *`make install`*.

=== Make the FS

As _prog_:

 cd /usr2/fs
 make clean rmdoto rmexe all >& /dev/null
 make -s

No output from the last command indicates a successful _make_.


=== Update your station code.

Except if noted otherwise, these steps should all be performed as
_prog_. Click on the *Details* toggle in each item for the needed
steps.

. If your station code depends on `none` indicating that no schedule
and/or no schedule procedure file are in use, you need to make
changes. Most stations, possibly all, won't need to make any changes.

+
[%collapsible]
====

There are two situations in which local code will need to be updated:

[disc]

* If it compares the shared memory variables `LSKD2` and `LPRC2` (or
`LSKD` or `LPRC`) to `none` to determine that no schedule or schedule
procedure library is active, the comparison(s) will need to be changed
to use spaces.

* If it filters the log (or display) output to determine if no
schedule or schedule procedure library is active, it will need to be
changed to accept a null field (i.e., empty, not even spaces), instead
of `none` in the `schedule/` and `proc/` output.

====

=== Make the station software

The layout of some variables in shared memory has changed. Even if you
have not updated your station code, you should re-_make_ it to be
safe. If _/usr2/st/Makefile_ is set-up in the standard way, you can do
this with (as _prog_):

 cd /usr2/st
 make rmdoto rmexe all

=== Reboot

This step is not needed at this time.

IMPORTANT: This will make sure shared memory is reallocated.

=== Additional steps

Except if noted otherwise, these should all be performed as _oper_.
Click on the *Details* toggle in each item for the needed steps.

. If your SNAP procedures use the `if=schedule:none...` command to
test for no schedule being active, you need to make changes. Most
stations, possibly all, won't need to make any changes.

+
[%collapsible]
====

If the `if=schedule:none...` command is used to determine that no
schedule is active, the `:none` will need to be removed and the `true`
and `false` commands swapped. Additionally, embedded spaces are no
longer supported and a second colon, `:`, is now considered part of the
schedule name.

====

. For DBBC(2) and DBBC3 stations, make sure that the AGC is restored
after scans for legacy calibration.

+
[%collapsible]
====

Add the following to `postob` in the `station` procedure library:

 if=cont_cal,,ifagc
 if=cont_cal,,if=ddc\,bbc_gain=all\\\,agc

====

. Optionally, update the comments in your _.rxg_ files to correctly
show the correct maximum number of T~cal~ table entries allowed.

+
[%collapsible]
====

A script, _/usr2/fs/misc/rxgfix4_, has been provided for this. If the
original version of the affected comments have been preserved, they
will be updated to the new form. Only the comments immediately before
the active T~cal~ entries will be updated.

Execute:

 cd /usr2/control/rxg_files
 /usr2/fs/misc/rxgfix4 *.rxg

If the script stops because there are existing _.bak_ files, you can
delete them, if it is safe to do so,  by adding the `-d` option (see
`*/usr2/fs/misc/rxgfix4{nbsp}-h*` for the details) to the command
_before_ the files to be updated. If it is not safe to delete them,
you could, for example, rename them to end in _.bak2_ with
`*rename{nbsp}'s/.bak$/.bak2/'{nbsp}++*++.rxg.bak*` first. The
_rename_ command, by default, will not overwrite existing files, but
you might want to check that your new ending is not already in use for
some _.rxg_ backup files to avoid possibly mixing different
"`generations`" of backups.


NOTE: If you don't have the (_perl_ based) _rename_ command, you can
install it on FSL__x__ systems as _root_ with
`*apt-get{nbsp}install{nbsp}rename*`.

====

. Optionally, add the new day-of-year aliases. _dj_ and _lj_, to your
shells.

+
[%collapsible]
====

Execute the commands for all the shells that you use, typically just
your login shell:

[disc]

* _bash_ -- The default login shell for FSL10 and FSL11 (and
possibly later):

 cd ~
 tail -2 /usr2/fs/st.default/oper/.bash_aliases >>.bask_aliases

* _tcsh_ -- The default login shell for FSL8 and FSL9:

 cd ~
 tail -2 /usr2/fs/st.default/oper/.cshrc >>.cshrc

You will need to exit any active shell (including possibly logging out
and back and in again) to make the aliases active.

You may also wish to make these changes for _prog_ (and any AUID
accounts).

====

. Optionally, install the  _fsy_ utility for use with the display
server to conditionally start the client if the FS is already running.

+
[%collapsible]
====

To install this script, execute:

  cp /usr2/fs/misc/fsy cd ~oper/bin

If you are using a remote connection and would like to open a new
window to run the FS (or client) in, comment out the "`normal`" `if`
clause and uncomment the command for a new window. In either case, if
you use AUID accounts, you must promote to _oper_ before running the
script.

====

. Optionally, update the `check_ntp` SNAP procedure for the new,
simpler, standard.

+
[%collapsible]
====

The updated _/usr2/fs/misc/ntp.txt_ file describes the new form and
how to install the needed scripts, all in sections 6a and 6e. Please
use those directions as a guide if you want to update.

====

== Changes since 10.2.0

There are separate subsections below with summaries of the changes in
the FS and _drudg_.

Clickable links such as https://github.com/nvi-inc/fs/issues/36[#36]
connect to specific issues reported at
https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ working directory, usually _/usr2/fs-git_.

Each change is listed as a numbered summary typically followed by a
"`Details`" _toggle_, like:

[%collapsible]
====
Details are shown here.
====

that can be clicked on to toggle showing (or not showing) a
collapsible box with the details. In this way, you can view the
summary as a list and only reveal the details of items that interest
you. The collapsible box may be omitted if providing further details
didn't seem warranted. The collapsible boxes for the details may also
have nested collapsible boxes inside them if there are many sub-items.

=== FS changes

. Fix bug in `mk5_status` (and `fb_status`) command when handling long
recorder `error?` query responses (closing
https://github.com/nvi-inc/fs/issues/234[#234]).

+
[%collapsible]
====

In the `mk5_status` (and `fb_status`) command, if an `error?` query
response was too long to fit in the buffer (`256` characters), the
basic checks on its format could generate an error. If so, the class
number that had been allocated to return previous `status?` (and
possibly other  `error?`) responses would not be passed back to the
caller to be processed, leaving the class number in limbo (a class
number leak). After about 35+ of these errors there would be no class
numbers left and the FS would crash.

Additionally, the `error?` response was not reported to the caller
preventing it from being displayed for relatively easy identification
of the underlying recorder error.

The cause of the problem was actually more general in nature. Any
error in the process of getting the `error?` response (or in the
process of getting a `status?` response after the first), could also
cause a class number leak.

In addition to fixing these two class number leaks, some other small
improvements were made:

[disc]

* The buffer size was increased `1024` characters.

* The error message for an incorrectly formatted `status?` and
  `error?` response was revised to say that it was a format error and
  that it could have been due to truncation. Previously, it just said
  there was no reply, which is a different case.

* The available response when a formatting error is detected is
  returned to the caller for display.

* The error number codes of the `mk5_status` command were moved to an
  `include` header to make them accessible in more than one file of
  code without duplicating them. This was helpful for returning the
  available response where there was a formatting error.

* If the command ends with a processing error so that it is not known
  whether there are remaining recorder errors to process, the error
  report says there _may_ be errors yet to process, instead of that
  there _are_.

This fix was also included in the _10.2.1_ patch release.

Thanks to Jon Quick (HartRAO) for reporting this bug and testing the
fix.

====

. Fix bug in the `terminate` command (closing
https://github.com/nvi-inc/fs/issues/226[#226]).

+
[%collapsible]
====

Sometimes the `terminate` command would incorrectly not, in fact,
terminate the FS when using the display server. Instead it would give
an `un{nbsp}{nbsp}{nbsp}{nbsp}2` (and ultimately a `bo{nbsp}-176`)
error. This happened when the FS was checking to make sure _autoftp_
and _fs.prompt_ weren't active. Workarounds were:

[disc]

* Trying `terminate` again. More than one try may have been needed.

* Using `terminate=force`. That should have worked in all cases
(except _pfmed_ being active), but would defeat the check for
_autoftp_ and _fs.prompt_ being active. So it had to be used with
care.

This bug was triggered by a process file disappearing from _/proc/_
after it was found in the directory and before it was opened for
reading to see if it was for an instance of _autoftp_ or _fs.prompt_.
There was usually only a very small time window in which this could
happen. The code was aware of this case, but there was a bug in how it
was handled.

This fix was also included in the _10.2.1_ patch release.

====

. Fix bug in the display server shim for _xterm_ on FSL11, restoring
use of _autoftp_ (closing
https://github.com/nvi-inc/fs/issues/218[#218]).

+
[%collapsible]
====

The conversion to _python3_ for FSL11 (_bullseye_) missed
_fsserver/shims/xterm_. As a result, it was not possible on FSL11
systems to use _autoftp_ (or `sy=xterm ...`, which should be avoided
anyway). The simple fix for this was to make separate _python2_ and
_python3_ versions, like the other _python_ scripts in FS _10.2_.
This bug only occurred for FSL11 systems (and other systems that use
FS _python3_ support).

This fix was also included in the _10.2.1_ patch release.

====

. Fix bug in the `satellite=...` command that prevented temporary TLE
files from being closed (closing
https://github.com/nvi-inc/fs/issues/220[#220]).

+
[%collapsible]
====

When cleaning up at the end of processing, `satellite=...` commands
were not closing the temporary TLE files. As a result, if many of the
commands were used in a single invocation of the FS, the limit on the
number of open files could be reached, causing subsequent
`satellite=...` commands to fail. This situation could happen, e.g.,
if many of the commands were used sequentially to approximate
continuous tracking.

This fix was also included in the _10.2.1_ patch release.

Thanks to Jamie McCallum and David Schunck (both at Hobart) for
finding this, reporting it, and providing the fix.

====

. Add missing restoration of AGC in DBBC3 `postob` for legacy
calibration (closing https://github.com/nvi-inc/fs/issues/231[#231]).

+
[%collapsible]
====

For legacy calibration, it is necessary to hold the gains fixed during
a scan so that sampled TPI values can be related to the most recent
T~sys~ measurement. At the end of the scan, the gains should be
released to seek an appropriate level for the next scan. For the
DBBC(2), this is done by the next mode setup. However for the DBBC3,
`setup_proc` keyword in _skedf.ctl_ is normally used to suppress the
setup procedure for most scans. Instead, the gains can be released in
`postob`.

To accomplish this, the following was added to the example `postob`
for DBBC3:

 if=cont_cal,,ifagc
 if=cont_cal,,if=ddc\,bbc_gain=all\\\,agc

The same addition was also made for DDBC(2) since it is benign and the
`setup_proc` keyword might be used.

The updated example files in _/usr2/fs/st.default/proc/_ are
_d3fbstation.prc_, _dstation.prc, dfbstation.prc,_ and
_d5cstation.prc_.

Thanks to Christian Plötz (Wettzell) for pointing out that this was
missing and Beppe Maccaferri (Medicina) for confirming the fix.

====

. Fix bug in reporting time from DBBC3 multicast (closing
https://github.com/nvi-inc/fs/issues/224[#224]).

+
[%collapsible]
====

This was a mostly cosmetic (but pretty unsightly) bug that occurred in
certain situations. For DDC_V firmware, which does not have multicast
time, it caused spurious times to be displayed. While for non-DDC_V
(DDC_E/DDC_U) firmware, which does have time available, it caused the
time to be suppressed. This was due to an error in FS initialization
in _10.2.0_. The two situations where the bug occurred were:

[disc]

*  When using only DDC_V firmware, the first time the FS was run after
rebooting.

*  When switching between DDC_V firmware and a non-DDC_V firmware
(DDC_E/DDC_U), in either direction, the first time the FS was run
after the change in _equip.ctl_.

This bug did not occur if only non-DDC_V firmware was used.

There was a fairly simple workaround for this bug. It was to terminate
and restart the FS before using it, after:

[disc]

*  A reboot, when only using DDC_V firmware

*  Changing _equip.ctl_, when switching between DDC_V firmware and a
non-DDC_V firmware (DDC_E/DDC_U), in either direction.

This fix was also included in the _10.2.1_ patch release.

Thanks to Jon Quick (HartRAO) for reporting this bug.

====

. Stop attempting to receive RDBE multicast messages when the selected
rack type is not `rdbe` (closing
https://github.com/nvi-inc/fs/issues/225[#225]).

+
[%collapsible]
====

When the selected rack type is not `rdbe` it doesn't make sense to
process multicast messages from RDBEs. Before, this was only disabled
if no RDBEs were defined in the _rdbc<x>.ctl_ control files. Doing
that was necessary to avoid error messages if the RDBEs were not
transmitting multicast for some reason. However, having to remove the
definitions when RDBEs were not in use makes it cumbersome to switch
between RDBEs and other rack types. Additionally, not having the RDBEs
defined disables any access to RDBEs, specifically with the `rdbe=`
and `rdbe__x__=` low-level device communication commands.
Traditionally for flexibility, the FS has allowed low-level
communication with devices that were not selected.

Thanks to Javi González-García (Yebes) for reporting this oversight.

====

. Move the `onoff` command's testing for valid LOs for RDBE detectors
to when the _onoff_ program is started.

+
[%collapsible]
====

Previously when using RDBE detectors with _onoff_, the LOs being valid
was only tested for when setting up _onoff_ (`onoff=...`) for `all`
detectors. It was not tested for other detector selections. It is only
necessary that the LOs  be valid when _onoff_ is started (`onoff`) and
all selected detectors should be checked. That is also the time when
the LO and other channel information is collected. This supports
changing the configuration of the channels after _onoff_ is setup,
which is consistent with how other racks are handled.

====

. Fix bug in the reporting of the `MA -104` error that caused an
extraneous `(  -4)` to be displayed in the error message.

+
[%collapsible]
====

The `MA -104` error is a warning that there may be a 30 second delay
while a possible serial line error is worked around at the start-up of
_matcn_. The value of an argument in the call to report the error had
a value of `-4` instead of, the correct value, `0`.

====

. Issue warning if only one processor is in use (closing
https://github.com/nvi-inc/fs/issues/178[#178] and
https://github.com/nvi-inc/fs/issues/228[#228]).

+
[%collapsible]
====

The display server requires at least two processors (cores) to operate
properly. The issue occurs in server termination. Occasionally,
termination occurs normally even when there is only one processor.

Typically this problem only occurs if the FS is being run in a virtual
machine with only one processor. Virtual machines can usually be
reconfigured to have more processors.

It should be possible to make it work with one processor, but that
hasn't been implemented yet. Until then, if there is only one
processor available, warning messages (with hints about what to do)
are printed at FS startup and when restarting fails because apparently
a previous instance of the server failed to terminate.

Thanks to Christian Plötz (Wettzell), Uwe Bach (Effelsberg) and Javi
González-García (Yebes) for reporting this issue. Thanks to David
Horsley (Hobart) for diagnosing the cause when it was first reported
(issue https://github.com/nvi-inc/fs/issues/178[#178]).

====

. Add detector device `none` to the `fivept` and `onoff` commands for
exercising/testing an antenna without a signal chain.

+
[%collapsible]
====

Normally, the `fivept` and `onoff` commands are used to collect
pointing and antenna sensitivity data, respectively. This requires
some sort of signal chain and detector device. The latter is usually
in the back-end rack. If no detector is available, or doesn't produce
useful radiometry data, it is now possible to exercise/test the
antenna with `acquire` by using device `none` in the `fivept` and
`onoff` setup commands. In this case, there will be no detector
interaction.

Sample procedure library file _st.default/proc/point_no_det.prc_ and
control file _st.default/control/ctlpo_no_det.ctl_ are provided as
examples for using `none` as detector. They are mentioned in the
`help` pages for `fivept` and `onoff` as a reminder.

====

. Add _rdbemsg_ emails to experiment log as comments (closing
https://github.com/nvi-inc/fs/issues/213[#213]).

+
[%collapsible]
====

Including the emails in the log avoids having to enter comments from the
email messages a second time to get them into the log.

When originally written (by Jason Soohoo, Haystack Observatory), the
program that became _rdbemsg_ did not run on FS computers and could
not easily add comments to the log. Due to on oversight when the
program was ported to FS computers, adding the email message to the
log, as _msg_ does, was not added. This has been corrected for both
the _python2_ and _python3_ versions of _rdbemsg_.

Thanks to the staff at KPGO for reporting this issue.

====

. Add `-p` option to _popen_ for streamlined log output.
+
[%collapsible]
====

The _popen_ program is used to log the output of Linux programs. A
`-p` option was added to replace the `+#popen#+` string at the start
of log entries with `/` (the logging system inserts the `/`). This
makes the log entries look like the output of internal FS commands.
Its use is not necessary and is not recommended in most circumstances.
However, it does look better, particularly for replacements of
internal FS commands line `wx`. Information on using the _popen_
program can be found from `*help=sy*`.

Thanks to Jon Quick (HartRAO) for conceiving, and providing an
implementation, of this change,

====

. Restore `-b` startup option as `-C` (closing
https://github.com/nvi-inc/fs/issues/216[#216]).

+
[%collapsible]
====

The removal of the `-b` option in FS _10.2.0_ was a bit too hasty. The
long form of the option was `--background`, which suggested that it
was the inverse of `--foreground`. This was not the case. With the
server enabled, it started the FS without a client. This might be
convenient to use for starting the FS from a script or otherwise
without the log being displayed on the terminal. A pitfall of using it
is that there is no feedback about the whether the FS started
correctly or had a start-up error and aborted. As a result, this
option must be used with caution.

To make it clearer that it does not start the client, the short option
was changed to `-C` (_not_ client) and the long option to
`--no-client`. The help output now includes a warning about the lack
of feedback for startup errors.

Thanks to Christian Kristukat (AGGO) for reporting the loss of
functionality when the `-b` option was removed. Thanks to Beppe
Maccaferri (Medicina) for pointing out the possible pitfall.

====

. Comment out all lines in example _mdlpo.ctl_ and _parpo.ctl_ files
(closing https://github.com/nvi-inc/fs/issues/214[#214]).

+
[%collapsible]
====

This prevents these example files being used accidentally with values
that are incorrect for a new installation. Instead, the pointing
analysis programs and/or _antcn_ (while reading the default
_mdlpo.ctl_) will fail until the files have been setup with (hopefully
reasonable) values for the antenna. While this may make the first time
use for a new antenna a little painful, it is better than having
incorrect values being used.

====

. Improve recovery for loss of an open log file.

+
[%collapsible]
====

.. Handle the open log file being replaced by a file that is renamed
to the open log file's name.

+

Previously automatic lost log file recovery worked if either the log
file open in the FS have been deleted (_rm_) or renamed (_mv_). It did
not cover the case of a different file being renamed to have the name
of the open file. That latter most case is now detected by comparing
the ``inode``s of the open log file and the file with the name of the
open log. If they don't agree they aren't the same file. In that case,
the open log file will be recovered to a file with __recovered_
appended to the original name. If a file with that name already
exists, the log will instead be recovered to a file with:

+
[subs="+quotes"]
....
__recovered.<XXXXXX>_
....

+

appended at the original name, where `_<XXXXXX>_` is a random string,
chosen by the kernel, that makes the filename unique, e.g., _3fDhIa_.

+

There is a consequence of this feature that may not initially appear
to be intuitive. It occurs if the user was re-opening the original
file (with `log=...` or `schedule=...`) when the `inode` mismatch was
discovered. In this case, new log entires will be appended to the file
with the original name (regardless of what was already in it), not the
recovered log file. The recovery process doesn't know what the new (if
there is one) log file's name is, but will print a message warning
about this possibility, which can occur whenever the recovery file's
name includes _recovered_. Will all this in mind, this may not be so
unintuitive after all.

+

[WARNING]
=====

The case of an open log file being overwritten by copying onto it
(_cp_) is not handled. So it is not possible to automatically recover
the log in that case. It should still be possible to recover, most, if
not all, of a log lost in this way using the technique described in
_/usr2/fs/misc/logrecovery.txt_

Two possible approaches to prevent overwriting by copying (_cp_) onto
an open log are described in the *Details* collapsible box below.
Neither have been implemented at this time.

[%collapsible]
======

Two possible solutions to this are:

. Use _chattr_ to make the open log file _append_ only.

+

The approach would be for _ddout_ to use _chattr_ to set _attribute_
`+a` on the log file after opening to make it append only. When the
log is closed, it would be changed to `-a` to allow the file to be
used normally thereafter. It is probably necessary to include
`O_APPEND` in the _flags_ for `open()` calls in _ddout_ in case for
some reason `-a` was not applied (probably a crash) when a log was
closed. To employ this method, it is necessary to give _chattr_ the
capability to set the append attribute (as _root_):

 setcap cap_linux_immutable=eip /usr/bin/chattr

+

There are two minor drawbacks to this approach:

.. If an existing log file is owned by a different user (perhaps
_prog_), the attributes can't be changed.

.. If the attribute is not changed back to `-a` (perhaps due to a
crash), the file becomes very difficult to work with (no
renaming/moving, editing, compressing, etc.) until that is corrected.

. Use mandatory file locking to prevent overwriting of the open log
file.

+

In this case, the _/usr2_ partition must be mounted with the `mand`
option. _ddout_ would create new logs with a _mode_ including
`S_ISGID`. It should set the _mode_ of an existing file that it opens
to include `S_ISGID` Then it would need to lock the entire file
(`.l_whence = SEEK_SET`; `.l_start = 0`, `.l_len = 0`) for reading
(`.l_type = RDLCK`). When the log is closed, _ddout_ would clear its
`setgid` bit.

+

There are four minor drawbacks to this approach:

.. If an existing log file is owned by a different user (perhaps
_prog_), the `setgid` bit can't be set/cleared.

.. If the `setgid` bit is not cleared (perhaps due to a crash), it
will follow the file, including being compressed or renamed, until
that is corrected.

.. Mandatory file locking is not considered reliable, but the example
cases where there may be problems do not seem relevant to this use.

.. Although not deprecated, it seems as though mandatory file locking
may be headed to extinction.

======

=====

.. Make recovery more robust.

+

Previously if errors were detected while determining if the log file
existed, recovery would be aborted. The code has been restructured to
not give up for this case or for a problem determining the `inode`
values. It now aborts only if an unrecoverable error occurs in the
process of recopying the log contents. Making the recovery as robust
as possible is prudent since this is the only chance to accomplish
this.

.. Update _/usr2/fs/misc/logrecovery.txt_ note.

+

This note provides an alternate recovery process that may be helpful
if the automatic process isn't sufficent. It has been updated to also
cover more modern systems and to include more specific steps. This
approach was originally suggested by Pablo de Vicente (Yebes).

.. Make miscellaneous improvements:

+

[disc]
* Simplify recovery logic
* Show recovery activity even if a percentage can't be shown
* Make error reports more consistent
* Report partial recovery even if an error occurred

====

. Improve overall _Makefile_ (closing
https://github.com/nvi-inc/fs/issues/212[#212]).

+
[%collapsible]
====

In FSL11, the `*make{nbsp}install*` command would fail if the source
directory was not owned by _root_. While this situation would not
normally occur, it could if the `*make{nbsp}install*` was executed a
second time after an initial installation. This might happen, for
example, if `*make{nbsp}install*` were used to reset the _/usr2/fs_
link. The failure occurred because of a confluence of two issues: (i)
_git_ was unnecessarily used to determine the version of the FS with
the `install` target and (ii) the  version of _git_ in FSL11, and
probably later versions, will throw an error if the directory is not
owned by the user. The problem was resolved by removing the use of
_git_ to determine the FS version for `*make{nbsp}install*`.

Thanks to Jon Quick (HartRAO) for reporting this issue.

Two further enhancement were made:

[disc]

* `*make{nbsp}install*` can only be used by _root_ and `install` is
the only _make_ target allowed for _root_.

* When installing from an archive, if the source directory name is
incorrectly formed (missing the tag information), an explanatory error
will be reported and the _make_ will be aborted.

====

. Prevent _root_ from running the FS.

+
[%collapsible]
====

The FS is a user application. It is risky, and a potential security
issue, to run it as _root_. In particular, the `sy=...` command, if
misused either accidentally or on purpose, could cause serious damage.
To avoid this, the FS startup program, _fs_, the server, _fsserver_,
and the client program, _fsclient_, will refuse to run if the user is
_root_. This is not strictly necessary for the client, but it was
included for consistency. Off-line utilities, including _pfmed_, can
still be run by _root_, but this is not recommended and should be
avoided. It may lead to problems. However, it would not be inherently
dangerous.

====

. Create shell aliases for _date_ and _ls_ command output with
day-of-year and 24-hour time display.

+
[%collapsible]
====

Two new shell aliases were added:

[disc]

* _dj_ -- Display the current date/time (down to the seconds) in the
same format as used by FS logs as well as some additional date
information. This might be useful if the day-of-year and/or 24-hour
time are not readily visible elsewhere. Example output:

 Mon 2025.104.13:44:54 UTC (Apr 14)


* _lj_ -- Display an _ls -l_ listing with the date/time field (down to
the seconds) in the same format as used by FS logs. This is intended
to help associate logs with the day-of-year they were used when
troubleshooting. It can be combined with other _ls_ flags. For
example, the _-t_ flag can used and the output piped to _less_ to show
the logs, newest first, one page at a time:

 cd /usr2/log
 lj -t | less

====

. Add _fsy_ utility for conditionally running _fsclient_ if the FS is
already active.

+
[%collapsible]
====

This utility can be found in _misc/fsy_. It can installed in
_~oper/bin_. It will check to see if the client can be run (i.e. FS is
running and display server is enabled). If not, it will start the FS.
It can be useful for systems using the display server to start the FS
if it is not already running or the client if it is. There is some
risk associated with this since you will not get obvious feedback if
the FS is not running and you expect it to be. However, you may prefer
to not have to enter a separate command to run the FS if attempting to
start the client (_fslcient_) first fails.

The script includes commented out commands that you can use instead if
you prefer to open a new window to run the FS or client in. This may
be useful for some remote connections.

CAUTION: For systems with AUID accounts, it is necessary to promote
_oper_ before running the script.

Thanks to Chevo Terrazas (MGO) for pointing out the overall usefulness
of this script, which was originally only provided as a site-specific
ad hoc tool.

====

. Add utilities to simplify the `check_ntp` SNAP procedure.

+
[%collapsible]
====

New scripts, _grep_ntpq_, _cname_ntpq_ip_, and _redact_ntpq_ip_ were
added to simplify (i.e., make more readable and easier to maintain)
the `check_ntp` SNAP procedure.  The updated _/usr2/fs/misc/ntp.txt_
file describes the new form and how to install the new scripts, all in
sections 6a and 6e.

====

. Remove using `none` as the displayed _name_ when no schedule or no
schedule procedure library is in use (closing
https://github.com/nvi-inc/fs/issues/222[#222]).

+
[%collapsible]
====

Previously when no schedule and schedule procedure library was in use,
`none` was displayed as the _name_ in the  output of the `schedule`
and `proc` commands, respectively. Also, in _pfmed_'s preamble, the
`current{nbsp}FS{nbsp}schedule{nbsp}procedure{nbsp}library` was shown
as `none`. This came about because the FS used `none` internally when
there was no active file. This was inconsistent and could be confusing
because `none` was also an allowed name for schedules and schedule
procedure libraries. This was corrected by making the following
changes:

.. A string of spaces is now used internally to indicate no file is
use.

.. The `schedule` and `proc` commands now display the _name_ as a null
field (i.e., empty, not even spaces) when no schedule or schedule
procedure library, respectively, is in use.

.. Spaces are no longer allowed in these names. Actually, they weren't
before, but this only became apparent when the low-level RTE-A
emulation file routines truncated the name at the first space and
attempted to use a file with the shorter name. That might lead to a
difficult to understand error message if the file didn't exist or
unexpected behavior if it did. This is now trapped at the highest
level and an appropriate error message is given.

.. The `if=schedule:...` command was updated to no longer use `none`
as the schedule name to test if no schedule is active. The use of
embedded spaces in the schedule name are no longer supported. If a
second colon, `:`, is used, it will now be interpreted as part of the
name. See `*help=if*` for more information on the `if` command.

.. _pfmed_ was updated to agree with the changes above. This included
making the `current{nbsp}FS{nbsp}schedule{nbsp}procedure{nbsp}library`
in the preamble display `no{nbsp}library{nbsp}is{nbsp}selected` when
there is none.

.. Some other small incidental improvements were made to _pfmed_:

... Empty input at the main prompt no longer prints an obscure error
message before re-prompting.

... The check of the length of a second library name in `pf__xx__,...`
commands is now correct. It was still eight characters.

... The length of the optional `_library_` in the
`st,...[::__library__],...` command is now checked. It wasn't before.

.. Additionally, a few error messages for _boss_ were fixed to refer
to schedules and schedule procedure libraries more consistently.

The consequences of these changes for existing FS installations is
fairly limited. It seems unlikely they will affect anyone, but to be
complete, they are listed here:

.. If any station software compares the shared memory variables
`LSKD2` and `LPRC2` (or `LSKD` or `LPRC`) to `none` to determine that
no schedule or schedule procedure library is active, the comparison(s)
will need to be changed to use spaces.

.. If any station software filters the log (or display) output to
determine if no schedule or schedule procedure library is active, it
will need to be changed to accept a null field (i.e., empty, not even
spaces), instead of `none` in the `schedule/` and `proc/` output.

.. If any station uses the `if=schedule:none...` command to determine
that no schedule is active, they will need to remove `:none` from the
command and swap the `true` and `false` commands. No embedded spaces
are allowed, and a second colon, `:`, is now considered part of the
schedule name.

The positive outcome of all this is that the schedule and schedule
procedure library names are now handled consistently. The use of
`none` is not recommended for either since that may be confusing, but
the behavior will now be clearer and predictable.

====

. Update comments in _.rxg_ files for the current maximum number of
T~cal~ table entries (closing
https://github.com/nvi-inc/fs/issues/211[#211]).

+
[%collapsible]
====

The comments in the example _.rxg_ files
(_/usr2/fs/st.default/control/rxg_files/*.rxg_) had not kept up with
the expansion of the size of the T~cal~ table, first from `400`
entries to `600` and then `1200`. The files have now been updated.

A script, _/usr2/fs/misc/rxgfix4_, has been provided for optional use
to update the working _.rxg_ files at station. If the original version
of the comments, with `400`, have been preserved, they will be updated
to the new form. Only the comments immediately before the active
T~cal~ entries will be updated. Lines that list `100` and `600` as the
maximum will also be updated. The former was apparently the size in
some preliminary versions before the first official release (_9.6.9_,
September 2003, commit `7c26ea900dee19b01958e5c4ad846b89d64638c5`)
that supported _.rxg_ files. The latter was never provided as an
example, but is covered just in case. See
`*/usr2/fs/misc/rxgfix4{nbsp}-h*` for the details.

====

. Remove bad characters from ASCII files.

+
[%collapsible]
====

A few ASCII files had non-ASCII characters in them.

[disc]

* There were UTF-8 characters in _help/core3h_mode.j___ and
_misc/logrecover.txt_. They were removed.  They did not display
properly on non-UTF-8 systems, principally FSL9 and earlier.

* The extended ASCII character for angstroms (&Aring;) was incorrectly
specified in the _help/lvdt.*_ files. It was replaced with the word.

====

. Add patch release _10.2.1_.

+
[%collapsible]
====

Please see the <<10.2.1.adoc#,FS 10.2.1 Update Notes>> document for
the details. All of the changes in that patch release have already
been merged into the _main_ branch and will be included in the _10.3_
release when it becomes available.

====

. Improve web documents

+
[%collapsible]
====

.. Add a sub-step to update the comments for rack types in _equip.ctl_
in the FS _10.1_ and FS 10.2 updates notes. Updating the comments is
strictly speaking optional, but not doing so could lead to confusion
later since the available DBBC3 rack types were changed in both of
those updates. The previous omission of these sub-steps  was an
oversight.

+

Thanks to J. Gonzalez (Yebes) for pointing out that these sub-steps
were missing.

.. Add examples for non-breaking spaces and hyphens to the Font
Conventions.

.. Miscellaneous wording and typographic corrections were made to the
_10.2_ documents

====

=== drudg changes

There are no _drudg_ changes yet.
