//
// Copyright (c) 2020-2023 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= FS 10.2-beta1 to FS 10.2-beta2 Update Notes
Version 0.72 - June 2023

:sectnums:
:stem: latexmath
:sectnumlevels: 4
:experimental:

:toc:

== Introduction

This document covers the steps needed to update from FS _10.2-beta1_
to _10.2-beta2_  and the changes in the new version.  Installing the
new version (see the <<Upgrading from 10.2-beta1>> section below)
is simpler than the update to _10.2-beta1_.

IMPORTANT: Despite the next paragraph, _alpha_ and _beta_ releases are
not intended for operations.

FS _10.2_ has been tested for a few configurations but not all
possible ones. You should test it carefully before using it for
operations. Please email Ed if you encounter problems so that we can
resolve them.

The changes in the FS and _drudg_ for _10.2-beta2_ are covered in the
<<Changes since 10.2-beta1>> section below. The most significant
changes are:

== Upgrading from 10.2-beta1

You must have already upgraded to _10.2-beta1_ according to the
<<10.2-beta1.adoc#,FS 10.2-beta1 Update Notes>> document before
installing this update.

=== Fetch 10.2-beta2

There are two alternatives:

. If you are using FSL9, FSL10, FSL11, or another system that supports
connections to _github_ and you are using _git_ (as is recommended)
then as _prog_ execute:

 cd /usr2/fs-git
 git fetch
 git checkout -q 10.2.0-beta2

. If you are using FSL8 or are otherwise unable, or prefer not, to use
_git_ (you will probably need to be _root_):

+

Refer to the
<<../../misc/release_model.adoc#_installing_from_an_archive,Installing
from an archive>> subsection in the
<<../../misc/release_model.adoc#,Release Model>> document. Follow the
steps there, through the one that includes the option to set the
__/usr2/fs__ link. Please note that:

+
[disc]

* For FSL8, or if you are otherwise unable to connect to _github_, you
will need the *TIP* in the `*wget*` step.

* For the __tag__ use `10.2.0-beta2`.

* You will end using the "`installing from an archive`" procedure with
the step setting the link for __/usr2/fs__ by running *`make
install`*.

=== Login as prog

If you are not already logged-in as _prog_, do that. This is necessary
for the remaining steps until <<Reboot>>.

=== Make the FS

As _prog_:

 cd /usr2/fs
 make clean rmdoto rmexe all >& /dev/null
 make -s

No output from the last command indicates a successful _make_.

=== Make the station software

The layout of some variables in shared memory has changed. Even if
you have not updated your station code, you should re-_make_ your
station code to be safe. If _/usr2/st/Makefile_ is set-up in the
standard way, you can do this with (as _prog_):

 cd /usr2/st
 make rmdoto rmexe all

=== Reboot

IMPORTANT: This will make sure the FS server is stopped and shared
memory is reallocated.

== Changes since 10.2-beta1

There are separate subsections with summaries of the changes in the FS
and _drudg_.

Clickable links such as https://github.com/nvi-inc/fs/issues/36[#36]
connect to specific issues reported at
https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

Each change is listed as a numbered title, usually with a few summary
sentences, followed by a "`Details`" _toggle_, like:

[%collapsible]
====
Details are shown here.
====

that can be clicked on to toggle showing (or not showing) the details.
In this way, you can view the summary as a list and only reveal the
details of items that interest you. The summary sentences and/or the
details toggle may be omitted if they would not add any new
information, usually because it is already covered in the numbered
title item, summary, and/or the details are very brief.

=== FS changes

No changes so far.

=== drudg changes

_drudg_ opening message date is `2023-02-21`.

No changes so far.
