//
// Copyright (c) 2020-2022 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= FS 10.1.0 to Latest Commit Update Notes
Version 4.0 - August 2022

:sectnums:
:stem: latexmath
:sectnumlevels: 4
:experimental:

:toc:

== Introduction

The document covers updating from FS _10.1.0_ to the _latest commit_
on its branch. The latest commit is experimental. We make every effort
to keep the latest commit usable, but any commit that is not tagged
for release is not intended for operations. The intended use of this
document is to collect update information, as it becomes available,
before the next release.

IMPORTANT: Commits that are not tagged for release may have
significant issues including: not building, crashing, and
incompatibilities with operational observation schedule files. Such
commits are intended for testing only. _Let the user beware._

CAUTION: It is expected that those using the latest commit are experts
and will manage the differences for updating to the next official
release themselves. No specific documentation will be provided. What
commit was last updated to will determine what needs to be done. It
might work to verify that all the steps in the latest version of this
document, appropriately renamed as an update from the old release to
the new release, were completed. An alternate, but not necessarily
complete, approach would be to review the update steps in the new
release to make sure everything has been covered. _Let the user
beware._

This document is up to date with the `03c5571` commit. Due to small
increments, such as updating this document, that may not be the
literal last commit, but the differences should be small unless you
happen to `pull` between a significant change and this document being
updated.

== Upgrading from 10.1.0 to the latest commit

You must have already upgraded to _10.1.0_ according to the
<<10.1.0.adoc#,FS 10.1.0 Update Notes>> document before installing
this update.

=== Fetch and make the latest commit and make station code

. Update the FS

+

If you are using _git_, as is recommended, then as _prog_ execute:


             cd /usr2/fs-git
             git checkout main
             git pull
             make clean rmdoto rmexe all >& /dev/null
             make -s

+

No output from the last command indicates a successful _make_.

. Reload your station code.

+

TIP: This step is not required at this time.

+

If _/usr2/st/Makefile_ is set-up in the standard way, you can do this
with:

       cd /usr2/st
       make rmdoto rmexe all

=== Reboot

This will make sure the FS server is restarted.

=== Additional steps

Except if noted otherwise, these steps should all be performed as
_oper_.

There are no additional steps yet.

=== Review changes

Please see the <<Changes since 10.1.0>> section below for the details
of the changes since that release.

== Changes since 10.1.0

There are separate sub-sections with summaries of changes in the FS
and _drudg_.

Clickable links such as
https://github.com/nvi-inc/fs/issues/36[#36] connect to specific issues
reported at https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

Each change is listed as a numbered title, then usually a few summary
sentences, followed by a _toggle_:

[%collapsible]
====
Details are shown here.
====

that can be clicked on to toggle showing (or not showing) the details.
In this way, you can view the summary as a list and only reveal the
details of items that interest you. The summary sentences and/or the
details toggle may be omitted if they would not add any new
information, usually because it is already covered in the numbered
title item and/or the details are very brief.

=== FS changes

. Improvements to _logpl_

+

An error was fixed that caused incorrect plots for the data from some
paired commands. The help output was improved.

+

[%collapsible]
====

.. Fix plotting of data from paired commands (closing
https://github.com/nvi-inc/fs/issues/182[#182]).

+

_logpl_ can plot data from paired commands. The first command of a
pair (its description in _logpl.ctl_ starts with a `$`) is associated
with the second of the pair (its description ends with `$`). _logpl_
selects the data to plot based on the first command. The next
following instance of the second command has the value to  be plotted.
This can be useful for situations where one command identifies what is
being sampled (e.g., a BBC defined by `pcalports=`) and the data
values come from a second command (e.g., amplitude or phase for a
single sideband from `decode4/pcal`).

+

The problem arises if the corresponding second command is missing
(perhaps due to a time-out) before the next instance of the first
command. In that case, _logpl_ thinks the next occurring second
command should be used, even if the intervening first command
identifies different data.  The result is that data from two different
selections may appear on one plot. That makes a mess.

+

This was fixed by invalidating the match of a first command if another
instance of it occurs, but with a different string value.  This
prevents a match on the second command of a pair if the first command
of that pair with a different string has occurred since the original
first command with the right string.

.. Improve Help contents for the Main screen

+

The description of the three bottom buttons in the Plot Details box
was improved. This was primarily to say that the deleting of
individual points is with a double right-click instead of a
left-click. Other small improvements were made.

====

. Improvements to _plotlog_

+

The default plot device for an X11 display was changed to be useful.
The plotting of `fmout-gps` and `gps-fmout` data was changed to
`fmout-gps`. The `-h` help output was improved.

+

[%collapsible]
====

.. Change the plot device for X11 displays to `/xw` (closing
https://github.com/nvi-inc/fs/issues/183[#183]).

+

If the `DISPLAY` variable is set and no other plog device was
specified, the program assumes it should be plot on the X11 display.
The old default X11 plot device, `/xterm`,  didn't work. That device
apparently worked for some pre-FSL8 distribution. For as far back as
FSL8 `/xterm` seems to be available, but doesn't work. So this has
probably been a problem since at least 2009. _plotlog_ was introduced
(using `/xterm`) in FS _9.8.0_ (July 2005) with commit
52398939d5f867b2e7ab4e18f8886babda6dfaae. FSL5 (_woody_) was probably
active at that time. `/xw` now seems to be a good choice in FSL8 and
later.

.. Change plotting of `fmout-gps` and `gps-fmout` data to `fmout-gps`.

+

All of the `fmout-gps` and `gps=fmout` data were combined in a single
`gps-fmout` plot. This was changed to a single `fmout-gps` plot, which
agrees with the `clock_early` convention used by the correlators.

.. Improved the `-h` help output.

+

A suggestion for a file name extension for the `/vps` device was
added. The explanation of the `-2` option improved. How to set the
background and foreground plot colors was added. That can be used to
change the background color from black, which is used by default for
the X11 display with some FSL__x__.

====

=== drudg changes

There are no _drudg_ changes yet.

