//
// Copyright (c) 2020-2022 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= FS 10.1.0 to Latest Commit Update Notes
Version 3.9 - January 2022

:sectnums:
:stem: latexmath
:sectnumlevels: 4
:experimental:

:toc:

== Introduction

The document covers updating from FS _10.1.0_ to the _latest commit_
on its branch. The latest commit is experimental. We make every effort
to keep the latest commit usable, but any commit that is not tagged
for release is not intended for operations. The intended use of this
document is to collect update information, as it becomes available,
before the next release.

IMPORTANT: Commits that are not tagged for release may have
significant issues including: not building, crashing, and
incompatibilities with operational observation schedule files. Such
commits are intended for testing only. _Let the user beware._

CAUTION: It is expected that those using the latest commit are experts
and will manage the differences for updating to the next official
release themselves. No specific documentation will be provided. What
commit was last updated to will determine what needs to be done. It
might work to verify that all the steps in the latest version of this
document, appropriately renamed as an update from the old release to
the new release, were completed. An alternate, but not necessarily
complete, approach would be to review the update steps in the new
release to make sure everything has been covered. _Let the user
beware._

This document is up to date with the features in the `10.1.0` commit.
Due to small increments, such as updating this document, that may not
be the literal last commit, but the differences should be small unless
you happen to `pull` between a significant change and this document
being updated.

== Upgrading from 10.1.0 to the latest commit

You must have already upgraded to _10.1.0_ according to the
<<10.1.0.adoc#,FS 10.1.0 Update Notes>> document before installing
this update.

=== Fetch and make the latest commit and make station code

. Update the FS

+

If you are using _git_, as is recommended, then as _prog_ execute:


             cd /usr2/fs-git
             git checkout main
             git pull
             make clean rmdoto rmexe all >& /dev/null
             make -s

+

No output from the last command indicates a successful _make_.

. Reload your station code.

+

If _/usr2/st/Makefile_ is set-up in the standard way, you can do this
with:

       cd /usr2/st
       make rmdoto rmexe all

=== Reboot

This will make sure the FS server is restarted.

=== Additional steps

Except if noted otherwise, these steps should all be performed as
_oper_.

There are no additional steps yet.

=== Review changes

Please see the <<Changes since 10.1.0>> section below for the details
of the changes since that release.

== Changes since 10.1.0

There are separate sub-sections with summaries of changes in the FS
and _drudg_.

Clickable links such as
https://github.com/nvi-inc/fs/issues/36[#36] connect to specific issues
reported at https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

=== FS changes

There are no FS changes yet.

=== drudg changes

There are no _drudg_ changes yet.

