//
// Copyright (c) 2020-2022 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= FS 10.1.0 to Latest Commit Update Notes
Version 4.1 - October 2022

:sectnums:
:stem: latexmath
:sectnumlevels: 4
:experimental:

:toc:

== Introduction

The document covers updating from FS _10.1.0_ to the _latest commit_
on its branch. The latest commit is experimental. We make every effort
to keep the latest commit usable, but any commit that is not tagged
for release is not intended for operations. The intended use of this
document is to collect update information, as it becomes available,
before the next release.

IMPORTANT: Commits that are not tagged for release may have
significant issues including: not building, crashing, and
incompatibilities with operational observation schedule files. Such
commits are intended for testing only. _Let the user beware._

CAUTION: It is expected that those using the latest commit are experts
and will manage the differences for updating to the next official
release themselves. No specific documentation will be provided. What
commit was last updated to will determine what needs to be done. It
might work to verify that all the steps in the latest version of this
document, appropriately renamed as an update from the old release to
the new release, were completed. An alternate, but not necessarily
complete, approach would be to review the update steps in the new
release to make sure everything has been covered. _Let the user
beware._


This document is up to date with the `5bc44f23` commit. Due to small
increments, such as updating this document, that may not be the
literal last commit, but the differences should be small unless you
happen to `pull` between a significant change and this document being
updated.

== Upgrading from 10.1.0 to the latest commit

You must have already upgraded to _10.1.0_ according to the
<<10.1.0.adoc#,FS 10.1.0 Update Notes>> document before installing
this update.

=== Fetch and make the latest commit and make station code

. Update the FS

+

If you are using _git_, as is recommended, then as _prog_ execute:


             cd /usr2/fs-git
             git checkout main
             git pull
             make clean rmdoto rmexe all >& /dev/null
             make -s

+

No output from the last command indicates a successful _make_.

. Reload your station code.

+

TIP: This step is not required at this time.

+

If _/usr2/st/Makefile_ is set-up in the standard way, you can do this
with:

       cd /usr2/st
       make rmdoto rmexe all

=== Reboot

This will make sure the FS server is restarted.

=== Additional steps

Except if noted otherwise, these steps should all be performed as
_oper_.

There are no additional steps yet.

=== Review changes

Please see the <<Changes since 10.1.0>> section below for the details
of the changes since that release.

== Changes since 10.1.0

There are separate sub-sections with summaries of changes in the FS
and _drudg_.

Clickable links such as
https://github.com/nvi-inc/fs/issues/36[#36] connect to specific issues
reported at https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

Each change is listed as a numbered title, then usually a few summary
sentences, followed by a _toggle_:

[%collapsible]
====
Details are shown here.
====

that can be clicked on to toggle showing (or not showing) the details.
In this way, you can view the summary as a list and only reveal the
details of items that interest you. The summary sentences and/or the
details toggle may be omitted if they would not add any new
information, usually because it is already covered in the numbered
title item and/or the details are very brief.

=== FS changes

. Fix _plog_ to support sending multiple files to BKG (closes
https://github.com/nvi-inc/fs/issues/186[#186]).

+

[%collapsible]
====

Due to a bug, _plog_ was unable to send multiple files to BKG in one
invocation. The result was that none were sent.

Thanks to Kiah Imai (KPGO) for reporting this and testing the fix.

====

. Shutdown display server on `terminate`.

+

When the display server is in use, terminating the FS now also
shutdowns the server. An interlock was introduced to prevent
termination if it would also stop active _autoftp_ and/or _fs.prompt_
instances.

+

[%collapsible]
====

Previously, if the display server was in use, it continued running in
background when the FS was terminated; now it will shutdown. Not
shutting down was introduced in commit
`85b24dc67111d82371c3fd0b850b19174840e0e4`, and first released in FS
_10.0.0_, as part of a larger scheme to serve client web pages. In the
short-term that plan is not being followed through on and the change
had some negative impacts for local use. Manually stopping the server
was required in certain cases:

* If _antcn_, or another local program opens an X11 application, say
for example, for a dialog box to let the operator select the antenna,
and later an operator on a different display wants to restart the FS.
In that case the X11 application would attempt, to reopen on the
original display.

* To update the environment variables used by the FS

* To change the user that owns the FS processes

Manually stopping the server is no longer required in these, or any
other, cases.

An implication of stopping the server is that any running _autoftp_
and _fs.prompt_ processes will also be terminated. This is
undesirable, especially in the case of _autoftp_ since any active data
transfers would be terminated. To avoid this, an interlock was
introduced. When the server is in use and any _autoftp_ or _fs.prompt_
instances are active, termination will be prevented with explanatory
error messages. If it is necessary terminate, an override parameter,
`force`, can be used:

 terminate=force

To keep things simple, the previous override parameter,
`disk_record_ok`, for terminating if disk recording is active has been
eliminated and that functionality is now included in the `force`
parameter as well. See `*help=terminate*` for more explanation.

The interlock for preventing termination if _pfmed_ is active was
moved to be before the interlocks that can be overridden with `force`.
It is not possible to override the _pfmed_ interlock and there is no
point using `force` if termination will be blocked by _pfmed_ anyway.

The <<../../../misc/env_vars.adoc#_runtime_variables,Runtime
variables>> section of the <<../../../misc/env_vars.adoc#,FS
Environment Variables>> document was updated to reflect this change.

====

. Add _streamlog_ utility.

+

The _streamlog_ utility is a script that outputs log entries as they
are written. It can be used by itself or with other programs that
filter for specific log entries. It will provide the most complete
output when the display server is enabled, but should also be useful
when it is not.

+

[%collapsible]
====

By default, if the FS is already running, the script will output log
entries to `stdout` (for simple interactive use, this is the user's
terminal) as they are generated. A small number of entries may be lost
when the FS is started. When the display server is not enabled, a
small number of entries may be lost when the active log is changed.

The script has four command line options:

. `-d` -- display stream

+

This option is only available if the display server is enabled. It
outputs the display server stream instead of the log stream. The
display stream is what is displayed in the log display window by the
FS client. There are several differences between what is is shown in
the log display window and what goes in the log. The most significant
of these are:

* The log display output uses a shorter time-tag field.

* Some output lines are suppressed in the log display window because
they would be overwhelming and would generally not be helpful for
interactive use.

* Some FS error messages are not shown in the log display window
because the operator has suppressed them with the `tnx` command.

* The log display window includes some output that is no in the log,
specifically the FS startup and termination messages and some program
error messages.

. `-h` -- help output

. `-s` -- scroll-back

+

When the display server is enabled and the script is started and/or
the FS is started, any log entries in the scroll-back buffer will also
be output.

+

If the display server is not enabled, up to 20 (a little more than the
number of lines in the typical log header) old log lines will be
output when the script is started, the active file log is changed, or
the FS is started. This may result in some lines being output more
than once. It may reduce the number of lines that will be missed
during these transitions.
`
. `-w` -- wait for FS start

+

Wait for the FS to start and/or continue to wait for the FS to be
restarted if it is terminated.

There are some limitations and considerations when _streamlog_ is used
in the _stpgm.ctl_ file:

* The `-h` option is not useful in this situation. Its use in
_stpgm.ctl_ will cause the FS to terminate immediately after start-up.

* The `-s` option can be used, but is generally not useful unless the
display server is not enabled. Even then it is of marginal value in
_stpgm.ctl_.

* The `-w` option is not useful and will cause problems in some cases
if the display server is not enabled. It is best to avoid it entirely
in _stpgm.ctl_..

Thanks to Dave Horsley (Hobart) for coming up with the idea for this
script, the initial version, and most of the incremental improvements.

====

. Improve _logpl_

+

An error was fixed that caused incorrect plots for the data from some
paired commands. The help output was improved.

+

[%collapsible]
====

.. Fix plotting of data from paired commands (closing
https://github.com/nvi-inc/fs/issues/182[#182]).

+

_logpl_ can plot data from paired commands. The first command of a
pair (its description in _logpl.ctl_ starts with a `$`) is associated
with the second of the pair (its description ends with `$`). _logpl_
selects the data to plot based on the first command. The next
following instance of the second command has the value to be plotted.
This can be useful for situations where one command identifies what is
being sampled (e.g., a BBC defined by `pcalports=`) and the data
values come from a second command (e.g., amplitude or phase for a
single sideband from `decode4/pcal`).

+

The problem arises if the corresponding second command is missing
(perhaps due to a time-out) before the next instance of the first
command. In that case, _logpl_ thinks the next occurring second
command should be used, even if the intervening first command
identifies different data. The result is that data from two different
selections may appear on one plot. That makes a mess.

+

This was fixed by invalidating the match of a first command if another
instance of it occurs, but with a different string value. This
prevents a match on the second command of a pair if the first command
of that pair with a different string has occurred since the original
first command with the right string.

.. Improve Help contents for the Main screen

+

The description of the three bottom buttons in the Plot Details box
was improved. This was primarily to say that the deleting of
individual points is with a double right-click instead of a
left-click. Other small improvements were made.

====

. Improve _plotlog_

+

The default plot device for X11 displays was changed to be useful.
The plotting of clock data was expanded. Plots of wind speed and
direction were added. Plotting CDMS data was added. T~sys~ plots for
DBBC3s and RDBEs were added. Phase-cal tone plots for RDBEs were
added. Plots of LSB Mark IV decoder phase-cal data were added. The
`-y` option was added to delete phase-cal phases outside
[-180°,+180°]. Bad horizontal tick marks in some `-p` plots were
fixed. Clock and cable values outside (-10,+10) seconds are now
automatically deleted, but can be included with the `-C` option. Any
values in time plots that did not decode are now consistently
displayed at the upper edge of the plots. Some command line options
were changed. The `-h` (help) output was improved. The version was
bumped to _2.0_. Some improvements were made in the code.

+

[%collapsible]
====

.. Change the plot device for X11 displays to `/xw` (closing
https://github.com/nvi-inc/fs/issues/183[#183]).

+

If the `DISPLAY` variable is set and no other plot device was
specified, the program assumes it should plot on the X11 display. The
old default X11 plot device, `/xterm`, didn't work. That device
apparently worked for some pre-FSL8 distribution. For as far back as
FSL8 `/xterm` seems to be available, but doesn't work. So this has
probably been a problem since at least 2009. _plotlog_ was introduced
(using `/xterm`) in FS _9.8.0_ (July 2005) with commit
52398939d5f867b2e7ab4e18f8886babda6dfaae. FSL5 (_woody_) was probably
active at that time. `/xw` now seems to be a good choice in FSL8 and
later.

.. Expand clock plotting.

+

The clock plotting was expanded to plot all data collected by commands
with names that contain `fmout`, `gps`, and `maser`. Additionally,
RDBE `dot2pps` and `dot2gps` data from multicast and `dbe_pps_offset`
and `dbe_gps_offset` commands are plotted. The DBBC3 `pps2dot` data
from multicast and the `mcast_time` command are plotted. For the RDBE
and DBBC3, if both command stream and multicast versions are
available, only the multicast is plotted unless the `-B` option is
used, which will include both.

+

Opposite signed versions of the same offset (e.g. `gps-fmout` and
`fmout-gps`) are no longer combined in one plot (with appropriately
adjusted signs). Keeping them separate makes the plots more
representative of the log contents.

+

Thanks to Karine Le Bail and Rüdiger Haas (both at Onsala) for
arranging to produce experiment logs with `mcast_time` data for
testing.

.. Add plotting of wind speed and direction.

+

If fields for these data are present in the `wx/` log entries they
will be plotted. This is in contrast to temperature, pressure and
humidity, which are always plotted if `wx/` entires are present.
Missing values for any fields are shown as "`out-of-range`" (along the
top-edge of the corresponding plot).

.. Add plotting of CDMS data.

+

The raw units are picoseconds.

.. Add plotting of RDBE and DBBC3 T~sys~ values from multicast.

+

By default, only the data from the first encountered detector, other than
channel zero, from each IF band is plotted. The `-m`, and `-M`,
options can be used to select, and deselect, different sets of
detectors based on regular expressions. This is similar in function to
the `-g`/`-G` options (the latter, formerly the `-e` option), except
`-m`/`-M` only apply to RDBE and DBBC3 T~sys~ data and are applied as
are they are read-in instead of when they are plotted. This makes them
a bit faster since there are typically many values involved.

.. Add plotting of RDBE phase-cal data from multicast

+

By default, only the first encountered tone from each IF is plotted.
The `-d`, and `-D`, options can be used to select, and deselect,
different sets of tones based on regular expressions. This is similar
in function to the `-g`/`-G` options (the latter, formerly the `-e`
option), except that `-d`/`-D` are only applied to RDBE phase-cal
tones and are applied as they are read-in instead of when they are
plotted. This makes them a bit faster since there are typically many
values involved.

+

The `-j` (T~sys~ normalization) and `-k` options are not supported for
RDBE phase-cal yet.

+

The (new) `-v` option plots phase differences between tones in the
same RDBE IF channel.

.. Add plotting of the first encountered LSB phase-cal tone per
channel from video/baseband converters.

+

This is in addition to the already supported first encountered USB
tone per converter.

+

For phase difference plots (options `-lanw`) when both USB and LSB
tones are present, the differences for only one tone per converter are
plotted. If USB and LSB is present for an individual converter, the
difference between the side-bands is plotted after the differences for
pairs of different converters.

.. Add option `-y` to remove phases outside [-180°,+180°].

+

This can helpful when Mark IV decoder communication errors occur.

.. Fix bad horizontal ticks for `-p` option.

+

Previously except for the last page, there was an extra set of
horizontal tick marks in the bottom plot on each page. Additionally,
the horizontal tick labels on these pages were for the extra set of
ticks. This has been fixed. There is no extra set of tick marks and
the labels are correct.

.. Reject clock and cable values outside (-10,10) seconds

+

These are generally not useful values, but can be included if needed
with the new `-C` option. Normally they only occur if a counter is
being used and a bad value is returned.

.. Always display values that don't decode on the upper edge of the plots.

+

Previously for some data types, specifically `cable`, `rx`, `sx`, `sk`
and `fmout-gps`, samples were omitted if they did not decode as
floating point numbers. Now they are displayed on the upper edge of
the plot, as occurs for data types, so their presence is visible. The
only cases where samples are completely omitted now is when the form
of the entry is too garbled to be identified or the command is missing
(possibly because it timed-out). These two situations may be
noticeable if the plot for a data type is missing entirely or is
sparser than expected.

.. Change the command line options.

+

In addition to adding the `-B`, `-C`, `-d`/`-D`, `-m`/`-M`, and `-y`
options as mentioned above, the following changes were made:

... The old `-e` option was moved to `-G` for parallel construction
with `-d`/`-D` and `-m`/`-M` and to make room for the new `-e` option.

... The new `-e` option can be used to specify the rack type as
`dbbc3` or `rdbe`, This can be useful for DBBC3 and RDBE log snippets
that don't contain an `equip` line near the start. This only affects
DBBC3 and RDBE T~sys~, and RDBE phase-cal, processing.

... The new `-l` option can used to specify the location, which is
only used in the plot titles. This can be useful for log snippets that
don't contain a `location` line.

... The old `-v` (version) option was moved to `-V` to make room for
the `-v` option.

.. Improve the `-h` help output.

+

... A suggestion for a file name extension for the `/vps` device was
added.

... The explanation of the `-2` option was improved.

... How to set the background and foreground plot colors was added.

+

+

This can be used to change the background/foreground colors from to
white/black from black/white. The latter are used by default for the
X11 display with some FSL__x__.

... An explanation was added that out-of-range phase values in the
`-p` plots are placed on the right-hand edge of the plots.

.. Bump version number to _2.0_.

.. Improve the code

+

A few internal improvements were made:

... The efficiency of finding the `location` log record was improved
by only parsing for it if it has not been found before (and was not
specified by `-l`). As a result, only the first one encountered (or
the `-l` value) is used now.

... The help output was changed to a multi-line string for easier
maintenance.

... The order of options in the `Getopts` call was alphabetized.

... Removing DOS end-of-lines (to help with files that were
transferred via machines with such end-of-lines) was improved so that
it did not need to be handled in each search string.

====

. Fix `-help` command line option for _gnplt_ (closing
https://github.com/nvi-inc/fs/issues/184[#184]).

+

This option was fixed to provide a synopsis of the command line
arguments instead of failing entirely.

+

Thanks to Jon Quick (HartRAO) for reporting this.

. Add explanation for generating an _ssh_ key for _scp_ commands when
converting to 64-bit.

+

The <<../../../misc/64-bit_conversion.adoc#,Converting to a 64-bit
System>> document was updated.

=== drudg changes

There are no _drudg_ changes yet.

