//
// Copyright (c) 2020-2021 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= FS 10.0.0 to Latest Commit Update Notes
Version 1.4 - May 2021

//:hide-uri-scheme:
:sectnums:
:sectnumlevels: 4
:experimental:

:toc:
:toclevels: 4

== Introduction

The document covers updating from FS _10.0.0_ to the _latest commit_
on its branch. The latest commit is experimental. We make ever effort
to keep the latest commit usable, but any commit that is not tagged
for release is not intended for operations. The intended use of this
document is to collect update information, as it becomes available,
before the next release.

IMPORTANT: Commits that are not tagged for release may have
significant issues including: not building, crashing, and
incompatibilities with operational observation schedule files. Such
commits are intended for testing only. _Let the user beware._

CAUTION: It is expected that those using the latest commit are experts
and will manage the differences for updating to the next official
release themselves. No specific documentation will be provided. What
commit was last updated to will determine what needs to be done.  It
might work to verify that all the steps in the latest version of this
document, appropriately renamed as an update from the old release to
the new release, were completed. An alternate, but not necessarily
complete, approach would be to review the update steps in the new
release to make sure everything has been covered. _Let the user
beware._

This document is up to date with the features in the `1a94029e`
commit. Due to small increments, such as updating this document, this
may not be the literal last commit, but the differences should be
small unless you happen to `pull` between a significant change and
this document being updated.

== Upgrading from 10.0.0 to the latest commit

You must have already upgraded to _10.0.0_ according to the
<<10.0.0.adoc#,FS 10.0.0 Update Notes>> document before installing
this update.

=== Fetch and make the latest commit

If you are using _git_, as is recommended, then as _prog_
execute:

             cd /usr2/fs-git
             git fetch
             git checkout master
             make clean rmdoto rmexe
             make >& /dev/null
             make -s

No output from the last command indicates a successful _make_.

=== Reboot

This will make sure the FS server is restarted.

=== Additional steps

. Run the FS to check for _.rxg_ file errors.

+

Five additional formatting errors are now reported for _.rxg_ files.
While it is unlikely, if your _.rxg_ files have any of these errors,
they will be reported when you try to run the FS. Only one error is
reported at a time. You will need to correct each error in turn until
the FS starts successfully.  The new errors reported are described in
the <<additional_rxg_errors,Additional .rxg file errors>> change in
the <<FS changes>> sub-section below.

. Adjust _~/.session_ if you are using _tcsh_ as your
login shell for _oper_ or _prog_ (or AUID accounts).

+

This step is optional, but may be helpful if you are using _tcsh_ as
your login shell for _oper_ and/or _prog_ (or AUID accounts) and use
the FS with the graphical display on the console.  For this case, you
may wish to make the changes in the <<10.0.0.adoc#xsession,Updating
~/.xsession>> sub-step in
<<10.0.0.adoc#_miscellaneous_fslx_changes,Miscellaneous FSLx changes>>
step of the <<10.0.0.adoc#,FS 10.0.0 Update Notes>> document.

+

This change will make sure the window manager (__fvwm2__) operates
with the FS runtime environment variables set. This could be important
for example, if you want to run __fsclient__ (perhaps for a
`scan_check` window) from a console hotkey.

. Make the `scnch` and `erchk` windows `NeverFocus`.

+

This step is optional. You may want to add `NeverFocus` for the
`scnch`, `erchk`, and `monan` windows in your _~/.fvm2rc_ files so
they will never accidentally get the focus (they don't accept input).
They will still be able to be scrolled. If this is desired, add the
lines:

  Style "erchk" NeverFocus
  Style "scnch" NeverFocus
  Style "monan" NeverFocus
+

As _oper_, you can compare your version of the file with the new
default using:

  cd
  diff .fvwm2rc /usr2/fs/st.default/oper

+

You can make the same change for _prog_, after logging into that
account.

. [[cleanup_comments]] <<cleanup_comments,Clean-up .rxg
file comments>>:

+

This step is optional, but may help you if want the leading and
trailing comments in your _.rxg_ files to be easy to interpret. The
steps here are designed to be as simple as possible when applying the
update, but preserve the opportunity for a full clean-up, whether it
is done now or at a later date.

+

NOTE: For a complete description of this issue and why you might want
to make at least some of these changes, please see the
<<stop_adding_extra_comments,Stop adding extra comment when updating
.rxg files>> change in the <<FS changes>> sub-section below.

+

[NOTE]
====

If you have been curating your _.rxg_ files to fix the issues
with the comments, you may not need to follow these steps. You may
still wish to review them to see if any might be helpful.

====

+

.. Make a backup of your current _.rxg_ files.

+

This will give you a backup to recover from  in case something goes
wrong and will simplify cleaning up the trailing comments if you defer
that to a later date. Enter these commands as _oper_, using current
values for `_year_`, `_month_`, and `_day_`:

+

[subs="+quotes"]
....
cd /usr2/control/rxg_files
mkdir BACKUP._year_._month_._day_
cp -a *.rxg BACKUP._year_._month_._day_
....

+

.. Reduce the _.rxg_ files to just the active calibration.

+

This will remove leading comments added by _gnplt_ and all trailing
comments. This will not disturb the active calibration or any of the
other comments before the last non-comment line.

+

CAUTION: The trailing comments may be a complicated hash unless you
have been curating them. If you have, you probably do not want to use
the `-c` option with the _rxgfix3_ script below, if you use the script
at all. If you have not been curating them, it may be a laborious
process to straighten them out. Removing them now will help make that
process a little easier.

... [[check]] <<check,Check what changes would be made>>:

+

This sub-step uses the _rxgfix3_ script. Its default behavior is to
remove "`extra`" leading comments that _gnplt_ may have added. It has
several options that may also be useful.  This sub-step uses the
recommended options along with the `-t` option, which runs the script
in "`test`" mode to just show what changes would be made. The
recommended options are explained below. To see what changes would be
made, as _oper_  enter:


   cd /usr2/control/rxg_files
   /usr2/fs/misc/rxgfix3 -cdrt *.rxg

+

NOTE: If the output is too large to work with, you can simplify it by
running _rxgfix3_ on any subset of files, even a single file, at a
time.

+

The meanings of the recommended options used with _rxgfix3_ script
above are:

+

NOTE: Help text and a complete listing of available options can be
viewed with `*/usr2/fs/misc/rxgfix3{nbsp}-h*`.

+

* `-c` -- Delete trailing comments. This will make it easier to update
your trailing comments to the correct form. You should drop this
option if you want to keep your trailing comments the way they are.

* `-d` -- Delete existing _.bak_ files before processing. If old
_.bak_ files are left over from using _rxgfix<n>_ scripts in the past,
this will delete them. If you prefer to keep them, you can rename them
before running _rxgfix3_ without `-t`.

* `-r` -- Use the date in the first `GnPlt2` leading comment to
replace the date on the date line. This will not be needed if you have
updated the _.rxg_ file with _gnplt_ since FS version _10.0.0-beta3_,
but is benign in that case. If you have manually changed the date line
in your _.rxg_ file(s) you may prefer to use the `-k` option to keep
the current date line.

+

If some of these changes are unacceptable, you can change the actions
by dropping some options or making changes, such as using `-k` in
place of `-r`. You can always process the files in subsets with
different options if that is needed.

... Apply the changes:

+

If the changes shown in <<check,Check what changes would be made>>
sub-step above are acceptable or you have figured out how you want to
modify them, you can re-run _rxgfix3_ with the options you decided on,
but without the `-t`, in order to apply them.

+

.. Clean-up the trailing comments

+

Once the "`extra`" comments have been removed you can decide how and
when to deal with reinstalling the trailing comments. This may be
quite involved. To keep this update easy to apply, it has been
designed so that you can reinstall the trailing comments at a later
date. It can of course be done now if you prefer.  For the details on
how to make this change, now or later, see the
<<stop_adding_extra_comments,Stop adding extra comments when updating
.rxg files>> change in the <<FS changes>> sub-section below.

+


=== Review changes

Please see the <<Changes since 10.0.0>> section below for the details
of the changes since that release.

== Changes since 10.0.0

There are separate sub-sections with summaries of changes in the FS
and _drudg_.

Clickable links such as
https://github.com/nvi-inc/fs/issues/36[#36] connect to specific issues
reported at https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

=== FS changes

. Clean-up of suppressing signals.

+

--

.. Remove redundant ignoring of signals in _ddout_ and _oprin_
(partially closing https://github.com/nvi-inc/fs/issues/100[#100]).

.. Re-enable suppression of signals (partially closing
https://github.com/nvi-inc/fs/issues/100[#100]).

+

As of _10.0.0-beta1_, the previous practice of disabling receipt of
certain signals, in particular `SIGINT` (for kbd:[Control+C]) had been
removed. It has been reinstated. When the FS is run without the
display server, this assures that no FS programs will be aborted if a
kbd:[Control+C] is accidentally entered in the terminal session where
the FS is running. However, this does not prevent a kbd:[Control+C]
from killing an _xterm_ that is wrapped around a FS program (typically
only _oprin_) in the FS terminal session from being killed.
Preventing that is discussed next.

.. Use `setsid()` to shelter __xterm__s from keyboard generated
kbd:[Control+C].

+

To prevent kbd:[Control+C] killing an _xterm_ in the FS terminal
session all `x` programs in _fspgm.ctl_ and _stpgm.ctl_ (usually just
_oprin_) are now run under `setsid()` when the display server is not
being used. This disconnects the programs from the terminal session
that the FS is being run in, thereby preventing a kbd:[Control+C] from
reaching them, but not otherwise affecting them.

--
+

With these changes, it should no longer be possible to kill the FS
with a kbd:[Control+C], even when the display server is not being
used.

+

CAUTION: An FS _xterm_  window can still be terminated using the
decorations for the window. When the FS is not being running with the
display server, this will kill the FS _abnormally_. The decoration
button that includes the `Delete` and `Destroy` options can be removed
if desired. In the _~/.fvm2rc_ file include `NoButton 1` in the
window's `Style` (see the `Style "oprin" ...` line in
_st.default/oper/.fvwm2rc_ for an example).

. Add command line options to _rdbemsg_.

+

Two command line options were added to _rdbemsg_:

* `-f` -- which takes an integer argument to set the font size,
default is `14`

* `-g` -- which takes a string argument to set the window geometry,
default is not to set it

+

Only the position part of the geometry should be set with `-g`, e.g.,
`-g{nbsp}-0-0`.  The useful way to control the size is with `-f`.

+

. Improve _msg_ to always pick-up a new log file name (closing
https://github.com/nvi-inc/fs/issues/118[#118]).

+

Previously _msg_ only read the log file (and session) name on start-up
and when sending messages. It was modified to reread the log file (and
session) name whenever a new form is displayed. As a result, selecting
any form or send a sending a message from one will cause the log file
name to be reread (and session name reset), in other words, this will
occur for any significant user action. This should provide more
intuitive behavior, primarily because it is no longer necessary to
restart _msg_ for each session.  The setting of the session name when
reading the log file name can be turned off by disabling the `Setup`
selection `Get session name from log` if it is not desired.

+

Thanks to Jonathan Quick (HartRAO) for reporting the issue, providing
feedback on the changes,  and testing the fix.

. Add adjustable log size warning message (closing
https://github.com/nvi-inc/fs/issues/114[#114]).

+

When a log is opened (including _station.log_ when starting the FS,
there was  a warning error if the size exceeded 100 MB. Different
stations may find different sizes useful. The size for the warning is
now adjustable by setting the environment variables
`FS_LOG_SIZE_WARNING` to the desired size in MB. If it is not set, it
defaults to 100 MB.

+

The FS must be restarted in a session with the variable set for it to
take effect. If the display server is in use, _fsserver_ must be
stopped (or the system rebooted) _after_ stopping the FS and _before_
restarting it with:

  fsserver stop

+

Thanks to Kiah Imai (KPGO) for suggesting this.

. Add explanatory comments to the example _flux.ctl_ control file (closing
https://github.com/nvi-inc/fs/issues/121[#121]).

+

Although the data used in the file came from other sources, for many
years the code that read the _flux.ctl_ file was the complete
documentation for the format.  The example file in
_/usr2/fs/st.deafault_ now includes the details in an easier to read
form. You can merged these comments, which are at the end of the
example file, into your local copy or refer to the example.

+

Thanks to Stuart Weston (Warkworth) for suggesting this and
contributing some of the information in the comments.

. Increase buffer size for recovering a deleted log.

+

If a log file is not locatable as a file (it has been deleted or
renamed) when a user command would close the log, the FS will attempt
to recover the file and give it its original name. The buffer used to
recopy the file was increased to 2 Mib (512 sectors) so it is faster,
particularly for very large experiment logs with multicast data.

+

IMPORTANT: The recovery will not work if in the meantime a file has
been created with the same name. The FS will think that is the log and
give up. The log file contents will be lost. Using `log=_name_` or
`schedule=_name_` will not cause this.

+

As part of this change, the handling of the file size and positions
were restored to using `long` variables. These had been changed to
`int` variables by the bulk _unlongify_ before _10.0.0-beta1_, but hadn't
been changed back.

. Fix _gndat_.

+

.. Correct bad Tsys data in _gnplt_ (closing
https://github.com/nvi-inc/fs/issues/107[#107] and
https://github.com/nvi-inc/fs/issues/104[#104]).

+

This was caused by an incorrectly sized array in _gndat_ that was
introduced in commit `f84a2bb9` dated June 2003.  This error was
benign unless more than 20 detectors were used in a single _onoff_
run.  Before the advent of RDBEs and DBBC3s, this was unlikely, but
not impossible.

+

Due to the layout of the automatic variables, this error should only
have impacted `Tsys` and `Tsys-Tspill` data in _gnplt_ and only when
there were more than 20 detectors used. However, also considering the
layout of the automatic variables, it is unclear why there were not
catastrophic program failures in such a case. It would be prudent to
reanalyze any current data sets that used more than 20 detectors with
the fixed version to see if the results change.

+

Thanks to Beppe Maccaferri (Medicina), and subsequently Eskil Varenius
(Onsala), for reporting this issue.

.. Remove extraneous _gndat_ debug output for the processing of
weather data.

+

The debug output was not visible when _gndat_ was run from _gnplt_,
which is normally the only way it is run.

+

. Update _plog_.

.. Fix _plog_ to only refuse to reduce a log with multicast data if it
is the active log in the FS.

+

In the process of reducing a log (removing multicast data), the log is
renamed. This can cause a log recovery to occur if the log is
currently open in the FS since it appears to be missing. This was
protected against by _plog_, which would refuse to rename the log if
it was open to any program. This meant that if the log was was being
viewed with `tail -f` or _less_ it could not be renamed. However,
_plog_ only needed to refuse if the log was open in the FS (by
_ddout_). This was fixed so that _plog_ will only refuse to rename the
log if it is open in the FS.

+

NOTE: In such a case, the operator needs to close the log before
running _plog_ on it. That is good practice in any case.

+

NOTE: Other, non-reduction, log processing by _plog_ was not affected
by this issue since renaming is not needed. It is still good practice
to close the log before pushing it.

+

Thanks to Katie Pazamickis and Jay Redmond (both at GGAO) for
reporting this.

+

.. Add use of _bzip2_ compression to _plog_.
+

_plog_ will now use _bzip2_ as the default program for compressing
___full.log__ files to send to the data centers. It is possible to use
__gzip__ instead by setting the environment variable
`PLOG_COMPRESSED_EXT` to `gz` or using the `-g` command line option.
Please use `*plog{nbsp}-h*` for more information.

.. Respect `NETRC_DIR` for the `BKG` data center (closing
https://github.com/nvi-inc/fs/issues/113[#113]).

+

This had been overlooked in
https://github.com/nvi-inc/fs/issues/39[#39], which had added the
`NETRC_DIR` environment variable.

+

Thanks to Kiah Imai (KPGO) for reporting this and testing the fix.

+

. Update _fesh_.

.. Add `-P` option to print the summary listing to the printer (closing
https://github.com/nvi-inc/fs/issues/112[#112]).

+

With `-P`, when _drudg_ is run by _fesh_, it will print the summary
directly to the printer. It is appropriate to make this a _fesh_
option since it is an integrated feature of _drudg_. To print other
files, it is recommended to make a wrapper for _fesh_. An example
wrapper, that prints the summary and the _.prc_ file, is included as
_/usr2/fs/fesh/feshp_. This can be copied to _~oper/bin_ and
customized to print other files.

+

Thanks to Kiah Imai (KPGO) for suggesting this.

.. Add `-S` option to _fesh_ to skip downloading.

+

This allows _fesh_ to trigger the normal _drudg_ processing when the
schedule is already on the disk. This might be useful for example, if
the schedule was generated locally by shifting the schedule (_drudg_
option `10`).

+

. Instrument _fsserver_ (closing
https://github.com/nvi-inc/fs/issues/105[#105]).
+

The display server now makes a file with a name of the form
_~/fsserver.<time-stamp>.err_ each time it is started. It is used to
collect server error information. The file will be deleted if
_fsserver_ terminates normally. If you experience a server crash,
please send this file to Ed or post it as part of an issue on
_github_. The _<time-stamp>_ portion of the name will correspond to
the time when the server was last started before the crash. That is
usually when the FS was first started after the last boot. Any file of
this type with non-empty contents is worth reporting.

+

Thanks to Dave Horsley (AuScope) for suggesting this and contributing
to the implementation.

+

NOTE: The FS also makes a file with a name of the form
_~/fs.<time-stamp>.err_ each time it is started. It is used to collect
FS error information. The FS will attempt to delete this file if it
terminates normally. If you experience a FS crash, please send this
file to Ed or post it as part of an issue on _github_. The
_<time-stamp>_ portion of the name will correspond to the time when
the FS was last started before the crash.

. Improve error messages when reading _flux.ctl_ (closing
https://github.com/nvi-inc/fs/issues/124[#124]).

+

The error messages when reading _flux.ctl_ were confusing and
uninformative. This has been the situation since the file was first
added in October 2002, for version _9.5.15_ (commit `1b68b90f`).
Apparently, this was not a significant issue because, apparently,
modifying the default contents was uncommon. If you have been having
trouble with this, we apologize.

+

The error messages have been more explicit about the cause of any read
error and the offending line is printed to aid in correcting the
problem.

+

Thanks to Stuart Weston (Warkworth) for reporting this.

. Improve error messages when reading _.rxg_ files.

.. Make error messages more informative (closing
https://github.com/nvi-inc/fs/issues/83[#83]).

+

The error messages when reading _.rxg_ files  were confusing and
uninformative. This has been the situation since _.rxg_ files were
first added in October 2002, for version _9.5.15_ (commit `1b68b90f`).
Apparently, this was not a significant issue because _.rxg_ files were
usually updated by _gnplt_, which wrote correctly formatted lines. If
you have been having trouble with this, we apologize.

+

The error messages have been more explicit about the cause of any read
error. Unfortunately, it is not possible to show the offending line
without more significant changes. However, the messages are fairly
explicit about where the error occurred.

+

The same reading routine is used in _gnplt_ (which uses _gndat_ to
read the _.rxg_ files) for consistency. Unfortunately, the error
messages for _gnplt_ will still not be as informative, but restarting
the FS should provide a more explicit error message that help make it
clear what the problem is. If it is not possible to use the FS for
this, another strategy is to use the error number reported in status
line at the bottom of _gnplt_ to identify the corresponding `RG` error
in _controlfserr.ctl_.


+

.. [[additional_rxg_errors]]<<additional_rxg_errors,Additional .rxg
file errors>>: Five additional errors are now reported (closing
https://github.com/nvi-inc/fs/issues/134[#134]):

+
--

* The third field on the LO line is missing for type `range`.

* If a third field exists on the LO line, but does not decode as a
number.

* The second field on the FWHM line is missing for type `constant`.

* If a second field exists on the FWHM line, but does not decode as a
number.

* A field exists after the gain curve coefficients, but is not
`opacity_corrected`.

--
+

While it is unlikely, if any of your _.rxg_ files have these errors,
they will be reported the first time you run the FS after the update.
You can correct them at that time. The error messages should be pretty
clear.

+

A few other, minor, errors are still not being caught. In particular,
if a character that cannot be part of a numeric field appears
_within_, or at the end of, a numeric field, that error will not be
reported. In that case, the field up to the out-of-place character will
be used as the value. Hopefully this is an unlikely error. A leading
character that cannot be part of a numeric field will be reported as
an error.

+

. Add instructions to the example _.xsession_ files for how to
make them work correctly when _tcsh_ is the login shell.

+

Instructions for implementing this were added to the <<10.0.0.adoc#,FS
10.0.0 Update Notes>> document as the <<10.0.0.adoc#xsession,Updating
~/.xsession>> sub-step in the
<<10.0.0.adoc#_miscellaneous_fslx_changes,Miscellaneous FSLx changes>>
step.

. Correct error in FORTRAN calls to get FiLa10G time for _setcl_.

+

An argument was missing. This was a bug from the VGOS branch, which
technically do not support using _setcl_ for FiLa10G. The bug
apparently did not affect versions since the merge since there was a
relatively low, not quite 1 in 2^32^ chance of it being excited.

+

NOTE: _setcl_ only works for the first FiLa10G if there are two. A
second is only used for VGOS. _fmset_ works for both.

. Correct `bbc_gain` command error codes.

+

If an error occurred in the monitor form of the command, the error was
reported as `di` instead of `dg`.

. Add use of `NeverFocus` for the `scnch` and `erchk` windows in
the _.fvwm2rc_ files.

+

This was previously added in _10.0.0-beta1_, but removed on _10.0.0_
because it was thought to prevent scrolling of those windows. However,
that turned out to not be the case. Using this setting prevents the
focus from accidentally being given to these windows, which don't
accept input. This only affects behavior on the console GUI.

. [[stop_adding_extra_comments]]<<stop_adding_extra_comments, Stop
adding extra comments when updating .rxg files>>.

+

The trailing comments are intended to hold the old calibration data,
in reverse chronological order, as an historical record. There was a
longstanding bug in the current _gnplt_ (so-called _gnplt2_) that
caused it to include additional, out-of-order, commented out, copies
of old calibration data when updating _.rxg_ files.  This has been
fixed (closing https://github.com/nvi-inc/fs/issues/111[#111])..

+

Another "`feature`" in _gnplt_ caused extra comments to be inserted in
._rxg_ files. It was not updating the date line. The program was
compensating for this by adding a new first line comment with the date
each time it updated the file.  Since the date line is now being
updated (https://github.com/nvi-inc/fs/issues/72[#72]), the date
comment line is no longer added.

+

Thanks to Jonathan Quick (HartRAO) for reporting these issues,
suggestions for the fixes, and testing them.

+

While these bugs have been fixed, it could be a lot of work for
stations to clean-up the comments if they have not been doing so right
along as they updated the _.rxg_ files with _gnplt_. Cleaning-up the
comments is entirely optional. To make the current update easy to
apply, the process has been broken down into two parts. The first
part, which is relative easy, includes making a backup of the files as
they are now, and then reducing them to the minimum needed to preserve
the active calibration data. That is covered in the
<<cleanup_comments,Clean-up .rxg file comments>> sub-step in the
<<Additional steps>> step above. The second part is to clean-up the
trailing comments. This part is an optional follow-up to the first
part. It is more involved and can be deferred to a later date. That
part is described next.

+

[CAUTION]
====

Depending on the size of the _.rxg_ files, this step could be very
laborious. Using this procedure is entirely optional. It is provided
only in case you are interested in using it. If your trailing comments
are in the form you want or if you do not want to clean them up, you
can skip this procedure. If you don't want to clean them up, you can
either keep them in the backup you made or append all the trailing
comments from the backups into the corresponding _.rxg_ files. Future
updates with _gnplt_ will add comments in reverse chronological
order.

If you do append them and they are not in reverse chronological order,
they will not be consistent with new updates made with _gnplt_, which
will add new comments in reverse chronological order. As a result,
straightening out the trailing comments at a later date will be more
complicated. It is probably best to avoid this unless you are not
worried about the older trailing comments. Keeping the trailing
comment clean-up simpler is the reason that it is recommended to
delete the trailing comments (with _rxgfix3_ option `-c`) in the
<<cleanup_comments,Clean-up .rxg file comments>> sub-step in the
<<Additional steps>> step above. The procedure here assumes that no
new comments have been inserted in the backup copy in reverse
chronological order.

====

+

[CAUTION]
====

This approach for cleaning up the trailing comments will work
correctly if the _.rxg_ files have _only_ been updated with _gnplt_
and not modified otherwise. If they have been modified, the following
procedure may not work, but it may be possible to adapt it to your
situation.

If your _.rxg_ files have only been updated by _gnplt_, it may be
possible to automate this step. If you are interested in a script to
implement this procedure, please mail Ed. If there is sufficient
interest, a script can be provided.

====

+

[NOTE]
====

The procedure makes use of the added `GnPlt2` date comment lines in
the file. Although the date encoded will typically be different, the
lines will be of the form:

....
* RXG file updated by GnPlt2 on 2021-4-19
....

The procedure works by identifying particular instances of these
comments and finding the next matching instance.

====

+

As _oper_, for each individual _.rxg_ file:

+
--

.. Make a temporary copy, to work on, of the backup of the file you
created in the <<cleanup_comments,Clean-up .rxg file comments>>
sub-step in the <<Additional steps>> step above. Working with the
temporary copy will allow for easy recovery in case there is problem,
including an error in this procedure. To make a working copy for
_<name>.rxg_:

+

[subs="+quotes"]
....
cp /usr2/control/rxg_files/BACKUP._year_._month_._day_/_<name>_.rxg /tmp
....

+

For the remainder of these steps, work on the copy you just made.

.. Find the uncommented calibration data set at the top of the file.

.. The first two lines in the file should be `GnPlt2` date comments.
Note the date in the second date comment. Ignore any date comments
that follow the second one.

+

If there are no `GnPlt2` date comments, delete from the start of the
file to (and including) the `end_spillover_table` line at the end of
the active calibration, then go to the <<save_file,Save file>> step
below.

+

If only the first line is a `GnPlt2` date comment, delete from the
start of the file to (and including) the `end_spillover_table` line at
the end of the active calibration, then go to the <<finish,Finish>>
step below. 

.. Search for the _next_ occurrence of a date comment with the date
you noted above.

.. Call the line before that location _B_. It should be
`end_spillover_table`.

.. Delete from the beginning of the file to _B_, inclusive.

.. [[loop]] <<loop,Loop>>:

... If the line after `GnPlt2` date comment that you found is another
`GnPlt2` date comment, note the date in that comment.

+

Otherwise go to the step labeled <<finish,Finish>> below.

+

... Find the last line of the commented out calibration set at this
point. It should be `*end_spillover_table`.

... Call the next line location  _A_.

... Search for the next occurrence of the date you noted above in
<<loop,Loop>>.

... Call the previous line location _B_. It should be
`*end_spillover_table`.

... Delete from _A_ to _B_, inclusive.

... Repeat the above steps above starting with the step labeled
<<loop,Loop>> above until you reach a commented out calibration that
doesn't have a second `GnPlt2` date comment at the start.

.. [[finish]] <<Finish,Finish>>: If your _.rxg_ file was updated with
_gnplt1_ in the past, please consider using the <<gnplt1,gnplt1>>
additional procedure below. Then continue with the next step here,
<<save_file,Save file>>.

.. [[save_file]]<<save_file,Save file>>: Save the file.

.. Append the saved file to what is now in the  _.rxg_ file its
contents originally came from.

+

NOTE: Any trailing comments that were added by _gnplt_ after applying
the <<cleanup_comments,Clean-up .rxg file comments>> sub-step in the
<<Additional steps>> step above, will be in the correct order. As a
result, appending after those will maintain the correct order.

--
+

To understand how this process works, consider two cases: (1) only the
_gnplt2_ has been used to update the file, and (2) the file was
previously updated by _gnplt1_. In the former case, the growth of the
file follows the pattern (where the integers indicate the sequential
versions of the calibration, the leftmost is the active one, all the
others are commented out):

+

....
0
1 0
2 0 1 0
3 0 1 0 2 0 1 0
4 0 1 0 2 0 1 0 3 0 1 0 2 0 1 0
...
....

+

For each new version, _gnplt2_ inserted a new data comment at the
start. The previous date comments were preserved after it.  After the
above procedure, the content is reduced to (for the case of `4` being
the active calibration):

+

....
4 3 2 1 0
....

+

The other case is if the file was updated with _gnplt1_ before
switching to _gnplt2_. In this case the progression is (where `A`
represents _all_ the trailing comments before the first _gnplt2_
update):

+

....
0 A
1 A 0 A
2 A 0 A 1 A 0 A
3 A 0 A 1 A 0 A 2 A 0 A 1 A 0 A
4 A 0 A 1 A 0 A 2 A 0 A 1 A 0 A 3 A 0 A 1 A 0 A 2 A 0 A 1 A 0 A
...
....

+

After the above procedure, the content is reduced to (for the case of
`4` being the active calibration):

+

....
4 3 2 1 A 0 A
....

+

In this case, there is an extra `A`
section between the final `1` and `0 A` at the end of the file. This
can be found and removed with these steps:

.. [[gnplt1]] <<gnplt1,gnplt1>>: Locate the end of  the `1` comments,
which is the _first_ `*end_spillover_table` line after the _last_
`GnPlt2` date comment.

.. Call the _next_ line _A_.

.. Find the commented out calibration with the latest date line
(commented out) and _no_ `GnPlt2` date comment) line. This is last
update made by _gnplt1_ (`0`).

.. Find the _previous_ `*end_spillover_table` line. It should be the
last line before the `0` calibration set.

.. Call that location _B_.

.. Delete from _A_ to _B_, inclusive.

.. If you executed this as part of the main procedure, you can
continue with the step labeled <<save_file,Save file>> above.

=== drudg changes

There have been no changes at this time.
