//
// Copyright (c) 2020-2021 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= FS 10.0.0 to Latest Commit Update Notes
Version 1.3 - April 2021

//:hide-uri-scheme:
:sectnums:
:sectnumlevels: 4
:experimental:

:toc:
:toclevels: 4

== Introduction

The document covers updating from FS _10.0.0_ to the _latest commit_
on its branch. The latest commit is experimental. We make ever effort
to keep the latest commit usable, but any commit that is not tagged
for release is not intended for operations. The intended use of this
document is to collect update information, as it becomes available,
before the next release.

IMPORTANT: Commits that are not tagged for release may have
significant issues including: not building, crashing, and
incompatibilities with operational observation schedule files. Such
commits are intended for testing only. _Let the user beware._

CAUTION: It is expected that those using the latest commit are experts
and will manage the differences for updating to the next official
release themselves. No specific documentation will be provided. What
commit was last updated to will determine what needs to be done.  It
might work to verify that all the steps in the latest version of this
document, appropriately renamed as an update from the old release to
the new release, were completed. An alternate, but not necessarily
complete, approach would be to review the update steps in the new
release to make sure everything has been covered. _Let the user
beware._

This document is up to date with the features in the `1a94029e`
commit. Due to small increments, such as updating this document, this
may not be the literal last commit, but the differences should be
small unless you happen to `pull` between a significant change and
this document being updated.

== Upgrading from 10.0.0 to the latest commit

You must have already upgraded to _10.0.0_ according to the
<<10.0.0.adoc#,FS 10.0.0 Update Notes>> document before installing
this update.

=== Fetch and make the latest commit

If you are using _git_, as is recommended, then as _prog_
execute:

             cd /usr2/fs-git
             git fetch
             git checkout master
             make clean rmdoto rmexe
             make >& /dev/null
             make -s

No output from the last command indicates a successful _make_.

=== Additional steps

No additional steps are needed at this time.

=== Review changes

Please see the <<Changes since 10.0.0>> section below for details of
the changes since that release.

== Changes since 10.0.0

There are separate sub-sections with summaries of changes in the FS
and _drudg_.

Clickable links such as
https://github.com/nvi-inc/fs/issues/36[#36] connect to specific issues
reported at https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

=== FS changes

. Clean-up of suppressing signals.

+

--

.. Remove redundant ignoring of signals in _ddout_ and _oprin_
(partially closing https://github.com/nvi-inc/fs/issues/100[#100]).

.. Re-enable suppression of signals (partially closing
https://github.com/nvi-inc/fs/issues/100[#100]).

+

As of _10.0.0-beta1_, the previous practice of disabling receipt of
certain signals, in particular `SIGINT` (for kbd:[Control+C]) was
removed. It has been reinstated. This assures that no FS programs will
be aborted if a kbd:[Control+C] is accidentally entered in the session
where the FS is running. However, this does not prevent a
kbd:[Control+C] from killing an _xterm_ that is wrapped around a FS
program, typically only _oprin_, in the FS session from being killed.
Preventing that is discussed next.

.. Use `setsid()` to shelter __xterm__s from keyboard generated
kbd:[Control+C].

+

To avoid kbd:[Control+C] killing an _xterm_ in the FS session all `x`
programs in _fspgm.ctl_ and _stpgm.ctl_ (usually just _oprin_) are now
run under `setsid()`. This disconnects the programs from the session
that the FS is being run in, thereby preventing a kbd:[Control+C] from
reaching them, but not otherwise affecting them.

--
+

With these changes, it should no longer be possible to kill the FS
with a kbd:[Control+C], even when the display server is not being
used.

+

CAUTION: An _xterm_  window can still be terminated using the
decorations for the window. When the FS is not being running with the
display server, this will kill the FS abnormally. The decoration
button that includes the `Delete` and `Destroy` options can be removed
if desired. In the _~/.fvm2rc_ file include `NoButton 1` in the
window's `Style` (see the `Style "oprin" ...` line in
_st.default/oper/.fvwm2rc_ for an example).

. Add command line options to _rdbemsg_.

+

Two command line options were added to _rdbemsg_:

* `-f` -- which takes an integer argument to set the font size,
default is `14`

* `-g` -- which takes a string argument to set the window geometry,
default is not to set it

+

Only the position part of the geometry should be set, e.g., `-0-0`.
The useful way to control the size is with `-f`.

+

. Fix _gndat_.

+

--

.. Correct bad Tsys data in _gnplt_ (closing
https://github.com/nvi-inc/fs/issues/107[#107] and
https://github.com/nvi-inc/fs/issues/104[#104]).

+

This was caused by an incorrectly sized array in _gndat_ that was
introduced in commit `f84a2bb9` dated June 2003.  This error was
benign unless more than 20 detectors were used in a single _onoff_
run.  Before the advent of RDBEs and DBBC3s, this was unlikely, but
not impossible.

+

Due to the layout of the automatic variables, this error should only
have impacted `Tsys` and `Tsys-Tspill` data in _gnplt_ and only when
there were more than 20 detectors used. However, also considering the
layout of the automatic variables, it is unclear why there were not
catastrophic program failures in such a case. It would be prudent to
reanalyze any current data sets that used more than 20 detectors with
the fixed version to see if the results change.

+

Thanks to Beppe Maccaferri (Medicina), and subsequently Eskil Varenius
(Onsala), for reporting this issue.

.. Remove extraneous _gndat_ debug output for the processing of
weather data.

+

The debug output was not visible when _gndat_ was run from _gnplt_.

--

. Fix _plog_ to only refuse to reduce a log with multicast data in it
if it is the active log in the FS.

+

In the process of reducing a log (removing multicast data), the log is
renamed. This can cause a log recovery to occur if the log is
currently open in the FS since it appears to be missing. This was
protected against by _plog_, which would refuse to rename the log if
it was open to any program. This meant that the log was was being
viewed with `tail -f` or _less_ it could not be renamed. However,
_plog_ only needed to refuse if the log was open in the FS (by
_ddout_). This was fixed so that _plog_ will only refuse to rename the
log if it is open in the FS.

+

NOTE: In such a case, the operator needs to close the log before
running _plog_ on it. That is good practice in any case.

+

NOTE: Other, non-reduction, log processing by _plog_ was not affected
by this issue since renaming is not needed.

+

Thanks to Katie Pazamickis and Jay Redmond (both at GGAO) for
reporting this.

. Correct error in FORTRAN calls to get FiLa10G time for _setcl_.

+

An argument was missing. This was a bug from the VGOS branch, which
technically do not support using _setcl_ for FiLa10G. The bug
apparently did not affect versions since the merge since there was a
relatively low, not quite 1 in 2^32^ chance of it being excited.

+

NOTE: _setcl_ only works for the first FiLa10G if there are two. A
second is only used for VGOS.

. Correct `bbc_gain` command error codes.

+

If an error occurred in the monitor form of the command, the error was
reported as `di` instead of `dg`.

=== drudg changes

There have been no changes at this time.
