//
// Copyright (c) 2020-2021 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= FS 10.0.0 to Latest Commit Update Notes
Version 3.1 - January 2022

:sectnums:
:stem: latexmath
:sectnumlevels: 4
:experimental:

:toc:
:toclevels: 4

== Introduction

The document covers updating from FS _10.0.0_ to the _latest commit_
on its branch. The latest commit is experimental. We make ever effort
to keep the latest commit usable, but any commit that is not tagged
for release is not intended for operations. The intended use of this
document is to collect update information, as it becomes available,
before the next release.

IMPORTANT: Commits that are not tagged for release may have
significant issues including: not building, crashing, and
incompatibilities with operational observation schedule files. Such
commits are intended for testing only. _Let the user beware._

CAUTION: It is expected that those using the latest commit are experts
and will manage the differences for updating to the next official
release themselves. No specific documentation will be provided. What
commit was last updated to will determine what needs to be done.  It
might work to verify that all the steps in the latest version of this
document, appropriately renamed as an update from the old release to
the new release, were completed. An alternate, but not necessarily
complete, approach would be to review the update steps in the new
release to make sure everything has been covered. _Let the user
beware._

This document is up to date with the features in the `00399fa8`
commit. Due to small increments, such as updating this document, that
may not be the literal last commit, but the differences should be
small unless you happen to `pull` between a significant change and
this document being updated.

== Upgrading from 10.0.0 to the latest commit

You must have already upgraded to _10.0.0_ according to the
<<10.0.0.adoc#,FS 10.0.0 Update Notes>> document before installing
this update.

=== Fetch and make the latest commit and make station code

. Update the FS

+

If you are using _git_, as is recommended, then as _prog_ execute:


             cd /usr2/fs-git
             git fetch
             git checkout master
             make clean rmdoto rmexe
             make >& /dev/null
             make -s

+

No output from the last command indicates a successful _make_.

. Reload your station code.

+

If _/usr2/st/Makefile_ is set-up in the standard way, you can do this
with:

       cd /usr2/st
       make rmdoto rmexe all

+

IMPORTANT: If your station code uses `refrw()` you will need to update
to use `refrw_bad()` or `refrwn()`. The use of `refrw_bad()` should be
sufficient in the short-term, but you should change to `refrwn()` in
the long term. Please see the <<refrw_bad,refrw_bad()>> FS change
below from more details.


=== Reboot

This will make sure the FS server is restarted.

=== Additional steps

Except if noted otherwise, these steps should all be performed as
_oper_.

. Create the _dbbc3.ctl_ control file.

+

The contents of DBBC3 line in the _equip.ctl_ control file has been
moved to the new control file, _dbbc3.ctl_, and reorganized. To create
the new file and remove the obsolete contents of _equip.ctl_, execute:

  cd /usr2/control
  /usr2/fs/misc/equipctlfix equip.ctl

+

NOTE: This will create the file, preserving the values from the DBBC3
line in your old _equip.ctl_ file. That should allowing running the FS
if you don't have a DBBC3. If you have a DBBC3, you should customize
the contents in the <<dbbc3config,FS DBBC3 Configuration>> step below.

. Run the FS to check for _.rxg_ file errors.

+

Five additional formatting errors are now reported for _.rxg_ files.
While it is unlikely, if your _.rxg_ files have any of these errors,
they will be reported when you try to run the FS. Only one error is
reported at a time. You will need to correct each error in turn until
the FS starts successfully.  The new errors reported are described in
the <<additional_rxg_errors,Additional .rxg file errors>> change in
the <<FS changes>> sub-section below.

. Use _pfmed_ to add `mk5c_config` and `fb_config` procedures to your
`station` procedure library.

+

This procedures are used to tune the configuration of _jive5ab_ for
your hardware. They can be empty if don't have a Mark 5C or Flexbuff
recorder or no tuning is needed for your recorder(s). We recommend
adding the procedures even if you don't have a Mark 5C or FlexBuff in
case you get them in the future. This will prevent an otherwise
unexpected error about the procedure(s) being missing at that time.

+

NOTE: These procedures are called by _drudg_ generated setup
procedures for systems with Mark 5C and FlexBuff recorders. They
provide a means to tune the setup of _jive5ab_ for your hardware
independent of the observing mode. These procedures are called after
the `mk5c_mode` or `fb_mode` commands to allow the default
configuration to be overridden. The default configuration is described
in the <<../../../dbbc3_ops.adoc#_default_configuration,Default
configuration>> subsection of the <<../../../dbbc3_ops.adoc#,FS DBBC3
Operations>> document and in the `help` pages for `mk5c_mode` and
`fb_mode`. The commands in these procedures should be mode
independent.  Mode dependent tuning should be handled differently;
perhaps by inserting commands directly at the top-level of the setup
procedure.

. If you have a FlexBuff recorder, use _pfmed_ to add a `checkfb` procedure to your
`station` procedure library.

+

_drudg_ uses this procedure in place of `checkmk5` when the selected
recorder is FlexBuff.

+

You can do make this change in one of two ways, using _pfmed_ commands:

.. If you don't also have a Mark 5 recorder, you can rename your existing
procedure:

  pf,station
  rn,checkmk5,checkfb

.. If you also have a Mark 5 recorder, you can make a copy of your
existing procedure:

  pf,station
  st,checkmk5,checkfb

+

Optionally you can modify the new procedure, created by either method,
to make it more appropriate for a FlexBuff recorder.


. <<dbbc3config,FS DBBC3 Configuration>>[[dbbc3config]]: If you have a
DBBC3, you should make the configuration changes described in the
<<../../../dbbc3_ops.adoc#_configuring_the_fs_for_a_dbbc3,Configuring
the FS for a DBBC3>> appendix of the <<../../../dbbc3_ops.adoc#,FS
DBBC3 Operations>> document. If you expect to get a DBBC3, these
changes can be deferred until then.

. If you are using _tcsh_ as your login shell for _oper_ or _prog_ (or
AUID accounts) and have not already done so, adjust _~/.session_ .

+

This step is optional, but may be helpful if you are using _tcsh_ as
your login shell for _oper_ and/or _prog_ (or AUID accounts) and use
the FS with the graphical display on the console.  For this case, you
may wish to make the changes in the <<10.0.0.adoc#xsession,Updating
~/.xsession>> sub-step in
<<10.0.0.adoc#_miscellaneous_fslx_changes,Miscellaneous FSLx changes>>
step of the <<10.0.0.adoc#,FS 10.0.0 Update Notes>> document. If you
have already made these changes, this step can be skipped.

+

This change will make sure the window manager (__fvwm2__) operates
with the FS runtime environment variables set. This could be important
for example, if you want to run __fsclient__ window (perhaps a
`scan_check` window) from a console hotkey.

. Make the `scnch` and `erchk` windows `NeverFocus`.

+

This step is optional. You may want to add `NeverFocus` for the
`scnch`, `erchk`, and `monan` windows in your _~/.fvm2rc_ files so
they will never accidentally get the focus (they don't accept input).
They will still be able to be scrolled. If this is desired, add the
lines:

  Style "erchk" NeverFocus
  Style "scnch" NeverFocus
  Style "monan" NeverFocus
+

As _oper_, you can compare your version of the file with the new
default using:

  cd
  diff .fvwm2rc /usr2/fs/st.default/oper

+

You can make the same change for _prog_, after logging into that
account.

=== Review changes

Please see the <<Changes since 10.0.0>> section below for the details
of the changes since that release.

== Changes since 10.0.0

There are separate sub-sections with summaries of changes in the FS
and _drudg_.

Clickable links such as
https://github.com/nvi-inc/fs/issues/36[#36] connect to specific issues
reported at https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

=== FS changes

. Add more complete support for DBBC3 DDC personality.

+

Previously, the FS only provided limited functionality for DBBC3
racks, as described in the <<dbbc3.adoc#,FS DBBC3 support>> document
for release _10.0.0_. More complete support is provided now. The
updated support is described in the <<../../../dbbc3_ops.adoc#,FS DBBC3
Operations Manual>> document and includes:

+
--

* A separate _dbbc3.ctl_ control file

* Core3H board setting and monitoring with `core3h_mode__n__` commands

* T~sys~ display window (_monit7_)

* Multicast logging, which is controlled with the `tpicd` command.

* `mcast_time` command for checking DBBC3 time from the multicast data

* _drudg_ support for schedules (closing
https://github.com/nvi-inc/fs/issues/33[#33])

* Integrated support for recording DBBC3 data with a FlexBuff recorder

* FS time setting from a DBBC3 with _setcl_ if NTP is not available

--
+

CAUTION: The current FS support is structured around the features of
the DBBC3 DDC firmware, `DDC_U` _v125_ and `DDC_V` _v124_, available
at the time of this release. Firmware updates and experience with the
current approach may lead to different FS support and operations in
the future.

+

Thanks to: the EVN, for funding this development work; Eskil Varenius
(Onsala) for making a system available for development as well as
testing the FS; Sven Dornbusch (MPIfR, Bonn) for elaborating on the
details of DBBC3 functionality; and Uwe Bach (Effelsberg), H.
Verkouter (JIVE), and Jon Quick (HartRAO) for providing helpful
suggestions.

. Expand setup of Mark 5C and Flexbuff recorders

+

The `mk5c_mode` command sends configuration commands, beyond `mode`,
depending on which recorder is selected in equip.ctl, `mk5c` or
`flexbuff`, the total data rate, and the data type, VDIF or
5B/Ethernet. The updated default configuration is described in the
<<../../../dbbc3_ops.adoc#_default_configuration,Default
configuration>> subsection of the <<../../../dbbc3_ops.adoc#,FS DBBC3
Operations Manual>> document.

+

All the settings can be overridden by the `mk5c_config` (or
`fb_config`, depending on the recorder type selected when running
_drudg_) local procedure. See the
<<../../../dbbc3_ops.adoc#_overriding_the_defaults,Overriding the
defaults>> subsection of the <<../../../dbbc3_ops.adoc#,FS DBBC3
Operations Manual>> document.

+

NOTE: Another change, <<fbsyns,FlexBuff synonyms>> in this document,
makes `mk5c_mode` available with the synonym `fb_mode`.

+

Thanks H. Verkouter (JIVE) for extensive discussions about what the
correct settings should be.

. Improve _msg_ to always pick-up a new log file name (closing
https://github.com/nvi-inc/fs/issues/118[#118]).

+

Previously _msg_ only read the log file (and session) name on start-up
and when sending messages. It was modified to reread the log file (and
session) name whenever a new form is displayed. As a result, selecting
any form or send a sending a message from one will cause the log file
name to be reread (and session name reset), in other words, this will
occur for any significant user action. This should provide more
intuitive behavior, primarily because it is no longer necessary to
restart _msg_ for each session.  The setting of the session name when
reading the log file name can be turned off by disabling the `Setup`
selection `Get session name from log` if it is not desired.

+

Thanks to Jonathan Quick (HartRAO) for reporting the issue, providing
feedback on the changes,  and testing the fix.

. Add features to _rdbemsg_:

.. Add command line options to _rdbemsg_.

+

Two command line options were added to _rdbemsg_:

* `-f` -- which takes an integer argument to set the font size,
default is `14`

* `-g` -- which takes a string argument to set the window geometry,
default is not to set it

+

Only the position part of the geometry should be set with `-g`, e.g.,
`-g{nbsp}-0-0`.  The useful way to control the size is with `-f`.

+

.. Add `mci-version` parameter to _rdbemsg.ctl_ control file.

+

This was added to allow distinguishing the early version of MCI node
at Westford, which requires different handling. Specifically, the MCI
logs are in the directory _~oper/node_software/V0_, the file names do
not contain the station code, the fields in the file are space
delimited, and the fields are in a different order. The correct form
for Westford is:

  mci-version:0

+

Other stations do not need this parameter and can either not include
it or comment it out.

+

The example control file, _/usr2/fs/st.default/control/rdbemsg.ctl_
was updated accordingly.

+

NOTE: As with other  _rdbemsg.ctl_ parameters, this one should not
have any white space on its (non-comment) line.


. Add adjustable log size warning message (closing
https://github.com/nvi-inc/fs/issues/114[#114]).

+

When a log is opened (including _station.log_ when starting the FS,
there was  a warning error if the size exceeded 100 MB. Different
stations may find different sizes useful. The size for the warning is
now adjustable by setting the environment variables
`FS_LOG_SIZE_WARNING` to the desired size in MB. If it is not set, it
defaults to 100 MB.

+

The FS must be restarted in a session with the variable set for it to
take effect. If the display server is in use, _fsserver_ must be
stopped (or the system rebooted) _after_ stopping the FS and _before_
restarting it with:

  fsserver stop

+

Thanks to Kiah Imai (KPGO) for suggesting this.

. Increase buffer size for recovering a deleted log.

+

If a log file is not locatable as a file (it has been deleted or
renamed) when a user command would close the log, the FS will attempt
to recover the file and give it its original name. The buffer used to
recopy the file was increased to 2 Mib (512 sectors) so it is faster,
particularly for very large experiment logs with multicast data.

+

IMPORTANT: The recovery will not work if in the meantime a file has
been created with the same name. The FS will think that is the log and
give up. The log file contents will be lost. Using `log=_name_` or
`schedule=_name_` will not cause this.

+

As part of this change, the handling of the file size and positions
were restored to using `long` variables. These had been changed to
`int` variables by the bulk _unlongify_ before _10.0.0-beta1_, but hadn't
been changed back.

. Fix issues in _gnplt_ and _gndat_:

.. Fix plotting of working file T~cal~ curve on zoomed T~cal~ versus
frequency plots in _gnplt_ (closing
https://github.com/nvi-inc/fs/issues/117[#117]).

+

Previously, if you zoomed in the T~cal~ versus frequency plot and
selected display of the working file T~cal~ curve, it would reset the
left plot edge to the unzoomed value when drawing the curve.  This was
caused by an interaction of two issues:

+

--

* The program tried to draw the entire T~cal~ curve, not just the part
in the zoomed frequency range.

* The function, `drawValues`, that adds T~cal~ or T~rec~ lines to
plots, reset any plot limit, except the right edge one, if any data to
be plotted was beyond that edge. This was apparently to allow showing
the vertical axis intercept of the T~rec~ fit and to make sure that
all vertical extents of T~rec~ and T~cal~ curves were not off the
visible plot area.

--

+

This was fixed by limiting the T~cal~ curve plotted to just segments
within the zoomed area. In addition for consistency, the `drawValues`
function was change to reset any plot limit that is exceeded by the
data. Since all other uses of `drawValues` already limited the
horizontal values to be plotted to the zoomed area, there was no
impact on those other uses.

+

Thanks to Eskil Varenius (Onsala), for reporting this issue and
testing the fix.

.. Correct bad T~sys~ data in _gnplt_ (closing
https://github.com/nvi-inc/fs/issues/107[#107] and
https://github.com/nvi-inc/fs/issues/104[#104]).

+

This was caused by an incorrectly sized array in _gndat_ that was
introduced in commit `f84a2bb9` dated June 2003.  This error was
benign unless more than 20 detectors were used in a single _onoff_
run.  Before the advent of RDBEs and DBBC3s, this was unlikely, but
not impossible.

+

Due to the layout of the automatic variables, this error should only
have impacted stem:[\mathit{T_{sys}}] and
stem:[\mathit{T_{sys}-T_{spill}}] data in _gnplt_ and only when there
were more than 20 detectors used. However, also considering the layout
of the automatic variables, it is unclear why there were not
catastrophic program failures in such a case. It would be prudent to
reanalyze any current data sets that used more than 20 detectors with
the fixed version to see if the results change.

+

Thanks to Beppe Maccaferri (Medicina), and subsequently Eskil Varenius
(Onsala), for reporting this issue.

.. Remove extraneous _gndat_ debug output for the processing of
weather data.

+

The debug output was not visible when _gndat_ was run from _gnplt_,
which is normally the only way it is run.

+

. Update _plog_.

.. Fix _plog_ to only refuse to reduce a log with multicast data if it
is the active log in the FS.

+

In the process of reducing a log (removing multicast data), the log is
renamed. This can cause a log recovery to occur if the log is
currently open in the FS since it appears to be missing. This was
protected against by _plog_, which would refuse to rename the log if
it was open to any program. This meant that if the log was was being
viewed with `tail -f` or _less_ it could not be renamed. However,
_plog_ only needed to refuse if the log was open in the FS (by
_ddout_). This was fixed so that _plog_ will only refuse to rename the
log if it is open in the FS.

+

NOTE: In such a case, the operator needs to close the log before
running _plog_ on it. That is good practice in any case.

+

NOTE: Other, non-reduction, log processing by _plog_ was not affected
by this issue since renaming is not needed. It is still good practice
to close the log before pushing it.

+

Thanks to Katie Pazamickis and Jay Redmond (both at GGAO) for
reporting this.

+

.. Add use of _bzip2_ compression to _plog_.

+

_plog_ will now use _bzip2_ as the default program for compressing
___full.log__ files to send to the data centers. It is possible to use
__gzip__ instead by setting the environment variable
`PLOG_COMPRESSED_EXT` to `gz` or using the `-g` command line option.
Please use `*plog{nbsp}-h*` for more information.

.. Upload both reduced and compress logs when multicast is present as
the default.

+

Before, when a log contained multicast data, the default was to only
upload a reduced log (with multicast removed). Now both the reduced
and compressed full log are uploaded by default.

+

A new option, `-r`, was added for uploading just a reduced log. As
before, the `-z` option will upload just a compressed full, It is not
expected that either of these options will get much use. The `-r` and
`-z` options cannot be used together.

+

Thanks to Chevo Terrazas (MGO) for suggesting uploading both files in
one step.

.. Respect `NETRC_DIR` for the `BKG` data center (closing
https://github.com/nvi-inc/fs/issues/113[#113]).

+

This had been overlooked in
https://github.com/nvi-inc/fs/issues/39[#39], which had added the
`NETRC_DIR` environment variable.

+

Thanks to Kiah Imai (KPGO) for reporting this and testing the fix.

+

. Update _fesh_.

.. Add `-P` option to print the summary listing to the printer (closing
https://github.com/nvi-inc/fs/issues/112[#112]).

+

With `-P`, when _drudg_ is run by _fesh_, it will print the summary
directly to the printer. It is appropriate to make this a _fesh_
option since it is an integrated feature of _drudg_. To print other
files, it is recommended to make a wrapper for _fesh_. An example
wrapper, that prints the summary and the _.prc_ file, is included as
_/usr2/fs/fesh/feshp_. This can be copied to _~oper/bin_ and
customized to print other files.

+

Thanks to Kiah Imai (KPGO) for suggesting this.

.. Add `-S` option to _fesh_ to skip downloading.

+

This allows _fesh_ to trigger the normal _drudg_ processing when the
schedule is already on the disk. This might be useful for example, if
the schedule was generated locally by shifting the schedule (_drudg_
option `10`).

+

.. Map station code to lower case (closing
https://github.com/nvi-inc/fs/issues/136[#136]).

+

Before the station code was expected to be lower case. If it wasn't,
this could cause a conflict with _drudg_ which maps it to lower case.
This could result in a mismatch on the file names for deleting _.snp_
and _.prc_ files with the `-f` option. _fesh_ now maps the station
code, from both the `STATION` environment variable and `-s` option, to
lower case.

+

+

Thanks to Eskil Varenius (Onsala), for reporting this issue.

.. Add new environment variables.

+

+

Support for new environment variables `FESH_GEO_USE_SETUP_PROC` and
`FESH_GEO_VDIF_SINGLE_THREAD_PER_FILE` were added. These variables can
be used to supply fixed answers to the new optional _drudg_ prompts as
described in <<drudg changes>> below. For more details about the use
of the new variables, please see the `*fesh{nbsp}-h*` output.


. Fix continuous calibration T~sys~ calculations for DBBC and DBBC3
racks (closing https://github.com/nvi-inc/fs/issues/157[#157]).

+

For the direct sample of count data by _tpicd_ for monitoring T~sys~
for DBBC and DBBC3 racks with continuous calibration, the value of
T~sys~ was being underestimated by about
stem:[\mathit{\frac{T_{cal}}{2}}]. This was because the CAL~on~ counts
were being ignored for determining the count level of T~sys~. This has
been fixed.

+

For the DBBC, this error has been occurring since continuous cal was
first supported in 2012, FS _9.11.0_, commit `f5817f65`. For the
DBBC3, it has been present since the rack was first supported in 2018,
FS _9.12.12_, commit `19a69540`. However, the T~sys~ monitoring for
the DBBC3 was largely unused before then current release because the
device communication rate made it difficult to work with.

+

NOTE: The fix for the DBBC3 is now irrelevant. As of this release,
T~sys~ for the DBBC3 is calculated, correctly, from the multicast
data.

+

This error is fairly small and probably did not have an impact on
routine local performance monitoring. However, if some specialized
measurements were being made, they may have been affected. If this
error had a significant effect for you, please contact Ed.

+

NOTE: Downstream amplitude calibration data should not have been
affected as long as it uses the raw count data, which is how it is
designed to be used.

+

Thanks to Jun Yang (Onsala) for discovering and reporting this. Thank
to Jun and Eskil Varenius (also at Onsala) for making systems
available to verify the fixes.

. Fix continuous calibration T~sys~ calculations in `fivept` (closing
https://github.com/nvi-inc/fs/issues/131[#131]).

+

For continuous calibration systems, T~sys~ was being underestimated
in `fivept` by about stem:[\mathit{\frac{T_{cal}}{2}}]. This was
because the CAL~on~ counts were being ignored for determining the
count level of T~sys~. This has been fixed.

+

This made the point-by-point T~ant~ values larger by the same amount.
This should not have biased the fitted peak source T~ant~ since the
fitting process removes a background level. Nor should it affected the
pointing offsets. Perhaps it actually had some benefit since it made
it less likely that the point-by-point T~ant~ would be negative, which
is always a little unpleasant. It does affect the T~sys~ derived
values of the `#fivpt#perform` output, but those values are mostly a
curiosity and typically not used for any significant work.

+

For the DBBC, this error has been occurring since continuous cal was
first supported in 2012, FS _9.11.0_, commit `f5817f65`. For the RDBE,
this error has been occurring since continuous cal was first supported
in  2016, FS _9.12.5_, commit `217940c1`. For the DBBC3, it has been
present since the rack was first supported in 2018, FS _9.12.12_,
commit `19a69540`.

+

Thanks to Eskil Varenius (Onsala) for making a system available to
verify the fix.

. Add `setup_proc` command.

+

This command is used to identify the setup procedures in the _.snp_ files, e.g.:

  setup_proc=setup01

+

The setup procedure (in this example `setup01`) will be executed if it
is the first `setup_proc=...` command since the schedule was started
or if a different procedure was used in the previous instance of the
command in a schedule.  This can be useful to avoid executing setup
procedures more than necessary, especially if they take very long to
execute, as is the case the DBBC3, or if they may  disturb the
equipment.

+

Use of this command in _drudg_ generated _.snp_ files is controlled
with the `use_setup_proc` option in _skedf.ctl_. The default is to not
use it, which is the same as the previous behaviour.

+

WARNING: The previous behavior of re-executing a setup procedure for
each recording can provide some "`self-healing`" of the equipment
setup if there errors occurred during the previous setup or if the
equipment malfunctioned. The use of this command will eliminate this
added robustness. Each site will need to evaluate whether to use the
option in _drudg_ for this command based on their equipment's
performance. It is typically necessary for DBBC3 systems.

+

See `*help=setup_proc*` for more information.

. Add `mk5init` command to reinitialize the Mark 5 or Flexbuff
connection without restarting the FS (closing
https://github.com/nvi-inc/fs/issues/164[#164]).

+

The `mk5init` command will close the current connection to the Mark 5
or FlexBuff recorder, reread the _mk5ad.ctl_ control file, and
establish a new connection based on the contents. This may be useful
for changing which recorder is used without restarting the FS.

+

NOTE: Another change, <<fbsyns,FlexBuff synonyms>>, in this document,
makes `mk5init` available with the synonym `fb_init`.

+

WARNING: This feature is considered experimental. It appears to work
well, but more extensive field testing may reveal issues.

+

CAUTION: The function of this command may be revised or the command
may be removed in the future.

+

Thanks to Jun Yang (Onsala) for suggesting this.

. <<fbsyns,FlexBuff synonyms>>:[[fbsyns]] Add FlexBuff synonyms for certain Mark 5 commands.

+

The following synonyms for FlexBuff recorders (and their correspond
Mark 5 versions)  were added:

+
--

* `fb` -- `mk5` (`jive5ab` is also a synonym) -- low-level recorder
communication

* `fb_close` -- `mk5close` -- close connection to recorder

* `fb_init` -- `mk5init` -- initialize connection after rereading
_mk5ad.ctl_ control file

* `fb_mode` -- `mk5c_mode` -- set recording mode

+

This command tailors it behaviour depending on what type of recorder
is specified in _equip.ctl_  control file, not by the name of the
command.

* `fb_relink` -- `mk5relink` -- relink to recorder after closing
connection

+

This command is used after `fb_close`/`mk5close` to reestablish the
connection.

* `fb_status` -- `mk5_status` -- report recorder errors

--
+

There is no differences in the function of the commands when the
FlexBuff synonyms are used. They may be used to make the meaning of
procedure files and log entries clearer.

. Split `equip` log header line into to parts.

+

The `equip` line in the log header has been broken into two lines,
`equip1` and `equip2`. The break occurs between the Mark 4 Decoder
Transmission Terminator Character value and the DBBC DDC Firmware
Version value. Except for the clock rate value, the values in the
`equip2` line are only DBBC related values. The clock rate value is
also used for Mark 5B recorders.


. <<refrw_bad,refrw_bad()>>:[[refrw_bad]] Rename _poclb_ routine
`refrw()` to `refrw_bad()`.

+
--
This change makes it explicit that the calculation used in (the now)
`refrw_bad()` routine is incorrect. This has been known about since
2006. The error is generally small above 5&deg; elevation.

The change of the name is intended, belated, to force users to switch
to using the correct `refrwn()` routine in station code. The old
routine can still be used by changing calls to the new name. This may
preferable in the short term if the effect of this error is built into
current point models. To get consistent results, station code can be
converted to use `refrwn()` and a new model can be determined when it
is convenient.

Thanks to Jon Quick (HartRAO) for pointing out this error and
supplying the corrected `refrwn()` in 2006.

--

. Add new refraction calculations to _poclb.a_.

+

Two additional refraction calculations are now
available in the C language _poclb.a_ library:

+
--

* `sbend()` -- from A. L. Berman and S. T. Rockwell, "`A New Radio
Frequency Angular Tropospheric Refraction Model,`" JPL DSN Progress
Report 42-25, pp. 142-153, November and December 1974
(https://ipnpr.jpl.nasa.gov/progress_report/42-25/25V.PDF) and A. L.
Berman, "`Modification of the DSN Radio Frequency Angular Tropospheric
Refraction Model,`" JPL DSN Progress Report 42-38, pp. 184-186,
January and February 1977
(https://tmo.jpl.nasa.gov/progress_report2/42-38/38V.PDF).

* `lanyi()` -- from G. Lanyi, "`Atmospheric Refraction Corrections to
Antenna Pointing at 1 Millidegree Level,`" JPL IOM 335.3-89-026, 24
March 1989, with corrections, and T. D. Moyer, "`Formulation for
Observed and Computed Values of Deep Space Network Data Types for
Navigation,`" Section 9.3.2.2.1 (pp. 295-297), John Wiley, 2003
(https://descanso.jpl.nasa.gov/monograph/series2/Descanso2_S09.pdf).

--
+

The older `refrwn()` is apparently from W. R. Iliff and J.  M. Holt,
"`Use of Surface Refractivity in the Empirical Prediction of Total
Atmosphere Refractions,`" J. Research NBS 67D (Radio Prop.), No.  1,
pp. 31-35, January-February, 1963
(https://www.semanticscholar.org/paper/Use-of-surface-refractivity-in-the-empirical-of-Iliff-Holt/1ddcd0e4e672dd890198539361c5237c033001f7)
and C. A. Clark, "`Haystack Pointing System: Radar Coordinate
Correction,`" MIT LL Technical Note 1966-56, 24 October 1966
(https://www.semanticscholar.org/paper/HAYSTACK-POINTING-SYSTEM%3A-RADAR-COORDINATE-Clark/bf564e4ebc49a4ae8d69333b267a97cc320109a0).
Thanks to Ludwig Schwardt (SKA, South Africa) for tracking down these
references.

. Add test utilities: _precess_, _move_, and _refrac_.

+

This utilities are available in sub-directories in _misc/_ with the
names of the programs. They are intended for testing and
experimentation.

.. The _precess_ program can be used to precess mean coordinates
between epochs B1950 and J2000. Two options approaches are available:

+
--

** The method used by the FS in _fslb/prefr.f_. This is the same
method used by _drudg_ (which has its own copy of _prefr.f_).

** The method provided by the SOFA library.

--
+

See the _README.txt_ file in the directory for more information.

+

.. The _move_ program can be used to calculate apparent coordinates of
date and apparent topocentric coordinates of date.


+

This uses the same method as the FS `source=...` command.

+

See the _README.txt_ file in the directory for more information,

.. The _refrac_ program can be used to compare different refraction
algorithms at different elevations and under different meteorological
conditions.

+

+

This is program has a set of comparisons hard-coded, but could be
modified to test other situations.

. Correct erroneous Ethernet transaction error messages.

+

Previously, the message for reporting errors when sending data to the
Ethernet devices (Mark 5s, DBBCs, RDBEs, Mark 6s), incorrectly stated
that the connection was closed. The connection is not closed. Perhaps
it should be, but the incorrect statements have been removed until the
functionality is changed.  The affected errors are:
`DB`/`M5`/`M6`/`RA` `-102`.

. Clean-up suppressing of signals.

+

--

.. Remove redundant ignoring of signals in _ddout_ and _oprin_
(partially closing https://github.com/nvi-inc/fs/issues/100[#100]).

.. Re-enable suppression of signals (partially closing
https://github.com/nvi-inc/fs/issues/100[#100]).

+

As of _10.0.0-beta1_, the previous practice of disabling receipt of
certain signals, in particular `SIGINT` (for kbd:[Control+C]) had been
removed. It has been reinstated. When the FS is run without the
display server, this assures that no FS programs will be aborted if a
kbd:[Control+C] is accidentally entered in the terminal session where
the FS is running. However, this does not prevent a kbd:[Control+C]
from killing an _xterm_ that is wrapped around a FS program (typically
only _oprin_) in the FS terminal session from being killed.
Preventing that is discussed next.

.. Use `setsid()` to shelter __xterm__s from keyboard generated
kbd:[Control+C].

+

To prevent kbd:[Control+C] killing an _xterm_ in the FS terminal
session all `x` programs in _fspgm.ctl_ and _stpgm.ctl_ (usually just
_oprin_) are now run under `setsid()` when the display server is not
being used. This disconnects the programs from the terminal session
that the FS is being run in, thereby preventing a kbd:[Control+C] from
reaching them, but not otherwise affecting them.

--
+

With these changes, it should no longer be possible to kill the FS
with a kbd:[Control+C], even when the display server is not being
used.

+

CAUTION: An FS _xterm_  window can still be terminated using the
decorations for the window. When the FS is not being running with the
display server, this will kill the FS _abnormally_. The decoration
button that includes the `Delete` and `Destroy` options can be removed
if desired. In the _~/.fvm2rc_ file include `NoButton 1` in the
window's `Style` (see the `Style "oprin" ...` line in
_st.default/oper/.fvwm2rc_ for an example).

. Record _fsserver_ error messages (closing
https://github.com/nvi-inc/fs/issues/105[#105]).
+

The display server now makes a file with a name of the form
_~/fsserver.<time-stamp>.err_ each time it is started. It is used to
collect server error information. The file will be deleted if
_fsserver_ terminates normally. If you experience a server crash,
please send this file to Ed or post it as part of an issue on
_github_. The _<time-stamp>_ portion of the name will correspond to
the time when the server was last started before the crash. That is
usually when the FS was first started after the last boot. Any file of
this type with non-empty contents is worth reporting.

+

Thanks to Dave Horsley (AuScope) for suggesting this and contributing
to the implementation.

+

NOTE: The FS also makes a file with a name of the form
_~/fs.<time-stamp>.err_ each time it is started. It is used to collect
FS error information. The FS will attempt to delete this file if it
terminates normally. If you experience a FS crash, please send this
file to Ed or post it as part of an issue on _github_. The
_<time-stamp>_ portion of the name will correspond to the time when
the FS was last started before the crash.

. Add explanatory comments to the example _flux.ctl_ control file (closing
https://github.com/nvi-inc/fs/issues/121[#121]).

+

Although the data used in the file came from other sources, for many
years the code that read the _flux.ctl_ file was the complete
documentation for the format.  The example file in
_/usr2/fs/st.deafault_ now includes the details in an easier to read
form. You can merged these comments, which are at the end of the
example file, into your local copy or refer to the example.

+

Thanks to Stuart Weston (Warkworth) for suggesting this and
contributing some of the information in the comments.

. Improve error messages when reading _flux.ctl_ (closing
https://github.com/nvi-inc/fs/issues/124[#124]).

+

The error messages when reading _flux.ctl_ were confusing and
uninformative. This has been the situation since the file was first
added in October 2002, for version _9.5.15_ (commit `1b68b90f`).
Apparently, this was not a significant issue because, apparently,
modifying the default contents was uncommon. If you have been having
trouble with this, we apologize.

+

The error messages have been more explicit about the cause of any read
error and the offending line is printed to aid in correcting the
problem.

+

Thanks to Stuart Weston (Warkworth) for reporting this.

. Improve error messages when reading _.rxg_ files.

.. Make error messages more informative (closing
https://github.com/nvi-inc/fs/issues/83[#83]).

+

The error messages when reading _.rxg_ files  were confusing and
uninformative. This has been the situation since _.rxg_ files were
first added in October 2002, for version _9.5.15_ (commit `1b68b90f`).
Apparently, this was not a significant issue because _.rxg_ files were
usually updated by _gnplt_, which wrote correctly formatted lines. If
you have been having trouble with this, we apologize.

+

The error messages have been more explicit about the cause of any read
error. Unfortunately, it is not possible to show the offending line
without more significant changes. However, the messages are fairly
explicit about where the error occurred.

+

The same reading routine is used in _gnplt_ (which uses _gndat_ to
read the _.rxg_ files) for consistency. Unfortunately, the error
messages for _gnplt_ will still not be as informative, but restarting
the FS should provide a more explicit error message that help make it
clear what the problem is. If it is not possible to use the FS for
this, another strategy is to use the error number reported in status
line at the bottom of _gnplt_ to identify the corresponding `RG` error
in _controlfserr.ctl_.


+

.. [[additional_rxg_errors]]<<additional_rxg_errors,Additional .rxg
file errors>>: Five additional errors are now reported (closing
https://github.com/nvi-inc/fs/issues/134[#134]):

+
--

* The third field on the LO line is missing for type `range`.

* If a third field exists on the LO line, but does not decode as a
number.

* The second field on the FWHM line is missing for type `constant`.

* If a second field exists on the FWHM line, but does not decode as a
number.

* A field exists after the gain curve coefficients, but is not
`opacity_corrected`.

--
+

While it is unlikely, if any of your _.rxg_ files have these errors,
they will be reported the first time you run the FS after the update.
You can correct them at that time. The error messages should be pretty
clear.

+

A few other, minor, errors are still not being caught. In particular,
if a character that cannot be part of a numeric field appears
_within_, or at the end of, a numeric field, that error will not be
reported. In that case, the field up to the out-of-place character will
be used as the value. Hopefully this is an unlikely error. A leading
character that cannot be part of a numeric field will be reported as
an error.

+

. Add instructions to the example _.xsession_ files for how to
make them work correctly when _tcsh_ is the login shell.

+

Instructions for implementing this were added to the <<10.0.0.adoc#,FS
10.0.0 Update Notes>> document as the <<10.0.0.adoc#xsession,Updating
~/.xsession>> sub-step in the
<<10.0.0.adoc#_miscellaneous_fslx_changes,Miscellaneous FSLx changes>>
step.

. Improve default _.fvwm2rc_ files.

+

The _.fvwm2rc_ files in the _auid_, _oper_, and _prog_ sub-directories
of _/usr2/fs/st.default_ were updated. These changes  only affect
behavior on the console GUI.

.. Add use of `NeverFocus` for the `scnch` and `erchk` windows.

+

This was previously added in _10.0.0-beta1_, but removed on _10.0.0_
because it was thought to prevent scrolling of those windows. However,
that turned out to not be the case. Using this setting prevents the
focus from accidentally being given to these windows, which don't
accept input.

.. Improve consistency of hot key definitions.

+

+

Previously the handling of _msg_, _rdbemsg_, _monpcal_, and _monit6_
were not consistent. Now the default configuration is for
kbd:[Control+Shift+M] to open _msg_ and kbd:[Control+Shift+6] to open
_monpcal_ and for these programs to be displayed in the `Button 2`
menu. Immediately below the configuration lines for these programs are
commented out lines for _rdbemsg_ and _monit6_, which can be used
instead by sites with RDBEs.

. Correct error in FORTRAN calls to get FiLa10G time for _setcl_.

+

An argument was missing. This was a bug from the VGOS branch, which
technically do not support using _setcl_ for FiLa10G. The bug
apparently did not affect versions since the merge since there was a
relatively low, not quite 1 in 2^32^ chance of it being excited.

+

NOTE: _setcl_ only works for the first FiLa10G if there are two. A
second is only used for VGOS. _fmset_ works for both.

. Remove extra comma in T~cal~ table log entires (closing
 https://github.com/nvi-inc/fs/issues/160[#160]):

+

The contents of the _.rxg_ selected by an `lo=...` command are logged
the first time the file is selected since the log was last opened.
There was a redundant comma in the T~cal~ table log entries after the
_.rxg_ file name.

. Correct `bbc_gain` command error codes.

+

If an error occurred in the monitor form of the command, the error was
reported as `di` instead of `dg`.

. Improve font conventions.

+

These conventions are covered in the
<<../../../misc/font_conventions.adoc#,FS Document Font Conventions>>
document. The following descriptions refer to sections in that
document. The conventions themselves are covered in the
<<../../../misc/font_conventions.adoc#_conventions,Conventions>>
subsection. Examples are in the
<<../../../misc/font_conventions.adoc#_source_examples,Source
examples>> section.

.. Add description of using inline anchors.

+

These can be used to making linking references to arbitrary text in
the documents. This convention is covered as "`other anchors`" in the
<<../../../misc/font_conventions.adoc#_links,Links>> subsection.
The document also shows how to make the anchor visible in
the text. This is described in the example
<<../../../misc/font_conventions.adoc#_linking_to_inline_anchors,Linking
to inline anchors>> subsection.

.. Improve description of code blocks.

+

Add use of bold for user input and bold italic for replaceable user
input. This convention is described in the
<<../../../misc/font_conventions.adoc#_code_blocks,Code blocks>>
subsection.  The example is covered in the subsection
<<../../../misc/font_conventions.adoc#_italics_and_bold_in_code_blocks,Italics
and bold in code blocks>>.

.. Add description for using appendices.

+

This convention is covered in the
<<../../../misc/font_conventions.adoc#_links,Links>> subsection. The
example is covered in the subsection
<<../../../misc/font_conventions.adoc#_appendices,Appendices>>.

+

. Improved wording for setting geometry values in _~/.Xresources_.

+

Using differently named _~/.Xreources_ files that are used by
different aliases for different displays is described in the final
*NOTE* of the
<<../../misc/install_reference.adoc#_setting_geometry_values_in_xresources,Setting
geometry values in .Xresources>> in the
<<../../misc/install_reference.adoc#,Installation Reference>>
document.

. Change cut-and-paste phrasing in documents to copy-and-paste

+

This is technically more accurate. The change primarily affects the
(now)
<<../../misc/install_reference.adoc#_copy_and_paste_installation_tips,Copy-and-paste
installation tips>> in the
<<../../misc/install_reference.adoc#,Installation Reference>> document
and references to it.

. Add other fixes:

.. Remove `e` rack type in help files.

+

+

Help for the `pcald` and `tpicd` commands is now for every rack.

.. Add the missing `formbbc` and `formif` detector groups in `onoff`
for DBBC3 racks.

.. Corrected `error number for trouble opening _time.ctl_.

.. Add missing `32` and `64` MHz BWs in help for DBBC `bbc__nn__`
commands.

.. Add missing `64` MHz BW for `fivept` and `onoff` with DBBC BBCs.

.. Add `0` MHz BW for display of DBBC3 BBCs that are not configured.

.. When sending a target level for the DBBC3 IFs, always send `1` for
the filter selection, and ignore the filter selection on read back.

+

+

Currently, this parameter is used in the syntax for the device, but is
meaningless.

.. Add useful default IF sources for DBBC3 `bbc__nnn__` commands.

.. Allow `0` for DBBC3 BBC frequencies.

.. Generalize DBBC3 `dbbcgain` command read back to handle DBBC3s.

.. Make numerous wording fixes.

.. Correct a few compile warnings, but certainly not a significant number.

.. Add missing `help` page for `jive5ab` command.

.. Reorganize and cleanup the `help` file for `onoff`.

.. Fix error that prevent DBBC3 `ack` responses from passed to logging
system.

.. Add missing `bbc110` command for DBBC3.

=== drudg changes

_drudg_ opening message date is 2021-12-28`.

. Add support for DBBC3 DDC racks.

+

_drudg_ can handle VEX schedules, _.vex_, with up to 128 dual
side-band BBCs and eight IFs, It can handle Mark III schedules, _.skd,
with up to 16 dual sideband BBCs (`1`-`16`) and two IFs (`a` and `b`).

+
[NOTE]
====

At this time it is only considered safe to set the configuration of
then Core3H boards with the DBBC3 boot configuration file. As a result
the _drudg_ generated setup procedures only _check_ the configuration
of the Core3H boards. Once it is possible to set the Core3H boards
remotely. The setup procedure can be run with `force` as its argument
set the configuration manually. For example:

  setup01=force

====

+

[TIP]
====

A full check (or setup) of the Core3H boards will take longer than
schedules allow for setup procedures to execute. As a result, it is
strongly recommended that the new `use_setup_proc` _drudg_ option in
_skedf.ctl_ (see <<use_setup_proc,use_setup_proc>> below) be enabled
for use with DBBC3s. This will cause the mode to be checked only at
the start of the schedule. If the schedule is started at least a few
minutes ahead of time, there should be no delays in schedule
execution due to the setup procedure.

====

. Replace use of all `mk5...` commands with `fb_...` commands in
generated procedures when the selected recorder is FlexBuff. The
following substitutions are made:
 
* `fb` for `mk5`

* `fb_mode` for `mk5c_mode`

* `fb_status` for `mk5_status`

+

NOTE: As a general rule, _drudg_ will use the `fb` versions of `mk5`
commands and procedures when the selected recorder is FlexBuff. The
procedures are discussed in individual items below.


. Replace use of the `checkmk5` procedure with `checkfb` in _.snp_
files when the selected recorder is FlexBuff.

. Add, optionally, `thread...` procedures to setup procedures
for Mark 5C and FlexBuff recorders.

+

This procedure controls whether VDIF data is recorded multithreaded or
single thread per file. Its use is described in
<<../../../dbbc3_ops.adoc#_thread_procedure,Thread procedure>>
subsection of the <<../../../dbbc3_ops.adoc#,FS DBBC3 Operations
Manual>> document.

+

NOTE: Although it is expected that only one thread selection will be
used for an entire experiment, a separate `thread...` procedure is
created for each mode. This allows them to be customized by mode if
that should prove useful.


. Add `mk5c_config` or `fb_config` procedure calls to setup
procedures for Mark 5C and Flexbuff recorders, respectively.

+

These procedures can be used to override the default configuration of
Mark 5C and FlexBuff recorders. They are called after the `mk5c_mode`
or `fb_mode` commands (and after the `thread...` procedure if
present). They are local procedures intended to provide tuning for the
recorder configuration.

+

For more information see the
<<../../../dbbc3_ops.adoc#_mk5c_configfb_config_procedure,mk5c_config/fb_config
procedure>> subsection of the <<../../../dbbc3_ops.adoc#,FS DBBC3
Operations Manual>> document.

. Enhancements to summary listings, from option `5`:

.. The `GB` positions and totals
are now also listed when the recorder is none (closing
https://github.com/nvi-inc/fs/issues/166[#166]).

.. The `GB` fields were expanded to allow for larger data volumes.

.. The `Info` column and the captions in the header describing it were
cleaned-up.

. Changes to _skedf.ctl_ options

+

Please see the _/usr2/fs/st,default/control/skedf.ctl_ for details
about the use of these options.

.. New `e-vlbi_override` option

+

If enabled, _drudg_ will automatically convert the recorder to `none`
if the `target_correlator` parameter in a VEX schedule includes the
string `e-vlbi` (case insensitive). This can still be overridden with
_drudg_ option `11`.

.. New `scan_close` option

+

If enabled, _drudg_ will detect gaps in the schedule at least as long
as a user settable `max_gap_time`, say an hour, and wait to start the
next scan a user settable `pre_time` time before it is scheduled. The
`pre_time` should probably be short, but at least as long as the worst
case slewing time of the antenna. The concept is that the scan at the
start of gap is _closed_, i.e., `check...` procedure is run before
slewing to the next source. Then there is a wait until the `pre_time`
before the next scan will begin for the `scan_name=...` and
`source=...` to be commanded.

+

This can be useful for intensive schedules. The antenna won't slew
needlessly to a new source or setup for new scan at the start of the
gap. The schedule can be broken into while it is waiting for the next
scan to start, the intensive schedule run, and then the original
schedule rejoined for the next scan.

.. <<use_setup_proc,use_setup_proc>>[[use_setup_proc]]: New `use_setup_proc` option

+

+

If enabled, _drudg_ prefixes each setup procedure with `setup_proc=`
to invoke that command. For more information see
the
<<../../../dbbc3_ops.adoc#_minimizing_the_use_of_setup_procedures,Minimizing
the use of setup procedures>> subsection of the
<<../../../dbbc3_ops.adoc#,FS DBBC3 Operations Manual>> document.

.. New `vdif_single_thread_per_file` option

+

This option allows control of whether the VDIF files created by Mark
5C and FlexBuff recorders are multi-threaded or single threaded.

+

For more information see the
<<../../../dbbc3_ops.adoc#_thread_procedure,Thread procedure>>
subsection of the <<../../../dbbc3_ops.adoc#,FS DBBC3
Operations Manual>> document.

.. Expanded `default_dbbc_if_inputs` option

+

Defaults for up to eight IF inputs can be specified for DBBC3s.

.. Expanded `default_dbbc_if_targets` option

+

+

Defaults for up to eight IF inputs can be specified for DBBC3s.

. Add other enhancements:

.. Support slewing model acceleration in _.skd_ files.

.. Use ISO  format for opening message date

.. Remove trailing spaces in _.prc_ files

.. Remove some obsolete variables

.. Various clean-ups
