//
// Copyright (c) 2020 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= FS 10.0.0-beta3 to FS 10.0.0 Update Notes
Version 1.0 - December 2020

//:hide-uri-scheme:
:sectnums:
:sectnumlevels: 4
:experimental:

:toc:
:toclevels: 4

== Introduction

The document covers updating from the _beta3_ pre-release to the
FS _10.0.0_.

For instructions for other upgrade paths, see the
<<10.0.0.adoc#_other_update_documents,Other update documents>>
sub-section of the
<<10.0.0.adoc#,FS 10.0.0 Update Notes>> document.

== Upgrading from 10.0.0-beta3 to 10.0.0

You must have already upgraded to the <<beta3.adoc#,10.0.0-beta3>>
release before installing this update.

=== Fetch and make the latest commit

If you are using _git_, as is recommended, then as _prog_
execute:

             cd /usr2/fs-git
             git checkout -q 10.0.0
             git pull
             make clean rmdoto rmexe
             make >& /dev/null
             make -s

No output from the last command indicates a successful _make_.

=== Additional steps

. If you are updating from the VGOS branch, and haven't already, you
should remove use of the deprecated _be_client_, _mcicn_, and
_udceth0_ scripts with the more general _s_client_ script.
+

You can find instances of the deprecated scripts commands, using,
e.g., for _be_client_:

   cd /usr2/proc
   grep be_client *.prc

+

You can use `less` to identify the SNAP procedures in each file that
uses the script. Use _pfmed_ to make the changes.
+

Information about using _s_client_ can be found using `*help=sy*`.

=== Review changes

Please see the sub-section <<Changes since 10.0.0-beta3>> below
for details of the changes since that pre-release.

== Changes since 10.0.0-beta3

There are separate sub-sections with summaries of changes in the FS
and _drudg_.

Clickable links such as
https://github.com/nvi-inc/fs/issues/36[#36] connect to specific issues
reported at https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

=== FS changes

. [[makeinc]] Add _make_ commands after `git checkout` in incremental
update notes.

+

For incremental updates it is necessary to clean the old compiled
code. This is due to _drudg_ not participating in the new _Makefile_
scheme, but it is generally cleaner too. Thanks to Carlo Migoni
(Sardinia) for reporting this.

. Add switching to _s_client_ to the update notes.

=== drudg changes

There are no changes.
