//
// Copyright (c) 2020 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= FS 10.0.0-beta3 Update Notes
E. Himwich, D. Horsley, J. Gipson, J. Quick
Version 1.0 - December 2020

//:hide-uri-scheme:
:sectnums:
:sectnumlevels: 4
:experimental:

:toc:
:toclevels: 4

== Introduction

This update is intended as a test version for all stations using FS9.
This includes both stations using the main, non-VGOS, branch (latest
version _9.13.2_) and the VGOS branch (latest versions
_9.12.10_-_9.12.13_). Installing the new version as an update for
these cases is fairly simple but has several steps, see the
<<Upgrading from an FS9 version>> section below.

The most significant changes in _10.0.0_ are:

. One unified version for all FS users.

+

Both non-VGOS and VGOS operations are supported by the new version.
Previous installations of the main (non-VGOS) branch will need to have
some new local control files added.

+

The most significant change for users is that previous main branch users will
find that in the new FS input is case sensitive, as it was already
in the VGOS branch.

. Support for use on both 32- and 64-bit systems.

+

The new version should run on 32-bit systems that currently support
the FS as well as on 64-bit systems. We have verified it will run on
32-bit systems as far back as FSL8. We have not yet tested it on even
older systems, such as FSL7.
+

There are also instructions for transitioning to a 64-bit system,
which may require some relatively simple changes to station software.
See the <<../../misc/64-bit_conversion.adoc#,Converting to a 64-bit System>>
document for more details. Also see the *TIP* in
<<Upgrading from an FS9 version>>.

+

A new FS Linux distribution, FSL10 (based on Debian _Stretch_), is now
available for 64-bit (and 32-bit) use. We recommend using this
distribution if you would like to move to using a 64-bit OS or need a
32-bit OS that is still under support (the base Debian distribution,
_Wheezy_, used for FSL9, and those for older FSLx versions, are no
longer under support). This also may be an alternative for users with
distributions (such as FSL7) that may be too old to support the
current FS.  Installation instructions for FSL10 can be found at
<https://nvi-inc.github.io/fsl10>.

+

. Version control with _git_.

+

The FS source is now managed using _git_ and _github_ is used for
distribution. The source code is now under the GPL3 license.

+

The details of the model used for FS releases under _git_ are
described in the <<../misc/release_model.adoc#,Release Model>> document.

+

This change increases the importance of not modifying the
_/usr2/fs_ directory tree since such changes will make it more
difficult to simply `pull` updates to install bug fixes and new
features.

. The FS display server is now recommended for normal use.

Please also see the section <<Changes from FS9>> below for details of
the changes compared to the latest FS9 versions.

The release of _10.0.0_ would not have been possible without the many
and large contributions of Dave Horsley (UTAS, Australia and
NVI/GSFC).  These contributions include, but are not limited to:

. Making the FS 32- and 64-bit compatible
. Placing the FS under _git_ version control
. Importing the existent archive of FS versions into _git_
. Merging the main and VGOS branches of FS9

An essential contribution was also made by Tetsuro Kondo (NICT, Japan
and SHAO, China). Kondo-san pioneered 64-bit support in the FS with
his 64-bit implementations for the Sejong and Ishioka stations. Dave
built on his work in developing a version that would support both 32-
and 64-bit systems.

Dave single-handedly imported the entire existent history of FS source
code into _git_. This includes over 130 FS9 versions (under Linux), 17
FS8 versions (under VENIX), and two older versions (under HP
RTE-1000/A) going back to version 5.5 in 1988.  Having the source code
in _git_ greatly simplified the task of merging the main and VGOS
branches. Dave also did the most critical work on that and provided
excellent guidance on using _git_. Having the historical code in _git_
is a great resource for understanding its evolution.

As always, we are deeply indebted to Jonathan Quick (HartRAO, South
Africa) for his many significant contributions that go far beyond what
is explicitly mentioned here. For this particular release, his
contributions include testing and insights for adapting the code for
64-bit use, patiently solving various problems, identifying and fixing
issues with the new version on FSL8, developing FSL10, making many
helpful suggestions for changes, testing, and providing feedback.

We also thank Beppe Maccaferri (Medicina) for being a diligent beta
tester, reporting bugs, helping test several fixes, and making helpful
suggestions for changes.

We would also like to thank Eskil Varenius (Onsala) for bug reports
and feedback, particularly on DBBC3 related issues.

== Other useful documents

This section provides links to some other useful documents.

=== Other update documents

* https://raw.githubusercontent.com/nvi-inc/fs/259e203330fff145dba5ea6b2f48c8bcd23b4333/misc/fs10.0.0up.txt[FS 10.0.0 Beta[1\] Update Notice]

* <<beta1_to_beta2.adoc#,FS 10.0.0-beta1 to FS 10.0.0-beta2 Update Notes>>

* <<beta2.adoc#,FS 10.0.0-beta2 Update Notes>>

* <<beta2_to_beta3.adoc#,FS 10.0.0-beta2 to FS 10.0.0-beta3 Update Notes>>

* <<beta3_to_latest.adoc#,FS 10.0.0-beta3 to Latest Commit Update Notes>>

=== Miscellaneous documents

* <<../misc/known_bugs.adoc#,Known Bugs>> document with the known bugs list from FS9.

* <<../misc/install_reference.adoc#,Installation Reference>> document with other useful install
information is available.  It includes eight sub-sections:


. <<../misc/install_reference.adoc#_upgrading_from_fs_versions_before_the_previous_stable,Upgrading from FS versions before the previous stable>>
. <<../misc/install_reference.adoc#_example_standard_procedure_libraries,Example standard procedure libraries>>
. <<../misc/install_reference.adoc#_cut_and_paste_installation_tips,Cut-and-paste installation tips>>
. <<../misc/install_reference.adoc#_making_a_back_up_before_installing,Making a back-up before installing>>
. <<../misc/install_reference.adoc#_disk_space_requirements,Disk space requirements>>
. <<../misc/install_reference.adoc#_set_operations_file_permissions,Set operations file permissions>>
. <<../misc/install_reference.adoc#_fix_prc_file_define_lines,Fix .prc file define lines>>
. <<../misc/install_reference.adoc#_setting_geometry_values_in_xresources,Setting geometry values in .Xresources>>

If you haven't upgraded or installed the FS before, you may want to
review the appendix.  It is _strongly_ recommended that you back-up your
operational system before upgrading.

== Upgrading from an FS9 version

CAUTION: This release of the FS may not _build_ on older Linux
distributions, such as FSL7 (_Etch_). If you do try it on a FSL7 or an
earlier distribution please email Ed with your experience. If it
doesn't work we will try to help resolve any issues.

This section covers upgrading from FS9, which was always 32-bit only,
to _10.0.0-beta3_. It is assumed you are upgrading on a 32-bit system.
There are two possible paths for upgrading:

. Upgrading from a main branch version. The main branch versions
are numbered _9.13.x_ and _9.11.x_ or older.  Specifically, versions
_9.12.x_ are not part of the main branch.  If you are upgrading
from a main branch version, it is assumed that upgrade is from
_9.13.2_, the previous stable release.  If you have a main branch
version older than version _9.13.2_ you should upgrade to _9.13.2_
first, please refer to the
<<../misc/install_reference.adoc#_upgrading_from_fs_versions_before_the_previous_stable,Upgrading from FS versions before the previous stable>>
section in the
<<../misc/install_reference.adoc#,Installation Reference>> document
for more information.

. Upgrading from a VGOS branch version.  The VGOS branch versions
are numbered _9.12.x_.  The instructions provided in this section
are for installing as an upgrade to versions
_9.12.10_-_9.12.13_, the latest VGOS branch releases. As far as we
know, no other VGOS versions are in use.  If you have a different
version, please email Ed for more information.

The upgrade instructions for the update from the main branch and the
VGOS branch differ only in the details of the step <<Update control files>>.
To upgrade from FS9 to FS10 on a 32-bit system, please
follow the steps below.

[TIP]
====

It is also possible to upgrade as a new installation on a 64-bit
system. Doing so will allow you to upgrade to _10.0.0_ and 64-bit
without disturbing your operational 32-bit system. However, the upgrade may
be more involved because it may require additional changes and
testing for your station software.  The instructions for combining the
FS and 64-bit upgrade are:

. Follow the steps in the
<<../../misc/64-bit_conversion.adoc#,Converting to a 64-bit System>> document
down to the 
<<../../misc/64-bit_conversion.adoc#_make_local_software,Make local software>>
step. Instead of following that step, return to the next step in this *TIP*.
+

NOTE: After completing this step, you will have a base
FS10 installation on a 64-bit system with your local software (updated
for 64-bit), control files, and procedure files from your FS9 32-bit
system. That is an inconsistent configuration that will not work
properly.  Your local software and other local files need to be
updated for _10.0.0_, which is covered in the next step in this *TIP*.

. To update your local software and other local files for _10.0.0_,
follow the instructions beginning with the
<<Case sensitive strings in antenna= commands>>
sub-step below and continue with the remaining sub-steps and steps
thereafter.

+

When you get to the <<Test the FS>> step, you may need to debug
your, 64-bit converted, station software.

====

=== Back-up your operational system

Having a back-up to return to
will allow you to continue operations in case something goes
wrong with the installation.  For more details, please see the
<<../misc/install_reference.adoc#_making_a_back_up_before_installing,Making a back-up before installing>>
section in the
<<../misc/install_reference.adoc#,Installation Reference>> document.

NOTE: If you are using FSL10 with a RAID, that sub-section points you to the
improved backup and test procedure that is available with
that distribution.

NOTE: That section also includes a description of how to
preserve your operational files and switch back and forth
between an operational and a test set-up by changing
symbolic links.

=== Login as root

Login as _root_.

=== Download the FS

Place a copy of the FS _git_ repository in the _/usr2_ directory on
your computer. For example, you might do the following:

       cd /usr2
       git clone https://github.com/nvi-inc/fs.git fs-git

or alternatively, if you are using FSL8 or other old Linux
distribution, or otherwise need to use _ssh_ instead:

       cd /usr2
       git clone git@github.com:nvi-inc/fs fs-git

[TIP]
====

Using _ssh_ requires you to have a _github_ account and for you to add
an _ssh_ public key from your machine's _root_ account to your
_github_ account. For more information, go to https://github.com/join
and
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account.

CAUTION: We also recommend you add a _ssh_ public key from your _prog_
account. This will make it easier to install later updates from
_github_ as _prog_. All instructions for further _github_ use are
written for _prog_.

====

[TIP]
====

If you don't have _git_, you may be able to install it. Some older
Linux distributions, e.g., FSL8, have the _git_ package available
under a different name, _git-core_. To install _git_, we recommend
trying to install the _git-core_ package first.  In older Debian-based
distributions this should install the required package instead of
another package that was named _git_ in those distributions (Gnu IT).
If you don’t see anything named _git-core_, then try installing _git_
instead.

If you are unable to install _git_ (or _git-core_), you can install
the FS from an archive. Please follow these
directions:

. Stopping _before_ the `*make install*` step, execute the steps in the
<<../misc/release_model.adoc#_installing_from_an_archive,Installating from an archive>>
sub-section in the
<<../misc/release_model.adoc#,Release Model>> document.

. Return to the current document, jumping ahead to the
<<Set the /usr2/fs link>>
step below and continue the installation, but skip the
`*cd /usr2/fs-git*` command in that step.

====

=== Checkout the release

Checkout the _beta3_ release from the local repository:

       cd fs-git
       git checkout -q 10.0.0-beta3

=== Set the /usr2/fs link

Set the link for the new FS version:

       cd /usr2/fs-git
       make install

Answer `*y*` to confirm installation.

CAUTION: This step will change your _/usr2/fs_ symbolic link to point
to _/usr2/fs-git_. To switch back to your old version, you will need
to change the link manually.

NOTE: The `make install` command may create and possibly rename some
existing directories if the FS was never installed on this system
before. However, since you should only be following this path if you
are upgrading an FS9 installation, there should not be any problem.

=== Fix file permissions

Having the wrong ownership and/or permissions on the operational
files (procedure libraries, control files, schedules, and logs)
can cause errors during FS operations.  For a full discussion,
please refer to the
<<../misc/install_reference.adoc#_set_operations_file_permissions,Set operations file permissions>>
section of the
<<../misc/install_reference.adoc#,Installation Reference>> document.
For stations where all the operational files are
expected to owned by user __oper__ in group __rtx__, with permissions
`ug+rw,o+r,o-w`, the following command will enforce this (note
that the __execute__/__search__ bits are not changed):

       /usr2/fs/misc/fix_perm

Answer `*y*` to the prompt if you wish to proceed. It is recommended for most stations.

=== Login as prog

IMPORTANT: Logout as _root_, and login as _prog_.

=== Set FORTRAN compiler

Starting with version _10.0.0_, the standard
FORTRAN compiler for use with the FS is _f95_ (_gfortran_).
We recommend that you use it. On the 32-bit systems you can
still use _fort77_, but you should only use it if you either
don't have _f95_ or if you have FORTRAN station code that
is too difficult to convert to _f95_, see sub-step <<Conversion of FORTRAN code>> for more
details.

To select _f95_ as your compiler, you will need to set the
`FC` variable to this value. If your shell is _tcsh_ you can
use:

          setenv FC f95

If your shell is _bash_, you can use:

          export FC=f95

WARNING: For beta testing on a 32-bit system, you may not want to
make this change permanent since it is incompatible with
pre-_10.0.0_ versions.

To make this change permanent, you should add the appropriate
command to the appropriate _rc_ file depending on your login
shell: _~prog/.login_ for _tcsh_ or probably _~prog/.profile_
for _bash_.

=== Make the FS

TIP: If you are using an old distribution that is not compatible with
the latest update of the server, you can still use the FS without the
server by removing it from the _make_ process. If your first attempt
to build the FS fails because of the server (most likely in
_third_party/_), please follow the steps in the description of
<<noserver, not building the display server>>.  Please email Ed about
needing to do this or if you still can't build the FS.

          cd /usr2/fs
          make >& /dev/null

and then

          make -s

to confirm that everything compiled correctly (no news is good
news).

=== Update station programs

This step is for modifying your station programs in _/usr2/st_.  There
are three possible issues:

. <<Conversion of FORTRAN code>>
. <<Case sensitive strings in antenna= commands>>
. <<Update local lo command>>

They are discussed next.

==== Conversion of FORTRAN code

If you don't have any FORTRAN station code, you can skip this sub-step.
If you do have some, please email Ed so he is
aware.

Basically you have two options (also see step <<Set FORTRAN compiler>>):

. Change to using _f95_ for both the FS and your station
FORTRAN programs.   It is recommended that
you follow this approach for 32-bit systems and it is
necessary when moving to a 64-bit system.
+

You will need to adapt your __Makefile__s
to use the same compiler options as the FS, which can be
found in _/usr2/fs/include.mk_.
As a first cut, it may work to add the following two lines
to your __Makefile__s for FORTRAN programs:

    FFLAGS  += -ff2c -I../../fs/include -fno-range-check -finit-local-zero -fno-automatic -fbackslash
    FLIBS   += -lgfortran -lm

. Continue to use _fort77_ for both the
FS and your station programs. You should follow this approach _only_ if
you are on a 32-bit system and it is too difficult to convert to
_f95_.

==== Case sensitive strings in antenna= commands

In FS9 versions, the strings used in `antenna=...` commands were always
converted to uppercase before being sent to _antcn_.  An part of the FS
input being case sensitive that no longer happens.  If your
antenna, or your side of the antenna interface, requires that the
strings passed by the `antenna=...` command are uppercase, you have
two options:

. Convert your code. For simple backward compatibility,
change you _antcn_ program to always convert the
`antenna=...` strings to upper case. Alternatively, make
your code case insensitive.

. Convert the strings in your `antenna=...` commands
wherever they occur: SNAP procedures, SNAP schedules,
external programs, or scripts, to upper case. Field system
input is now case sensitive.

The former choice is probably easier, but in some cases the second is
probably better (it keeps with the spirit of case sensitivity). If you
have questions about which to use and how to do it, please email Ed.

==== Update local lo command

If you have a local (station) `lo` command, you will need to update it
(or replace it, see the next paragraph) to get full support for rack
types that were not in your previous FS9 version and to implement the
new capability described in <<logrxg,logging .rxg files>> below.

You should consider switching to use the newly provided `lo` command
<<lohooks,hooks>> described below. This approach may not be suitable
for all stations, but it may will work well for your station. If so,
it should reduce, and in most cases eliminate, the need to update your
local software when the FS `lo` command changes in the future.

=== Make local software

If _/usr2/st/Makefile_ is set-up in the standard way, you can do this with:

       cd /usr2/st
       make rmdoto rmexe all

NOTE: At this point, you are only trying to verify the code will _make_
successfully.  You may still need to debug it in the step <<Test the FS>>
below.

=== Reboot

IMPORTANT: Reboot the computer.  This is necessary to allocate FS, and
possibly station, shared memory for the new version. It will also make
sure you are using the latest version of the display server.

=== Login as oper

The remaining steps assume you are logged in as _oper_.

=== Update control files

This step is for updates to the local control files. There are six
sub-steps:

. <<Update stcmd.ctl>>
. <<Copy control files>>
. <<Update equip.ctl>>
. <<Review control files>>
. <<Update rdbemsg.ctl>>
. <<Update skedf.ctl>>

Differences for updating from different previous versions are
noted.  Please read all cases in each sub-step carefully to make
sure you find all the cases for your old version; sometimes an old
version is included in more than one case in a given sub-step.

==== Update stcmd.ctl

. Old version 9.13.2:

+

The non-comments lines need another digit added to the
subroutine number. This sub-step is only needed for updates from
_9.13.2_. You can fix your file with the commands:

  cd /usr2/control
  /usr2/fs/misc/cmdctlfix6 stcmd.ctl

+

You may also want to expand the (typically) second comment
line to correspond to the new format by adding a `U` after
character 18 to read as follows:

    *COMMAND     SEG SUBPA BO

==== Copy control files

You will need to execute the following commands to copy the new files
that are needed (cut-and-paste is your friend). There are three cases
depending on what your old version was:

. Old versions _9.12.10_ and _9.12.11_:

               cd /usr2/control
               cp /usr2/fs/st.default/control/clpgm.ctl .
               cp /usr2/fs/st.default/control/rdbemsg.ctl .

. Old versions _9.12.12_ and _9.12.13_:

               cd /usr2/control
               cp /usr2/fs/st.default/control/rdbemsg.ctl .

. Old version _9.13.2_:

               cd /usr2/control
               cp /usr2/fs/st.default/control/dbba2.ctl .
               cp /usr2/fs/st.default/control/mk6c?.ctl .
               cp /usr2/fs/st.default/control/monit6.ctl .
               cp /usr2/fs/st.default/control/rdbc?.ctl .
               cp /usr2/fs/st.default/control/rdbe.ctl .
               cp /usr2/fs/st.default/control/rdbemsg.ctl .

==== Update equip.ctl

It is necessary to add lines for the
FiLa10G input select and the DBBC3 configuration.  There
are three cases, please check which applies for you.  In any
event, you should compare your _equip.ctl_ to the example as
described when you get to sub-step <<Review control files>> below, to make sure there are
no duplicated lines or other problems caused by the commands
in this current sub-step, i.e., <<Update equip.ctl>>.

. If your old version was _9.12.10_ or _9.12.11_, you will need
to add the final four lines of the example _equip.ctl_
file to yours:

  cd /usr2/control
  tail -n 4 /usr2/fs/st.default/control/equip.ctl >>equip.ctl

. If your old version was _9.12.12_ or _9.12.13_, you will need
to insert two lines before the final two lines.  This is
covered in sub-step <<Review control files>> below.

. If your old version was _9.13.2_, you will need to add the
final two lines of the example _equip.ctl_ file to yours:

  cd /usr2/control
  tail -n 2 /usr2/fs/st.default/control/equip.ctl >>equip.ctl

==== Review control files

You should compare your versions of the following files:

* _clpgm.ctl_
* _equip.ctl_
* _stpgm.ctl_

to the example files, e.g., using:

          cd /usr2/control
          diff clpgm.ctl /usr2/fs/st.default/control/ | less

and consider whether and what changes you should make to your
copies.

The following sub-sections give the details of the changes in these
example files. You will need to make the corresponding changes to your
copies of the files.

===== Review clpgm.ctl

You may be able to just replace your copy with the new one.

. Old versions _9.12.10_ and _9.12.11_:
+
This file was not present so the new default version (copied by
commands in sub-step <<Copy control files>> above) should not
require modification.

. Old versions _9.12.12_, _9.12.13_, and _9.13.2_:

.. The `-title ...`  parameter for each
window was removed so that it is uniquely
supplied by the _.Xresources_ file.

.. The value of the `-name`
parameter for _erchk_ was changed from `ERRORS`
to `erchk`.

.. The useful display window _scnch_ was added.

.. The _xterm_
program was added.

.. For RDBE systems, the useful RDBE display windows: _monit6_,
and _monX_ (_X_=[_a_-_d_]) were added. The _monan_ program was added
to the default since it is used at several sites. If these are not
relevant for your site, you may prefer to not add them.

===== Review equip.ctl

CAUTION: This sub-step has the most complicated changes.
Please read all clauses to make sure you see
all that apply to your old version.

There are two sub-sections. The first
sub-section covers changes to non-comment lines; the
second, comments. The former are required. The
later are in some sense optional, especially
when they refer to equipment you don't (or
never will) have. However, changing them now
may help avoid confusion at a later date.

======  Non-comment lines

.  Old versions _9.12.10_-_9.12.13_:

.. The line for DBBC PFB version was changed to have a
minimum version number of `v15_1`. The line is
shown here with the typical preceding comment:

    *DBBC PFB version
    v15_1    v15_1 or later

.. The line that defines the DBBC2 CoMo configuration was changed. Please
see item (12) in the installation instructions in _/usr2/fs/misc/fs91119up.txt_ for
full details on handling this. However, the following commands will
probably make the needed change if you don't have a DBBC2 or if your
DBBC2 configuration is four CoMos with one Core per CoMo:

  cd /usr2/control
  /usr2/fs/misc/dbbc_equip '1 1 1 1' equip.ctl
+
If the script prints a warning about the number
of IF power conversions being incorrect, the
issue must be resolved before continuing,
either by adjusting the number of power
conversions, adjusting the CoMo configuration,
or both.

. Old versions _9.12.10_ and _9.12.11_:
+
A FiLa10G input select line was added, but
sub-step <<Update equip.ctl>> above should have handled that.

. Old versions _9.12.12_ and _9.12.13_:
+
A _stanza_ (actually one comment and one FiLa10G
input select line) was inserted before the
final stanza (typically one comment and one
DBBC3 configuration line). An example of the
lines inserted can be found near the end of the
default example _/usr2/fs/st.default/control/equip.ctl_ file. They are
listed here as well (one comment and one
FiLa10G input select line):

    *FiLa10G input select, one of: vsi1, vsi2, vsi1-2, vsi1-2-3-4, gps, tvg
    vsi1-2

. Old versions _9.12.10_, _9.12.11_, and _9.13.2_:
+
A new line for the DBBC3 configuration was added at the end, but sub-step
<<Update equip.ctl>>  above should have handled that.

====== Comment lines

. All old versions:
+
Compared to all old versions, comment lines
were added or modified for new equipment type
options.
+
. Old versions _9.12.10_-_9.12.13_:
+
The trailing comment on the line for the met. device was
reworded.

. Old versions _9.12.10_-_9.12.13_:
+
The comment lines describing the available clock
rates was completely rewritten and greatly
expanded, and an additional clock rate (`128`)
was appended to the end of the comment on
the clock rate line itself.

===== Review stpgm.ctl

. All old versions:

+

WARNING: If you are _not_ planning to use the FS display
server, we recommend you comment out the lines
for _erchk_, _monit2_, and _scnch_ and not add any other _monitX_ programs. If they are
used in _stpgm.ctl_ without the display server and they are
accidentally closed, the FS will be killed.
This applies as well if you built the FS without
the display server as described in <<noserver, not building the
display server>>.

.. The line for _erchk_ is now uncommented and differs from the
previous commented version with the addition of the `-name erchk`
parameter and the removal of the `-title ...` and `-geom ...` parameters,
so that the latter two are uniquely supplied by the _.Xresources_
file.

.. New lines were
added for _monit2_, and _scnch_ for when the
display server is in use.
+
If you are using the display server you may
want to add other _monitX_ programs. If so, you
may also want to add resources for them (if
 they aren't already there) in the
_~/.Xresources_ files for _oper_ and _prog_.

==== Update rdbemsg.ctl

. Versions 9.12.10-9.12.13:

+

If you have RDBEs for your back-end and will use the _rdbemsg_
utility to send operations messages, you will need to
customize your _/usr2/control/rdbemsg.ctl_ file.

.. You will need to update the `station` two letter code (lower case)
to your station's value.

.. You will need to update  the `name` station name to your station's
value. The station name is also defined in the
_/usr2/control/location.ctl_ file.

.. If you don't have a _HubPC_ (_mci_) node for front end monitor
and control, you should comment out that line.

.. You should set the addresses for the RBDE-A (`R-A`) through RDBE-D
(`R-D`). The example file uses aliases, _rdbea_ through _rdbed_, that
you can define in _/etc/hosts_.  Likewise, if you have an _mci_ node,
you should set its alias, _hubpc_, in _/etc/hosts_. (It is usually
necessary to have _root_ access to modify _/etc/hosts_.)  Alternatively
of course, you can use any scheme you prefer for defining these
addresses in _rdbemsg.ctl_.

.. The default email address `to` is for the `ivs-vgos-ops` mail
list. You can of course change that to whatever you like. You
can also temporarily override the address in the _rdbemsg_
utility itself.

==== Update skedf.ctl

. All versions:

+

.. This sub-step applies only if you use the _fesh_ script to fetch
schedules, and optionally run _drudg_ for them. There are two possible
changes:

... If not already set, specify a directory for _.skd_ files in the
`$schedules` block of the _/usr2/fs/skedf.ctl_ control file. You can
use any value you want, but to be backward compatible with the
previous behavior of _fesh_ it must be _/usr2/sched_.

... Likewise, directories should be specified in the `$snap` and `$proc`
blocks of _/usr2/contol/skedf.ctl_. You can use any
values you want, but typically they should be set to _/usr2/sched_ and
_/usr2/proc_, respectively, to agree with the FS.

.. Due to an <<skedf.ctl,error>> in the example
_/usr2/fs/st.defaut/control/skedf.ctl_ file in previous releaeses,
most stations probably incorrectly show the `lo_config` keyword as
`if_config` in their local _/usr2/control/skedf.ctl_ version. Please
check your local copy and update any occurrences, even in comments,
of `if_config` to `lo_config`.

=== Update .prc files

This step is for updates to your _.prc_ SNAP procedure libraries.  The
are two sub-steps.  Only the  change in the first is required:
converting from using the old FS _go_ program to _rte_go_. The change
in the second is optional and only relevant if upgrading from
_9.13.2_: removing `if=cont_cal,,` from the `fivpt` and `onoff`
procedures for `calon` and `caloff` procedures.

==== Convert from go to rte_go

Convert use of the old FS _go_ program to use _rte_go_. This
is required because the compiler for the _go_ language
conflicts with the old program name _go_. This change is necessary even if
you do not have the _go_ language compiler installed.

To make this change for all your _.prc_ procedure libraries,
execute:

           cd /usr2/proc
           /usr2/fs/misc/go_fix *.prc

Files that are changed will have a pre-change back-up copy
with the extension _.bak_. You can use the _.bak_ file to
recover in case of a problem.

==== Remove extra if commands

This sub-step is optional and only relevant if you are upgrading
from _9.13.2_. You can remove the `if=cont_cal,,` as a prefix from before the
`calon` and `caloff` commands in you `calonnf`, `calonfp`,
`caloffnf`, and `calofffp` procedures, probably located in your
_point_ procedure library. This is just a clean-up and not
making this change will have no impact.

=== Miscellaneous FS related changes

There are three changes:

. <<Set FS_DISPLAY_SERVER>> environment variable for _oper_ and
_prog_. This is only needed if you were not running the FS display
server before.

. <<Update .Xresources>> file for the _oper_ and _prog_ accounts.

. <<Set environment variables for fesh>>. These are optional changes
to consider if you use _fesh_.

==== Set FS_DISPLAY_SERVER

Set the `FS_DISPLAY_SERVER` environment variable for _oper_ and
_prog_.  This will make using the display server the default for your
system.  We strongly recommend this, but if it is not suitable for you
for some reason you can skip this. If you are already using the
display server, you should also skip this. You should not implement
this step (or instead remove setting the variable if already being
set), if you built the FS without the display server as described in
<<noserver, not building the display server>>.

WARNING: If you don't use the
display server, you will probably need to update the _stpgm.ctl_ file for that
case as described in the *WARNING* in sub-step <<Review stpgm.ctl>> above.

. As _oper_:

.. Set the variable
+
* If using the _bash_ shell then in the _~oper/.profile_
file, you can uncomment or insert

          export FS_DISPLAY_SERVER=on

+
* If using the _tcsh_ shell then in the _~oper/.login_
file, you can uncomment or insert

          setenv  FS_DISPLAY_SERVER on

.. You should logout and login again after making this change.

. You should  make the corresponding change for _prog_ while logged
in as _prog_.

==== Update .Xresources

The main change was to add values for the _erchk_,
_scnch_, and _helpsh_  windows.  There were some minor changes
for other windows, but what to use for the changed values may
depend on the resolution of your display.  The example values
worked well for an FSL10 installation on a system with a
non-GPU CPU.

[TIP]
====

A strategy for setting the `geometry` resource for a window is:

. Adjust the position (and maybe the size) of the window to what you
want.

. Run the _xwininfo_ program

. Position the cursor on the window and click.

. Copy the string output for the `-geometry` parameter, e.g,
`80x24+0+0`.

. Paste the string as the value for `geometry` resource for that
window in the _~/.Xresources_ file.

You will need to logout and login again (or reload
the X resources a different way) for the change to become
effective.
====


As _oper_, you can find the differences between your file and
the example file with:

  cd
  diff .Xresources /usr2/fs/st.default/oper

Please make any changes to your file that you find appropriate, but at
a minimum you should probably add the lines for _monit6_, _erchk_,
_scnch_, and _helpsh_ if not already present.  You will need to logout
and login again (or reload the X-resources a different way) for the
changes to become effective.

[CAUTION]
====

The example _.Xresource_ file for _9.13.2_ did not have any of these
items, but you may have already included some in your local file.
Similarly, the example files for the _9.12.x_ versions only had
_monit6_ included.  However, you may have already included some of the
others in your local file.

You should be careful to _not_ specify values for a window more than
once.  So don't use the suggested commands below if they cover windows
that already values in your _.Xresources_ file. Instead you will need
to hand edit to make the appropriate changes.

Every station will probably need the lines for _helpsh_.

====

* All the new lines are at the end of the file, so if you need to add
lines for _monit6_, _erchk_, _scnch_, and _helpsh_, you can use:

  cd
  tail -n 24 /usr2/fs/st.default/st.default/oper/.Xresources >>.Xresources

* To add lines for just _erchk_, _scnch_, and _helpsh_, you can
use:

  cd
  tail -n 20 /usr2/fs/st.default/st.default/oper/.Xresources >>.Xresources

* To add lines for just _helpsh_, you can use:

  cd
  tail -n 6 /usr2/fs/st.default/st.default/oper/.Xresources >>.Xresources

You can update _prog_'s _.Xresources_ file similarly, but you will
need to be logged in as _prog_.

==== Set environment variables for fesh

These are optional changes that should be considered if you use _fesh_.

. The _fesh_ script uses _cddis_ as the default data center. You can
specify a different data center by setting the `FESH_DATA_CENTER`
environment variable. Available data centers for geodesy are _bkg_,
_cddis_, and _opar_; for astronomy, _vlbeer_.
+

TIP: For FSL8 and other old Linux distributions, access to _cddis_ may
not be possible, due to out-of-date certificates (for both FTP-SSL or
HTTPS). If you are in that situation, _bkg_ or _opar_ may be suitable
alternatives.

. The _fesh_ script uses FTP-SSL as the default access method for the
_cddis_ data center. For this case, you can avoid having to answer a
prompt for your email address each time you run _fesh_  by setting
your email address in the `FESH_EMAIL` environment variable.
+

TIP: The FTP-SSL method may not work from behind some firewalls.  If
it doesn't work for you, either use a different data center (see
above) or use HTTPS for _cddis_ (see below).

. You can change the access method for _cddis_ to HTTPS, by setting
the `FESH_CDDIS_METHOD` environment variable to `https`.
+

NOTE: Using HTTPS requires an _EarthData_ login and setting it in
your _.netrc_ file.  If you don’t have an _EarthData_ login, you
should be able to get one by selecting `REGISTER` at:
https://urs.earthdata.nasa.gov/.

Please see `*fesh -h*` for more information on using these features.
A more complete description is available in <<fesh,changes to fesh>>
below.

=== Miscellaneous FSLx changes

None are required for this update.

=== Test the FS


Generally speaking, a fairly thorough test is to run a test
experiment. Start with using _drudg_ to rotate a schedule,
__drudg__ing it to make _.snp_ and _.prc_ files, making listings,
and any other pre-experiment preparation and tests you normally
do, then execute part of schedule, and perform any normal
post-experiment plotting and clean-up that you do.  The idea here
is to verify that everything works as you expect for normal
operations.

Additionally if you use _fesh_ to download schedules, you should test
that using the latest version. If you also use it to _drudg_
schedules, you should test that as well. A quick check is to just make
sure the files have reasonable contents. If you want to make a
detailed check, a strategy for that might be:

. Move an old schedule file and its the _drudg_ output, e.g.,
_r4948.skd_, _r4948xx.lst_, _r4948xx.snp_, and _r4948xx.prc_, (where
_xx_ is your station's two letter code) to a different directory, e.g.,
_/tmp_.

. Rerun _fesh_ for that schedule.

. Compare the old and new versions with _diff_. They only differences
should be:

.. Comments in the _.snp_ and _.prc_ files.

.. The timestamps in the `define` lines in the _.prc_ file. However,
it is possible the procedures will be in a different order if you
edited the old version.

.. Insignificant rounding differences in the _.lst_ file.

. Copy your original files back from where you placed them, if you
want to preserve them.

=== Consider when to update your back-ups

WARNING: This step may not be appropriate if you are beta testing
since the beta test versions are not intended for
operations.

It would be prudent to wait until you have successfully run an
experiment or two and preferably received word that the
experiment(s) produced good data.  The chances of needing to use
your back-up should be small.  If something does happen, you can
copy the back-up to the (now assumed bad) updated disk.  You can
then either use the restored disk or apply the FS update again.
The FSL10 test procedure has more options for recovery.  Managing
this is a lot easier and safer if you have a third disk.

== Changes from FS9

[[details]] There are separate sub-sections with the changes
in the FS and _drudg_.  Each sub-section is divided into three parts:

. Changes that are in common since FS9
+
These parts cover changes compared
to both FS9 branches. These are changes that have been introduced in version _10.0.0_.

. Changes relative to the main branch
+

These parts cover changes that are only relative to the main branch,
specifically version _9.13.2_.  These are primarily features that were
in the VGOS branch but not in the main branch.

. Changes relative to the VGOS branch
+
These parts cover changes that are only relative to the VGOS branch,
specifically version _9.12.13_.  These are primarily features that
were in the main branch but not in the VGOS branch.


Clickable links such as
https://github.com/nvi-inc/fs/issues/36[#36] connect to specific issues
reported at https://github.com/nvi-inc/fs/issues.

A complete history of changes can be found using the `git log` command
from within the FS _git_ archive directory, usually _/usr2/fs-git_.

The file _/usr2/fs/misc/changes.txt_ contains the old history of
changes in FS9. The file _/usr2/fs/misc/VENIX_changes.txt_ contains
the old history of changes in FS8. However these two files have been
merged into the history given by `git log`.

The history of _drudg_ is also described in more detail in
_/usr2/fs/drudg/change_log.txt_.

=== FS changes

This sub-section is divided into three parts. Please see
<<Changes from FS9>> above for an explanation of the parts.

==== Changes that are in common since FS9

. [[unified]] One unified version for all FS users.

+

Both non-VGOS and VGOS operations are supported by the new version.
Previous installations of the main (non-VGOS) branch will need to have
some new local control files added.

+

The most significant change for users is that previous main branch
users will find that input is case sensitive, as it was already in the
VGOS branch.


. [[bit3264]] Support for use on both 32- and 64-bit systems.

+

The new version should run on 32-bit systems that currently support
the FS (we support as far back as FSL8, we have not yet been able to
test with FSL7 or other even older systems), as well as on 64-bit
systems. The <<../../misc/64-bit_conversion.adoc#,Converting to a
64-bit System>> document contains instructions for transitioning to a
64-bit system.

+

The key change to the source code to make this compatibility possible
is removing use of ``long``s as 32-bit ``int``s in C, particularly in
fixed length data structures. Note that  some system calls do require
``long``s. A tool, _unlongify_ was developed by Dave Horsley to help
convert the FS code.  It is available to help convert station code.
Its use is described in the
<<../../misc/64-bit_conversion.adoc#_conversion_of_c_code,Conversion
of C code>> sub-step of the
<<../../misc/64-bit_conversion.adoc#,Converting to a 64-bit System>>
document.

+

A second important issue is that pointers and `time_t` variables in C
are 64-bits on 64-bit systems and 32-bits on 32-bit systems. Care must
be taken if these are passed back to FORTRAN callers or used in fixed
length data structures.

. [[usegit]] Version control with _git_.

+

The FS source is now managed using _git_ and _github_ is used for
distribution. The source code is now under the GPL3 license.

+

The details of the model used for FS releases under _git_ are
described in the <<../misc/release_model.adoc#,Release Model>> document.

+

This change increases the importance of not modifying the
_/usr2/fs_ directory tree since such changes will make it more
difficult to simply `pull` updates to install bug fixes and new
features.

. [[server]] The FS display server is now recommended for
normal use. (This was changed as of the _beta2_ release.)

. [[adoc]] Reorganize update notes as HTML viewable on the web
(closing https://github.com/nvi-inc/fs/issues/71[#71]).
+

Hopefully, this change will make the update notes easier to read and
navigate.  Among other improvements, there are clickable links to
other sections within a document, as well as to sections in other
related documents, and a clickable table of contents..

.. Reorganized update notes as _.adoc_ files in the _docs/_
sub-directory.

.. All of the _.adoc_ files are viewable as HTML, and are hierarchically
indexed, at https://nvi-inc.github.io/fs/.

.. The first update notes available in HTML are for
<<beta2.adoc#,10.0.0-beta2>>.

..  <<../../misc/font_conventions.adoc#,Font Conventions>> similar to
the traditional printed FS manuals are used.

.. Add <<../misc/release_model.adoc#,Release Model>> document  describing
steps in making a release.

.. Add <<../../misc/env_vars.adoc#,FS Environment Variables>>
document. This document describes user settable environment variables
for both _make_ time and runtime.

.. Improve structure and correct some errors from original _.txt_ version.

.. Make many typo/wording fixes.

. [[fesh]] Update and expand _fesh_.

.. A typo in the error message for when the schedule is already
downloaded was fixed (closing
https://github.com/nvi-inc/fs/issues/34[#34]). Thanks to Morgan
Goodrich (KPGO) for reporting this.

.. The internal version number was replaced with the FS version.

.. _fesh_ now supports _bkg_, _cddis_, _opar_, and _vlbeer_ data
centers (closing https://github.com/nvi-inc/fs/issues/37[#37]).
+

The data center can be selected with the `FESH_DATA_CENTER`
environment variable or the `-D` command line option. The default data
center is _cddis_. For _vlbeer_ only _.vex_ files are supported; for
the others, only _.skd_.  Running _drudg_ automatically is not
supported for _vlbeer_.
+

TIP: For FSL8 and other old Linux distributions, access to _cddis_ may
not be possible, due to out-of-date certificates (for both FTP-SSL or
HTTPS). If you are in that situation, _bkg_ or _opar_ may be suitable
alternatives.

.. _fesh_ now supports encrypted access to _cddis_ using FTP-SSL and
HTTPS (closing https://github.com/nvi-inc/fs/issues/36[#36]).
+

This allows use of _cddis_ after non-SSL FTP access was disabled there
at the end of October 2020. FTP-SSL is the default method.
+

For FTP-SSL, it is recommended that the `FESH_EMAIL` environment
variable be set to avoid having to provide an email address as the
_anonymous_ FTP-SSL password for each invocation.

+

TIP: The FTP-SSL method may not work from behind some firewalls.
If it doesn't work for you, you can either use HTTPS for _cddis_  or
use a different data center (see below).

+

CAUTION: The use of FTP-SSL by _cddis_ may be deprecated in the future.

+

Using HTTPS can be activated for _cddis_ by setting the
`FESH_CDDIS_METHOD` environment variable to `https`.

+

NOTE: Using HTTPS for _cddis_ requires an _EarthData_ login and
setting it in your _.netrc_ file.  If you don’t have an _EarthData_
login, you should be able to get one by selecting `REGISTER` at:
https://urs.earthdata.nasa.gov/.

.. _fesh_ now respects the _/usr2/control/skedf.ctl_ control file
(closing https://github.com/nvi-inc/fs/issues/65[#65]).
+

Previously _fesh_ assumed that the directory for _.skd_ files was
_/usr2/sched/_ regardless of what was in the `$schedules` block of
_/usr2/control/skedf.ctl_. This only worked if the directory specified
was _/usr2/sched_ or was the working directory (i.e., not specified or
`.`). This prevented use with different directories, such as
_/usr2/exper_, for _.skd_ files.  Thanks to Jon Quick (HartRAO) for
reporting this.

.. _fesh_ now provides support for _drudg_ optional prompts for
geodesy schedules (partially closing
https://github.com/nvi-inc/fs/issues/38[#38]).
+

It is assumed that for geodesy the answers to these questions for a
station do not vary. This feature is intended to allow stations that
observe both astronomy and geodesy schedules to use _fesh_ to _drudg_
geodesy schedules.  The environment variables `FESH_GEO_TPICD`,
`FESH_GEO_CONT_CAL`, `FESH_GEO_CONT_CAL_POLARITY`, and
`FESH_GEO_VSI_ALIGN` or the command line options `-tcpa` can be used
to supply answers to the corresponding _drudg_ prompts.

+

IMPORTANT: _Let the user beware._ This feature must be used with
extreme care.  The answers that are specified must correspond exactly
to the questions that _drudg_ will ask. If they don't correspond
correctly, _drudg_ may produce subtly incorrect output with no obvious
indication of a problem. The _fesh_ script does what consistency
checking it can, e.g., if `FESH_CONT_CAL` is specified as `off`, no
answer can be supplied for `FESH_CONT_CAL_POLARITY` since that
question will not be asked. It is important to verify that correct
output is being produced.

+

IMPORTANT: The feature will not work for schedules that have more than
mode. It is extremely rare for geodesy schedules to have more than one
mode, but it is possible.

.. Use of an environment variable, `LIST_DIR`, was added to specify the
directory for _drudg_ listings. If not set, the `.skd` file directory is used.

.. Use of an environment variable, `NETRC_DIR`, was added to specify a
directory other than the user's home directory (__~__) for the
`.netrc` file used with HTTPS access for _cddis_. The same variable is
used by the _plog_ script for the same purpose.

+

NOTE: Normally, the _.netrc_  file would be in the user's home directory.
However, some systems have security policies that forbid that. This
variable provides a way to have the _.netrc_ file in a different
directory, perhaps _/usr2/control_.

+

.. The user name for the unencrypted FTP access to _bkg_, _opar_, and
_vlbeer_, is explicitly set to _ftp_ to avoid potential conflicts with
other accounts specified in _~/.netrc_ (this is not redirected by
`NETRC_DIR`).

.. Several new command line options were added:

... `-y` to override the year directory accessed for a geodesy data
center (the default is the current year).
+

This is particularly useful for getting schedules for the next year.

... `-t` to trigger also downloading the _.txt_ file associated with a
geodesy schedule.`

... `-m` to override the month directory accessed for _vlbeer_ (the
default is the current month).
+

This is particularly useful for getting schedules for a future month.

... `-H` to disable the default use of the _.latest_ sub-directory of
the month directory for _vlbeer_.

... `-D` to override the data center if the `FESH_DATA_CENTER`
environment variable is set, or change the data center from the
default if it is not set.

... `-s` to override the station code if the `STATION` environment
variable is set, or set it if it is not set.

+

Please see `*fesh -h*` for more information on using these features.

. [[logrxg]] Add _.rxg_ file logging to `lo` command.

.. Summary information logging.
+

When an LO is configured (or monitored) with the `lo` command, a
summary of information from the matching _.rxg_ file is displayed and
logged.  Details of the format are available with `help=lo`.  This is
intended to give the operator feedback that the correct version of the
_.rxg_ file is in use. The format of these lines may be adjusted in
future releases based on feedback from users about what is most
useful.  Thanks to Alastair Gunn (Jodrell Bank) for suggesting this.

.. Full logging of _.rxg_ file non-comment lines.
+

When an LO is configured with the `lo` command, the contents of the
corresponding _.rxg_ file are logged, but not displayed. This only
occurs the first time this _.rxg_ file matched an LO being configured
since the most recent opening of the current log. After the time-tag,
each logged line starts with `:rxg_file,` followed by the name of the
_.rxg_ file, and then the values from a single non-comment line in the
file. The lines are logged in the order from the _.rxg_ file. This is
intended to provide historical information about the values being used
in FS calculations.

. [[fsserver]] Add _fsserver_ improvements and log support.
+

These changes introduce new functionality to _fsserver_, as well as
simplify some use cases.

.. The first major change is that the server now only needs to use one
socket when using _websockets_ -- addresses that start with `ws://`
(closing https://github.com/nvi-inc/fs/issues/29[#29]).
+

The new default base URL for all _fsserver_ streams and control
channels is now:

    ws://127.0.0.1:7083
+
(70 83 are decimal ASCII encoding of `F` and `S`.)
+
This can be changed by editing `FS_SERVER_URL_BASE` in
_include/params.h_; however, we will likely introduce command-line
flag and/or environment variable to set this in the future.
+
This should be safe to expose on the network (rather than just
the loop-back), but users may wish to use an HTTP(S) as a proxy to
provide some authentication/authorisation.
+
This was enabled by factoring out functionality _spub_ into a
reusable "`buffered stream`" library, which has been incorporated
into _fsserver_. All the behaviour of streams are now managed
within the _fsserver_ process rather than an external _spub_
instance.

.. The second major change of this patch is the addition of the FS log
to the streams available from the server (closing
https://github.com/nvi-inc/fs/issues/25[#25]).
+

Previously only the
"`display`" was available, which has a reduced time-stamp format and
filters some output. The log stream is available at

    FS_SERVER_URL_BASE/log
+
that is, by default

    ws://127.0.0.1:7083/log

.. A third change is that the server now continues running after the
FS is terminated.
+

This allows clients to detect the FS termination and prevents a socket
conflict if the FS is terminated and restarted in quick succession.
The only user visible impact will be a slight delay if the FS is
restarted quickly after termination while the old session is finishing
up. This also means that after an FS upgrade or changing environment
variable values, it's important to either shutdown the server
(`*fsserver stop*`) or reboot the system before re-starting the FS.

.. Fourth, the server can now accept snap commands to be sent to FS,
e.g.:

   fsserver fs snap "terminate"
+
This allows clients to interact with the FS directly through
fsserver rather than needing access to _inject_snap_.
+
No filtering or authorisation is implemented on this command
channel, so it effectively allows complete command execution
privileges in the FS context to anyone with access to the socket.
Note this is also true for _inject_snap_ on a standard system. If
a station wishes to limit local access they can use
iptables/nftables, or use the server in UNIX socket mode and use
file system permissions. Stations that would like to enable remote
access should implement their own authentication/authorisation
that suits their needs, e.g. SSH port forwarding or HTTP proxying.

.. The fifth and final major change is that this patch also upgrades
the included messaging library _nng_ to version _1.3.0_.
+

This brings with it some performance improvements and bug fixes, the
most obvious to FS users caused some _ssub_ instances in "`wait`" mode
to use a high amount of CPU time.  However, some or all of the speed
improvement may have been lost in <<serverbuild,making the server
build work for FSL8 (_Lenny_)>>.

.. Fixed _spub_/_ssub_ occasionally freezing (tentatively closing
https://github.com/nvi-inc/fs/issues/69[#69]).
+

This may have been caused be the byte order being wrong in buffered
stream `cb`. The situation is still being monitored.  Please report
any instance of this problem that occurs. It happens very rarely so it
is challenging to get enough usage to verify that it is not happening
anymore.  If it does happen, restarting the client has been a
successful strategy for recovery.

.. Fixed `clean` function in _Makefile_.

.. Fixed _sspub_ to support more than 2^32^ messages.

. [[gnplt]] Improve _gnplt_.

.. Fix labels in _gnplt_ windows that display the gain curve
coefficients (closing https://github.com/nvi-inc/fs/issues/51[#51]).
+

Previously the labels, when displayed were in reverse order. In one
window, there were no coefficient labels at all. Thanks to Beppe
Maccaferri (Medicina) for reporting this and testing the solution.

.. _gnplt_ now updates the date in updated _.rxg_ files (closing
https://github.com/nvi-inc/fs/issues/72[#72]).
+

The original developer, (Tomas Gille), did very good work developing
this second version of _gnplt_, but ran out of time in his internship
and was unable to include this minor but important feature. Thanks to
Beppe Maccaferri (Medicina) for reporting this.

. [[lohooks]] Add hooks for local LO control to `lo` and `lo_config`
commands.

.. Hook in `lo` command.
+

While the FS has an option for any built-in command to have a local
version, having such a local overriding command can create a
maintenance burden if the FS command is updated.  Some commands very
rarely change, but others change fairly often. The more often they
change, the more maintenance burden there is.  Unfortunately the `lo`
command changes fairly often.
+

To address this issue, a hook has been added to the FS version of the
`lo` command to run _antcn_ in a particular local mode to configure an
LO when it is commanded.  This is triggered with the environment
variable `FS_LO_ANTCN_MODE`.  The details of the interface are
available in the `Comments` section shown with `help=lo`. This may not
be a suitable solution in all situations.  If you have (or need) a
local `lo` command you can continue to use it (or implement one), but
it will need to be updated to get new capabilities such as new racks
and <<logrxg,logging .rxg files>> when they come along.
+

NOTE: This feature does not currently provide a way to read back
information from the device for display.

.. Hook in `lo_config` command.
+

The _drudg_ program provides a means to include the calling of a
`lo_config` command at the end of each IF setup procedure it
generates. This is intended to provide stations that implement
commanding the LO configuration to device(s) with a way to do it in
one step for a mode as to opposed individually with
`lo=...` commands. It can also be used to implement command of the
LO setup for a mode instead of with the `lo` command to reduce (but not
eliminate) the maintenance burden that is  needed if a local `lo`
command is used.  See the example
_/usr2/fs/st.default/control/skedf.ctl_ file for how to trigger
``drudg``'s use of this command (also see the related
<<skedf.ctl,skedf.ctl fix>> in this sub-section.
+

Until now the `lo_config` command has been a station only command,
i.e., it had to be implemented as a local command. With this update,
there is now a built-in command that can used for this functionality,
if it is suitable. If it is not suitable, the local command can still
be used or implemented.
+

By default the built-in `lo_config` command is a no-op. However,
it has a hook that can used to run _antcn_ in a particular local mode
to implement configuring the LOs.  This is triggered with the
environment variable `FS_LO_CONFIG_ANTCN_MODE`. The details of the
interface are available in the `Comments` section shown with
`help=lo_config`.

. [[addrdbemsg]] Add _rdbemsg_ utility.
+

This utility was originally developed by Jason Soohoo (Haystack). It
is an RDBE oriented version of the FS _msg_ utility for sending
operations emails. Initially it ran on a different back-end computer.
It was ported to the FS and expanded to provide pointing data.

. [[clientn]] Make _fsclient_ honor the `-n` flag properly.
+

This eliminates opening "`double`" windows if _fsclient_ is run with
`-n` under an already running _fsclient_ (closing
https://github.com/nvi-inc/fs/issues/48[#48]).

. [[clientnx]] Make _fsclient_ ignore prompt in no-X11 mode.
+

If FS client is in no-X11 mode, it created a _fs.prompt_ when
instructed by the server.  This change removes that behaviour (closing
https://github.com/nvi-inc/fs/issues/49[#49]), though it may cause an
issue if no other clients exist to dismiss the prompt, as discussed in
issue https://github.com/nvi-inc/fs/issues/49[#49]. If this is a
problem for anyone's use case we will need a new feature here.

. [[helpsh]] Move X resources for _helpsh_ to _~/.Xresources_.
+

This allows the geometry and other parameter of the FS `help` display
_xterm_ to be controlled locally.

. [[day248]] Always check for "`day 248`" problem in _setcl_.
+

Previously _setcl_ only checked for this problem (which is due to use
of 32-bit arithmetic in the time handling code), if the time model was
_not_ `computer`. In principle, when the model is `computer` there is
no need to check for this issue.  However, since the time is still
managed with the same 32-bit arithmetic (to keep it the same on both
32- and 64-bit systems) as for the non-`computer` models, it is still
necessary to check.  Not doing so was an oversight. The result was
that there were no warnings of an impending 248 day time problem if
the model was `computer`.  This is now fixed (closing
https://github.com/nvi-inc/fs/issues/56[#56]). Thanks to Richard
Blaauw (WSRT), and subsequently Jon Quick (HartRAO) for reporting
this.

. [[scnch]] Generalize the _scnch_ window to cover Mark 5 recorders. 
+

The _scnch_ window was initially developed for Mark 6 recorders. The
form has now been generalized to cover Mark 5 recorders as well
(closing https://github.com/nvi-inc/fs/issues/61[#61]).

. [[cont_cal]] Add support for DBBC3 to `if=cont_cal,...` (closing
https://github.com/nvi-inc/fs/issues/54[#54]).
+

Thanks to Eskil Varenius (Onsala) for reporting that this was missing.

. [[new_ifdbb]] Add _new_ifdbb_ script for (RDBE) VGOS stations.
+

This script is intended as a tool to allow stations, and schedule
writers, a way to update schedules for changes in the _ifdbb_
procedure used by VGOS stations, particularly those with RDBE
back-ends. For RDBE stations, the attenuation used in the signal
chain, which is set by the schedule, depends on the observing mode
being used and the conditions at the station. The provides a way to
incorporate needed changes into schedules. If the script is run
without other command line arguments, it will output "`help`"
information.

. [[prc]] Add checking for a procedure or schedule file before
attempting to open it.
+

This change is to avoid accidentally closing an active procedure or
schedule file if the new one specified in the `proc=...` or
`schedule=...` commands, respectively, does not exist (or has
incorrect permissions) (closing
https://github.com/nvi-inc/fs/issues/45[#45]).  Previously, if the
files did not exist (or did not have the correct permission), the old
file would be closed.  Thanks to Jon Quick (HartRAO) for pointing out
this inconsistency.
+

CAUTION: This is a non-backward compatible change in how the SNAP
commands behave.  Previously supplying a non-existent procedure or
schedule file name would cause the closure of the corresponding file.
Now to close an open procedure or schedule without opening a new one,
a null parameter must be supplied, i.e., `proc=` or `schedule=`.  As
before, the latter will not close an open schedule procedure library.
+

NOTE: The old behavior was partly a consequence of how the original
file handling worked on HP-RTE systems, but is not sensible for how
the SNAP commands should work.

. [[help]] Improve `help` command.

.. Remove usage of `system()` call to find `help` files (closing
https://github.com/nvi-inc/fs/issues/3[#3], and
https://github.com/nvi-inc/fs/issues/40[#40]).

.. Improve `help` page for _tpicd_.
+

Made it clearer that when in the `no` mode, `data_valid=on` will only
start logging of _tpicd_ data when a schedule is running and
not-blocked.  This behavior was inherited from the VGOS branch where
accidentally leaving _tpicd_ logging RDBE multi-cast data after
closing or halting a schedule creates a lot of extra log entries. This
is probably beneficial for all back-ends.

.. Update `help` pages for _onoff_ and _fivpt_.

... Add section on switching between continuous and non-continuous
cal.

... Remove `if=cont_cal,,` in `calon`/`off`-`nf`/`fp` procedures.

... Add recovery method for misconfigured cal.

.. The `help` file for the `ddbc` command was expanded to also
describe the `dbbc2` and `dbbc3` commands and now includes a
description of the output for multi-line responses for all of these
commands (closing https://github.com/nvi-inc/fs/issues/75[#75]). The
`help` command now works for the `dbbc2` and `dbbc3` commands.

.. The `help` file for the `fila10g` command was expanded to also
support the `fila10g2` command. The `help` command now works for the
`fila10g2` command.

. [[plog]] Improve _plog_.

.. Use of an environment variable `NETRC_DIR` was added to support not
having the _.netrc_ file in the user's home directory.
+

Please see `*plog -h*` for details on how to use this.  The same
variable is used by the _fesh_ script for the same purpose.
+

NOTE: Normally, the _.netrc_  file would be in the user's home
directory.  However, some systems have security policies that forbid
that. This variable provides a way to have the _.netrc_ file in a
different directory, perhaps _/usr2/control_.

.. The internal version number was replaced with the FS version.

. [[popen]] Add _popen_ time-out feature.
+

There is a now a `-t ...` time-out option. If the command being run by
_popen_ has a time-out feature, it is generally better to use that
command's feature. See `help=sy` for more details.

. [[prc2]] Fix the remaining case of attempting to execute a procedure
from a closed library causing a crash.
+

There are very few cases in the code where a procedure library is
closed; one was overlooked in the previous fix of this issue in
9.13.1. This case could happen if the schedule that was opened was
named _station_, which would lead to the automatic closure of an
already open schedule procedure library (there cannot be a _station_
schedule procedure library since _station_ is already the station
procedure library).

. [[year]] Fix year wrap error message in procedure logging.
+

This fixed a benign and spurious error message if a log was kept open
past the end of the year and any procedures that had last been logged
in the previous year were executed again (closing
https://github.com/nvi-inc/fs/issues/23[#23]). Thanks to Eskil
Varenius (Onsala) and Alexander Neidhardt (Wettzell) for reporting
this.

. [[header_lines]]  Add more log header lines.

.. A log header line was added for `uname()` system information.

.. A log header line was added for the compile time value of the `FC`
environment variable.

. [[holog]] Improve _holog/MASK_.

.. The elevation spacing was corrected for the example in step (3)
of _mask-HOWTO.txt_.

.. Axis titles were added to _plot_mask.m_.

. [[monx]] Change the flags for the _monX_ programs in _clpgm.ctl_
from `a` to `d`.
+

Since these external programs do not depend on the FS, they can
continue running (``d``etached) after the client is closed.

. [[saterrors]] Fix ignoring _antcn_ errors in the `satellite` and
`satoff` commands.
+

This bug caused errors from _antcn_ to be ignored for _only_ these
commands. It has been fixed (closing
https://github.com/nvi-inc/fs/issues/82[#82]).
.

. [[cls_chk]] Eliminate `cls_chk` error from `inject_snap -w ...`
command when an error occurs.
+

This was caused by _inject_snap_ not implementing the new linkage that
was added for _fserr_. This is covered in more detail in issue
https://github.com/nvi-inc/fs/issues/50[#50]. To correctly retrieve
the error message would have required making a new interface to
_fserr_ or subsuming it into a library routine that both _ddout_ and
_inject_snap_ could use. It was not possible to do either in the
available time. Instead _inject_snap_ was modified to output the error
without the message, but pointing out that the message can be found in
the log and display (partly closing
https://github.com/nvi-inc/fs/issues/50[#50]). Thanks to Dave Horsley
(Hobart) for reporting this.

. [[fixmess]] Fix some errors in _control/fserr.ctl_.

.. Errors in some double double-quote (`""`) lines and some
incorrectly reused error codes were fixed (closing
https://github.com/nvi-inc/fs/issues/43[#43]).  Thanks to Alexander
Neidhardt (Wettzell) for reporting these.

.. The error messages for a error not being found when attempting to
manipulate its display setting were clarified (closing
https://github.com/nvi-inc/fs/issues/22[#22]).  Thanks to Jon Quick
(HartRAO) for reporting this.

.. Error messages that should refer to the (not yet implemented)
`active_rdbes` and `active_mk6s` commands were corrected to no longer
incorrectly refer to the `rdbe_active` and `mk5_active` commands,
respectively.

.. Obsolete errors for the, no longer used, _sw.ctl_ control file were
removed.

. [[dbbcn]] Improve error logging for _dbbcn_ initialization.
+

The instance of the program is now correctly reported. It can be
_dbbcn_ or _dbbc2_.

. [[skedf.ctl]] Fix example _/usr2/fs/st.default/control/skedf.ctl_.
+

The example _sked.ctl_ file incorrectly identified the `lo_config`
keyword as `if_config`. This has been fixed (closing
https://github.com/nvi-inc/fs/issues/81[#81]). It is recommended that
you check and, if needed update your local copy in
_/usr2/control/skedf.ctl_ appropriately, including the comments.

. [[makefile]] The FS uses a new _Makefile_ scheme.
+

This is accomplished by including the _/usr2/fs/include.mk_ file in
every _Makefile_ except for _drudg_ and its libraries. The scheme is
"`opt-in`" so it is not necessary for every program or station
programs to participate.  An explanation of the new scheme is provided
in _/usr2/fs/misc/fs10_makefile.md_.
+

For programs that are opted-in, the most significant consequence of
this is that a _make_ at the top-level  will re-compile anything that
depends on a library or include file that has changed. Since _drudg_
has not yet opted-in, updates to its library routines or include files
will require remaking all of _drudg_ to be sure of being complete. The
_drudg_ program has its own separate ecosystem within the FS,
consisting of the _skdrincl/_, _skdrlnfch/_, _skdrutil/_, and the
_drudg/_ sub-directories.

. [[noserver]] Add option to not build the display server into the FS.
+

The latest version of the server may not _make_ successfully on some
older Linux distributions such as FSL7. To help users in that
situation, an option was added to disable inclusion of the server by
setting the `FS_DISPLAY_SERVER_NO_MAKE` environment variable before
__make__-ing the FS (partially closing
https://github.com/nvi-inc/fs/issues/76[#76]). Follow the steps below
to remove the server.

.. As _prog_:

+

* If you use _tcsh_, add the following to _~/.login_:

  setenv FS_DISPLAY_SERVER_NO_MAKE 1

+

* If you use _bash_, add the following to _~/.profile_:

  export FS_DISPLAY_SERVER_NO_MAKE=1

+

.. Logout of and then back into the _prog_ account before
__make__-ing the FS.

.. It is also necessary to also make sure that users running the FS do
not have the `FS_DISPLAY_SERVER` environment variable set.

... As  _oper_:

.... Delete or comment out any lines in the _~/.login_
file (if using _tcsh_) or _~/.profile_ (if using _bash_) setting
the variable.

.... Logout and back in before attempting to run the FS.

... Repeat the above steps as _prog_.

. [[symlinks]] No longer set _/usr2/fs_ and _/usr2/st_ to be owned by
_prog_.
+

This was a long standing but benign error in the _misc/fsinstall_
script.

. [[serverbuild]] Modify the display server build so that it will
work for FSL8. (The
change that prevented it from building on FSL8 was introduced in
_beta2_ and fixed in _beta3_.)
+

Thanks to Jon Quick (HartRAO) for special effort on this (re-closing
https://github.com/nvi-inc/fs/issues/76[#76] and closing
https://github.com/nvi-inc/fs/issues/78[#78]) including adding
documentation, _third_party/src/README_nng.make_, to assist with future
upgrades of _nng_.

. [[if]] Restore `if` command. (It had accidentally been overlooked in
the merge of the VGOS and main branches. It was first missing in
_beta1_ and was restored in _beta2_.)
+

Thanks to Beppe Maccaferri (Medicina) for reporting this.

. [[gnpltfsl8]] Make _gnplt_ work on FSL8 (_Lenny_) again. (These
 errors were introduced in _beta1_ and fixed in _beta3_.)
+

Some recent improvements in _gnplt_ made it fail for FSL8. These were
fixed (closing https://github.com/nvi-inc/fs/issues/73[#73]).

. [[onoff]] Fix _onoff_ for the DBBC3 rack. (This error was introduced
in _beta1_ and fixed in _beta2_.) +
+

A code block from _9.12.13_ in _onoff/get_samples.c_ had been omitted
in the merge of the main and VGOS branches, preventing sampling of the
TPI values and causing _onoff_ to crash. This has been fixed
(closing https://github.com/nvi-inc/fs/issues/52[#52]). Thanks to
Eskil Varenius (Onsala) for reporting that this caused a crash.

. [[dbbc3help]] Restore `help` command for DBBC3 commands. (The
selection of DBBC3 specific `help` commands was lost in _beta1_ from
the merge of VGOS and main branches.  It was restored in _beta3_).

. [[stationrdbemsg]] Remove hard coding of the station name in
_rdbemsg_. (This error was introduced in _beta1_ and fixed in _beta3_.)
+

The station name is now set in _rdbemsg.ctl_ control file (closing
https://github.com/nvi-inc/fs/issues/62[#62]). Thanks to Chevo Terraza
(MGO) for reporting this.

. [[equip.ctl]] Update example _equip.ctl_ for DBBC3.

.. The example DBBC3 firmware version is now more sensible (closing
https://github.com/nvi-inc/fs/issues/35[#35]). (This error was
introduced in _beta1_ and fixed in _beta2_.) Thanks to Eskil Varenius
(Onsala) for reporting this.

.. The minimum DBBC3 firmware version required was added in a comment.

. [[bash]] Fixes to _~/.bashrc_ for FSL10.  (This changed from _beta1_
to  _beta2_.)

.. Move unsetting of `TMOUT` environment variable for _oper_ to
_~/.bashrc_ in the default files. This allows disabling the time-out
for all interactive shells.

.. Some settings were rearranged in _~/.bashrc_ to make them only
apply to interactive shells for _oper_, _prog_, and AUID accounts.

+

These changes are only relevant for stations using FSL10.

. [[gpl]] Update GPL in files. (The GPL was left out of some files and
incorrectly include in some others in _beta1_. These errors were
corrected in _beta2_ and _beta3_.)
+

The GPL header was added to the _holog/MASK/\*.m_, _misc/mk6in/*_, and
the _include/*.i_ files. It was removed from the
_fserver/tests/convey.*_ files.

. [[updatenotes]] Improve update notes. (These changes were
made after _beta1_.)

.. The `-q` option was added to the `pull` to suppress the detached
HEAD warning.

.. A sentence was added to the description of the change to using
_git_ that it now even more important to not change the contents
of the _/usr2/fs_ source tree.  Changing the source tree will make
it harder to install bug fixes and updates.

.. The paths to the example control files now include the needed
intermediate directory _fs/_.

.. The sub-steps for updating the control files were corrected
to properly
depend or not depend on the old version being _9.12.12_.

.. A sub-step was added to make using the FS display server the default.

.. A sub-step was added for updating the _~/.Xresources_ file for _oper_
and _prog_.

.. A sub-step to update where the `TMOUT` environment variable is unset
for stations using FSL10 was added.

.. A recommendation was added to sign-up for the _go_ language
announcements to be informed of security updates if you are
installing the latest version of _go_ language.

.. Modify steps for updating to a specific commit after _beta2_ to
use the latest commit instead. As well as being
simpler, this is part of a new approach to try to keep the update
notes current with the latest commit. It is important
to be aware that the latest commit is not a version
intended for operations. We make every effort to make sure it is
bug free, but problems may occur. Since it represents the
"`bleeding edge`" of development, features may not be as stable nor
use as reliable as released (tagged) versions.

.. Add the inclusion of the new _rdbemsg_ utility as a change. It was
not mentioned for _beta1_ or _beta2_.

.. Add _rdbemsg.ctl_ customization. It was missing in _beta1_.

==== Changes relative to the main branch

#TODO: Complete this sub-section.#

. [[case]] Input is now case sensitive.
+

As was the case for the VGOS branch, input from the operator,
schedules, and procedures is now case sensitive. This change should
present no difficulties if all normal input is in lower case.  All
SNAP commands and most parameters are lower case.
+

The change was made because in some cases it necessary to send upper
or mixed case input to devices and other computers from SNAP commands.
For MAT and GPIB communication, all communications sent to the devices
is still mapped to upper case.
+

The biggest consequence of this change is perhaps that strings sent in
`antenna=...` commands to the antenna are not by default mapped to
upper case. If this an issue for your antenna, it may require
changes to your _antcn_ program. This is covered in the
<<Case sensitive strings in antenna= commands>> sub-step of the
<<Update station programs>> step above.

. [[tpicdno]] `tpicd=no` now requires a running (not halted) schedule
to log data.
+

This change was introduced from VGOS branch, where it was needed to
avoid logging very large amounts of data for RDBE systems if the
schedule ends or is halted while _tpicd_ is recording data i.e., when
`data_valid` is `on`. It is probably beneficial for all back-ends, so
has been made a general feature. Data can still be logged when a
schedule is not running using `tpicd=yes` (which doess not depend on
`data_valid`).

==== Changes relative to the VGOS branch

#TODO: Complete this sub-section.#

=== drudg changes

This sub-section is divided into three parts. Please see
<<Changes from FS9>> above for an explanation of the parts.

==== Changes that are in common since FS9

_drudg_ opening message date is `2020Nov20`.

. [[bit3264_drudg]] Source code now works on 32- and 64-bit platforms.
+

For 64-bit use of FORTRAN, eight-byte integers are needed to support
some calls in the VEX library. As a result, _drudg_ and its libraries
are configured to automatically use four byte integers for 32-bit and
eight byte integers for 64-bit.  The rest of the FS uses four byte
integers for both.  This made it necessary to give _drudg_ it own
version of _lnfch/_, in _skdrlnfch/_.


. [[git_drudg]] Source version control is maintained with _git_.
+

The _drudg_ program is external to the FS. For each _drudg_ update the
source in imported into the FS _git_ repo for distribution with the
FS. This does not provide the same level of tracking as having _drudg_
itself in _git_ but it is still useful.

. [[uninit]] Fix uninitialized variables.
+

Several previously uninitialized variables are now initialized. As
part of this `implicit none` was added to all FORTRAN routines that
did not have it before, except for _xat.f_.

. [[preob]] Fix missing `preob` when `EARLY` start is non-zero.
+

This was broken in the implementation of staggered start for FS
_9.13.0_ and has been restored.

. [[wait]] Add support for additional wait at the end of recording for
broadband.
+

This allows schedules to include a fixed amount of additional wait for
buffering per station. This seems to be needed for Mark 6 recorders in
configurations that otherwise would require no buffer time for disks
that are slower than nominal.

. [[comment]] Update comment on line three of _.snp_ files.
+

Previously at the end of line, the number of passes and the tape
length were listed. Since there is no tape support, these fields were
replaced with the recorder type.

. [[head]] Fix crash if `$HEAD` is the last block in a `.skd` file.
+

Fixed bug in _reads.f_.

. [[mask]] Fix crash if error in mask (closing
https://github.com/nvi-inc/fs/issues/74[#74]).
+

A particular error in the mask format intermittently excited an
uninitialized variable bug.  Thanks to Beppe Maccaferri (Medicina) for
reporting this. He discovered it while testing with _r1971.skd_ (which
was not an experiment that included Medicina).

. [[drudgsource]] Clean-up source.

.. Remove references to pass, headstacks, and S2.

.. Add the GPL to files it was missing from.

.. Remove source files no longer used.

.. Unify source between _sked_ and the FS.


==== Changes relative to the main branch

#TODO: Complete this sub-section.#

==== Changes relative to the VGOS branch

#TODO: Complete this sub-section.#

