//
// Copyright (c) 2020 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= Upgrading to 10.0.0 with 64-bit
Version 0.2 - November 2020

//:hide-uri-scheme:
:sectnums:
:sectnumlevels: 4
:experimental:

:toc:
:toclevels: 4

== Introduction

This document covers converting to a 64-bit system while upgrading
from FS9 to 10.0.0. This approach assumes you will be installing a
64-bit system on a new computer. Doing so will allow you to upgrade to
10.0.0 and 64-bit without disturbing your operational 32-bit system.

The approach here depends heavily on the
<<../../misc/64-bit_conversion.adoc#,64-bit Conversion>> document,
additionally
using some steps from the <<beta2.adoc#,beta2 update>> document.

== Instructions

. Please follow the steps in the
<<../../misc/64-bit_conversion.adoc#,64-bit Conversion>> document 
down to the 
<<../../misc/64-bit_conversion.adoc#_make_local_software,Make local software>>
step. Instead of following that step, return to this document.

. Please switch to the <<beta2.adoc#,FS beta2 update>> document, starting with the
<<beta2.adoc#_case_sensitive_strings_in_antenna_commands,Case sensitive strings in antenna= commands>>
sub-step. Follow the rest of the installation procedure in that document.
