#!/usr/bin/python

import socket
#import netstring
import os
import sys
import getopt
import string
import select
from subprocess import call
    
parms = {'-h': '127.0.0.1', '-p':5000, '-t':1,'-c': "dbe_atten?;",
         '-n': os.path.basename(__file__)}
try:
    opts, pargs = getopt.getopt(sys.argv[1:], "h:p:c:t:n:")
except getopt.GetoptError, msg:
    sys.exit(msg)

for o,v in opts:
    #print o,v
    parms[o] = v

host = str(parms['-h'])
port = int(parms['-p'])
mycmd = str(parms['-c'])
timeout=float(parms['-t'])
name= str(parms['-n'])
#print "Host:", host, "port:", port, "cmd:", mycmd," Timeout: ",timeout

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.settimeout(timeout)
try:
     s.connect ((host,port))
except socket.timeout:
    call(["lgerr","lg","-1",
         name+': '+host+': '+"Connection time-out"])
#    print "Connection time-out"
    sys.exit()
except socket.error as e:
    call(["lgerr","lg","-1",
          name+': '+host+': '+"error {0}: {1}".format(e.errno, e.strerror)])
#    print host+': '+"error {0}:{1}".format(e.errno, e.strerror)
    sys.exit()

# ADD \n TO END IF NOT THERE
mycmd = string.strip(mycmd)
mycmd = mycmd + '\n'
        
# SEND COMMAND
#print mycmd
rv = s.send(mycmd)
if rv <= 0 :
    print "Fail to send ", rv
            
# WAIT FOR RESPONSE
ready=select.select([s], [], [],timeout)
if ready[0]:
    ret = s.recv(8192)
    ret=string.rstrip(ret,"\n")
    print ret
else:
    call(["lgerr","lg","-1",
          name+': '+host+': '+"Read time-out"])
#    print "Read time-out"

s.close()

