#!/usr/bin/python3
#
# Copyright (c) 2020, 2022, 2026  NVI, Inc.
#
# This file is part of VLBI Field System
# (see http://github.com/nvi-inc/fs).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import socket
#import netstring
import os
import sys
import getopt
import string
import select
from subprocess import call

parms = {'-h': '127.0.0.1', '-p':5000, '-t':1,'-c': "dbe_atten?;",
         '-n': os.path.basename(__file__)}
try:
    opts, pargs = getopt.getopt(sys.argv[1:], "FHh:p:c:t:n:")
except getopt.GetoptError as msg:
    sys.exit(msg)

for o,v in opts:
    #print o,v
    parms[o] = v

if '-H' in parms:
     sys.exit("""
Usage %s [-FHhptcn]
Socket client to write command to host/port and read response

Options (defaults):
  -F      -- use non-FS error messages
  -H      -- help, this output
  -h host -- hostname (127.0.0.1)
  -p port -- port (5000)
  -c cmd  -- command to send (dbe_atten?;), new-line appended if not present
  -t to   -- time-out in seconds (1)
  -n name -- name for FS error messages (%s)"""
%(os.path.basename(__file__),os.path.basename(__file__)))

host = str(parms['-h'])
port = int(parms['-p'])
mycmd = str(parms['-c'])
timeout=float(parms['-t'])
name= str(parms['-n'])
#print "Host:", host, "port:", port, "cmd:", mycmd," Timeout: ",timeout

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.settimeout(timeout)
try:
    s.connect ((host,port))
except socket.timeout:
    if '-F' not in parms:
        call(["lgerr","lg","-1", name+': '+host+': '+"Connection time-out"])
    else:
        print("Connection time-out")
    sys.exit()
except socket.error as e:
    if '-F' not in parms:
        call(["lgerr","lg","-1", name+': '+host+': '+"error %s"%(e)])
    else:
        print(host+': '+"error {0}:{1}".format(e.errno, e.strerror))
    sys.exit()

# ADD \n TO END IF NOT THERE
mycmd = mycmd.strip()
mycmd = mycmd + '\n'

# SEND COMMAND
#print mycmd
rv = s.send(mycmd.encode())
if rv <= 0 :
    if '-F' not in parms:
        call(["lgerr","lg","-1", name+': '+host+': Failed to send '+rv])
    else:
        print("Fail to send ", rv)

# WAIT FOR RESPONSE
ready=select.select([s], [], [],timeout)
if ready[0]:
    ret = s.recv(8192).decode()
    ret=ret.rstrip("\n")
    print(ret)
else:
    if '-F' not in parms:
        call(["lgerr","lg","-1", name+': '+host+': '+"Read time-out"])
    else:
        print("Read time-out")

s.close()
