C COMMON FOR PFMED     LAST MODIFIED BY GAG  910321
      LOGICAL KNEWPF,KBOSS_PF
      CHARACTER*28 LSF2
      CHARACTER*64 pathsave
      character*(MAX_SKD) lpsave
      COMMON /DCBS/ IDCB1,IDCB2,IDCB3,
     .              LSF2,KNEWPF,KBOSS_PF,pathsave,lpsave
