#!/bin/bash
#
# Copyright (c) 2020-2023, 2026 NVI, Inc.
#
# This file is part of VLBI Field System
# (see http://github.com/nvi-inc/fs).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

VERSION=2026-01-22

version(){
    echo "[fesh $VERSION]"
}

download_files() {
    if [[ -z "${FESH_EMAIL:-}" ]]; then
        user=anonymous
    else
        user="anonymous:$FESH_EMAIL"
    fi
    if [[ -n "$verbose" ]]; then
        CURL_VERBOSE=-v
        WGET_VERBOSE=
    else
        WGET_VERBOSE=-nv
        CURL_VERBOSE=
    fi

    if [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
        echo "Fetching $sched.vex ..." >&2
        if wget $WGET_VERBOSE "ftp://ftp@vlbeer.ira.inaf.it/vlb_arc/ftp/vlbi_arch/$month/$sched.vex"; then
            echo Done >&2
        else
            echo "Downloading $sched.vex failed" >&2
            echo "Use -H to try getting a PRELIMINARY schedule (not in .latest) only if you must." >&2
            exit 1
        fi
        return
    fi

    echo "Fetching $sched.skd ..." >&2
    if [[ "$FESH_DATA_CENTER" =~ cddis ]]; then
        if [[ "$FESH_CDDIS_METHOD" =~ ^ftp$ ]]; then
            if wget $WGET_VERBOSE "ftp://ftp@cddis.gsfc.nasa.gov/vlbi/ivsdata/aux/$year/$sched/$sched.skd"; then
                echo Done >&2
            else
                fatal "Downloading $sched.skd failed"
            fi

            if [[ -z "$no_txt" ]]; then
                echo "Fetching $sched.txt ..." >&2
                if wget $WGET_VERBOSE "ftp://ftp@cddis.gsfc.nasa.gov/vlbi/ivsdata/aux/$year/$sched/$sched.txt"; then
                    echo Done >&2
                elif [[ -n "$txt" ]]; then
                    fatal "Download of $sched.txt, required by '-x', failed."
                else
                    echo "Failed, but continuing since $sched.txt was not required by using '-x'." >&2
                fi
            fi
        elif [[ "$FESH_CDDIS_METHOD" =~ ^https$ ]]; then
            if [[ ! -e "$NETRC_DIR/.netrc" ]]; then
                fatal "$NETRC_DIR/.netrc not found, see usage"
            fi

            if ! grep -q urs.earthdata.nasa.gov "$NETRC_DIR/.netrc"; then
                fatal "$NETRC_DIR/.netrc does not contain CDDIS login information, see usage"
            fi
            if curl  -k  -f -c /dev/null $CURL_VERBOSE -n \
                $CURL_NETRC_FILE_OPTION \
                -L -O "https://cddis.nasa.gov/archive/vlbi/ivsdata/aux/$year/$sched/$sched.skd"; then
                echo Done >&2
            else
                fatal "Downloading $sched.skd failed"
            fi

            if [[ -z "$no_txt" ]]; then
                echo "Fetching $sched.txt ..." >&2
                if curl  -k  -f -c /dev/null $CURL_VERBOSE -n \
                    $CURL_NETRC_FILE_OPTION \
                    -L -O "https://cddis.nasa.gov/archive/vlbi/ivsdata/aux/$year/$sched/$sched.txt"; then
                     echo Done >&2
                elif [[ -n "$txt" ]]; then
                    fatal "Download of $sched.txt, required by '-x', failed."
                else
                    echo "Failed, but continuing since $sched.txt was not required by using '-x'." >&2
                fi
            fi
        else
            if curl -u "$user" -k -O $CURL_VERBOSE --ftp-ssl "ftp://gdc.cddis.eosdis.nasa.gov/vlbi/ivsdata/aux/$year/$sched/$sched.skd" ; then
                echo Done >&2
            else
                fatal "Downloading $sched.skd failed"
            fi

            if [[ -z "$no_txt" ]]; then
                echo "Fetching $sched.txt ..." >&2
                if curl -u "$user" -k -O $CURL_VERBOSE --ftp-ssl "ftp://gdc.cddis.eosdis.nasa.gov/vlbi/ivsdata/aux/$year/$sched/$sched.txt"; then
                    echo Done >&2
                elif [[ -n "$txt" ]]; then
                    fatal "Download of $sched.txt, required by '-x', failed."
                else
                    echo "Failed, but continuing since $sched.txt was not required by using '-x'." >&2
                fi
            fi
        fi
    elif [[ "$FESH_DATA_CENTER" =~ opar ]]; then
        if wget $WGET_VERBOSE "ftp://ftp@ivsopar.obspm.fr/vlbi/ivsdata/aux/$year/$sched/$sched.skd"; then
            echo Done >&2
        else
            fatal "Downloading $sched.skd failed"
        fi

        if [[ -z "$no_txt" ]]; then
            echo "Fetching $sched.txt ..." >&2
            if wget $WGET_VERBOSE "ftp://ftp@ivsopar.obspm.fr/vlbi/ivsdata/aux/$year/$sched/$sched.txt"; then
                echo Done >&2
            elif [[ -n "$txt" ]]; then
                fatal "Download of $sched.txt, required by '-x', failed."
            else
                echo "Failed, but continuing since $sched.txt was not required by using '-x'." >&2
            fi
        fi
    elif [[ "$FESH_DATA_CENTER" =~ bkg ]]; then
        if [[ "$FESH_BKG_METHOD" =~ ^ftp$ ]]; then
            if wget $WGET_VERBOSE "ftp://ftp@ivs.bkg.bund.de/pub/vlbi/ivsdata/aux/$year/$sched/$sched.skd"; then
                echo Done >&2
            else
                fatal "Downloading $sched.skd failed"
            fi

            if [[ -z "$no_txt" ]]; then
                echo "Fetching $sched.txt ..." >&2
                if wget $WGET_VERBOSE "ftp://ftp@ivs.bkg.bund.de/pub/vlbi/ivsdata/aux/$year/$sched/$sched.txt"; then
                  echo Done >&2
                elif [[ -n "$txt" ]]; then
                   fatal "Download of $sched.txt, required by '-x', failed."
                else
                    echo "Failed, but continuing since $sched.txt was not required by using '-x'." >&2
                fi
            fi
        else
            if curl --ssl-reqd $CURL_VERBOSE -u anonymous:anonymous -O "ftp://ivs.bkg.bund.de/pub/vlbi/ivsdata/aux/$year/$sched/$sched.skd"; then
                echo Done >&2
            else
                fatal "Downloading $sched.skd failed"
            fi

            if [[ -z "$no_txt" ]]; then
                echo "Fetching $sched.txt ..." >&2
                if curl --ssl-reqd $CURL_VERBOSE -u anonymous:anonymous -O "ftp://ivs.bkg.bund.de/pub/vlbi/ivsdata/aux/$year/$sched/$sched.txt"; then
                  echo Done >&2
                elif [[ -n "$txt" ]]; then
                   fatal "Download of $sched.txt, required by '-x', failed."
                else
                    echo "Failed, but continuing since $sched.txt was not required by using '-x'." >&2
                fi
            fi
        fi
    fi
}
# Find latest temporary directory
get_latest_tmp() {
    local tmp=$(ls -t /tmp\
        | grep "^fesh_${sched}_...$"\
        | head -1)

    if [[ -z "$tmp" ]]; then
        echo "No '-C' temporary directory for ${sched} found." >&2
        echo "Rerun with '-C' to check for any needed updates." >&2
        exit 1
    fi
    if [ -n "$(find "/tmp/$tmp" -mmin +30 -print -quit 2>/dev/null)" ]; then
        echo "Most recent '-C' temporary directory for ${sched} is more than 30 minutes old." >&2
        echo "Rerun with '-C' to make a fresh check for updates." >&2
        exit 1
    fi
    echo "/tmp/$tmp"
}
check_station() {
    set +u
    if [[ -z "$station" ]]; then
        fatal "Use STATION environment variable or '-s' to set the station code."
    fi
    set -u

    if [ ${#station} -ne 2 ]; then
        fatal "Station code from STATION env. var. or '-s' must be two characters."
    fi

#force lower case station code
    station=$(echo "$station" | tr '[:upper:]' '[:lower:]')
}
check_file_date() {
    local need_drudg=
    if [[ -e "$1" ]]; then
        if [[ "$1" -ot "$2" ]]; then
            need_drudg=1
            echo "    $(basename $1) is older than $(basename $2)" >&2
        else
            echo "    $(basename $1) is newer than $(basename $2)" >&2
        fi
    else
        echo "    $(basename $1) doesn't exist" >&2
        need_drudg=1
    fi
    echo "$need_drudg"
}
check_drudg_output () {
# station this was already checked, but try again for safety
    check_station
    local need_drudg=
    if [[ -e $CONTROL_DIR/skedf.ctl ]]; then
        echo -e "\nChecking drudg output:" >&2
        snp_date=$(check_file_date "$SNAP_DIR/$sched$station.snp" $1)
        prc_date=$(check_file_date "$PROC_DIR/$sched$station.prc" $1)
        lst_date=$(check_file_date "$LIST_DIR/$sched$station.lst" $1)
        if [[ -n "$snp_date" || -n "$prc_date" || -n "$lst_date"  ]]; then
            echo -e "\n    At least some drudg output is older than $(basename $1) or missing." >&2
            need_drudg=1
        else
            echo -e "\n    All drudg output is newer than $(basename $1). That should be okay." >&2
        fi
    else
        echo -e "\n'$CONTROL_DIR/skedf.ctl' doesn't exist, can't check drudg output" >&2
        exit 1
    fi
    echo "$need_drudg"
}
get_file_string() {
     local string=""
     if grep -q "$1" "$2"; then
        string=$(grep "$1" "$2")
     fi
     echo "$string"
}
get_PI_revision() {
     local string=""
     string=$(sed -n -e 's/^.*\(PI revision number:\)  \+| \+\([^ ]\+\).*/\1 \2/p' "$1")
     echo "$string"
}
print_version_string() {
    if [[ -n "$1" ]]; then
        if [[ -n "$2" ]]; then
            printf "        %s:\n            %s\n" "$1" "${2//$'\n'/$'\n'            }" >&2
        else
            printf "        %s:\n            %s\n" "$1" "Doesn't have a $3." >&2
        fi
    else
        if [[ -n "$2" ]]; then
            printf "        %s\n" "Both have: $2" >&2
        else
            printf "        %s\n" "Neither has a $3" >&2
        fi
    fi
}
check_open_drudg_files() {
    local open_drudg_files=
# these were already checked, but try again for safety
    check_station
    if [[ ! -e $CONTROL_DIR/skedf.ctl ]]; then
        echo -e "\n'$CONTROL_DIR/skedf.ctl' doesn't exist, can't check for open drudg output." >&2
        exit 1
    fi
    if [[ -e $SNAP_DIR/$sched$station.snp ]]; then
        if fuser -v $SNAP_DIR/$sched$station.snp 2>&1 | grep -q " boss$" ; then
            if [[ -z "$open_drudg_files" ]]; then
                echo "" >&2
                echo "    File(s) open in the FS:" >&2
            fi
            echo "        $SNAP_DIR/$sched$station.snp (boss)." >&2
            open_drudg_files=1
        fi
    fi
    if [[ -e $PROC_DIR/$sched$station.prc ]]; then
        if fuser -v $PROC_DIR/$sched$station.prc 2>&1 | grep -q " boss$" ; then
            if [[ -z "$open_drudg_files" ]]; then
                echo "" >&2
                echo "    File(s) open in the FS:" >&2
            fi
            echo "        $PROC_DIR/$sched$station.prc (boss)." >&2
            open_drudg_files=1
        fi
        if fuser -v $PROC_DIR/$sched$station.prc 2>&1 | grep -q " pfmed$" ; then
            if [[ -z "$open_drudg_files" ]]; then
                echo "" >&2
                echo "    File(s) open in the FS:" >&2
            fi
            echo "        $PROC_DIR/$sched$station.prc (pfmed)." >&2
            open_drudg_files=1
        fi
    fi
    echo "$open_drudg_files"
}

version

#enable 'strict' mode
set -euo pipefail

FS_BASE=${FS_BASE:-'/usr2'}
FS_DIR=${FS_DIR:-"${FS_BASE}/fs"}
CONTROL_DIR=${CONTROL_DIR:-"${FS_BASE}/control"}
LOG_DIR=${LOG_DIR:-"${FS_BASE}/log"}
# check for skedf.ctl
if [[ -e $CONTROL_DIR/skedf.ctl ]]; then
    proc_dir=$( perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$proc/i     ) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t\r]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
    snap_dir=$( perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$snap/i     ) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t\r]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
    sched_dir=$(perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$schedules/i) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t\r]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
    PROC_DIR=${PROC_DIR:-"${proc_dir}"}
    SNAP_DIR=${SNAP_DIR:-"${snap_dir}"}
    SCHED_DIR=${SCHED_DIR:-"${sched_dir}"}
#do not use the above the three *_DIR environment variables
#to override what is in skedf.ctl; they can be used to override
#what is placed in the corresponding *_dir variables if the
#perl directory extracts get the wrong result
    LIST_DIR=${LIST_DIR:-${SCHED_DIR}}
else
# drudg won't run without skedf.ctl, maybe some day it will
# we can still get the schedule
# use current directory without other information
    SCHED_DIR=${SCHED_DIR:-"."}
    echo "WARNING: '$CONTROL_DIR/skedf.ctl' doesn't exist,"  >&2
    echo "WARNING: 'using '$SCHED_DIR' for schedule directory"  >&2
fi

FESH_DATA_CENTER=${FESH_DATA_CENTER:-'cddis'}

FESH_CDDIS_METHOD=${FESH_CDDIS_METHOD:-'ftp-ssl'}
FESH_BKG_METHOD=${FESH_BKG_METHOD:-'ftp-ssl'}

if [[ ! -z "${FESH_GEO_TPICD:-}" ]]; then
    tpicd=$FESH_GEO_TPICD
fi
if [[ ! -z "${FESH_GEO_CONT_CAL:-}" ]]; then
    cont_cal=$FESH_GEO_CONT_CAL
fi
if [[ ! -z "${FESH_GEO_CONT_CAL_POLARITY:-}" ]]; then
    cont_cal_polarity=$FESH_GEO_CONT_CAL_POLARITY
fi
if [[ ! -z "${FESH_GEO_VSI_ALIGN:-}" ]]; then
    vsi_align=$FESH_GEO_VSI_ALIGN
fi
if [[ ! -z "${FESH_GEO_USE_SETUP_PROC:-}" ]]; then
    use_setup_proc=$FESH_GEO_USE_SETUP_PROC
fi
if [[ ! -z "${FESH_GEO_VDIF_SINGLE_THREAD_PER_FILE:-}" ]]; then
    vdif_single_thread_per_file=$FESH_GEO_VDIF_SINGLE_THREAD_PER_FILE
fi
if [[ -z "${NETRC_DIR:-}" ]]; then
    NETRC_DIR=$HOME
    CURL_NETRC_FILE_OPTION=
else
    CURL_NETRC_FILE_OPTION=" --netrc-file $NETRC_DIR/.netrc"
fi
if [[ ! -z "${STATION:-}" ]]; then
    station=$STATION
fi

fatal(){
    echo -e "ERROR: fesh:" "$*" >&2
    exit 1
}

year=$(date +%Y)
month=$(LANG=C date +%b%y|tr [:upper:] [:lower:])

run_drudg_file="run_drudg"

usage() {
    cat <<EOF
Usage: $0 [options] schedule
Fetch schedule file (and .txt file, if available, for geo)

Options:
 -n       Fetch next schedule in master file (not supported yet)
 -C       check for changed schedule file (and .txt file if previously
          download) on server; if there were any changes, new versions
          are left on /tmp and a hint for how proceed is printed
 -R       Update files that were found to be changed with '-C; the latest
          versions less than 10 minutes old on /tmp are used; for geo, drudg
          will be run automatically if the schedule file is updated or if the
          drudg output was stale when '-C' was used
 -d       drudg schedule with default settings, not supported for vlbeer
          (needs STATION environment variable or -s set with station code)
 -D dc    Use alternate data center; dc=bkg, cddis, opar, or vlbeer. Upper
          and lower case are accepted. (see more below about setting the
          default data center)
 -v       Verbose mode: curl/wget verbose and drudg output printed to stdout
 -V       Print version and exit.
 -P       With -d, use drudg to send the schedule summary to the printer
 -S       Skip download (including for -x and -f)
 -m mmmyy Specify three character month and two digit year for the vlbeer
          data center (see more below about specifying the month/year)
          uses the hidden .latest sub-directory by default, use -H to suppress
 -H       suppress use of the hidden .latest sub-directory for vlbeer
 -y yyyy  Specify different (four-digit) year than the current one
          for geo data centers (see more below about specifying the year)
 -f       Force downloading of schedule (and .txt) files from server (if -S is
          not used) and force re-drudging when -d is used, otherwise existing
          files will not be replaced
 -x       require downloading corresponding .txt file (geo only), otherwise it
          is skipped if not available
 -X       don't attempt downloading corresponding .txt file (geo only)
 -s xx    Override STATION environment variable
 -a val   Override drudg VSI_ALIGN answer to val
 -c val   Override drudg CONT_CAL answer to val
 -p val   Override drudg CONT_CAL_POLARITY answer to val
 -t val   Override drudg TPICD answer to val
 -T val   Override drudg VDIF_SINGLE_THREAD_PER_FILE answer to val
 -u val   Override drudg SETUP_PROC answer to val
 -h       Print this message

NOTE: If you specify a schedule that doesn't exist on the server, you will get
a file or a directory error from the server.

For the '-d' option, the STATION environment variable, or the -s option, must
be set with the two character station code. For example, for STATION:

    setenv STATION gs #in ~/.login for tcsh or
    export STATION=gs #in ~/.profile for bash

If both are set, -s overrides STATION. In any event, the value is mapped to
lower case, if it isn't already, for agreement with drudg.

The '-C' option allows checking that already downloaded files and drudg output
are up-to-date. If files need to updated, the '-R' option should be used
afterward for that. Additionally, messages for some errors recommend ways to
use '-C'/'-R' for recovering. Other approaches may work better depending on
your needs, but the recommended ones fit most situations.

Some protections are built into '-R'. It will stop before making any changes,
if: any of the files to be updated (.vex, .skd, .txt) are newer than their
replacements; the most recent '-C' was more than 30 minutes ago; and if drudg
would be run, any of the drudg output files are open in the FS.

Please see the end of this message about handling optional 'skedf.ctl'
specified prompting for 'drudg'.

The '-d' option is not supported for data center 'vlbeer'.

The default data center is CDDIS but can be changed by setting the
FESH_DATA_CENTER environment variable. Accepted values are bkg, cddis, opar
(the three 'geo' centers) or vlbeer. The value is mapped to lower case, if it
isn't already. For example, to make the default bkg, use:

    setenv FESH_DATA_CENTER bkg #in ~/.login for tcsh or
    export FESH_DATA_CENTER=bkg #in ~/.profile for bash

The '-D' option can be used to specify an alternate data center when running
the script.  If the data center is vlbeer, the '-d' option cannot be used.

For geo data centers, fesh by default gets a schedule for the current year,
but this can be overridden with '-y yyyy' option to specify a four digit year
'yyyy'. That option can be used to get a schedule for the next year. The
'yyyy' is not checked for validity and the download will fail if it is not
correct.

For vlbeer, fesh by default gets a schedule from the hidden .latest
sub-directory for the current month, but this can be overridden with '-m
mmmyy' to specify a three character month abbreviation 'jan', 'feb', 'mar',
'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec' as 'mmm' and a
two digit year 'yy'. The hidden .latest sub-directory of the specified month
will be used.  The adding of /.latest to the current or '-m' specified
directory can be suppressed the -H option.  The 'mmmyy' is not checked for
validity and the download will fail if it is not correct.

fesh (curl actually) will prompt for an email to use as the password for
anonymous ftp-ssl access for CDDIS. The prompt can be suppressed by setting a
working email address in the FESH_EMAIL variable, e.g.:

    setenv FESH_EMAIL user@address #in ~/.login for tcsh or
    export FESH_EMAIL=user@address #in ~/.profile for bash

The directories for .skd, .snp, and .prc files are obtained from the skedf.ctl
control file. The listing files go with the .skd files by default, but can be
over-ridden with the LIST_DIR environment variable. For example to make it the
current directory, use:

    setenv LIST_DIR . #in ~/.login for tcsh or
    export LIST_DIR=. #in ~/.profile for bash

The .txt file (for geo schedules only) is placed in the same directory as the
schedule file.

The default transfer method from CDDIS is ftp-ssl.  You can use https as the
method with CDDIS if you set:

    setenv FESH_CDDIS_METHOD https #in ~/.login for tcsh or
    export FESH_CDDIS_METHOD=https #in ~/.profile for bash

For the CDDIS https method, the login must be configured in ".netrc" which by
default is in "~".  For example:

    machine urs.earthdata.nasa.gov
        login mycddisuser
        password secret

See "man 5 netrc" for more details on ".netrc".

If your curl supports the "--netrc-file" option (see "man curl") , you can
change the directory used for ".netrc" by setting the NETRC_DIR environment
variable.  This matches plog. E.g., add the following to your login script

    setenv NETRC_DIR "/usr2/control" #in ~/.login for tcsh or
    export NETRC_DIR="/usr2/control" #in ~/.profile for bash

If you have FSL8 or another old distribution that does not support curl
ftp-ssl or https with CDDIS, but worked with the previous versions of fesh
that used wget for non-ssl ftp, you can restore the previous behaviour with:

    setenv FESH_CDDIS_METHOD ftp #in ~/.login for tcsh or
    export FESH_CDDIS_METHOD=ftp #in ~/.profile for bash

However, this method will no longer work when CDDIS stops support of non-ssl
ftp, which is expected at the end of October 2020.

The default transfer method from BKG is ftp-ssl.  If you have FSL8 or another
old distribution that does not support curl ftp-ssl with BKG, but worked with
the previous versions of fesh that used wget for non-ssl ftp, you can restore
the previous behaviour with:

    setenv FESH_BKG_METHOD ftp #in ~/.login for tcsh or
    export FESH_BKG_METHOD=ftp #in ~/.profile for bash

However, this method will no longer work when BKG stops support of non-ssl
ftp, which is expected at the end of May 2022.

With the '-d' option, if the 'skedf.ctl' control file specifies prompting for
any of: tpicd, vsi_align, cont_cal, cont_cal_polarity, using setup_proc, or
single VDIF thread per file, a fixed answer can be provided by setting the
environment variables: FESH_GEO_TPICD, FESH_GEO_VSI_ALIGN, FESH_GEO_CONT_CAL,
FESH_GEO_CONT_CAL_POLARITY, FESH_GEO_USE_SETUP_PROC, and
FESH_GEO_VDIF_SINGLE_THREAD_PER_FILE respectively. These settings can be
overridden when running the script with the options: '-t', '-a', '-c', '-p',
'-u', and '-T' respectively.  Using '' as the value for an option will unset
the corresponding value supplied as an environment variable. Please be sure to
read the follow four NOTEs:

  NOTE: If used incorrectly, this feature can fail in complicated ways with no
  obvious indication. Use at your own risk. Simple use with single mode
  schedules should be fine.

  NOTE: If there is more than mode in the schedule, it is not possible to
  supply answers in this way. 'drudg' will have to be run manually.

  NOTE: If any of these environment variables or options are used, the
  corresponding prompts must be enabled in 'skedf.ctl'. If there isn't
  agreement, incorrect .prc files may be created without an obvious indication
  of a problem. Be careful in particular of FESH_GEO_VSI_ALIGN and the '-a'
  option since the corresponding prompt will only occur if a DBBC3 PFB mode is
  in use.

  NOTE: To provide minimal protection, the script will reject:

   -setting an answer for vsi_align and answers either for cont_cal and/or
    cont_cal_polarity
   -setting an answer for cont_cal_polarity if the answer for cont_cal is off
   -setting the tpicd answer to anything but a non-negative integer
   -setting the cont_cal answer to anything but on or off
   -setting the cont_cal_polarity to answer anything but 0, 1, 2, 3, or none
   -setting the vsi_align answer to anything but 0, 1, or none
   -setting the use_setup_proc answer to anything but yes or no
   -setting the vdif_single_thread_per_file answer to anything but yes or no
EOF
}

run_drudg=
force=
verbose=
txt=
no_txt=
print=
download=1
check_new=
replace_files=
while getopts 'a:Cc:nfdD:hHm:p:PRs:St:T:u:vVxXy:' opt; do
    case $opt in
        n)
            echo "'next' not implemented."
            exit 1
            ;;
        C)
            if [[ -n "$replace_files" ]] ; then
                echo "Can't use '-R' and '-C' together."
                exit 1
            fi
            if [[ -n "$run_drudg" ]] ; then
                echo "Can't use '-d' and '-C' together."
                exit 1
            fi
            check_new=1
            ;;
        R)
            if [[ -n "$check_new" ]] ; then
                echo "Can't use '-C' and '-R' together."
                exit 1
            fi
            if [[ -n "$run_drudg" ]] ; then
                echo "Can't use '-d' and '-R' together."
                exit 1
            fi
            replace_files=1
            ;;
        d)
            if [[ -n "$check_new" ]] ; then
                echo "Can't use '-C' and '-d' together."
                exit 1
            fi
            if [[ -n "$replace_files" ]] ; then
                echo "Can't use '-R' and '-d' together."
                exit 1
            fi
            run_drudg=1
            ;;
        D)
            FESH_DATA_CENTER=$OPTARG
            ;;
        f)
            force=1
            ;;
        m)
            month=$OPTARG
            month_option=1
            ;;
        H)
            not_hidden=1
            ;;
        y)
            year=$OPTARG
            year_option=1
            ;;
        h)
            usage
            exit 0
            ;;
        v)
            verbose=1
            ;;
        V)
            version
            exit 0
            ;;
        x)
            if [[ -n "$no_txt" ]] ; then
                echo "Can't use '-X' and '-x' together."
                exit 1
            fi
            txt=1
            ;;
        X)
            if [[ -n "$txt" ]] ; then
                echo "Can't use '-x' and '-X' together."
                exit 1
            fi
            no_txt=1
            ;;
        P)
            print=1
            ;;
        S)
            download=
            ;;
        s)
            station=$OPTARG
            ;;
        t)
            if [ ! -z ${OPTARG} ]; then tpicd=$OPTARG; fi
            ;;
        c)
            if [ ! -z ${OPTARG} ]; then cont_cal=$OPTARG; fi
            ;;
        p)
            if [ ! -z ${OPTARG} ]; then cont_cal_polarity=$OPTARG; fi
            ;;
        a)
            if [ ! -z ${OPTARG} ]; then vsi_align=$OPTARG; fi
            ;;
        u)
            if [ ! -z ${OPTARG} ]; then use_setup_proc=$OPTARG; fi
            ;;
        T)
            if [ ! -z ${OPTARG} ]; then vdif_single_thread_per_file=$OPTARG; fi
            ;;
        *)
            echo "Try the '-h' option for help" >&2
            exit 1
    esac
done
shift $((OPTIND - 1))

if [[ $# -eq 0 ]] ; then
    echo "Usage: fesh [options] schedule"
    echo "A 'schedule' is required."
    echo "Try 'fesh -h' option for help" >&2
    exit 1
fi

sched=$1

FESH_DATA_CENTER=$(echo "$FESH_DATA_CENTER" | tr '[:upper:]' '[:lower:]')
if [[ ! "$FESH_DATA_CENTER" =~ ^(cddis|opar|bkg|vlbeer)$ ]]; then
   echo "Unknown data center: $FESH_DATA_CENTER."
   exit 1
fi
if [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
    if [[ -n "$txt" ]]; then
        echo "Option -x (.txt) is not supported for the vlbeer data center."
        echo "To fetch the schedule, rerun without -x."
        exit 1
    elif [[ -n "$no_txt" ]]; then
        echo "Option -X (NO .txt) is not supported for the vlbeer data center."
        echo "To fetch the schedule, rerun without -X."
        exit 1
    elif [[ -n "$run_drudg" ]]; then
        echo "Option -d (drudg) is not supported for the vlbeer data center."
        echo "To fetch the schedule, rerun without -d."
        exit 1
    fi
    if [[ ! -z  "${year_option:-}" ]]; then
        echo "The -y option can't be used for the vlbeer data center"
        exit 1
    fi
    if [[ -z  "${not_hidden:-}" ]]; then
        month="${month}/.latest"
    fi
elif [[ ! -z "${month_option:-}" ]]; then
        echo "The -m option can't be used for a geo data center"
        exit 1
fi

if [[ -n "$run_drudg" ]]; then
    check_station
    if [[ ! -e $CONTROL_DIR/skedf.ctl ]]; then
        echo "$CONTROL_DIR/skedf.ctl doesn't exist, can't run drudg, don't use '-d'" >&2
        exit 1
    fi
    open_drudg_files=$(check_open_drudg_files)
    if [[ -n "$open_drudg_files" ]]; then
        echo "" >&2
        echo "ERROR: Can't run drudg because the above files are open in the FS." >&2
        echo "ERROR: Try again after the files are closed in the FS or don't use '-d'." >&2
        exit 1
    fi
fi

if [[ ! "$FESH_CDDIS_METHOD" =~ ^(ftp|ftp-ssl|https)$ ]]; then
   echo "Unknown cddis method: $FESH_CDDIS_METHOD."
   exit 1
fi

if [[ ! "$FESH_BKG_METHOD" =~ ^(ftp|ftp-ssl)$ ]]; then
   echo "Unknown bkg method: $FESH_BKG_METHOD."
   exit 1
fi

# build optional answers
tpicd_answer=
if [ ! -z ${tpicd+x} ]; then tpicd_answer=$tpicd$'\n'; fi
cont_cal_answer=
if [ ! -z ${cont_cal+x} ]; then cont_cal_answer=$cont_cal$'\n'; fi
cont_cal_polarity_answer=
if [ ! -z ${cont_cal_polarity+x} ]; then cont_cal_polarity_answer=$cont_cal_polarity$'\n'; fi
vsi_align_answer=
if [ ! -z ${vsi_align+x} ]; then vsi_align_answer=$vsi_align$'\n'; fi
use_setup_proc_answer=
if [ ! -z ${use_setup_proc+x} ]; then use_setup_proc_answer=$use_setup_proc$'\n'; fi
vdif_single_thread_per_file_answer=
if [ ! -z ${vdif_single_thread_per_file+x} ]; then vdif_single_thread_per_file_answer=$vdif_single_thread_per_file$'\n'; fi

#prevent simple errors in answers
if [[ ! "$tpicd_answer" =~ ^([0-9]+$'\n'|)$ ]]; then
   echo -n "tpicd must be a non-negative integer or not set, was $tpicd_answer"
   exit 1
fi
if [[ ! "$cont_cal_answer" =~ ^(on$'\n'|off$'\n'|)$ ]]; then
   echo -n "CONT_CAL must be on, off, or not set, was $cont_cal_answer"
   exit 1
fi
if [[ ! "$cont_cal_polarity_answer" =~ ^([0-3]+$'\n'|none$'\n'|)$ ]]; then
   echo -n "CONT_CAL_POLARITY must be 0, 1, 2, 3, none, or not set, was $cont_cal_polarity_answer"
   exit 1
fi
if [[ ! "$vsi_align_answer" =~ ^([0-1]+$'\n'|none$'\n'|)$ ]]; then
   echo -n "VSI_ALIGN must be 0, 1, none, or not set, was $vsi_align_answer"
   exit 1
fi
if [[ ! "$use_setup_proc_answer" =~ ^(yes$'\n'|no$'\n'|)$ ]]; then
   echo -n "USE_SETUP_PROC must be yes, no, or not set, was $use_setup_proc_answer"
   exit 1
fi
if [[ ! "$vdif_single_thread_per_file_answer" =~ ^(yes$'\n'|no$'\n'|)$ ]]; then
   echo -n "VDIF_SINGLE_THREAD_PER_FILE must be yes, no, or not set, was $vdif_single_thread_per_file_answer"
   exit 1
fi
if [ ! -z "$vsi_align_answer"  ]
then
    if [ ! -z "$cont_cal_answer" ]
    then
        if [ ! -z "$cont_cal_polarity_answer" ]
        then
            echo "setting VSI_ALIGN is not compatible with setting CONT_CAL and CONT_CAL_POLARITY"
            exit 1
        fi
        echo "setting VSI_ALIGN is not compatible with setting CONT_CAL"
        exit 1
    fi
    if [ ! -z "$cont_cal_polarity_answer" ]
    then
        echo "setting VSI_ALIGN is not compatible with setting CONT_CAL_POLARITY"
        exit 1
    fi
fi
if [[ "$cont_cal_answer" =~ off  ]]; then
    if [ ! -z "$cont_cal_polarity_answer" ]
    then
        echo "setting CONT_CAL_POLARITY with CONT_CAL off is not supported"
        exit 1
    fi
fi

## Conflict check
if [[ -z "$check_new" && -z "$replace_files" ]]; then
    if [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
	if [[ -e $SCHED_DIR/$sched.vex ]]; then
	    if [[ -z "$force" ]]; then
		echo "$SCHED_DIR/$sched.vex exists. Rerun with '-C' to check it (and then" >&2
		echo "with '-R', if appropriate, to replace it)." >&2
		echo "Or rerun adding '-f' to force deleting all conflicting files." >&2
		exit 1
	    fi
	    rm "$SCHED_DIR/$sched.vex"
	fi
    elif [[ -n "$download" ]]; then
	if [[ -e $SCHED_DIR/$sched.skd ]]; then
	    if [[ -z "$force" ]]; then
		echo "$SCHED_DIR/$sched.skd exists. Rerun with '-C' to check it (and then " >&2
		echo "with '-R', if appropriate, to replace it and drudg it)." >&2
		echo "Or rerun adding '-f' to force deleting all conflicting files." >&2
		exit 1
	    fi
	    rm "$SCHED_DIR/$sched.skd"
	fi
	if [[ -e $SCHED_DIR/$sched.txt ]]; then
	    if [[ -z "$force" ]]; then
		echo "$SCHED_DIR/$sched.txt exists. Rerun with '-C' to check it (and then " >&2
		echo "with '-R', if appropriate, to replace it; that will also update the schedule if" >&2
		echo "that is needed, and run drudg if that is needed)." >&2
		echo "Or rerun adding '-f' to force deleting all conflicting files." >&2
		exit 1
	    fi
	    rm "$SCHED_DIR/$sched.txt"
	 fi
    fi
fi

if [[ -n "$replace_files" ]]; then
    download=
    run_drudg=
    tmp=$(get_latest_tmp)
    echo "Found '-C' temporary directory $tmp" >&2
    action=
    if [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
       if [[ -e "$tmp/$sched.vex" ]]; then
           if [[ "$SCHED_DIR/$sched.vex" -nt "$tmp/$sched.vex" ]]; then
               echo "" >&2
               echo "    $SCHED_DIR/$sched.vex is newer than the file that would replace it." >&2
               echo "" >&2
               echo "ERROR: The file in $SCHED_DIR is newer than the file that would replace it." >&2
               echo "ERROR: Rerun with '-C' to check again." >&2
               exit 1
           fi
           echo "Updating $SCHED_DIR/$sched.vex" >&2
           cp -f "$tmp/$sched.vex" "$SCHED_DIR"
           echo -e "\nBEWARE: Any drudg output is older than $SCHED_DIR/$sched.vex."
           echo      "        You should run drudg manually to update any files you need." >&2
           unlink "$tmp/$sched.vex"
           action=1
       fi
    else
       if [[ -e "$tmp/$run_drudg_file" ]] ; then
# check station, open drudg files, and skedf.ctl here, so we don't overwrite files if we need to abort
           check_station
           open_drudg_files=$(check_open_drudg_files)
           if [[ -n "$open_drudg_files" ]]; then
               echo "" >&2
               echo "ERROR: Can't run drudg because the above files are open in the FS." >&2
               echo "ERROR: Try again after the files are closed in the FS." >&2
               exit 1
           fi
           if [[ ! -e $CONTROL_DIR/skedf.ctl ]]; then
               fatal "$CONTROL_DIR/skedf.ctl doesn't exist, can't run drudg with '-R'"
           fi
           run_drudg=1
           force=1
           unlink "$tmp/$run_drudg_file"
           action=1
       fi
       old_files=
       if [[ -e "$tmp/$sched.skd" && "$SCHED_DIR/$sched.skd" -nt "$tmp/$sched.skd" ]]; then
           if [[ -z "$old_files" ]]; then
               echo "" >&2
           fi
           echo "    $SCHED_DIR/$sched.skd is newer than the file that would replace it." >&2
           old_files=1
       fi
       if [[ -e "$tmp/$sched.txt" && "$SCHED_DIR/$sched.txt" -nt "$tmp/$sched.txt" ]]; then
           if [[ -z "$old_files" ]]; then
               echo "" >&2
           fi
           echo "    $SCHED_DIR/$sched.txt is newer than the file that would replace it." >&2
           old_files=1
       fi
       if [[ -n "$old_files" ]]; then
           echo "" >&2
           echo "ERROR: At least one file in $SCHED_DIR is newer than the file that would" >&2
           echo "ERROR: replace it. Rerun with '-C' to check again." >&2
           exit 1
       fi
       if [[ -e "$tmp/$sched.skd" ]]; then
           echo "Updating $SCHED_DIR/$sched.skd" >&2
           cp -f "$tmp/$sched.skd" "$SCHED_DIR"
           unlink "$tmp/$sched.skd"
           action=1
       fi
       if [[ -e "$tmp/$sched.txt" ]]; then
          echo "Updating $SCHED_DIR/$sched.txt" >&2
          cp -f "$tmp/$sched.txt" "$SCHED_DIR"
          unlink "$tmp/$sched.txt"
          action=1
       fi
    fi
    if [[ -n "$action" ]]; then
       rmdir "$tmp"
    else
       echo "No updates were found. Maybe the download for the previous '-C' failed." >&2
       echo "Rerun with '-C' to make a fresh check for updates." >&2
       exit 1
    fi
fi

if [[ -n "$run_drudg" && -z "$check_new" ]]; then
    if [[ ! -n "$download" ]]; then
        if [[ ! -e $SCHED_DIR/$sched.skd ]]; then
            echo "$SCHED_DIR/$sched.skd doesn't exist. Download it first. Rerun without '-S'." >&2
            exit 1
        fi
    fi

    if [[ -e $SNAP_DIR/$sched$station.snp ]]; then
        if [[ -z "$force" ]]; then
            echo "$SNAP_DIR/$sched$station.snp exists. Rerun with '-C' to check it" >&2
            echo "(and then follow the directions)." >&2
            echo "Or rerun adding '-f' to force deleting all conflicting files." >&2
            exit 1
        fi
        rm "$SNAP_DIR/$sched$station.snp"
    fi
    if [[ -e $PROC_DIR/$sched$station.prc ]]; then
        if [[ -z "$force" ]]; then
            echo "$PROC_DIR/$sched$station.prc exists. Rerun with '-C' to check it" >&2
            echo "(and then follow the directions)." >&2
            echo "Or rerun adding '-f' to force deleting all conflicting files." >&2
            exit 1
        fi
        rm "$PROC_DIR/$sched$station.prc"
    fi
    if [[ -e $LIST_DIR/$sched$station.lst ]]; then
        if [[ -z "$force" ]]; then
            echo "$LIST_DIR/$sched$station.lst exists. Rerun with '-C' to check it" >&2
            echo "(and then follow the directions)." >&2
            echo "Or rerun adding '-f' to force deleting all conflicting files." >&2
            exit 1
        fi
        rm "$LIST_DIR/$sched$station.lst"
    fi
fi

if [[ -n "$check_new" ]]; then
    if [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
        if [[ ! -e $SCHED_DIR/$sched.vex ]]; then
            fatal "Schedule $SCHED_DIR/$sched.vex is not present. Rerun without '-C'."
        fi
    else
        if [[ ! -e $SCHED_DIR/$sched.skd ]]; then
            echo "Schedule $SCHED_DIR/$sched.skd is not present. Rerun without -C,' probably" >&2
            echo "adding '-fd' to overwrite everything and drudg the schedule." >&2
            exit 1
        fi
    fi

#check here so nothing is created unless drudg check can work
    check_station
    if [[ ! -e $CONTROL_DIR/skedf.ctl ]]; then
        fatal "$CONTROL_DIR/skedf.ctl doesn't exist, can't check drudg output"
    fi

    FESH_TEMP_DIR=$(mktemp -d  "/tmp/$(basename $0)_${sched}_XXX" || fatal "Using mktemp to create temporary directory failed." )
    if [[ "$FESH_TEMP_DIR" == "" ]]; then
        fatal "Creating temporary directory failed"
    fi

    pushd "$FESH_TEMP_DIR" >/dev/null
    echo "Fetching from $FESH_DATA_CENTER to $FESH_TEMP_DIR for checking" >&2
    download_files
    update_needed=
    echo -e "\nComparison results:" >&2
    if [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
       if [[ ! -e "$sched.vex" ]]; then
            echo "    $FESH_TEMP_DIR/$sched.vex from the server does not exist" >&2
        elif cmp -s "$sched.vex" $SCHED_DIR/$sched.vex ; then
            unlink "$sched.vex"
            echo "    $SCHED_DIR/$sched.vex agrees with the server." >&2
            old_date=$(get_PI_revision "$SCHED_DIR/$sched.vex")
            print_version_string "" "$old_date" 'PI revision number'
        else
            echo "    $FESH_TEMP_DIR/$sched.vex from the server is different" >&2
            old_date=$(get_PI_revision "$SCHED_DIR/$sched.vex")
            new_date=$(get_PI_revision "$FESH_TEMP_DIR/$sched.vex")
            echo "" >&2
            print_version_string "$SCHED_DIR/$sched.vex"                     "$old_date" 'PI revision number'
            echo "" >&2
            print_version_string "$FESH_TEMP_DIR/$sched.vex from the server" "$new_date" 'PI revision number'
            echo "" >&2
            if [[ -z "$old_date" || -z "$new_date" ]]; then
                echo "        BEWARE: PI revision number is missing from one or both schedules." >&2
                if [[ "$old_date" == *$'\n'* || "$new_date" == *$'\n'* ]]; then
                    echo "        BEWARE: One schedule has more than one PI revision number." >&2
                fi
            elif [[ "$old_date" == *$'\n'* || "$new_date" == *$'\n'* ]]; then
                echo "        BEWARE: One or both schedules have more than one PI revision number." >&2
            elif [[ "$old_date" == "$new_date" ]]; then
                echo "        BEWARE: The files are different but have the same PI revision number."
            elif [[  "$old_date" > "$new_date" ]]; then
                echo "        BEWARE: The PI revision number in the server file appears to be LOWER." >&2
            else
                echo "        The PI revision number in the server file appears to be GREATER." >&2
            fi
            update_needed=1
        fi
    else
        if [[ ! -e "$sched.skd" ]]; then
            echo "    $FESH_TEMP_DIR/$sched.skd from the server does not exist" >&2
        elif cmp -s "$sched.skd" $SCHED_DIR/$sched.skd ; then
            unlink "$sched.skd"
            echo "    $SCHED_DIR/$sched.skd agrees with the server." >&2
            old_date=$(get_file_string SCHEDULE_CREATE_DATE "$SCHED_DIR/$sched.skd")
            print_version_string "" "$old_date" SCHEDULE_CREATE_DATE
            if [[ -z "$old_date" ]]; then
                echo -e "\n        BEWARE: SCHEDULE_CREATE_DATE is missing from both schedules." >&2
            elif [[ "$old_date" == *$'\n'* ]]; then
                echo -e "\n        BEWARE: Both schedules have more than one SCHEDULE_CREATE_DATE.\n" >&2
            fi
        else
            echo "    $FESH_TEMP_DIR/$sched.skd from the server is different" >&2
            old_date=$(get_file_string SCHEDULE_CREATE_DATE "$SCHED_DIR/$sched.skd")
            new_date=$(get_file_string SCHEDULE_CREATE_DATE "$FESH_TEMP_DIR/$sched.skd")
            echo "" >&2
            print_version_string "$SCHED_DIR/$sched.skd"                     "$old_date" SCHEDULE_CREATE_DATE
            echo "" >&2
            print_version_string "$FESH_TEMP_DIR/$sched.skd from the server" "$new_date" SCHEDULE_CREATE_DATE
            echo "" >&2
            if [[ -z "$old_date" || -z "$new_date" ]]; then
                echo "        BEWARE: SCHEDULE_CREATE_DATE is missing from one or both schedules." >&2
                if [[ "$old_date" == *$'\n'* || "$new_date" == *$'\n'* ]]; then
                    echo "        BEWARE: One schedule has more than one SCHEDULE_CREATE_DATE." >&2
                fi
            elif [[ "$old_date" == *$'\n'* || "$new_date" == *$'\n'* ]]; then
                echo "        BEWARE: One or both schedules have more than one SCHEDULE_CREATE_DATE." >&2
            elif [[ "$old_date" == "$new_date" ]]; then
                echo "        BEWARE: The files are different but have the same SCHEDULE_CREATE_DATE." >&2
            elif [[  "$old_date" > "$new_date" ]]; then
                echo "        BEWARE: SCHEDULE_CREATE_DATE in the server file appears to be OLDER." >&2
            else
                echo "        The SCHEDULE_CREATE_DATE in the server file appears to be NEWER." >&2
            fi
            update_needed=1
        fi
        echo "" >&2
        if [[ ! -e "$sched.txt" && ! -e "$SCHED_DIR/$sched.txt" ]]; then
            echo "    Neither $SCHED_DIR or the server have a $sched.txt file." >&2
        elif [[ ! -e "$sched.txt" ]]; then
            echo "    The server doesn't have a $sched.txt file, but $SCHED_DIR does." >&2
            echo "" >&2
            echo "        BEWARE: $SCHED_DIR/$sched.txt will not be removed by '-R'." >&2
        elif [[ ! -e "$SCHED_DIR/$sched.txt" ]]; then
            echo "    The server has a $sched.txt file, but $SCHED_DIR does not." >&2
            update_needed=1
        elif cmp -s "$sched.txt" $SCHED_DIR/$sched.txt ; then
            unlink "$sched.txt"
            echo "    $SCHED_DIR/$sched.txt agrees with the server." >&2
        else
            echo "    $FESH_TEMP_DIR/$sched.txt from the server is different" >&2
            update_needed=1
        fi
    fi
    if [[ -z "$update_needed" ]] ; then
        echo -e "\n    The files that are on the server agree with those in $SCHED_DIR." >&2
    else
        echo -e "\n    The files that are on the server do not agree with those in $SCHED_DIR." >&2
    fi
    if [[ ! "$FESH_DATA_CENTER" =~ vlbeer ]]; then
        ext="skd"
    else
        ext="vex"
    fi
    drudg_needed=$(check_drudg_output "$SCHED_DIR/$sched.$ext")
    if [[ ! "$FESH_DATA_CENTER" =~ vlbeer ]]; then
       if [[ -e "$sched.skd" ]]; then
           drudg_needed=1
       fi
       if [[ -n "$drudg_needed" ]] ; then
           touch "$FESH_TEMP_DIR/$run_drudg_file"
       fi
    fi
    if [[ -z "$update_needed" && -z "$drudg_needed" ]] ; then
        rmdir $FESH_TEMP_DIR
        echo -e "\nNo action needed. Do NOT rerun with '-R'." >&2
    elif [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
        if [[ -n "$update_needed" ]]; then
            cat <<EOF >&2

Rerun with '-R' to update $SCHED_DIR with
$FESH_TEMP_DIR/$sched.$ext. You should run drudg
manually afterward to update/create any drudg output you need.
EOF
        elif [[ -n "$drudg_needed" ]]; then
            rmdir $FESH_TEMP_DIR
            cat <<EOF >&2

Do NOT rerun with '-R'. You should run drudg manually to update/create
any drudg output you need.
EOF
        fi
    else
       if [[ -n "$update_needed" ]]; then
           cat <<EOF >&2

Rerun with '-R' to update $SCHED_DIR with the different files in
$FESH_TEMP_DIR. Drudg will be run automatically if needed.
EOF
       elif [[ -n "$drudg_needed" ]]; then
           cat <<EOF >&2

Rerun with '-R' to update the drudg output.
EOF
       fi
       if [[ -n "$drudg_needed" ]]; then
           open_drudg_files=$(check_open_drudg_files)
           if [[ -n "$open_drudg_files" ]]; then
               echo "">&2
               echo "WARNING: '-R' will be blocked because it will run drudg and the above files," >&2
               echo "WARNING: that it will recreate, are open in the FS." >&2
           fi
       fi
    fi
    popd >/dev/null
    exit 0
fi

if [[ -n "$download" ]]; then
    pushd "$SCHED_DIR" >/dev/null
    echo "Fetching from $FESH_DATA_CENTER to $SCHED_DIR" >&2
    #TODO: if not found, maybe check next or previous years?
    download_files
    popd >/dev/null
fi

if [[ -n "$run_drudg" ]]; then
    nine=$'9'
    twelve=$'12'

    drudg_out="/dev/null"
    if [[ -n "$verbose" ]]; then
        drudg_out="/dev/stdout"
    fi

    if [[ -n "$print" ]]; then
        print=$'5'$'\n'
        echo "Will send summary to printer" >&2
    fi
    echo -n Drudging schedule... >&2
    cat <<EOF | "$FS_DIR/bin/drudg" "$sched.skd" > "$drudg_out"
$station
3
$use_setup_proc_answer$twelve
$tpicd_answer$vdif_single_thread_per_file_answer$cont_cal_answer$cont_cal_polarity_answer$vsi_align_answer$print$nine
$LIST_DIR/$sched$station.lst



5
0
EOF

    echo Done. >&2
fi
