
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "version.h"

/* Do not edit this file (version.c). It is automatically generated by 
   makever.unx, so edit that file.  Set the version number in version.h. */

const char* rclco_version(void)
{
   static char result[80];

   strcpy(result,RCLCO_VERSION);
   strcat(result,"  (compiled Thu Jun 27 23:12:56 EDT 1996)");

   return(result);
}

