= SNAP Commands
W. E. Himwich, N. R. Vandenberg
FS Operations Manual - Version 10.0.1 - August 10 2021

:sectnums:

<<<

== SNAP Command Descriptions
:sectnums!:

___
<<<

=== bbcnn - baseband converter (VLBA, VLBA4 racks)

==== Syntax

[subs="+quotes"]
....
bbc__nn__=_freq_,_ifsource_,_bwu_,_bwl_,_avper_,_gainmode_,_gainu_,_gainl_
....

==== Response

[subs="+quotes"]
....
bbc__nn__/_freq_,_ifsource_,_bwu_,_bwl_,_avper_,_gainmode_,_gainu_,_gainl_,_lock_,_USBpwr_,_LSBpwr_,_serno_,_err_
....

==== Settable Parameters

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_nn_` | Index number of the BBC, corresponding to its position in the rack, `01` to `14`.  Not all racks have all BBCs.

a| `_freq_` | L.O. frequency in MHz, between `450.00` and `1050.00` inclusive.  Only two digits (0.01 MHz steps) allowed after the decimal point allowed. No default.

a| `_ifsource_` | I.F. input source.  One of `a`, `b`, `c`, `d`.  No default.

a| `_bwu_` | Bandwidth for USB in MHz. One of `0.0625`, `0.125`, `0.25`, `0.5`, `1`, `2`, `4`, `8`, `16`. Default `2`.

a| `_bwl_` | Bandwidth for LSB in MHz. One of `0.0625`, `0.125`, `0.25`, `0.5`, `1`, `2`, `4`, `8`, `16`.  Default `_bwu_`.

a| `_avper_` | Averaging period in seconds for TPI. May be `0`, `1`, `2`, `4`, `10`, `20`, `40`, or `60` seconds. A value of `0` results in `1/80` sec averaging time.  Default `1`.

a| `_gainmode_` | Gain control mode, either `agc` (automatic gain control) or `man` (manual). Use `man` to set gain values with `_gainu_` and `_gainl_` . Default `agc`.

a| `_gainu_` | Gain value for USB in dB. This is a valid parameter only if `_gainmode_` is `man`. May be any value  between `-18.0` dB and `12.0` dB. Not all gains are settable, the lowest available gain greater than `_gainu_` is used.  Step size is linear in voltage. Default is the current USB gain level. The actual gain setting reported as a monitor value may go as low `-99.99` dB.

a| `_gainl_` | Gain value for LSB in dB. This is a valid parameter only if `_gainmode_` is `man`. May be any value  between `-18.0` dB and `12.0` dB. Not all gains are settable, the lowest available gain greater than `_gainl_` is used. Step size is linear in voltage. Default is the current LSB gain level. The actual gain setting reported as a monitor value may go as low `-99.99` dB.
|===

==== Monitor-only Parameters:

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_lock_` | L.O. lock status, `lock` or `unlock`.

a| `_USBpwr_` | Power in upper sideband in counts. Range `0` to `65535`, nominal operating level is `16000`.

a| `_LSBpwr_` | Power in lower sideband in counts. Range `0` to `65535`, nominal operating level is `16000`.

a| `_serno_` | Module serial number, decimal.

a| `_err_` | Module timing error indication, `1pps` or `no_1pps`.
|===

==== Comments:

This command sets up the baseband converters in the VLBA rack.
It is analogous to the Mark IV ``vc__nn__`` commands.

The frequency range is greater than the normal range over which the
BBC is specified to lock (500 to 1000 MHz) to allow for testing.

The averaging period is common to both sidebands. The
averaging period is synchronous with the 1 pps.

The gain mode is common to both sidebands.

Unlike the output of most other commands which have no embedded
blanks, the output for this command is organized in columns so when
multiple commands are used in sequence it is easy to read gains and
power levels.

MCB module functions are available. See <<MCB Module Functions>>
section of the <<snapcmd.adoc#,SNAP Commands>> document.

The power-up setting for the gain control is manual control with a
value of +6 dB. If the IF level is nominal coming in to the BBC then
the operating level for the AGC is +6 dB. Normal setting during an
experiment is `agc`.

To hold the gain at a given value, switch to `man` gain control.  The
gain value will stay at the value it had when the AGC was changed to
`man`. Then use `agc` to return to AGC control. This method is used
for radiometry by the `fivept` and `onoff` commands.

For standard VLBA racks all IFs are available to all BBCs. On
terminals wired like the geodetic (VLBAG) racks, the following table
shows which BBCs have which IF inputs available. All VLBA4 racks are
believed to have VLBAG IF wiring. Essentially all VLBA racks
controlled by the FS are wired in this way.

.Geodetic (VLBAG & VLBA4) Rack BBC-to-IF input availability
[options="header"]
|===
|BBC numbers|IF input channels
|1, 2| A, B, C, D
|3, 4, 5, 6, 7, 8| A, C
|9, 10, 11, 12, 13, 14| B, D
|===

CAUTION: This command does not check whether you have specified a
valid IF source for the BBC.

---
<<<

=== form - Sampler mode (DBBC racks)

==== Syntax

[subs="+quotes"]
....
form=_mode_,_test_
....

==== Response

[subs="+quotes"]
....
form/_mode_,_test_
....

==== Settable Parameters

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_mode_` | Output mode. For DDC: `astro`, `geo`, `wastro`, `test`, `lba`, `astro2`, `astro3`, or `geo2`. For PFB: `flex`, `full`, `full_auto`, or `spol`. No default. See the <<formd,Comments>> for special cases and output pin assignments.

a| `_test_` | DDC only test mode: `0`, `1`, `bin`, `tvg`.  No default. Ignored unless `_mode_` is `test`. Not available for readback for version `v100`.
|===

==== Monitor-only Parameters

None

==== [[formd]]Comments
Special cases:

* DDC personality:

** Version _v100_ does not support monitor for the `_test_` values.

** Versions before _v104_ do not support `astro2`.

** Versions before _v105_ do not support `astro2` on VSI2.

** Only versions with suffixes _e_ and _f_, version _v105_ or greater, support `astro3`.

** Versions with suffixes _e_ and _f_, version _v105_ or greater, use only VSI1 and
support only `astro3` and `_test_` modes.

** Only versions _v106_ greater, support `geo2`.

* PFB personality:

** Only the `flex` mode is supported by the FS. The output is
determined by preceeding `vsi1=...` and `vsi2=...` commands. Although
the other PFB modes are not suppported by the FS, the `form` command
will accept the `full`, `full_auto`, and `spol` modes for "`off-label
use.`"

The following tables give the pin assignments for the DDC modes.

.VSI1 output pin assignments for the DDC modes
[options="header,footer"]
[cols=">m,>m,>m,>m,>m,>m,>m,^m,^m,<m,<m,>m"]
|===
|VSI1|geo|astro|wastro|astro2|astro3|lba|test=0|test=1|test=bin|test=tvg|geo2

| 1 | 1us|  1us|   1us|   1us|  1us |1us|  0   |  1   | BinC0  |  TVG0  | 1us
| 2 | 1um|  1um|   1um|   1um|  1um |1um|  0   |  1   | BinC1  |  TVG1  | 1um
| 3 | 2us|  2us|   2us|   2us|  3us |2us|  0   |  1   | BinC2  |  TVG2  | 2us
| 4 | 2um|  2um|   2um|   2um|  3um |2um|  0   |  1   | BinC3  |  TVG3  | 2um
| 5 | 3us|  3us|   3us|   3us|  5us |5us|  0   |  1   | BinC4  |  TVG4  | 3us
| 6 | 3um|  3um|   3um|   3um|  5um |5um|  0   |  1   | BinC5  |  TVG5  | 3um
| 7 | 4us|  4us|   4us|   4us|  7us |6us|  0   |  1   | BinC6  |  TVG6  | 4us
| 8 | 4um|  4um|   4um|   4um|  7um |6um|  0   |  1   | BinC7  |  TVG7  | 4um
| 9 | 5us|  5us|   5us|   9us|  9us |3us|  0   |  1   | BinC8  |  TVG8  | 5us
|10 | 5um|  5um|   5um|   9um|  9um |3um|  0   |  1   | BinC9  |  TVG9  | 5um
|11 | 6us|  6us|   6us|  10us| 11us |4us|  0   |  1   | BinC10 |  TVG10 | 6us
|12 | 6um|  6um|   6um|  10um| 11um |4um|  0   |  1   | BinC11 |  TVG11 | 6um
|13 | 7us|  7us|   7us|  11us| 13us |7us|  0   |  1   | BinC12 |  TVG12 | 7us
|14 | 7um|  7um|   7um|  11um| 13um |7um|  0   |  1   | BinC13 |  TVG13 | 7um
|15 | 8us|  8us|   8us|  12us| 15us |8us|  0   |  1   | BinC14 |  TVG14 | 8us
|16 | 8um|  8um|   8um|  12um| 15um |8um|  0   |  1   | BinC15 |  TVG15 | 8um
|17 | 1ls|  1ls|   1ls|   1ls|  1ls |1ls|  0   |  1   | BinC16 |  TVG16 | 9us
|18 | 1lm|  1lm|   1lm|   1lm|  1lm |1lm|  0   |  1   | BinC17 |  TVG17 | 9um
|19 | 8ls|  2ls|   2ls|   2ls|  3ls |2ls|  0   |  1   | BinC18 |  TVG18 |10us
|20 | 8lm|  2lm|   2lm|   2lm|  3lm |2lm|  0   |  1   | BinC19 |  TVG19 |10um
|21 | 9us|  3ls|   3ls|   3ls|  5ls |5ls|  0   |  1   | BinC20 |  TVG20 |11us
|22 | 9um|  3lm|   3lm|   3lm|  5lm |5lm|  0   |  1   | BinC21 |  TVG21 |11um
|23 |10us|  4ls|   4ls|   4ls|  7ls |6ls|  0   |  1   | BinC22 |  TVG22 |12us
|24 |10um|  4lm|   4lm|   4lm|  7lm |6lm|  0   |  1   | BinC23 |  TVG23 |12um
|25 |11us|  5ls|   5ls|   9ls|  9ls |3ls|  0   |  1   | BinC24 |  TVG24 |13us
|26 |11um|  5lm|   5lm|   9lm|  9lm |3lm|  0   |  1   | BinC25 |  TVG25 |13um
|27 |12us|  6ls|   6ls|  10ls| 11ls |4ls|  0   |  1   | BinC26 |  TVG26 |14us
|28 |12um|  6lm|   6lm|  10lm| 11lm |4lm|  0   |  1   | BinC27 |  TVG27 |14um
|29 |13us|  7ls|   7ls|  11ls| 13ls |7ls|  0   |  1   | BinC28 |  TVG28 |15us
|30 |13um|  7lm|   7lm|  11lm| 13lm |7lm|  0   |  1   | BinC29 |  TVG29 |15um
|31 |14us|  8ls|   8ls|  12ls| 15lm |8ls|  0   |  1   | BinC30 |  TVG30 |16us
|32 |14um|  8lm|   8lm|  12lm| 15ls |8lm|  0   |  1   | BinC31 |  TVG31 |16um

|VSI1|geo|astro|wastro|astro2|astro3|lba|test=0|test=1|test=bin|test=tvg|geo2
|===

.VSI2 output pin assignments for the DDC modes
[options="header,footer"]
[cols=">m,>m,>m,>m,>m,>m,>m,^m,^m,<m,<m,>m"]
|===
|VSI1|geo|astro|wastro|astro2|astro3|lba|test=0|test=1|test=bin|test=tvg|geo2

| 1 | 1us|  1us|   9us|   1us|      |1us|  0   |  1   | BinC0  |  TVG0  | 1ls
| 2 | 1um|  1um|   9um|   1um|      |1um|  0   |  1   | BinC1  |  TVG1  | 1lm
| 3 | 2us|  2us|  10us|   2us|      |2us|  0   |  1   | BinC2  |  TVG2  | 2ls
| 4 | 2um|  2um|  10um|   2um|      |2um|  0   |  1   | BinC3  |  TVG3  | 2lm
| 5 | 3us|  3us|  11us|   3us|      |5us|  0   |  1   | BinC4  |  TVG4  | 3ls
| 6 | 3um|  3um|  11um|   3um|      |5um|  0   |  1   | BinC5  |  TVG5  | 3lm
| 7 | 4us|  4us|  12us|   4us|      |6us|  0   |  1   | BinC6  |  TVG6  | 4ls
| 8 | 4um|  4um|  12um|   4um|      |6um|  0   |  1   | BinC7  |  TVG7  | 4lm
| 9 | 5us|  5us|  13us|   9us|      |3us|  0   |  1   | BinC8  |  TVG8  | 5ls
|10 | 5um|  5um|  13um|   9um|      |3um|  0   |  1   | BinC9  |  TVG9  | 5lm
|11 | 6us|  6us|  14us|  10us|      |4us|  0   |  1   | BinC10 |  TVG10 | 6ls
|12 | 6um|  6um|  14um|  10um|      |4um|  0   |  1   | BinC11 |  TVG11 | 6lm
|13 | 7us|  7us|  15us|  11us|      |7us|  0   |  1   | BinC12 |  TVG12 | 7ls
|14 | 7um|  7um|  15um|  11um|      |7um|  0   |  1   | BinC13 |  TVG13 | 7lm
|15 | 8us|  8us|  16us|  12us|      |8us|  0   |  1   | BinC14 |  TVG14 | 8ls
|16 | 8um|  8um|  16um|  12um|      |8um|  0   |  1   | BinC15 |  TVG15 | 8lm
|17 | 1ls|  1ls|   9ls|   1ls|      |1ls|  0   |  1   | BinC16 |  TVG16 | 9ls
|18 | 1lm|  1lm|   9lm|   1lm|      |1lm|  0   |  1   | BinC17 |  TVG17 | 9lm
|19 | 8ls|  2ls|  10ls|   2ls|      |2ls|  0   |  1   | BinC18 |  TVG18 |10ls
|20 | 8lm|  2lm|  10lm|   2lm|      |2lm|  0   |  1   | BinC19 |  TVG19 |10lm
|21 | 9us|  3ls|  11ls|   3ls|      |5ls|  0   |  1   | BinC20 |  TVG20 |11ls
|22 | 9um|  3lm|  11lm|   3lm|      |5lm|  0   |  1   | BinC21 |  TVG21 |11lm
|23 |10us|  4ls|  12ls|   4ls|      |6ls|  0   |  1   | BinC22 |  TVG22 |12ls
|24 |10um|  4lm|  12lm|   4lm|      |6lm|  0   |  1   | BinC23 |  TVG23 |12lm
|25 |11us|  5ls|  13ls|   9ls|      |3ls|  0   |  1   | BinC24 |  TVG24 |13ls
|26 |11um|  5lm|  13lm|   9lm|      |3lm|  0   |  1   | BinC25 |  TVG25 |13lm
|27 |12us|  6ls|  14ls|  10ls|      |4ls|  0   |  1   | BinC26 |  TVG26 |14ls
|28 |12um|  6lm|  14lm|  10lm|      |4lm|  0   |  1   | BinC27 |  TVG27 |14lm
|29 |13us|  7ls|  15ls|  11ls|      |7ls|  0   |  1   | BinC28 |  TVG28 |15ls
|30 |13um|  7lm|  15lm|  11lm|      |7lm|  0   |  1   | BinC29 |  TVG29 |15lm
|31 |14us|  8ls|  16ls|  12ls|      |8ls|  0   |  1   | BinC30 |  TVG30 |16ls
|32 |14um|  8lm|  16lm|  12lm|      |8lm|  0   |  1   | BinC31 |  TVG31 |16lm

|VSI1|geo|astro|wastro|astro2|astro3|lba|test=0|test=1|test=bin|test=tvg|geo2
|===

---
<<<

=== lo - LO Configuration

==== Syntax

[subs="+quotes"]
....
lo=_chan_,_freq_,_sb_,_pol_,_pcspace_,_pcoff_
....

==== Response

[subs="+quotes"]
....
lo/_chan_,_freq_,_sb_,_pol_,_pcspace_,_pcoff_
....

[subs="+quotes"]
....
lo/rxg,_chan_,_freq_,_pol_,_file_,_type_,_lo1_,_lo2_,_year_,_month_,_day_,_pol1_,_dpfu1_,_pol2_,_dpfu2_
....

==== Settable Parameters

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_chan_` |  ``lo__X__``, where `_X_` is one of: `1`, `2`, or `3` for Mark III/IV/5 and K-4; `a`, `b`, `c`, or `d` for VLBA/4/5; `1`, `2`, `3`, or `4` for LBA/4; `a`, `b`, `c`, `d`, `2a`, `2b`, `2c`, or `2d` for DBBC; `a0`, `a1`, `b0`, `b1`, `c0`, `c1`, `d0`, or `d1` for RDBE; `a`, `b`, `c`, `d`, `e`, `f`, `g`, or `h` for DBBC3; `1`-`8` for all others. No default. No previous value available.

a| `_freq_` |  LO frequency for this channel, MHz. No default. No previous value available.

a| `_sb_` | Net sideband for this channel, `unknown`, `usb` or `lsb`.  Default is `unknown`.

a| `_pol_` | Polarization for this channel, `unknown`, `rcp`, or `lcp`.  Default is `unknown`.

a| `_pcspace_` |  Spacing of phase-cal rails for this channel, MHz, `unknown`, or `off`. Default is `unknown`.

a| `_pcoff_` | First phase-cal rail frequency for this IF if not equal to the spacing, MHz. Default `0.0`. This offset is specified relative to DC in the IF.
|===

==== Monitor-only Parameters

[frame=none,grid=none]
[cols="1,8"]
|===
a| `rxg` |  literal text, `rxg`, to indicate this line has _.rxg_ file information for the LO `_chan_`
a| `_file_` |  name of the _.rxg_ file that matched the LO value; `undefined` if there was no match, in that case the remaining fields are omitted
a| `_type_` |  LO type from _.rxg_ file: `fixed` or `range`
a| `_lo1_` | first LO value from _.rxg_ file, MHz
a| `_lo2_` | second LO value from _.rxg_ file, if present, MHz
a| `_year_` | the year from the date in the _.rxg_ file
a| `_month_` | the month from the date in the _.rxg_ file
a| `_day_`  |  the day from the date in the _.rxg_ file
a| `_pol1_` |   first polarization from the _.rxg_ file
a| `_dpfu1_` | DPFU of the first polarization in the _.rxg_ file
a| `_pol2_` | second polarization from the _.rxg_ file, if present
a| `_dpfu2_` | DPFU of the second polarization in the _.rxg_ file, if present
|===

==== Comments

This command specifies the characteristics of each IF channel.

It is an information only command in its standard implementation, but
may be implemented as a station command to provide hardware control.

The values should represent the net of effect of all stages of
conversion before the signal enters the VC/BBCs. In other words any
upconverter should be included.  In particular, the values for the
Mark III/IV/5 IF3 channel should include the effect of the internal
IF3 mixer, if it is being used.

The LO frequencies are used by the _pcalr_ and _pcald_ programs to
calculate the frequencies of the phase calibrator tones. _pcalr_ has
not been tested with spacings other than 1 MHz.

The `fivept` and `onoff` commands use the values to look-up the source
flux, antenna gains and Tcal values for the the selected
detectors. The `caltemp` command uses it to look up the T~cal~ values.

For the DBBBC, the second four LOs (`2a`, `2b`, `2c`, `2d`) are not
used for anything but populating the internal LO array.

An `*lo=*` with no parameters clears all LO values.

The monitor form, `*lo*`, shows all defined LO values.

The `lo/rxg,...` line is displayed for each LO as it is set
(commanded) and for each LO in monitor responses. This is intended to
give the operator feedback to verify that the correct version of the
_.rxg_ file is in use. The format of these lines may be adjusted in
future releases based on feedback from users about what is most
useful.

Additionally, when an LO is set, the contents of the _.rxg_ file are
logged, but not displayed, in lines starting with `:rxg_file,`. After
a log is opened, the contents for a given _.rxg_ file are only logged
the first time a matching LO frequency is set.

The `FS_LO_ANTCN_MODE` environment variable can be set to trigger
running antcn in the specified local mode (greater than `99`) to
configure the LO being set. The index of the LO being set (numbering
starting as `0`) is passed as the value of fourth element of the run
parameter array (usually `ip[3]` in C).

In the future, for K4 type 1 rack, the range of LO values should be
`1`-`4`, for K4 type 2 rack, `1`-`16`.

---
<<<
