= SNAP Commands
W. E. Himwich, N. R. Vandenberg
FS Operations Manual - Version 10.0.1 - September 3 2021

:stem: latexmath
:sectnums:

<<<

== SNAP Command Syntax

This manual contains detailed descriptions of the SNAP commands
available in the Field System. Each command is described on a separate
"`page.`" Commands are ordered alphabetically.

Please refer to the *SNAP Language* (#add link#) manual for the
specifications of the language itself, including a description of
control commands and general syntax.

The subsections of this first section contain reference information that
applies to many commands.

=== Command Descriptions

In this manual, each command is described on a separate page. For each
command, the information provided is:

*command - function (equipment)*

[none]
* The command name and a few words that describe its function are
given at the top of each page. If the command is restricted to certain
types of equipment, that information is given in parentheses. For
example, the `bbc__nn__` command is applicable only to VLBA and VLBA4
racks, and the title will include the words "`(VLBA, VLBA4 racks)`".
Many commands don’t have restrictions because they are general FS
commands, such as `schedule` or `echo`. Commands that interact with
the equipment may be general as well. This may be because the command
is in fact implemented for all types of equipment. In fact some
commands that have no restrictions have very limited functionality
beyond some specific equipment configurations. Except for one command:
`pcal`, all commands that are restricted sre restricted by either the
rack or the recorder that is used, but not by both (this will be
corrected for `pcal` at a later date).

+

All of the currently existing rack restrictions are listed below:

+

NEW so far +
DBBC racks +
VLBA, VLBA4 racks +
S2 racks +
DBBC3 racks

+

OLD +
K4K3 racks +
Mark III racks +
Mark III, Mark IV racks +
Mark III, Mark IV, VLBA, VLBA4 racks +
Mark III, Mark IV, all K4 racks +
Mark IV, VLBA4, K4MK4 racks +
Mark IV, VLBA, VLBA4, K4MK4 racks +
VLBA racks +
VLBA, VLBA4 racks +
all K4 racks +
all racks

+

These restrictions all correspond to rack types that can be specified
in _equip.ctl_, except for the restrictions involving K4 racks: all
K4, K4K3, K4MK4, VLBA, and in addition: all racks. For the all K4
restriction, all K4 types are included irrespective of K4 VC sub-type
and including all K4K3 and K4MK4 types irrespective of K4 VC
sub-types.  The K4K3 restriction includes all K4 racks with a K3
formatter, irrespective of K4 VC sub-type. The K4MK4 restriction
includes all K4 racks with a Mark IV formatter, irrespective of K4 VC
sub-type. The VLBA restriction includes both the vlba and vlbag rack
types. The all restriction indicates that this command works for all
racks, i.e., the only rack for which it does not work is none.

+

All of the currently existing recorder restrictions are listed below:

+

NEW so far +

+

OLD +
K4 drives +
Mark III drives +
Mark III, Mark IV drives +
Mark IV drives +
VLBA, VLBA4 drives +
S2 drives +
all drives +
longitudinal drives

+

These restrictions generally include more than one recorder sub-type
that can be specified in _equip.ctl_. The K4 restriction includes all
K4 drive types with and without the DMS. The Mark IV restriction
includes both the mk4 and mk4b sub-types. The VLBA restriction include
vlba, vlba2, and vlbab sub-types. The all restriction indicates that
this command works for all recorders, i.e., the only recorder type for
which it does not work is none. The longitudinal restriction indicates
that it includes all of Mark III, Mark IV, VLBA (including VLBA2), and
VLBA4 recorders. All other restrictions: Mark III, VLBA4, and S2 all
apply to just those simple types.

*SYNTAX*

`command=__list of parameters__`

[none]

* The command syntax is shown first. The command name and the list of
parameters are shown. The various forms of the command are described
in the *COMMENTS* section. All commamnds are lower case. Parameters
are usally lower case as well, but some may not be if they are data
that is paased outside the FS, such as in the `sy=...` and
`antenna=...` commands.

*RESPONSE*

`command/_list of response parameters_`

[none]
* The response (if any) to the command is given with the list of
parameters appearing in the response. Normally the response to a command
has an identical list of parameters to the command itself, followed by
any monitor parameters. All responses to commands are displayed in lower
case letters only.

*SETTABLE PARAMETERS*

[none]
* This part of the page describes each parameter in the "`Syntax`" line that
can be specified by the operator. The allowable range of values for each
parameter is given. The default value, if any, is given. A default value
is obtained by entering a null for a particular parameter. The parameter
value specified in the previous issuing of this command may be obtained
by entering `***` instead of a value. Entering `*?*` as the first parameter
results in a response containing the parameters specified in the most
recent issuance of this command. If any parameter value is found to be
invalid, command interpretation stops at that point and an error message
is generated.

*MONITOR-ONLY PARAMETERS*

[none]
* Each parameter in the "`Response`" that does not appear in the "`Syntax`" is
described in this section. These are parameters that cannot be specified
by the operator, but are monitored or calculated by the Field System.

*COMMENTS*

[none]
* The final section of the page provides further descriptions of the way
in which the command works. These comments often describe the algorithm
that was used in implementing the command, and outline specific
conditions under which the command should be used.

=== Dual Recorder Support

The FS supports sequential recording on two recorders (or drives).With
the exception that K4 and S2 recorders are only supported as recorder
number 1, any and all recorders (including none) can be used either as
recorder 1 or recorder 2. When the FS operates in dual recorder mode,
all commands that refer to recorders come in two forms. They either have
a numeral `1` or a numeral `2` appended to the normal single recorder
version of the command depending on whether they refer to recorder 1 or
recorder 2. The single recorder version of the commands are the ones
documented in the SNAP command manual pages. As an example, if recorder
1 is a VLBA drive and recorder 2 is Mark III drive, the tape command
that refers to recorder 1 would be the VLBA drive tape command with a
`1` appended: `tape1`. Likewise for recorder 2, the tape command would
be the Mark III drive tape command with a `2` appended: `tape2`. For all
tape recorder commands (those that have some drive restriction specified
in their command -function title line of the SNAP command description
page) a numeral at the end distinguishes which drive they refer to.

There are also some rack oriented commands that need to know which
recorder is in use. In addition the _monit<n>_ and _chekr_ programs need to
know which recorder is in use. The `select` command allows the drive
being used for data recording to be specified. drudg does this
automatically for schedules that use two drives. Please note that the
recorder that is not being used for recording can be manipulated by the
operator using the appropriate commands to complete tasks such as
prepassing and mounting the next tape. The `mount1` command is not
available for K4 and or S2 recorders. All other aspects of two recorder
operation with a K4 or S2 recorder as recorder 1 are implemented.

If only one tape drive is used, the drive type of either recorder 1 or
recorder 2 in _equip.ctl_ must be none. In this case all of the
recorder specific commands are used without a numeral suffix and they
refer to the recorder that is not specified as none. This appears as
normal one tape drive operation as used in older versions of the FS,
except that it is possible to select which of two drives will be used
by just changing the _equip.ctl_ file and restarting the FS. Please note
that the `mount__n__` command is only available for dual recorder
configurations, i.e., the version without a numeral appended is never
available.

=== MAT Module Functions

The phrase "`MAT module functions available`" in the *COMMENTS*
section means that the following additional types of parameters may be
used.  This is available for those Mark III modules that have MAT
communications.

[frame=none,grid=none]
[cols="1,4"]
|===
a|`__module__=test/reset` | Issues an MAT reset to this module only.
a|`__module__=alarm`  | Resets the alarm on this module.
|===

=== MCB Module Functions

The following syntax is valid for those commands which state that
"`MCB module functions are available`" in the *COMMENTS* section of
the command description.

[frame=none,grid=none]
[cols="1,4"]
|===
a|`__module__=addr` | Sends the module its base address and length. This
sets the module's MCB address space.

a|`__module__=test` | Checks the module’s address. An error message in
response to this command indicates that the module needs to be sent its
address space.
a|`__module__=addr` | Sends the module its base address and length. This
|===

=== Module and Detector Mnemonics

The Field System makes use of mnemonics for Mark III, Mark IV, S2, VLBA,
and VLBA4 equipment in SNAP commands. No mnemonics are defined for K4
modules or detectors at this time. Displays of mnemonics are always two
characters, but many forms of module names are allowed when entering
commands. This is a convenience for the operator who does not have to
remember the exact two-character mnemonic.

The SNAP commands that pertain to total power radiometry allow the
operator to specify different detectors in the equipment. Detectors are
specified by using a mnemonic. When the Field System displays mnemonics
they are always two characters, but different forms of the detector
names are allowed when entering commands. This is a convenience for the
operator who does not have to remember the exact two-character mnemonic.

Valid mnemonics for modules and detectors are listed in the tables on
the following pages.

The `u5` and `u6` detector mnemonics are used for station specific
detectors that implemented via the _antcn_ program. Currently they are not
completely supported. They may be used in the `fivept` and `onoff`
commands for all rack types (including none). They may also be use in
the `tpi`, `tpical`, `tpzero`, and `tsys__X__` commands for _rack
types other than_ Mark III, Mark IV, VLBA, and VLBA4.

[options="header",]
[cols="<,^,^"]
|===
3+^|Field System Module Mnemonics
|Module |Standard mnemonic | Other allowed mnemonics
(* indicates mnemonics available only when only one drive is defined)

3+|*Mark III/IV modules*
|video converters |`v__n__`, `_n_`=`1`-`f` |`vc__n__`, __n__=`1`-`15`, `1`-`f`
|IF distributor a|`if` a|`ifd`
|formatter a|`fm` a|`form`
|tape transport 1 a|`r1` |`rec1`, `t1`, `tape1`, `rc`\*, `tp`*, `tape`*
|tape transport 2 a|`r2` |`rec2`, `t2`, `tape2`, `rc`\*, `tp`*, `tape`*
|high density heads a|`hd` a|
|high density heads transport 1 a|`h1` a|`hd`*
|high density heads transport 2 a|`h2` a|`hd`*
|S/X receiver a|`rx` |
|IF3 distributor a|`i3` |`if3`,`ifd3`

3+|*S2 modules*
|tape recorder 1 a|`r1` |`rec1`, `t1`, `tape1`, `rc`\*, `tp`*, `tape`*

3+|*VLBA modules*
|baseband converters |`b__n__`, `_n_`=`1-f` |`bc__n__`,
`bbc__n__`, `_n_`=`1`-`15`, `1`-`f`
|IF distributor 1, channels A&B a|`ia` |`ifa`, `ifb`, `ib`, `ifab`
|IF distributor 2, channels C&D a|`ic` |`ifc`, `ifd`, `ic`, `ifcd`
|formatter a|`fm` a|`form`
|tape recorder 1 (except heads) a|`r1` |`rec1`, `t1`, `tape1`, `rc`\*, `tp`*, `tape`*
|tape recorder 2 (except heads) a|`r2` |`rec2`, `t2`, `tape2`, `rc`\*, `tp`*, `tape`*
|high density heads a|`hd` |
|high density heads recorder 1 a|`h1` a|`hd`*
|high density heads recorder 2 a|`h2` a|`hd`*

3+|*Groups of modules*
|all modules which have been set up | a|`all`
|odd video or baseband converters | a|`odd`
|even video or baseband converters | a|`even`
|===

[options="header",]
[cols="<,^,^"]
|===
3+^|Field System Detector Mnemonics

|Detector |Standard mnemonic |Other allowed mnemonics

3+|*Mark III detectors*
|formatter selected VCs a|`formvc` |
|IFs feeding formatter selected VCs a|`formif` |
|video converters |`v__n__`, `_n_`=`1`-`f` |`vc__n__`,
`_n_`=`1`-`15`,`1`-`f`
|IF distributor channel 1 a|`i1` a|`if1`
|IF distributor channel 2 a|`i2` a|`if2`
|IF3 distributor a|`i3` a|`if3`

3+|*S2 detectors*
|none | |

3+|*VLBA detectors*
|formatter selected BBCs a|`formbbc` |
|IFs feeding formatter selected BBCs a|`formif` |
|baseband converters, USB |`__n__u`, `_n_`=`1`-`f` |
`b__n__u`, `bc__n__u`, `bbc__n__u`,
`_n_`=`1`-`15`,`1`-`f`
|baseband converters, LSB |`__n__l`, `_n_`=`1`-`f` |
`b__n__l`, `bc__n__l`, `bbc__n__l`,
`_n_`=`1`-`15`,`1`-`f`
|IF distributor 1, channel A a|`ia` a|`ifa`
|IF distributor 1, channel B a|`ib` a|`ifb`
|IF distributor 2, channel C a|`ic` a|`ifc`
|IF distributor 2, channel D a|`id` a|`ifd`

3+|*Station Dependent Detectors*
|Detector 1 (IF "`chain`" 5) |`u5` |
|Detector 2 (IF "`chain`" 6) |`u6` |

3+|*Groups of detectors*
|all non-station dependent detectors | a|`all`
|all odd video converters | a|`odd`
|all even video converters | a|`even`
|all odd baseband converters USB | a|`oddu`
|all odd baseband converters LSB | a|`oddl`
|all even baseband converters USB | a|`evenu`
|all even baseband converters LSB | a|`evenl`
|===

== On-Line Help

The entire documentation for each command is available as on-line help
in the Field System. The `help` command will display the information for
a specified command on the screen during Field System operations. The
information that is listed is identical to that found on the pages of
this manual.

Refer to the page with the `help` command description.

== SNAP Command Descriptions
:sectnums!:

___
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== active_mk6s - set/display active Mark 6s

==== SYNTAX

[subs="+quotes"]
....
active_mk6s=_list_
....

==== RESPONSE

[subs="+quotes"]
....
active_mk6s/_list_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_list_` | list of comma separated Mark 6 unit designation letters:
`a` or `b`
|===

==== MONITOR-ONLY PARAMETERS

None

==== COMMENTS

The letters may be given in any order. Duplicated letters are ignored.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== active_rdbes - set/display active RDBEs

==== SYNTAX

[subs="+quotes"]
....
active_rdbes=_list_
....

==== RESPONSE

[subs="+quotes"]
....
active_rdbes/_list_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_list_` | list of comma separated RDBE unit designation letters:
`a`, `b`, `c`, or `d`
|===

==== MONITOR-ONLY PARAMETERS

None

==== COMMENTS

The letters may be given in any order. Duplicated letters are ignored.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== agc - gain control mode (S2 racks)

==== SYNTAX

[subs="+quotes"]
....
agc=_gainmode_
....

==== RESPONSE

[subs="+quotes"]
....
agc/_gainmode_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_gainmode_` | Global gain control mode for all BBC. Either `on` or
`off`. No default.  Use `on` to activate automatic gain control on all
BBC.
|===

==== MONITOR-ONLY PARAMETERS

None

==== COMMENTS

This command selects the Automatic Gain Control mode for all BBC on S2
rack. For control over AGC settings for individual BBC, see the
``bbc__n__`` command.

Normal setting during an experiment is `on`.

To hold the gain at a given value, switch to `off` gain control. The BBC
gain value will stay at the value it had when the AGC was changed to
`off`. Then use `on` to return to AGC control. This method is used for
radiometry by _onoff_ and _fivpt_. 


---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== antenna - direct line to the antenna

==== SYNTAX

[subs="+quotes"]
....
antenna=_message1_,_message2_, ...
....

==== RESPONSE

[subs="+quotes"]
....
antenna/_response1_,_response2_, ...
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,6"]
|===
a| `_message<N>_` | messages to be sent to the antenna in the exact
form required by the pointing software. Each `_message<N>_` between
commas will be sent separately. The number of messages is not limited
to nine.
|===

==== MONITOR-ONLY PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,6"]
|===
a| `_response<N>_` | response of the antenna to `_message<N>_`. This
response is either `ack` or an error message sent by the antenna.
|===

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== azeloff - az-el source position offset

==== SYNTAX

[subs="+quotes"]
....
azeloff=_az_,_el_
....

==== RESPONSE

[subs="+quotes"]
....
azeloff/_az_,_el_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_az_` | Offset in azimuth, in numeric angle/degrees format.
Response is in decimal degrees.
a| `_el_` | Offset in elevation, in numeric angle/degrees format.
Response is in decimal degrees.

|===

==== MONITOR-ONLY PARAMETERS

None

==== COMMENTS

If supported by the pointing software, the antenna will move to the
offset position when this command is issued. To return to the
on-source position, issue this command with zero offsets.

These offsets are independent of, and can be used in addition to,
`radecoff` and `xyoff`, if the pointing software supports them.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== bank_check - Mark 5 recorder bank check

==== SYNTAX

[subs="+quotes"]
....
bank_check
....

==== RESPONSE

[subs="+quotes"]
....
bank_check/_VSN_,_serial1_,...,_serial<N>_
....

==== SETTABLE PARAMETERS

None

==== MONITOR-ONLY PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,7"]
|===
a| `_VSN_` | Volume serial number of bank to be recorded.
a| `_serial<N>_` | Serial number of the `_<N>_`-th disk in this volume
|===

==== COMMENTS

This command will check the VSN of the active bank. If it has changed
or hasn't been logged since the current log file was last opened, it
will be logged along with the disk serial numbers.

If the active drive type is `mk5a_bs`, `mk5b_bs`, or `mk5c_bs`, this
command will check the remaining record time on the current bank and
if the next scan (or continuous recording), as set by the previous
`scan_name=...` command plus 200 seconds will not fit, it will switch
banks.

If the bank is switched and the new bank also does not have enough
room for the next scan (or continuous recording) plus 200 seconds,
the bank will be switched again to return to the original bank.

If the bank is switched (once or twice) the VSN and disk serial
numbers in the final bank will be logged unconditionally and the SNAP
procedure `change_pack` will be invoked to prompt the user to change
packs.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== bank_status - Mark 5 recorder bank status

==== SYNTAX

[subs="+quotes"]
....
bank_status
....

==== RESPONSE

[subs="+quotes"]
----
bank_status/_active_,_vsn_,_seconds_,_gb_,_percent_,_ut_

bank_status/_inactive_,_vsn_,_seconds_,_gb_,_percent_,_ut_
----

==== SETTABLE PARAMETERS

None

==== MONITOR-ONLY PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_active_` | the active bank, `a` or `b`
a| `_inactive_` | the inactive bank, `a` or `b`
a| `_VSN_` | Volume serial number of pack in this bank
a| `_seconds_` | remaining seconds of record time in the current mode
a| `_gb_` | remaining gigabytes for pack in this bank
a| `_percent_` | remaining percentage for pack in this bank
a| `_ut_` | the time of the last check for this bank

|===

==== COMMENTS

This command will check the available recording time on the current
bank, switch banks, check the available recording time on the new
bank, and switch back to the original bank. This command is provided
as way to manually update the information used in the _monit5_, `Mark
5 Remaining Capacity`, window for the non-active bank.

This command displays two monitor response records. The first is for
the active bank, the second is for the other bank.

This command takes a few seconds to execute. It should only be
executed when the FS is otherwise quiet. It would potentially be most
useful before starting an experiment to check the status of the disk
modules current installed and to "`seed`" the _monit5_ display.

Please note the time remaining is the available record time not clock
time until the bank will be full. The clock time until the bank will
be full may be significantly different, typically around twice as long
for geodesy, depending on the recording duty cycle.

This command will return a Mark 5 error if any Mark 5 process that
conflicts with a bank switch, such as recording, is active (for Mark
5A, because of a bug in the _Mark5A_ control program, there may be no
error reported).

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== bbcn - baseband converter (S2 racks)


==== SYNTAX

[subs="+quotes"]
....
bbc__n__=_freq_,_ifsource_,_bwu_,_bwl_,_avper_,_agccontrol_
....

[subs="+quotes"]
....
bbc__n__=_state_
....

==== RESPONSE

[subs="+quotes"]
....
bbc__n__:__state__/_freq_,_ifsource_,_bwu_,_bwl_,_avper_,_gainmode_,_gainu_,_gainl_,_lock_,_USBpwr_,_LSBpwr_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,6"]
|===
a| `_n_` | The BBC index number, `1` to `4`. Not all BBCs are available.
a| `_state_` | The frequency switching state number. If frequency switching is not running, use `0`.
a| `_freq_` | L.O. frequency in MHz, between `100.00` and `1000.00`, inclusive. No default.
a| `_ifsource_` | I.F. input source, one of `1`, `2`, `3`, `4`. No default.
a| `_bwu_` | Bandwidth for USB in MHz. One of `0.0625`, `0.125`, `0.25`, `0.5`, `1`, `2`, `4`, `8`, `16`.
a| `_bwl_` | Bandwidth for LSB in MHz. One of `0.0625`, `0.125`, `0.25`, `0.5`, `1`, `2`, `4`, `8`, `16`.
a| `_avper_` | Averaging period for TPI in seconds (`0.01` to `10` seconds).
a| `_agccontrol_` | Turn AGC `on`/`off` control for this BBC.

|===

==== MONITOR-ONLY PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,6"]
|===
a| `_gainu_` | Gain value for USB in dB.
a| `_gainl_` | Gain value for LSB in dB.
a| `_lock_` | L.O. lock status, `lock` or `unlock`.
a| `_USBpwr_` | Power in upper sideband in counts. Range `0` to `300000`, nominal operating is `45000`.
a| `_LSBpwr_` | Power in lower sideband in counts. Range `0` to `300000`, nominal operating is `45000`.
|===

==== COMMENTS

This command sets up the baseband converters in the S2 rack. This command is
analogous to the VLBA ``bbc__nn__``
and Mark III/IV ``vc__nn__`` commands.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== bbcnn - digital baseband converter (DBBC racks)

==== SYNTAX

[subs="+quotes"]
....
bbc__nn__=_freq_,_IF_,_bw_,_tpint_
....

==== RESPONSE

[subs="+quotes"]
....
bbc__nn__/_freq_,_IF_,_bw_,_tpint_,_gainctrl_,_gainU_,_gainL_,_tpUcalon_,_tpLcalon_,_tpUcaloff_,_tpLcaloff_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,7"]
|===

a| `_nn_` | Index number of the BBC, corresponding to its position in
the rack, `01` to `16`. Not all racks have all BBCs.

a| `_freq_` | L.O. frequency in MHz, between `0.000001`-`2200`
inclusive.  Some DBBC versions do not support frequncies `2048` and
above. No default. This frequency may be specified to 1 Hz precison,
i.e. 6 places after the decimal point.

a| `_IF_` | I.F. input source, one of `a`, `b`, `c`, `d`. Defaults to
`a` for converters `01`-`04`, `b` for `05`-`08`, `c` for `09`-`12`,
and `d` for `13`-`16`.  This parameter does not affect equipment
set-up, but does affect the center frequency, Tcal, and FWHM values for
Tsys, pointing, and SEFD measurements.

a| `_bw_` | Sideband bandwidth in MHz. One of `2`, `4`, `8`, `16`,
`32`, or `64`. Default `8`.

a| `_avper_` | Averaging period in seconds for TPI. Positive integers
`1`-`60` allowed, Default is `1`. The averaging period is common to
both upper and lower sideband. The averaging period is synchronous
with the 1 pps.

|===

==== MONITOR-ONLY PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,7"]
|===

a| `_gainctrl_` | Gain control mode, either `agc` or `man`. The gain
mode is common to both sidebands.

a| `_gainU_` | Gain value for USB in steps, `0`-`255`.

a| `_gainL_` | Gain value for LSB in steps, `0`-`255`.

a| `_tpUcalon_` | Power in upper sideband in counts with the cal on
for synchronous radiometry or TP for non-synchronous. Range `0` to
`65535`. See the <<comments_bbcnn_j,*COMMENTS*>> for information
about the nominal operating level.

a| `_tpLcalon_` | Power in lower sideband in counts with the cal on
for synchronous radiometry or TP for non-synchronous. Range `0` to
`65535`. See the <<comments_bbcnn_j,*COMMENTS*>> for information
about the nominal operating level.

a| `_tpUcaloff_` | Power in upper sideband in counts with the cal off
for synchronous radiometry or `0` for non-synchronous. Range `0` to
`65535`. See the <<comments_bbcnn_j,*COMMENTS*>> for information
about the nominal operating level.

a| `_tpLcaloff_` | Power in lower sideband in counts with the cal off
for synchronous radiometry or `0` for non-synchronous. Range `0` to
`65535`. See the <<comments_bbcnn_j,*COMMENTS*>> for information
about the nominal operating level.

|===

==== [[comments_bbcnn_j]] COMMENTS

This command sets up the digital channel converters in the DBBC3 rack.
This command is analogous to the Mark IV ``VC__nn__`` and VLBA and
DBBC ``bbc__nn__`` commands.

Unlike the output of most other commands which have no embedded
blanks, the output for this command is organized in columns so when
multiple comands are used in sequence it is easy to read gains and
power levels.

The IF inputs are typically hardwired so that channels `01`-`04` get
IF `A`, `05`-`08` get IF `B`, `09`-`12` get IF `C`, and `13`-`16` get
IF `D`. For racks with three IFs, `09`-`16` typically get IF `c`.

The `_IF_` selection parameter does not affect the equipment
configuration. It does affect center frequency, Tcal, and FWHM values
for Tsys, pointing, and SEFD measurements.

CAUTION: This command does not check whether you have specified a
valid IF source for the channel.

`_gainU_` and `_gainL_` can be controlled with the `bbc_gain` command
for DDC versions` 103` and higher.

The nominal operating level for TP counts depends on the configuration
of the system.  If firmware version `v103` or later is in use, the
level is set by the `bbc_gain` command, typically `16000` in `agc`
mode.  For earlier firmware versions, the operating level is arbitrary
depending on the target levels of the IF modules, but can range from a
few hundred to a several thousand.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== bbcnn - baseband converter (VLBA, VLBA4 racks)

==== SYNTAX

[subs="+quotes"]
....
bbc__nn__=_freq_,_ifsource_,_bwu_,_bwl_,_avper_,_gainmode_,_gainu_,_gainl_
....

==== RESPONSE

[subs="+quotes"]
....
bbc__nn__/_freq_,_ifsource_,_bwu_,_bwl_,_avper_,_gainmode_,_gainu_,_gainl_,_lock_,_USBpwr_,_LSBpwr_,_serno_,_err_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_nn_` | Index number of the BBC, corresponding to its position in the rack, `01` to `14`.  Not all racks have all BBCs.

a| `_freq_` | L.O. frequency in MHz, between `450.00` and `1050.00` inclusive.  Only two digits (0.01 MHz steps) allowed after the decimal point allowed. No default.

a| `_ifsource_` | I.F. input source.  One of `a`, `b`, `c`, `d`.  No default.

a| `_bwu_` | Bandwidth for USB in MHz. One of `0.0625`, `0.125`, `0.25`, `0.5`, `1`, `2`, `4`, `8`, `16`. Default `2`.

a| `_bwl_` | Bandwidth for LSB in MHz. One of `0.0625`, `0.125`, `0.25`, `0.5`, `1`, `2`, `4`, `8`, `16`.  Default `_bwu_`.

a| `_avper_` | Averaging period in seconds for TPI. May be `0`, `1`, `2`, `4`, `10`, `20`, `40`, or `60` seconds. A value of `0` results in `1/80` sec averaging time.  Default `1`.

a| `_gainmode_` | Gain control mode, either `agc` (automatic gain control) or `man` (manual). Use `man` to set gain values with `_gainu_` and `_gainl_` . Default `agc`.

a| `_gainu_` | Gain value for USB in dB. This is a valid parameter only if `_gainmode_` is `man`. May be any value  between `-18.0` dB and `12.0` dB. Not all gains are settable, the lowest available gain greater than `_gainu_` is used.  Step size is linear in voltage. Default is the current USB gain level. The actual gain setting reported as a monitor value may go as low `-99.99` dB.

a| `_gainl_` | Gain value for LSB in dB. This is a valid parameter only if `_gainmode_` is `man`. May be any value  between `-18.0` dB and `12.0` dB. Not all gains are settable, the lowest available gain greater than `_gainl_` is used. Step size is linear in voltage. Default is the current LSB gain level. The actual gain setting reported as a monitor value may go as low `-99.99` dB.
|===

==== MONITOR-ONLY PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_lock_` | L.O. lock status, `lock` or `unlock`.

a| `_USBpwr_` | Power in upper sideband in counts. Range `0` to `65535`, nominal operating level is `16000`.

a| `_LSBpwr_` | Power in lower sideband in counts. Range `0` to `65535`, nominal operating level is `16000`.

a| `_serno_` | Module serial number, decimal.

a| `_err_` | Module timing error indication, `1pps` or `no_1pps`.
|===

==== COMMENTS

This command sets up the baseband converters in the VLBA rack.
It is analogous to the Mark IV ``vc__nn__`` commands.

The frequency range is greater than the normal range over which the
BBC is specified to lock (500 to 1000 MHz) to allow for testing.

The averaging period is common to both sidebands. The
averaging period is synchronous with the 1 pps.

The gain mode is common to both sidebands.

Unlike the output of most other commands which have no embedded
blanks, the output for this command is organized in columns so when
multiple commands are used in sequence it is easy to read gains and
power levels.

MCB module functions are available. See <<MCB Module Functions>>
section of the <<snapcmd.adoc#,SNAP Commands>> document.

The power-up setting for the gain control is manual control with a
value of +6 dB. If the IF level is nominal coming in to the BBC then
the operating level for the AGC is +6 dB. Normal setting during an
experiment is `agc`.

To hold the gain at a given value, switch to `man` gain control.  The
gain value will stay at the value it had when the AGC was changed to
`man`. Then use `agc` to return to AGC control. This method is used
for radiometry by the `fivept` and `onoff` commands.

For standard VLBA racks all IFs are available to all BBCs. On
terminals wired like the geodetic (VLBAG) racks, the following table
shows which BBCs have which IF inputs available. All VLBA4 racks are
believed to have VLBAG IF wiring. Essentially all VLBA racks
controlled by the FS are wired in this way.

.Geodetic (VLBAG & VLBA4) Rack BBC-to-IF input availability
[options="header"]
|===
|BBC numbers|IF input channels
|1, 2| A, B, C, D
|3, 4, 5, 6, 7, 8| A, C
|9, 10, 11, 12, 13, 14| B, D
|===

CAUTION: This command does not check whether you have specified a
valid IF source for the BBC.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== bbcnnn - digital baseband converter (DBBC3 racks)

==== SYNTAX

[subs="+quotes"]
....
bbc__nnn__=_freq_,_IF_,_bw_,_tpint_
....

==== RESPONSE

[subs="+quotes"]
....
bbc__nnn__/_freq_,_IF_,_bw_,_tpint_,_gainctrl_,_gainU_,_gainL_,_tpUcalon_,_tpLcalon_,_tpUcaloff_,_tpLcaloff_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,7"]
|===

a| `_nnn_` | Index number of the BBC, corresponding to its position in
the rack, `001` to `128`. Not all racks have all BBCs. See the
<<comments_bbcnnn_j,*COMMENTS*>> for the available BBCs depending on
BBCs/IF and IFs in rack.

a| `_freq_` | L.O. frequency in MHz, `0`-`4096`, inclusive. It may be
specified to 1 Hz precision, i.e., 6 places after the decimal point,
e.g., `1000.000001` for 1 Hz above 1 GHz.

a| `_IF_` | I.F. input source, one of `a`, `b`, `c`, `d`, `e`, `f`,
`g`, or `h`. See the <<comments_bbcnnn_j,*COMMENTS*>> for the default
values. This parameter does not affect equipment set-up, but does
affect the center frequency, Tcal, and FWHM values for Tsys, pointing,
and SEFD measurements.

a| `_bw_` | Sideband bandwidth in MHz. One of `2`, `4`, `8`, `16`,
`32`, `64`, or `128`. Default `32`. For monitor, a value of `0` maybe
displayed if the BBC has not been configured by the FS and the DBBC3
boot configuration.

a| `_avper_` | Averaging period in seconds for TPI. Positive integers
`1`-`60` allowed. Default is `1`. The averaging period is common to
both upper and lower sidebands. The averaging period is synchronous
with the 1 pps.

|===

==== MONITOR-ONLY PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,7"]
|===

a| `_gainctrl_` | Gain control mode, either `agc` or `man`. The gain
mode is common to both sidebands.

a| `_gainU_` | Gain value for USB in steps, `0`-`255`.

a| `_gainL_` | Gain value for LSB in steps, `0`-`255`.

a| `_tpUcalon_` | Power in upper sideband in counts with the cal on
for synchronous radiometry or TP for non-synchronous. Range `0` to
`65535`. See the <<comments_bbcnnn_j,*COMMENTS*>> for information
about the nominal operating level.

a| `_tpLcalon_` | Power in lower sideband in counts with the cal on
for synchronous radiometry or TP for non-synchronous. Range `0` to
`65535`. See the <<comments_bbcnnn_j,*COMMENTS*>> for information
about the nominal operating level.

a| `_tpUcaloff_` | Power in upper sideband in counts with the cal off
for synchronous radiometry or `0` for non-synchronous. Range `0` to
`65535`. See the <<comments_bbcnnn_j,*COMMENTS*>> for information
about the nominal operating level.

a| `_tpLcaloff_` | Power in lower sideband in counts with the cal off
for synchronous radiometry or `0` for non-synchronous. Range `0` to
`65535`. See the <<comments_bbcnnn_j,*COMMENTS*>> for information
about the nominal operating level.

|===

==== [[comments_bbcnnn_j]] COMMENTS

This command sets up the digital channel converters in the DBBC3 rack.
This command is analogous to the Mark IV ``VC__nn__`` and VLBA and
DBBC ``bbc__nn__`` commands.

Unlike the output of most other commands which have no embedded
blanks, the output for this command is organized in columns so when
multiple commands are used in sequence it is easy to read gains and
power levels.

The `_IF_` selection parameter does not affect the equipment
configuration. It does affect center frequency, Tcal, and FWHM values
for Tsys, pointing, and SEFD measurements.

CAUTION: This command does not check whether you have specified a
valid `_IF_` source for the channel.

`_gainU_` and `_gainL_` can be controlled with the `bbc_gain` command

The nominal operating level for TP counts depends on the configuration
of the system. The level is set by the `bbc_gain` command, typically
`16000` in `agc` mode.

.Available BBCs depending on available BBCs/IF and IFs
[options="header"]
|===
>| BBCs/IF ^| IFA ^| IFB ^| IFC ^|IFD ^| IFE ^| IFF ^| IFG  ^| IFH
>| 8 | `001`-`008` | `009`-`016` | `017`-`024` | `025`-`032` | `033`-`040` | `041`-`048` | `049`-`056` | `057`-`064`
>| 12 | `001`-`008`, `065`-`068` | `009`-`016`, `073`-`076` | `017`-`024`, `081`-`084` | `025`-`032`, `089`-`092` | `033`-`040`, `097`-`100` | `041`-`048`, `105`-`108` | `049`-`056`, `113`-`116` | `057`-`064`, `121`-`124`
>| 16 | `001`-`008`, `065`-`072` | `009`-`016`, `073`-`080` | `017`-`024`, `081`-`088` | `025`-`032`, `089`-`096` | `033`-`040`, `097`-`104` | `041`-`048`, `105`-`112` | `049`-`056`, `113`-`120` | `057`-`064`, `121`-`128`
|===

.Default _IF_ values
[options="header"]
[cols="^,^"]
|===
| Converters | _IF_
|`001`-`008`, `065`-`072`|`a`
|`009`-`016`, `073`-`080`|`b`
|`017`-`024`, `081`-`088`|`c`
|`025`-`032`, `089`-`096`|`d`
|`033`-`040`, `097`-`104`|`e`
|`041`-`048`, `105`-`112`|`f`
|`049`-`056`, `113`-`120`|`g`
|`057`-`064`, `121`-`128`|`h`
|===

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== form - Sampler mode (DBBC racks)

==== SYNTAX

[subs="+quotes"]
....
form=_mode_,_test_
....

==== RESPONSE

[subs="+quotes"]
....
form/_mode_,_test_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===

a| `_mode_` | Output mode. For DDC: `astro`, `geo`, `wastro`, `test`,
`lba`, `astro2`, `astro3`, or `geo2`. For PFB: `flex`, `full`,
`full_auto`, or `spol`. No default. See the
<<comments_form_d,*COMMENTS*>> for special cases and output pin
assignments.

a| `_test_` | DDC only test mode: `0`, `1`, `bin`, `tvg`.  No default. Ignored unless `_mode_` is `test`. Not available for readback for version `v100`.
|===

==== MONITOR-ONLY PARAMETERS

None

==== [[comments_form_d]]COMMENTS
Special cases:

* DDC personality:

** Version _v100_ does not support monitor for the `_test_` values.

** Versions before _v104_ do not support `astro2`.

** Versions before _v105_ do not support `astro2` on VSI2.

** Only versions with suffixes _e_ and _f_, version _v105_ or greater, support `astro3`.

** Versions with suffixes _e_ and _f_, version _v105_ or greater, use only VSI1 and
support only `astro3` and `_test_` modes.

** Only versions _v106_ greater, support `geo2`.

* PFB personality:

** Only the `flex` mode is supported by the FS. The output is
determined by preceeding `vsi1=...` and `vsi2=...` commands. Although
the other PFB modes are not suppported by the FS, the `form` command
will accept the `full`, `full_auto`, and `spol` modes for "`off-label
use.`"

The following tables give the pin assignments for the DDC modes.

.VSI1 output pin assignments for the DDC modes
[options="header,footer"]
[cols=">m,>m,>m,>m,>m,>m,>m,^m,^m,<m,<m,>m"]
|===
|VSI1|geo|astro|wastro|astro2|astro3|lba|test=0|test=1|test=bin|test=tvg|geo2

| 1 | 1us|  1us|   1us|   1us|  1us |1us|  0   |  1   | BinC0  |  TVG0  | 1us
| 2 | 1um|  1um|   1um|   1um|  1um |1um|  0   |  1   | BinC1  |  TVG1  | 1um
| 3 | 2us|  2us|   2us|   2us|  3us |2us|  0   |  1   | BinC2  |  TVG2  | 2us
| 4 | 2um|  2um|   2um|   2um|  3um |2um|  0   |  1   | BinC3  |  TVG3  | 2um
| 5 | 3us|  3us|   3us|   3us|  5us |5us|  0   |  1   | BinC4  |  TVG4  | 3us
| 6 | 3um|  3um|   3um|   3um|  5um |5um|  0   |  1   | BinC5  |  TVG5  | 3um
| 7 | 4us|  4us|   4us|   4us|  7us |6us|  0   |  1   | BinC6  |  TVG6  | 4us
| 8 | 4um|  4um|   4um|   4um|  7um |6um|  0   |  1   | BinC7  |  TVG7  | 4um
| 9 | 5us|  5us|   5us|   9us|  9us |3us|  0   |  1   | BinC8  |  TVG8  | 5us
|10 | 5um|  5um|   5um|   9um|  9um |3um|  0   |  1   | BinC9  |  TVG9  | 5um
|11 | 6us|  6us|   6us|  10us| 11us |4us|  0   |  1   | BinC10 |  TVG10 | 6us
|12 | 6um|  6um|   6um|  10um| 11um |4um|  0   |  1   | BinC11 |  TVG11 | 6um
|13 | 7us|  7us|   7us|  11us| 13us |7us|  0   |  1   | BinC12 |  TVG12 | 7us
|14 | 7um|  7um|   7um|  11um| 13um |7um|  0   |  1   | BinC13 |  TVG13 | 7um
|15 | 8us|  8us|   8us|  12us| 15us |8us|  0   |  1   | BinC14 |  TVG14 | 8us
|16 | 8um|  8um|   8um|  12um| 15um |8um|  0   |  1   | BinC15 |  TVG15 | 8um
|17 | 1ls|  1ls|   1ls|   1ls|  1ls |1ls|  0   |  1   | BinC16 |  TVG16 | 9us
|18 | 1lm|  1lm|   1lm|   1lm|  1lm |1lm|  0   |  1   | BinC17 |  TVG17 | 9um
|19 | 8ls|  2ls|   2ls|   2ls|  3ls |2ls|  0   |  1   | BinC18 |  TVG18 |10us
|20 | 8lm|  2lm|   2lm|   2lm|  3lm |2lm|  0   |  1   | BinC19 |  TVG19 |10um
|21 | 9us|  3ls|   3ls|   3ls|  5ls |5ls|  0   |  1   | BinC20 |  TVG20 |11us
|22 | 9um|  3lm|   3lm|   3lm|  5lm |5lm|  0   |  1   | BinC21 |  TVG21 |11um
|23 |10us|  4ls|   4ls|   4ls|  7ls |6ls|  0   |  1   | BinC22 |  TVG22 |12us
|24 |10um|  4lm|   4lm|   4lm|  7lm |6lm|  0   |  1   | BinC23 |  TVG23 |12um
|25 |11us|  5ls|   5ls|   9ls|  9ls |3ls|  0   |  1   | BinC24 |  TVG24 |13us
|26 |11um|  5lm|   5lm|   9lm|  9lm |3lm|  0   |  1   | BinC25 |  TVG25 |13um
|27 |12us|  6ls|   6ls|  10ls| 11ls |4ls|  0   |  1   | BinC26 |  TVG26 |14us
|28 |12um|  6lm|   6lm|  10lm| 11lm |4lm|  0   |  1   | BinC27 |  TVG27 |14um
|29 |13us|  7ls|   7ls|  11ls| 13ls |7ls|  0   |  1   | BinC28 |  TVG28 |15us
|30 |13um|  7lm|   7lm|  11lm| 13lm |7lm|  0   |  1   | BinC29 |  TVG29 |15um
|31 |14us|  8ls|   8ls|  12ls| 15lm |8ls|  0   |  1   | BinC30 |  TVG30 |16us
|32 |14um|  8lm|   8lm|  12lm| 15ls |8lm|  0   |  1   | BinC31 |  TVG31 |16um

|VSI1|geo|astro|wastro|astro2|astro3|lba|test=0|test=1|test=bin|test=tvg|geo2
|===

.VSI2 output pin assignments for the DDC modes
[options="header,footer"]
[cols=">m,>m,>m,>m,>m,>m,>m,^m,^m,<m,<m,>m"]
|===
|VSI1|geo|astro|wastro|astro2|astro3|lba|test=0|test=1|test=bin|test=tvg|geo2

| 1 | 1us|  1us|   9us|   1us|      |1us|  0   |  1   | BinC0  |  TVG0  | 1ls
| 2 | 1um|  1um|   9um|   1um|      |1um|  0   |  1   | BinC1  |  TVG1  | 1lm
| 3 | 2us|  2us|  10us|   2us|      |2us|  0   |  1   | BinC2  |  TVG2  | 2ls
| 4 | 2um|  2um|  10um|   2um|      |2um|  0   |  1   | BinC3  |  TVG3  | 2lm
| 5 | 3us|  3us|  11us|   3us|      |5us|  0   |  1   | BinC4  |  TVG4  | 3ls
| 6 | 3um|  3um|  11um|   3um|      |5um|  0   |  1   | BinC5  |  TVG5  | 3lm
| 7 | 4us|  4us|  12us|   4us|      |6us|  0   |  1   | BinC6  |  TVG6  | 4ls
| 8 | 4um|  4um|  12um|   4um|      |6um|  0   |  1   | BinC7  |  TVG7  | 4lm
| 9 | 5us|  5us|  13us|   9us|      |3us|  0   |  1   | BinC8  |  TVG8  | 5ls
|10 | 5um|  5um|  13um|   9um|      |3um|  0   |  1   | BinC9  |  TVG9  | 5lm
|11 | 6us|  6us|  14us|  10us|      |4us|  0   |  1   | BinC10 |  TVG10 | 6ls
|12 | 6um|  6um|  14um|  10um|      |4um|  0   |  1   | BinC11 |  TVG11 | 6lm
|13 | 7us|  7us|  15us|  11us|      |7us|  0   |  1   | BinC12 |  TVG12 | 7ls
|14 | 7um|  7um|  15um|  11um|      |7um|  0   |  1   | BinC13 |  TVG13 | 7lm
|15 | 8us|  8us|  16us|  12us|      |8us|  0   |  1   | BinC14 |  TVG14 | 8ls
|16 | 8um|  8um|  16um|  12um|      |8um|  0   |  1   | BinC15 |  TVG15 | 8lm
|17 | 1ls|  1ls|   9ls|   1ls|      |1ls|  0   |  1   | BinC16 |  TVG16 | 9ls
|18 | 1lm|  1lm|   9lm|   1lm|      |1lm|  0   |  1   | BinC17 |  TVG17 | 9lm
|19 | 8ls|  2ls|  10ls|   2ls|      |2ls|  0   |  1   | BinC18 |  TVG18 |10ls
|20 | 8lm|  2lm|  10lm|   2lm|      |2lm|  0   |  1   | BinC19 |  TVG19 |10lm
|21 | 9us|  3ls|  11ls|   3ls|      |5ls|  0   |  1   | BinC20 |  TVG20 |11ls
|22 | 9um|  3lm|  11lm|   3lm|      |5lm|  0   |  1   | BinC21 |  TVG21 |11lm
|23 |10us|  4ls|  12ls|   4ls|      |6ls|  0   |  1   | BinC22 |  TVG22 |12ls
|24 |10um|  4lm|  12lm|   4lm|      |6lm|  0   |  1   | BinC23 |  TVG23 |12lm
|25 |11us|  5ls|  13ls|   9ls|      |3ls|  0   |  1   | BinC24 |  TVG24 |13ls
|26 |11um|  5lm|  13lm|   9lm|      |3lm|  0   |  1   | BinC25 |  TVG25 |13lm
|27 |12us|  6ls|  14ls|  10ls|      |4ls|  0   |  1   | BinC26 |  TVG26 |14ls
|28 |12um|  6lm|  14lm|  10lm|      |4lm|  0   |  1   | BinC27 |  TVG27 |14lm
|29 |13us|  7ls|  15ls|  11ls|      |7ls|  0   |  1   | BinC28 |  TVG28 |15ls
|30 |13um|  7lm|  15lm|  11lm|      |7lm|  0   |  1   | BinC29 |  TVG29 |15lm
|31 |14us|  8ls|  16ls|  12ls|      |8ls|  0   |  1   | BinC30 |  TVG30 |16ls
|32 |14um|  8lm|  16lm|  12lm|      |8lm|  0   |  1   | BinC31 |  TVG31 |16lm

|VSI1|geo|astro|wastro|astro2|astro3|lba|test=0|test=1|test=bin|test=tvg|geo2
|===

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== help - display on-line help information

==== SYNTAX

[subs="+quotes"]
....
help=_command_
....

[subs="+quotes"]
....
?=_command_
....

==== RESPONSE

Displays information in a terminal window

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_command_` | The name of any SNAP command
|===

==== COMMENTS

This command displays available information on the specified SNAP
command. Either `help` or `?` may be used. Typing `*help*` or `*?*`
alone gives help on `help`. The help information is essentially the
listing of the manual page for the SNAP command. If no help is
available for a command, a message to that effect will be displayed in
the log output window. You will also receive the message if you
request help for a command that is not defined for your equipment.

The Field System `help` command opens a new _xterm_ window and uses
the _less_ pager, or the _man_ command (which also uses _less_) to
display the requested help information one screen-full at a time. At
the bottom of the window you will see a prompt in inverse video that
includes the name of the file being displayed (which you can ignore).
If you want to continue the listing, press the space bar and the next
screen-full will be displayed. To exit from the command, type the
letter `*q*` (not echoed on the screen). The window will persist until
`*q*` is pressed or it is closed otherwise. It being open will _not_
block the FS from executing.

When you see `(END)` in inverse video in the prompt at the bottom of
the screen, you have reached the end of the help information on this
topic. For help with _less_, type the letter `*h*` to the prompt. All
the features of _less_ are available, including text searches and
scrolling back. In some cases statistics about where in the file the
current screen-full comes from may be displayed in the prompt. In some
cases, _less_ will display only a colon `:` prompt.

Help files for different equipment configurations are distinguished by
the three characters in the file extension for the type of hardware.
The first character is for the type of rack, the second is for the
type of recorder 1, and the third is type of recorder 2. The table
farther below, <<families,_Equipment families for help file extension
characters_>>, gives the extension character correspondence to
different equipment _families_. Following tables, <<racks,_Rack
families for equip.ctl entries_>> give the correspondence of rack
families to rack entires in _equip.ctl_; <<recorders,_Recorder
families for equip.ctl entries_>>, for recorder families.

Files that include _.man._ between the command name and the equipment
extension are assumed to be in _troff_ format and are displayed using
the _man_ command. The output is formatted for the width of the
window. Unfortunately, the formatting does not adjust when the window
is re-sized. However, output that may overwrap the width of the
window, code blocks and tables and particular, can be unwrapped by
widening the window.

The help information is kept in files in the directory
_/usr2/fs/help_, one file per command. Local help files are found in
_/usr2/st/help_, which override those in _/usr2/fs/help_. Within
either _/usr2/st/help_ or _/usr2/fs/help_, _.man._ files take
precedence of non-_.man._ files.

.Equipment families for help file extension characters
[#families]
[cols="1,4,4"]
|===
| Character |Rack families|Recorder families

a| `_` a| All including `none`             a| All including `none`
a| `+` |                                   a| With two recorders,
allows a match for the other, see the table
<<recorder_matching,_Details of recorder matching_>> below
a| `3` | K4K3                              |
a| `m` | Mark III                          | Mark III
a| `n` | LBA4, Mark III/IV                 | Mark III, Mark IV
a| `e` | LBA4, Mark III/IV, VLBA, VLBA4, DBBC    |
a| `f` | LBA4, Mark III/IV, all K4         |
a| `4` | Mark IV                           | Mark IV
a| `s` | S2                                | S2
a| `g` | LBA4, Mark IV, VLBA/4, K4MK4      |
a| `h` | LBA4, Mark IV, VLBA4, K4MK4       |
a| `i` | Mark IV, VLBA/4, K4MK4            |
a| `v` | VLBA                              |
a| `w` | VLBA, VLBA4                      | VLBA, VLBA4
a| `k` | all K4                            | K4
a| `l` | LBA, LBA4                         | longitudinal
a| `d` | DBBC                             |
a| `a` a| Any, not includng `none`       a| Any, not including `none`
a| `j` | DBBC3                             |
|===

.Rack families for equip.ctl entries
[#racks]
[cols="1,4"]
|===
| Rack family | Rack _equip.ctl_ entries

| Mark III a| `mk3`
| VLBA     | `vlba`, `vlbag`
| Mark IV a| `mk4`
| VLBA4    | `vlba4`, `vlba5`, `vlbac`, `cdas`
| K4 | `K41`, `k41u`, `k42`, `k42a`, `k42bu`, `k42c`
| K4K3  | `K41/k3`, `k41u/k3`, `k42/k3`, `k42a/k3`, `k42bu/k3`
| K4MK4 | `K41/mk4`, `k41u/mk4`, `k42/mk4`, `k42a/mk4`, `k42bu/mk4`, `k4c/mk4`
| all K4 | all of the K4, K4K3, and K4MK4 rack families
| LBA   a| `lba`
| LBA4  a| `lba4`
| S2    a| `s2`
| Mark 5 a| `mk5`
| DBBC  | `dbbc_ddc`, `dbbc_ddc/fila10g`, `dbbc_pfb`, `dbbc_pfb/fila10g`
| RDBE  a| `rdbe`
| DBBC3 a| `dbbc3`
| none  a| `none`
|===

.Recorder families for equip.ctl entries
[#recorders]
[cols="1,4"]
|===
| Recorder family | Recorder _equip.ctl_ entries

| Mark III a| `mk3`
| VLBA     | `vlba`, `vlba2`, `vlbab`
| Mark IV | `mk4`, `mk4b`
| VLBA4    | `vlba4`, `vlba42`, `vlbab`
| K4 | `k41`, `k42`, `k41/dms`, `k42/dms`
| S2    a| `s2`
| Mark 5 | `mk5a`, `mk5b`, `mk5a_bs`, `mk5b_bs`, `mk5c`, `mk5c_bs`, `flexbuff`
| Mark 6 a| `mk6`
| longitudinal | all of the Mark III, Mark IV, VLBA, and VLBA4 recorder families
| none | `none`
|===

.Details of recorder matching (see *NOTE* below for explanation)
[#recorder_matching]
[options="header"]
|===
| Character for recorder 1 |Character for recorder 2| _equip.ctl_ recorder 1| _equip.ctl_  recorder 2
a| `+++++++` a| Any a| Not `none` a| Not `none`
a| Any a| `+++++++` a| Not `none` a| Not `none`
a| Not `+++++++` a| Not `+++++++` a| `none` a| Any
a| Not `+++++++` a| Not `+++++++` a| Any a| `none`
|===

NOTE: Regarding the table <<recorder_matching,_Details of recorder
matching_>> above: If there are two recorders defined, a `pass:[+]`
will match if the character for the other recorder matches. If there
is only one recorder defined, a `pass:[+]` will not match in either
position.


---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== lo - LO Configuration

==== SYNTAX

[subs="+quotes"]
....
lo=_chan_,_freq_,_sb_,_pol_,_pcspace_,_pcoff_
....

==== RESPONSE

[subs="+quotes"]
....
lo/_chan_,_freq_,_sb_,_pol_,_pcspace_,_pcoff_
....

[subs="+quotes"]
....
lo/rxg,_chan_,_freq_,_pol_,_file_,_type_,_lo1_,_lo2_,_year_,_month_,_day_,_pol1_,_dpfu1_,_pol2_,_dpfu2_
....

==== SETTABLE PARAMETERS

[%noheader]
[frame=none,grid=none]
[cols="1,8"]
|===
a| `_chan_` |  ``lo__X__``, where `_X_` is one of: `1`, `2`, or `3` for Mark III/IV/5 and K-4; `a`, `b`, `c`, or `d` for VLBA/4/5; `1`, `2`, `3`, or `4` for LBA/4; `a`, `b`, `c`, `d`, `2a`, `2b`, `2c`, or `2d` for DBBC; `a0`, `a1`, `b0`, `b1`, `c0`, `c1`, `d0`, or `d1` for RDBE; `a`, `b`, `c`, `d`, `e`, `f`, `g`, or `h` for DBBC3; `1`-`8` for all others. No default. No previous value available.

a| `_freq_` |  LO frequency for this channel, MHz. No default. No previous value available.

a| `_sb_` | Net sideband for this channel, `unknown`, `usb` or `lsb`.  Default is `unknown`.

a| `_pol_` | Polarization for this channel, `unknown`, `rcp`, or `lcp`.  Default is `unknown`.

a| `_pcspace_` |  Spacing of phase-cal rails for this channel, MHz, `unknown`, or `off`. Default is `unknown`.

a| `_pcoff_` | First phase-cal rail frequency for this IF if not equal to the spacing, MHz. Default `0.0`. This offset is specified relative to DC in the IF.
|===

==== MONITOR-ONLY PARAMETERS

[frame=none,grid=none]
[cols="1,8"]
|===
a| `rxg` |  literal text, `rxg`, to indicate this line has _.rxg_ file information for the LO `_chan_`
a| `_file_` |  name of the _.rxg_ file that matched the LO value; `undefined` if there was no match, in that case the remaining fields are omitted
a| `_type_` |  LO type from _.rxg_ file: `fixed` or `range`
a| `_lo1_` | first LO value from _.rxg_ file, MHz
a| `_lo2_` | second LO value from _.rxg_ file, if present, MHz
a| `_year_` | the year from the date in the _.rxg_ file
a| `_month_` | the month from the date in the _.rxg_ file
a| `_day_`  |  the day from the date in the _.rxg_ file
a| `_pol1_` |   first polarization from the _.rxg_ file
a| `_dpfu1_` | DPFU of the first polarization in the _.rxg_ file
a| `_pol2_` | second polarization from the _.rxg_ file, if present
a| `_dpfu2_` | DPFU of the second polarization in the _.rxg_ file, if present
|===

==== COMMENTS

This command specifies the characteristics of each IF channel.

It is an information only command in its standard implementation, but
may be implemented as a station command to provide hardware control.

The values should represent the net of effect of all stages of
conversion before the signal enters the VC/BBCs. In other words any
upconverter should be included.  In particular, the values for the
Mark III/IV/5 IF3 channel should include the effect of the internal
IF3 mixer, if it is being used.

The LO frequencies are used by the _pcalr_ and _pcald_ programs to
calculate the frequencies of the phase calibrator tones. _pcalr_ has
not been tested with spacings other than 1 MHz.

The `fivept` and `onoff` commands use the values to look-up the source
flux, antenna gains and Tcal values for the the selected
detectors. The `caltemp` command uses it to look up the T~cal~ values.

For the DBBBC, the second four LOs (`2a`, `2b`, `2c`, `2d`) are not
used for anything but populating the internal LO array.

An `*lo=*` with no parameters clears all LO values.

The monitor form, `*lo*`, shows all defined LO values.

The `lo/rxg,...` line is displayed for each LO as it is set
(commanded) and for each LO in monitor responses. This is intended to
give the operator feedback to verify that the correct version of the
_.rxg_ file is in use. The format of these lines may be adjusted in
future releases based on feedback from users about what is most
useful.

Additionally, when an LO is set, the contents of the _.rxg_ file are
logged, but not displayed, in lines starting with `:rxg_file,`. After
a log is opened, the contents for a given _.rxg_ file are only logged
the first time a matching LO frequency is set.

The `FS_LO_ANTCN_MODE` environment variable can be set to trigger
running antcn in the specified local mode (greater than `99`) to
configure the LO being set. The index of the LO being set (numbering
starting as `0`) is passed as the value of fourth element of the run
parameter array (usually `ip[3]` in C).

In the future, for K4 type 1 rack, the range of LO values should be
`1`-`4`, for K4 type 2 rack, `1`-`16`.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}

=== tsys - compute and display system temps

==== SYNTAX

[subs="+quotes"]
....
tsys=_list_
....

==== RESPONSE

[subs="+quotes"]
....
tsys/_systemps_
....

==== SETTABLE PARAMETERS

[frame=none,grid=none]
[cols="1,8"]
|===

a| _list_ | List of detectors for which stem:[\mathit{tsys}] will
be computed. Standard detector mnemonics allowed. In addition: for
VLBA/4/5/DBBC `formif` and `formbbc` are permitted; for Mark III/IV/5,
`formif` and `formvc` are permitted; station detectors `u5` and `u6`
are permitted.

|===

==== MONITOR-ONLY PARAMETERS

[frame=none,grid=none]
[cols="1,8"]
|===

a| _systemps_ | List of detector (using standard mnemonics) & system
temperature pairs. Temperatures are in degrees Kelvin.

|===

==== COMMENTS

The `_systemp_` results are returned grouped in pairs of
`__mnemonic__,__value__` for each detector. The output is collected
into lines by IF channel. Detectors that have no IF assigned are
displayed first followed by those for IFs `1`-`3` (Mark III/IV) or
`a`-`d` (VLBA/4/5/DBBC). If the output for an IF would make a long
output line, the output is split into more than one line. For station
detectors, the values are displayed on one line.

For Mark III/IV and LBA4 racks the detector mnemonics for the VCs are
displayed as `_hs_`, where `_h_` is the VC number as hex and `_s_` is
for the sideband: `d` (dual for upper/lower), `u` (upper), `l`
(lower), a digit `3`-`7` for other VC detectors or `x` for unknown.

For VLBA/4/5/DBBC, additional mnemonics `formif` and `formbbc` are
permitted in `_list_`. These select the detectors for the IF channels
and BBC sidebands currently being recorded by the formatter.  For Mark
III/IV/5, `formvc` is accepted instead of `formbbc`, as well as
`formif`.

A time-out or other error on one more devices for a Mark III/IV/5,
LBA, VLBA/4/5 or DBBC detector will not prevent results from other
detectors from being displayed. A negative integer will be shown for
each channel that had an error that prevented an actual measurement
from being displayed. An overflow value, larger than 999999.9 is
displayed as dollar signs, `+++$$$$$$$$+++`.

This command calculates and displays system temperatures for the
different detectors. The formula for Mark III/IV/5, LBA4, DBBC, and
station detectors is:

[.text-center]
stem:[\mathit{tsys = ( tpi - tpzero ) \frac{caltemp}{tpdiff}}]

For LBA and DBBC the above formula is used with stem:[\mathit{tpzero = 0}].

For VLBA/4/5 the formula is:

[.text-center]
stem:[\mathit{tsys = (tpi ( \frac{tpdiffgain}{tpgain})^2 - tpzero ) \frac{caltemp}{tpdiff}}]

where:

* stem:[\mathit{tsys}] -- system temperature, as reported in `tsys` command

* stem:[\mathit{tpi}] -- cal-off reading, from `tpi` command

* stem:[\mathit{tpzero}] -- zero-level reading, from `tpzero` command

* stem:[\mathit{tpical}] -- cal-on reading, from `tpical` command

* stem:[\mathit{caltemp}] -- noise calibration source temperature, from _.rxg_ file

* stem:[\mathit{tpgain}] -- gain for stem:[\mathit{tpi}], from `tpgain` command

* stem:[\mathit{tpdiff}] -- stem:[\mathit{tpical-tpi}], from `tpdiff` command

* stem:[\mathit{tpdiffgain}] -- gain for stem:[\mathit{tpdiff, tpzero}] from `tpdiffgain` command

For VLBA/4/5, there can be two different uses of the `tpi` command.
If there are, one is normally used with `tpical` to form
stem:[\mathit{tpdiff}]. The other is normally for the
stem:[\mathit{tpi}] value. The values measured by `tpi` for the
two uses may be different. The value for `tpdiff` is used to define
the conversion factor from counts to degrees (according to `caltemp`)
only. Subsequent stem:[\mathit{tpi}] values can be used to track
variations in the system temperature.  The gain must be sampled with
`tpidiffgain` for the former (and `tpzero`)  and `tpgain` for the
latter. However, if `tpgain` and/or `tpdiffgain` commands return
incorrect values when used because of some persistant problem, they
can be omitted as long as the gain level is the same for all of `tpi`,
`tpzero`, and `tpdiff`.

For station detectors, if the `_zero_` parameter in the `user_device`
command is set to `no`, the value of stem:[\mathit{tpzero}], is
assumed to be zero, i.e., any value measured by `tpzero` is ignored.

Please see the default `preob`, and `midob` procedures for examples of
how stem:[\mathit{tsys}] is measured.

---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}
