= SNAP Commands
W. E. Himwich, N. R. Vandenberg
FS Operations Manual - Version 9.5 - December 1 2001


:sectnums:

== SNAP Command Syntax

This manual contains detailed descriptions of the SNAP commands
available in the Field System. Each command is described on a separate
"`page.`" Commands are ordered alphabetically.

Please refer to the *SNAP Language* (#add link#) manual for the
specifications of the language itself, including a description of
control commands and general syntax.

The subsections of this first section contain reference information that
applies to many commands.

=== Command Descriptions

In this manual, each command is described on a separate page. For each
command, the information provided is:

command - function (equipment)

[none]
* The command name and a few words that describe its function are given at
the top of each page. If the command is restricted to certain types of
equipment, that information is given in parentheses. For example, the
`bbc__nn__` command is applicable only to VLBA and VLBA4 racks,
and the title will include the words "`(VLBA, VLBA4 racks)`". Many
commands don’t have restrictions because they are general FS commands,
such as `schedule` or `echo`. Commands that interact with the equipment
may be general as well. This may be because the command is in fact
implemented for all types of equipment. In fact some commands that have
no restrictions have very limited functionality beyond some specific
equipment configurations. Except for one command: `pcal`, all commands
are restricted by either the rack or the recorder that is used, but not
by both (this will be corrected for `pcal` at a later date).

+

All of the currently existing rack restrictions are listed below:

+

K4K3 racks +
Mark III racks +
Mark III, Mark IV racks +
Mark III, Mark IV, VLBA, VLBA4 racks +
Mark III, Mark IV, all K4 racks +
Mark IV, VLBA4, K4MK4 racks +
Mark IV, VLBA, VLBA4, K4MK4 racks +
VLBA racks +
VLBA, VLBA4 racks +
all K4 racks +
all racks

+

These restrictions all correspond to rack types that can be specified
in _equip.ctl_, except for the restrictions involving K4 racks: all
K4, K4K3, K4MK4, VLBA, and in addition: all racks. For the all K4
restriction, all K4 types are included irrespective of K4 VC sub-type
and including all K4K3 and K4MK4 types irrespective of K4 VC
sub-types.  The K4K3 restriction includes all K4 racks with a K3
formatter, irrespective of K4 VC sub-type. The K4MK4 restriction
includes all K4 racks with a Mark IV formatter, irrespective of K4 VC
sub-type. The VLBA restriction includes both the vlba and vlbag rack
types. The all restriction indicates that this command works for all
racks, i.e., the only rack for which it does not work is none.

+

All of the currently existing recorder restrictions are listed below:

+

K4 drives +
Mark III drives +
Mark III, Mark IV drives +
Mark IV drives +
VLBA, VLBA4 drives +
S2 drives +
all drives +
longitudinal drives

+

These restrictions generally include more than one recorder sub-type
that can be specified in _equip.ctl_. The K4 restriction includes all
K4 drive types with and without the DMS. The Mark IV restriction
includes both the mk4 and mk4b sub-types. The VLBA restriction include
vlba, vlba2, and vlbab sub-types. The all restriction indicates that
this command works for all recorders, i.e., the only recorder type for
which it does not work is none. The longitudinal restriction indicates
that it includes all of Mark III, Mark IV, VLBA (including VLBA2), and
VLBA4 recorders. All other restrictions: Mark III, VLBA4, and S2 all
apply to just those simple types.

Syntax: `command=__list of parameters__`

[none]
* The command syntax is shown first. The command name and the list of
parameters are shown. The various forms of the command are described in
the Comments section. Any combination of upper case and lower case
letters may be used in typing a command. All commands are converted to
lower case before they are processed.

Response: `command/_list of response parameters_`

[none]
* The response (if any) to the command is given with the list of
parameters appearing in the response. Normally the response to a command
has an identical list of parameters to the command itself, followed by
any monitor parameters. All responses to commands are displayed in lower
case letters only.

Settable parameters:

[none]
* This part of the page describes each parameter in the "`Syntax`" line that
can be specified by the operator. The allowable range of values for each
parameter is given. The default value, if any, is given. A default value
is obtained by entering a null for a particular parameter. The parameter
value specified in the previous issuing of this command may be obtained
by entering `***` instead of a value. Entering `*?*` as the first parameter
results in a response containing the parameters specified in the most
recent issuance of this command. If any parameter value is found to be
invalid, command interpretation stops at that point and an error message
is generated.

Monitor-only parameters:

[none]
* Each parameter in the "`Response`" that does not appear in the "`Syntax`" is
described in this section. These are parameters that cannot be specified
by the operator, but are monitored or calculated by the Field System.

Comments:

[none]
* The final section of the page provides further descriptions of the way
in which the command works. These comments often describe the algorithm
that was used in implementing the command, and outline specific
conditions under which the command should be used.

=== Dual Recorder Support

The FS supports sequential recording on two recorders (or drives).With
the exception that K4 and S2 recorders are only supported as recorder
number 1, any and all recorders (including none) can be used either as
recorder 1 or recorder 2. When the FS operates in dual recorder mode,
all commands that refer to recorders come in two forms. They either have
a numeral `1` or a numeral `2` appended to the normal single recorder
version of the command depending on whether they refer to recorder 1 or
recorder 2. The single recorder version of the commands are the ones
documented in the SNAP command manual pages. As an example, if recorder
1 is a VLBA drive and recorder 2 is Mark III drive, the tape command
that refers to recorder 1 would be the VLBA drive tape command with a
`1` appended: `tape1`. Likewise for recorder 2, the tape command would
be the Mark III drive tape command with a `2` appended: `tape2`. For all
tape recorder commands (those that have some drive restriction specified
in their command -function title line of the SNAP command description
page) a numeral at the end distinguishes which drive they refer to.

There are also some rack oriented commands that need to know which
recorder is in use. In addition the _monit<n>_ and _chekr_ programs need to
know which recorder is in use. The `select` command allows the drive
being used for data recording to be specified. drudg does this
automatically for schedules that use two drives. Please note that the
recorder that is not being used for recording can be manipulated by the
operator using the appropriate commands to complete tasks such as
prepassing and mounting the next tape. The `mount1` command is not
available for K4 and or S2 recorders. All other aspects of two recorder
operation with a K4 or S2 recorder as recorder 1 are implemented.

If only one tape drive is used, the drive type of either recorder 1 or
recorder 2 in _equip.ctl_ must be none. In this case all of the
recorder specific commands are used without a numeral suffix and they
refer to the recorder that is not specified as none. This appears as
normal one tape drive operation as used in older versions of the FS,
except that it is possible to select which of two drives will be used
by just changing the _equip.ctl_ file and restarting the FS. Please note
that the `mount__n__` command is only available for dual recorder
configurations, i.e., the version without a numeral appended is never
available.

=== MAT Module Functions

The phrase "`MAT module functions available`" in the comments section
means that the following additional types of parameters may be used.
This is available for those Mark III modules that have MAT
communications.

[frame=none,grid=none]
[cols="1,4"]
|===
a|`__module__=test/reset` | Issues an MAT reset to this module only.
a|`__module__=alarm`  | Resets the alarm on this module.
|===

=== MCB Module Functions

The following syntax is valid for those commands which state that "`MCB
module functions are available`" in the Comments section of the command
description.

[frame=none,grid=none]
[cols="1,4"]
|===
a|`__module__=addr` | Sends the module its base address and length. This
sets the module's MCB address space.

a|`__module__=test` | Checks the module’s address. An error message in
response to this command indicates that the module needs to be sent its
address space.
a|`__module__=addr` | Sends the module its base address and length. This
|===

=== Module and Detector Mnemonics

The Field System makes use of mnemonics for Mark III, Mark IV, S2, VLBA,
and VLBA4 equipment in SNAP commands. No mnemonics are defined for K4
modules or detectors at this time. Displays of mnemonics are always two
characters, but many forms of module names are allowed when entering
commands. This is a convenience for the operator who does not have to
remember the exact two-character mnemonic.

The SNAP commands that pertain to total power radiometry allow the
operator to specify different detectors in the equipment. Detectors are
specified by using a mnemonic. When the Field System displays mnemonics
they are always two characters, but different forms of the detector
names are allowed when entering commands. This is a convenience for the
operator who does not have to remember the exact two-character mnemonic.

Valid mnemonics for modules and detectors are listed in the tables on
the following pages.

The `u5` and `u6` detector mnemonics are used for station specific
detectors that implemented via the _antcn_ program. Currently they are not
completely supported. They may be used in the `fivept` and `onoff`
commands for all rack types (including none). They may also be use in
the `tpi`, `tpical`, `tpzero`, and `tsys__X__` commands for _rack
types other than_ Mark III, Mark IV, VLBA, and VLBA4.

[options="header",]
[cols="<,^,^"]
|===
3+^|Field System Module Mnemonics
|Module |Standard mnemonic | Other allowed mnemonics
(* indicates mnemonics available only when only one drive is defined)

3+|*Mark III/IV modules*
|video converters |`v__n__`, `_n_`=`1`-`f` |`vc__n__`, __n__=`1`-`15`, `1`-`f`
|IF distributor a|`if` a|`ifd`
|formatter a|`fm` a|`form`
|tape transport 1 a|`r1` |`rec1`, `t1`, `tape1`, `rc`\*, `tp`*, `tape`*
|tape transport 2 a|`r2` |`rec2`, `t2`, `tape2`, `rc`\*, `tp`*, `tape`*
|high density heads a|`hd` a|
|high density heads transport 1 a|`h1` a|`hd`*
|high density heads transport 2 a|`h2` a|`hd`*
|S/X receiver a|`rx` |
|IF3 distributor a|`i3` |`if3`,`ifd3`

3+|*S2 modules*
|tape recorder 1 a|`r1` |`rec1`, `t1`, `tape1`, `rc`\*, `tp`*, `tape`*

3+|*VLBA modules*
|baseband converters |`b__n__`, `_n_`=`1-f` |`bc__n__`,
`bbc__n__`, `_n_`=`1`-`15`, `1`-`f`
|IF distributor 1, channels A&B a|`ia` |`ifa`, `ifb`, `ib`, `ifab`
|IF distributor 2, channels C&D a|`ic` |`ifc`, `ifd`, `ic`, `ifcd`
|formatter a|`fm` a|`form`
|tape recorder 1 (except heads) a|`r1` |`rec1`, `t1`, `tape1`, `rc`\*, `tp`*, `tape`*
|tape recorder 2 (except heads) a|`r2` |`rec2`, `t2`, `tape2`, `rc`\*, `tp`*, `tape`*
|high density heads a|`hd` |
|high density heads recorder 1 a|`h1` a|`hd`*
|high density heads recorder 2 a|`h2` a|`hd`*

3+|*Groups of modules*
|all modules which have been set up | a|`all`
|odd video or baseband converters | a|`odd`
|even video or baseband converters | a|`even`
|===

[options="header",]
[cols="<,^,^"]
|===
3+^|Field System Detector Mnemonics

|Detector |Standard mnemonic |Other allowed mnemonics

3+|*Mark III detectors*
|formatter selected VCs a|`formvc` |
|IFs feeding formatter selected VCs a|`formif` |
|video converters |`v__n__`, `_n_`=`1`-`f` |`vc__n__`,
`_n_`=`1`-`15`,`1`-`f`
|IF distributor channel 1 a|`i1` a|`if1`
|IF distributor channel 2 a|`i2` a|`if2`
|IF3 distributor a|`i3` a|`if3`

3+|*S2 detectors*
|none | |

3+|*VLBA detectors*
|formatter selected BBCs a|`formbbc` |
|IFs feeding formatter selected BBCs a|`formif` |
|baseband converters, USB |`__n__u`, `_n_`=`1`-`f` |
`b__n__u`, `bc__n__u`, `bbc__n__u`,
`_n_`=`1`-`15`,`1`-`f`
|baseband converters, LSB |`__n__l`, `_n_`=`1`-`f` |
`b__n__l`, `bc__n__l`, `bbc__n__l`,
`_n_`=`1`-`15`,`1`-`f`
|IF distributor 1, channel A a|`ia` a|`ifa`
|IF distributor 1, channel B a|`ib` a|`ifb`
|IF distributor 2, channel C a|`ic` a|`ifc`
|IF distributor 2, channel D a|`id` a|`ifd`

3+|*Station Dependent Detectors*
|Detector 1 (IF "`chain`" 5) |`u5` |
|Detector 2 (IF "`chain`" 6) |`u6` |

3+|*Groups of detectors*
|all non-station dependent detectors | a|`all`
|all odd video converters | a|`odd`
|all even video converters | a|`even`
|all odd baseband converters USB | a|`oddu`
|all odd baseband converters LSB | a|`oddl`
|all even baseband converters USB | a|`evenu`
|all even baseband converters LSB | a|`evenl`
|===

== On-Line Help

The entire documentation for each command is available as on-line help
in the Field System. The `help` command will display the information for
a specified command on the screen during Field System operations. The
information that is listed is identical to that found on the pages of
this manual.

Refer to the page with the `help` command description.

