# NRV 920209
# Load users resources, merged with system defaults
xrdb -load $HOME/.Xresources
# Start window manager
mwm &
sleep 5
# Set mouse acceleration and threshold
#xset m 3 10
# Set click volume (values 0 to 100)
#xset c on 100
# Set screen saver blanking time
#xset s 300
xterm -C -ls -name login_sh -geometry 80x24+0+0
