/* shared memory (fscom C data structure) layout */

typedef struct fscom {
        long iclbox;
        long iclopr;
        long nums[MAX_CLS];
	float AZOFF;
	float DECOFF;
	float ELOFF;
        int ibmat;
        int ibmcb;
	int ICAPTP[2];
	int IRDYTP[2];
	int IRENVC;
	int ILOKVC;
	int ITRAKA[2];
	int ITRAKB[2];
	unsigned long TPIVC[15];
	float ISTPTP[2];
	float ITACTP[2];
	int KHALT;
	int KECHO;
        int KENASTK[2][2];
	int INEXT[3];
	float RAOFF;
	float XOFF;
	float YOFF;
        char LLOG[8];
	char LNEWPR[8];
	char LNEWSK[8];
	char LPRC[8];
	char LSTP[8];
	char LSKD[8];
        char LEXPER[8];
        char LFEET_FS[2][6];
        short lgen[2][2];
        int ICHK[23];
	float tempwx;
	float humiwx;
	float preswx;
	float ep1950;
        float epoch;
	float cablev;
        float height;
	double ra50;
	double dec50;
        double radat;
        double decdat;
        double alat;
        double wlong;
	float systmp[32];
        int ldsign;
	char lfreqv[90];
        char lnaant[8];
	char lsorna[10];
        char idevant[64];
        char idevgpib[64];
        char idevlog[64][5];
        long ndevlog;
	int imodfm;
        int ipashd[2][2];
	int iratfm;
	int ispeed[2];
	int idirtp[2];
	long cips[2];
        int bit_density[2];
	int ienatp[2];
	int inp1if;
	int inp2if;
	int ionsor;
        int imaxtpsd[2];
        int iskdtpsd[2];
        float motorv[2];
        float inscint[2];
        float inscsl[2];
        float outscint[2];
        float outscsl[2];
        int itpthick[2];
        float wrvolt[2];
        int capstan[2];
	struct {
	    int allocated;
	    char name[SEM_NUM][5];
	  } go;
        struct {
            int allocated;
            char name[SEM_NUM][5];
        } sem;
        struct {
	  int bbc[ MAX_BBC];
	  long bbc_time[ MAX_BBC];
	  int dist[ MAX_DIST];
	  int vform;
	  long fm_cn_tm;
	  int rec[2];
	  int vkrepro[2];
	  int vkenable[2];
	  int vkmove[2];
	  int systracks[2];
	  long rc_mv_tm[2];
	  int vklowtape[2];
	  int vkload[2];
	  long rc_ld_tm[2];
	  struct s2rec_check s2rec;
	  struct k4rec_check k4rec;
        } check;
        char stcnm[4][2];
        int  stchk[4];

        struct dist_cmd dist[ MAX_DIST];

        struct bbc_cmd bbc[ MAX_BBC];

        unsigned tpi[ MAX_DET];
        unsigned tpical[ MAX_DET];
        unsigned tpizero[ MAX_DET];

        struct {
           int rack;
           int drive[2];
	   int drive_type[2];
	   int rack_type;
        } equip; 

        int klvdt_fs[2];
        struct vrepro_cmd vrepro[2];
        struct vform_cmd vform;
        struct venable_cmd venable[2];
	struct systracks_cmd systracks[2];
        struct dqa_cmd dqa;
        struct user_info_cmd user_info;
        struct s2st_cmd s2st;
        int s2_rec_state;
        struct rec_mode_cmd rec_mode;
        struct data_valid_cmd data_valid[2];
        struct s2label_cmd s2label;
	struct form4_cmd form4;
        float diaman;
        float slew1;
        float slew2;
        float lolim1;
        float lolim2;
        float uplim1;
        float uplim2;
        float refreq;
        int i70kch;
        int i20kch;
        struct {
          float rate[2];
          long offset[2];
          long epoch[2];
          long span[2];
          long secs_off;
          int index;
          char model;
        } time;
	float posnhd[2][2];
        int class_count;
        float horaz[MAX_HOR];
        float horel[MAX_HOR];
        char mcb_dev[64];
        unsigned char hwid;
        int iw_motion;
        int lowtp[2];
        int form_version;
        int sterp;
	int wrhd_fs[2];
	int vfm_xpnt;
	struct {
	  struct {
	    int rstate;
	    int rstate_valid;
	    long int position;
	    long int posvar;
	    int position_valid;
	  } s2rec[2];
	  int s2rec_inuse;
	} actual;
	float freqvc[15];
	int ibwvc[15];
	int ifp2vc[16];  
	char cwrap[8];
	int vacsw[2];
	float motorv2[2];
	int itpthick2[2];
	int thin[2];
	int vac4[2];
        float wrvolt2[2];
        float wrvolt4[2];
        float wrvolt42[2];
        char user_dev1_name[2];
	char user_dev2_name[2];
	double user_dev1_value;
	double user_dev2_value;
	struct rvac_cmd rvac[2];
	struct wvolt_cmd wvolt[2];
	struct lo_cmd lo;
	struct pcalform_cmd pcalform;
	struct pcald_cmd pcald;
	float extbwvc[15];
        long freqif3;
        int imixif3;
	struct pcalports_cmd pcalports;
	int k4_rec_state;
	struct k4st_cmd k4st;
	char k4tape_sqn[9];
        struct k4vclo_cmd k4vclo;
        struct k4vc_cmd k4vc;
        struct k4vcif_cmd k4vcif;
        struct k4vcbw_cmd k4vcbw;
        struct k3fm_cmd k3fm;
        int reccpu[2];
        struct k4label_cmd k4label;
        struct k4rec_mode_cmd k4rec_mode;
        struct k4recpatch_cmd k4recpatch;
        struct k4pcalports_cmd k4pcalports;
        int select;
	int rdhd_fs[2];
        int knewtape[2];
        int ihdmndel[2];
        char scan_name[17];
        struct tacd_shm tacd;
/*        struct ifatt_shm ifatt; This will be used in the future.*/
        int iat1if;
        int iat2if;
        int iat3if;
        int erchk;
        int ifd_set;
        int if3_set;
        unsigned long bbc_tpi[MAX_BBC][2];
        unsigned long vifd_tpi[4];
        unsigned long mifd_tpi[3];
	float cablevl;
        float cablediff;
} Fscom;
