//
// Copyright (c) 2021 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= VERY ROUGH DRAFT FS DBBC3 Operations Manual
Version 0.3 - January 2021

:toc:
:sectnums:

== Introduction

This manual is intended to outline the model for FS operations with the DBBC3.

== DBBC3 operations

=== Initial configuration of the DBBC3

When the DBBC3 is booted, it is assumed it is set-up according to
the "`Setting up the DBBC3 for DDC_U mode`" document.

=== Ethernet configuration

The Ethernet configuration of a Core3H board can be changed on demand with a
predefined SNAP procedure with contents such as:

....
dbbc3=core3h=1,tengbcfg eth0 ip=192.168.1.16 gateway=192.168.1.1 nm=27
dbbc3=core3h=1,tengbcfg eth1 ip=192.168.1.17 gateway=192.168.1.1 nm=27
dbbc3=core3h=1,tengbarp eth0 2 00:60:dd:44:47:60
dbbc3=core3h=1,tengbarp eth1 3 00:60:dd:44:47:61
dbbc3=core3h=1,destination 0 192.168.1.2:46220
dbbc3=core3h=1,destination 1 192.168.1.3:46221
....

NOTE: The above example is for one board. Multiple boards can combined in one
procedure or one procedure can call a separate sub-procedure for each board.

====

Questions:

. Is anything else needed for the Ethernet configuration?

. Are there other things that would be useful to set from the FS? The mode is
covered below.

====

=== Experiment mode configuration

Due to certain changes in Core3H setup requiring a time sync afterwards, only
one mode can be used schedule. The issue is that there is reluctance to perform
the time sync without operator supervision.

As a result, during the schedule, only the configuration of the Core3H boards
are checked. A mechanism is provided to force the setting of the mode
configuration. This can be used before the experiment starts to place the
Core3H boards in the correct configuration without having to decode the
schedule configuration and set the Core3H boards up manually.

==== Configuring Core3H boards

To force the Core3H boards to be configured:

. _drudg_ the schedule to make the _.prc_ (and _.snp_) file
. Start the FS
. Open the experiment procedure library, e.g.:

  proc=r4849kk

. Execute the normal setup procedure with the `force` parameter, e.g.:

  setup01=force

For each Core3H that is in use, the following information will be sent, in this
order:

. Decimation
. Bitmask
. `vdif_frame ...`
. `start vdif`

For example:

....
core3h=1,vsi_samplerate 128000000 2
core3h=1,vsi_bitmask 0xcccccccc
core3h=1,vdif_frame 2 8 8000
core3h=1,start vdif
....

If the board is not being used by the current mode, then the following is sent:

....
core3h=1,stop
....

==== Time sync

Then the operator needs to sync each Core3H that is sending data, e.g.:

....
core3h=1,timesync
core3h=1,start vdif
....

====
Questions:

[start=3]
. Is this sufficient?

. Since there is concern that this may not work correctly, how does one tell if
it was successful?

. Can we then skip the `start vdif` when setting the mode?

====

=== equip.ctl

For DBBC3 use, the rack type in equip.ctl_ should be `dbbc3_ddc`.

====

Questions:

[start=6]
. Should we support  DDC_V?
+
We can use `dbbc3_ddcu` and `dbbc3_ddcv`.

. If we are supporting DDC_V, are there any differences besides:
+

* Sending only one mask per board instead of four
* Only having 32 MHz BW
* Is splitmode always on?

====

== Other Features

=== Minimizing use of setup procedures

Normally, the FS sets the mode for each scan (unless there is continuous
recording). If this takes too long or makes the equipment unstable, the _drudg_
option `use_setup_proc yes` in _skedf.ctl_ can be used to minimize the
execution of the set-up.

WARNING: Not executing the setup each scan may not be as robust if the
equipment sometimes loses it configuration. It is up to the station to
determine whether minimizing its use is better than always using it.

With this enabled, _drudg_ will replace the calls to setup procedures (e.g.,
`setup01`) in the _.snp_ file with, e.g.:

 setup_proc=setup01

When the FS encounters this command, it will conditionally execute the setup
procedure if either of the following is true:

* This is first setup since the schedule was last opened.
+

This will make sure the setup is run at the start and any restart of the
schedule.

* If there was mode change, i.e., the name of the setup procedure changed.

[NOTE]
====

The `use_setup_proc` option in _skedf.ctl_ has three possible settings:

* `yes` -- use the `setup_proc` command

* `no`  -- do not use the `setup_proc` command

* `ask` -- to prompt for `yes` or `no` for each schedule

If the option is not used, it defaults to `no`.

====

NOTE: The `use_setup_proc` option applies to all systems, not just DBBC3

=== jive5ab_cnfg procedure

NOTE: This also applies to any system using a Mark 5C or FlexBuff recorder.

Each mode SNAP procedure produced by _drudg_ for Mark 5C and FlexBuff recorders
includes a call to the `jive5ab_cnfg` SNAP procedure. This procedure call is
inserted immediately after the `mk5c_mode`/`fb_mode` command. The procedure is
mode independent, i.e., the same procedure is used for all modes.

This procedure is a local `station` library procedure to allow tuning of the
configuration of _jive5ab_ for the specifics of the recorder, including
overriding the "`default`" configuration given by the `mk5c_mode`/`fb_mode`
command.

==== Default configuration

The `mk5c_mode`/`fb_mode` command sends the follow commands depending on
whether the recorder selected in _equip.ctl_ is `mk5c` or `flexbuff`. It does
_not_ depend on which command is used; `fb_mode` is just an alias for
`mk5c_mode`. It does depend on the data type, VDIF or 5B/Ethernet. Thus there
are two options for each recorder type. These are given below.

===== FlexBuff recorder

For FlexBuff recorders, there is a variable field `_socketbuffer_` in the
`net_protocol` command sent to the recorder.

. VDIF data
+

[subs="+quotes"]
....
mtu = 9000 ;
net_protocol = udpsnor : _socketbuffer_ : 256000000 : 4 ;
....

. 5B/Ethernet data
+

[subs="+quotes"]
....
mtu = 6000 ;
net_protocol = udpsnor : _socketbuffer_ : 256000000 : 4 ;
....

Where the _socketbuffer_ field depends on the total data rate:

*   32000000 -- data rate < 1 Gbps
*   64000000 -- 1 Gbps < data rate <= 4 Gbps
*  128000000 -- data rate > 4 Gbps

The _socketbuffer_ parameter is an important setting trying to minimize risk of
packet loss when starting the recording. For (very) high data rates, the
`jive5ab_cnfg` procedure can be used to increase the _socketbuffer_ size to
values appropriate for that. This assumes that the FlexBuff has been tuned
(especially the kernel network buffer sizes) along the lines of the FlexBuff
tuning documentation at
https://www.jive.eu/~verkout/flexbuff/flexbuf.recording.txt.

===== Mark 5C recorder

. VDIF data
+
....
net_protocol = : 128k : 2M : 4;
packet = 36 : 0 : 8032 : 0 : 0 ;
....

. 5B/Ethernet data
+

....
net_protocol = : 128k : 2M : 4;
packet = 36 : 0 : 5008 : 0 : 0 ;
....

==== Overriding the default

You can override the commands sent by the `mk5c_mode`/`fb_mode` command or add
more by putting them in your local `jive5ab_cnfg`. This works because
`jive5ab_cnfg` is called after `mk5c_mode`/`fb_mode` in the setup procedure. An
example of local customizations is given in the sub-sections below.

CAUTION: If put any commands in `jive5ab_cnfg` that depend on the data type,
VDIF or 5B/Ethernet, you would need to change them if there is a change in the
data type. This is not a concern for most stations.

===== Multi-threaded

The FlexBuff recorders place all threads in one file by default. If instead you
need one thread per file, you can add the following commands to `jive5ab_cnfg`:

....
jive5ab=datastream=clear
jive5ab=datastream=add:{thread}:*
jive5ab=datastream=reset
....

If you need to switch between all threads in one file and each thread in its
own file, you can accomplish this by commenting out, or un-commenting, the
`jive5ab=datastream=add:{thread}:*` line, respectively. This will need to be
done an experiment-by-experiment basis depending on each experiment's needs.

NOTE: In SNAP, putting a double quote `"` as the first character in a line
makes it a comment.

===== Changing net_protocol

If you use different values for `net_protocol`, you can leave any field blank
that your don't need to change from what the FS has already sent. For example
to only set the _socketbuffer_ size to `64000000`, use:

....
net_protocol = : 64000000
....

====

Questions:

[start=8]
. Is the description correct for the above?
+

Harro: Yes

. Should we add guidelines for tuning parameters depending on the recorder?
+

Harro: I've put in a link to the FlexBuff tuning document

. Are there other examples we should give?

. Should `net_protocol` for Mark 5C have a value?
+

Harro: No, Mark5C recording ignores the `net_protocol` - all is configured through `packet=...`

. I know we decided to put this single file per thread option in
`jive5ab_cnfg`, but I can't remember now if we thought it was because it would
not be changed very often or if I was reluctant to ask for a _drudg_ option. I
am now thinking we might be able to add it as an option. A question is whether
it is worthwhile. I don't know how many stations would use it. I guess Eskil
would, but if so, is it better than commenting/un-commenting the relevant line
in `jive5ab_cnfg`?
+

Harro: Actually - having it as a _drudg_ option wouldn't be too bad! I think
there is wider interest in this feature. And it would make it more predictable
and convenient: stations can change as per experiment's request.
+

If we made it an option, it might be controlled by a _skedf.ctl_ option
`vdif_single_thread_per_file`:

* If the option is not present _drudg_ does nothing.

* If the option is set to `yes`, _drudg_ produces a `thread` procedure with the
commands above.

* If the option is set to `no`,  _drudg_ produces a `thread` procedure without
the `jive5ab=datastream=add:{thread}:*` command.

* If the option is set to `ask`, it will prompt for `yes` or `no` for each
experiment.
+

Maybe we could have `skip` option (do nothing) for `ask` as well if it would be
helpful.

* The `thread` procedure would come after `mk5c_mode`/`fb_mode` and before
`jive5ab_cnfg`.
+

Harro: Yup, that would allow stations to still override things the FS and
_drudg_ have done so far

====
