//
// Copyright (c) 2021 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= DRAFT FS DBBC3 Operations Manual
Version 0.6 - March 2021

:experimental:
:sectnums:
:toc:

== Introduction

This document outlines the model for FS operations with the DBBC3.

== DBBC3 operations

=== DBBC3 commands

The following SNAP commands support DBBC3s. You can access help information
with `help=_commmand_`.

* `bbc__nnn__` -- `_nnn_` from `001` to `128` -- BBC setup and monitoring
* `bbc_gain` -- Setup and monitor overall BBC gain
* `cont_cal` -- Setup and monitor continuous calibration configuration
* `core3h_mode__n__` -- `_n_` from `0` to `8` -- Core3H board setup and monitoring
* `fb_mode` -- Setting the FlexBuff (_jive5ab_) recording mode -- An alias for `mk5c_mode`
* `fivept` -- Pointing measurements
* `if__x__` -- `_x_` from `a` to `h` -- IF CoMo setup and monitoring
* `iftp__x__` -- `_x_` from `a` to `h` -- IF CoMo total power monitoring
* `mcast_time` -- display of multicast time
* `onoff` -- SEFD and antenna calibration measurements
* `tpicd` -- TP (multicast) recording daemon setup and control

=== FS DBBC3 channel and IF labels

The DBBC3 channel labels are of the form `_nnns_`, where:

* `_nnn_` is the channel number, `000`-`128`
* `_s_` is the side-band, `l` or `u`

For example, `032u`.

The DBBC3 IF labels are of the form `i__x__`, where:

* `_x_` is the IF, `a`-`h`

For example, `id`.

=== Initial configuration of the DBBC3

When the DBBC3 is booted, it is assumed it is set-up according to
the "`Setting up the DBBC3 for DDC_U mode`" document.

=== Local configuration changes

This section covers changes that may be needed for experiments but aren't
conveyed by the schedule file, yet. Some examples are given below.

==== Ethernet configuration

The Ethernet configuration of a Core3H board can be set in the DBBC3 boot
configuration file. It can be changed on demand with a predefined SNAP
procedure with contents such as:

....
dbbc3=core3h=1,tengbcfg eth0 ip=192.168.1.16 gateway=192.168.1.1 nm=27
dbbc3=core3h=1,tengbcfg eth1 ip=192.168.1.17 gateway=192.168.1.1 nm=27
dbbc3=core3h=1,tengbarp eth0 2 00:60:dd:44:47:60
dbbc3=core3h=1,tengbarp eth1 3 00:60:dd:44:47:61
dbbc3=core3h=1,destination 0 192.168.1.2:46220
dbbc3=core3h=1,destination 1 192.168.1.3:46221
....

NOTE: The above example is for one board. Multiple boards can combined in one
procedure or one procedure can call a separate sub-procedure for each board.

NOTE: A reset and sync is not required for Ethernet configuration changes.

====

Questions:

. Is anything else needed for the Ethernet configuration?
+

Sven: no

. Are there other things that would be useful to set from the FS? The mode is
covered below.

====

==== Changing thread numbers

The following command changes the thread number on _eth0_ tp `3`
(`196608/65536`) and _eth1_ to `4`.

....
dbbc3=core3h=1,regupdate vdif_header 3 196608 0x03FF0000
....

====

Questions:

[start=3]
. Does this also change the thread number for _eth1_ to `4`.
+
Sven: Yes.

====


=== Experiment mode configuration

This section covers configuration parameters that are defined per schedule.

Due to certain changes in Core3H setup requiring a time sync afterwards, only
one mode can be used per schedule. The issue is that there is reluctance to
perform the time sync without operator supervision.

As a result, during the schedule, only the configuration of the Core3H boards
are checked. A mechanism is provided to force the setting of the mode
configuration. This can be used before the experiment starts to place the
Core3H boards in the correct configuration without having to decode the
schedule configuration and set the Core3H boards up manually.

==== Configuring Core3H boards

To configure the Core3H boards for the schedule mode:

. _drudg_ the schedule to make the _.prc_ (and _.snp_) file
. Start the FS
. Open the experiment procedure library, e.g.:

  proc=r4849kk

. Execute the normal setup procedure, perhaps `setup01`, with the `force`
parameter, e.g.:

  setup01=force

NOTE: With or without the `force` the setup procedure configures all other
aspects of the mode besides the Core3H boards.

===== The details

For each Core3H that is in use, the following information will be set, in
this order:

--

* Decimation
* Splitmode
* Bitmask
* `reset`
* `vdif_frame ...`

--

For example:

....
core3h=1,vsi_samplerate 128000000 2
core3h=1,splitmode on
core3h=1,vsi_bitmask 0xcccccccc
core3h=1,reset
core3h=1,vdif_frame 2 8 8000 ct=off
....


[NOTE]
====

The FS makes some simplifying assumptions when forming the `vdif_frame`
command. These are believed to agree with limitations in the DBBC3 and what is
needed for practical operations:

* For the number of bits per channel:
+

If any channel on a board uses two bits, it is assumed that all do.

* For the number of channels:
+

The BBCs are handled as two groups: 1-8 and 9-16. This splits the BBCs in
agreement with the Ethernet ports where their channels are destined. The
number of channels in the group with largest number of channels is rounded up
to the next power of two, if it is not a power of two already. The resulting,
possibly rounded value, is used as the number of channels.

====

==== Time sync

After the Core3H boards are configured, the operator needs to sync each Core3H
and sync the PPS. In principle, this would consist of:

....
dbbc3=core3h=1,timesync
dbbc3=core3h=2,timesync
dbbc3=core3h=3,timesync
dbbc3=core3h=4,timesync
dbbc3=core3h=5,timesync
dbbc3=core3h=6,timesync
dbbc3=core3h=7,timesync
dbbc3=core3h=8,timesync
dbbc3=pps_sync
....

IMPORTANT: All the Core3H boards in the system need to synced, then a
`pps_sync` must be issued within 20 seconds of the first `timesync`. This is
not currently possible since each `timesync` requires about six seconds. A new
DBBC3 feature is being developed to allow syncing the boards in parallel and
issue a timely `pps_sync`. Until then, the only safe way to configure a DBBC3
is with the boot configuration. A _drudg_ setup procedure, not used with
`force` can be used to verify the configuration.

NOTE: The sync was successful if there no errors reported and all the boards
have the same time and VDIF epoch.

====
Questions:

[start=4]
. Is this sufficient?
+
Sven: No, the `pps_sync` was missing (but it requires a new command to implement properly).

. Since there is concern that this may not work correctly, how does one tell if
it was successful?
+

Sven: The sync was successful if there no errors reported and all the boards
have the same time and VDIF epoch.

. Can we then skip `start vdif` before the `timesync`?
+

Sven: Yes. Actually, the `start vdif` won't work until the board has been
synced.

====

==== Starting data transmission

After the boards are synced, data transmission needs to started or stopped for
each board, as appropriate for the mode. This can be accomplished with the
command:

....
core3h_mode0=end,force
....

[NOTE]
====

After the boards have been synced, data transmission can be freely started and
stopped on individual boards as needed. For example to start transmission on
board `1`, you can use:

....
dbbc3=core3h=1,start vdif
....

To stop transmission, use:

....
dbbc3=core3h=1,stop
....

CAUTION: Using these commands may make whether the board is transmitting data
inconsistent with the FS configuration and may lead to problems.

====

==== Checking the mode

After the data transmission has been started, the setup procedure can be
re-executed without the `force` to parameter to check that the setup is
correct:

  setup01

Any deviations will be reported as errors. This is how the setup is checked
within a schedule. This also checks that the personality and firmware version
agree with the FS control files.

=== Control files

==== equip.ctl

For DBBC3 use, the rack type in _equip.ctl_ should be `dbbc3_ddc_u` or
`dbbc3_ddc_v` depending on the firmware that is loaded.

The clock rate should be set to `nominal`, which gives the 128 MHz fixed value.

====

Questions:

[start=7]
. Should we support  DDC_V?
+
It may not be necessary since DDC_U is more general.

. If we are supporting DDC_V, are there any differences besides:
+

* Sending only one mask per board instead of four
* Only having 32 MHz BW, decimation 2
* Is splitmode always on?
+
Sven: For DDC_V, it is always off; DDC_U, always on.

====

==== dbbc3.ctl

The DBBC3 specific control file parameters are in the _dbbc3.ctl_ control file.
An example of the contents are:

....
* bbcs/if (8, 12, or 16), ifs (1-8)
  8 8
* DDCU firmware version (v121 or later)
 v124
* DDCV firmware version (v121 or later)
 v124
....

==== dbbad.ctl

The _dbbad.ctl_ file was expanded for use with DBBC3s. For the DBBC3 it can now
include the multicast address, port, and the interface being used. If the last
three parameters are omitted, receiving multi-cast data is disabled. If there
are only comments in the file or the file is empty, use of a DBBC3 at all will
be disabled. An example of the contents are:

....
* line 1: host(IP address or name), port(4000), time-out(centiseconds)
*         multicast addr, mult-cast port, multicast interface
* using an IP address avoids name server and potential network problems
*
192.168.1.2 4000 800 224.0.0.19 25000  eno2
....

=== Tsys monitor display

The Tsys monitor display is organized per IF. Some basic information: LO, time,
delay, Tsys for each IF/Core3H board  as well as BBC information: frequencies
and Tsys values. The display cycles through all the available IFs.

==== Modes

There are three modes:

* `Rec` shows IFs with channels configured for recording
+
This is intended for normal station operations.

* `Def` shows IFs with defined LO values
+
This may be useful for pointing or calibration runs.

* `All` shows all IFs

By default, if any channels are configured for recorded (selected by the bit
masks in the `Core3H` commands), the display will go into the `Rec` mode. If
there are no channels being recorded, but there are LOs defined for some IFs,
it will go into the `Def` mode. If neither the `Rec` or `Def` mode is
triggered, it will go into the `All` mode and automatically change to one of
other modes as appropriate. It is also possible to change to the `All` mode
from `Rec` or `Dec` with a single character (`*l*`) command. Another `*l*` will
toggle the display back to the other mode. The current mode is displayed in the
upper right hand corner.

==== Tsys values

Except for the `Rec` mode, the Tsys for all BBC side-bands on IF will be shown
if they can be calculated. If they can't be, a hint, in inverse video, for the
cause of the problem will be displayed the corresponding field instead. There
may be more than issue, but only the first encountered is reported. The order
is:

. `Nccal` -- continuous cal not enabled
. `N bbc` -- the BBC is not configured
. ``N lo `` -- the LO is not defined
. `Ntcal` -- no Tcal value was found

In the `Rec` mode, only Tsys fields for side-bands being recorded are
populated; Tsys fields for side-bands not being recorded are blank.

In the `All` mode, if no IFs are defined and no channels are being recorded
(e.g., at FS startup), Tsys fields for all side-bands are blank.


NOTE: As usual in the FS, an invalid value will be display as dollar signs:
`$$$$$`. That usually means that a value could be calculated, but there was a
problem with the result: the result was too large for the field, was negative
when only positive values are valid, or would have required dividing by zero.

==== Commands

The Tsys display accepts several one character commands:

* `*a*`-`*h*` -- show only that IF
* `*n*` -- next IF
* `*p*` -- previous IF
* `*1*`-`*9*` -- seconds of display time for each IF
* `*i*` -- toggle display of IF or RF frequency for BBCs
* `*l*` -- toggle between `All` and `Rec`*/*`Def` modes (unfortunately it couldn't be `*a*`)
* `*0*` -- reset to all defaults
* `*?*` or `*/*` -- show help summary
*  kbd:[esc] or kbd:[control+c] -- exit
* Any other key -- resume cycling

=== Checking DBBC3 time

The `mcast_time` command should be placed in the local `midob` procedure to
monitor the time in the DBBC3 for each scan. It will report an error if any
Core3H boards' time differs from the FS time or if the multicast data is more
than 20 seconds old. For future firmware versions, after `125` that report the
VDIF epoch in the multicast, it will report if there is a VDIF epoch mismatch
between the boards. Other checks may also be added, such as that the
`pps_delay` is too large.

=== Setting FS time

#TO BE IMPLEMENTED#

It is expected that normally the FS computer is running on NTP and the FS time
model is set to `computer` (see _misc/ntp.txt_ for more information). If good
NTP servers are available, it is expected that will give the best time in the
FS.

No suitable NTP servers may be available either because network connectivity is
poor and/or there are no local functioning NTP servers. In the case the FS
program _setcl_ can be used with DBBC3 firmware versions `125` and later to set
and adjust FS time (see _misc/fstime.txt_ for the details).

The implementation of _setcl_ for the DBBC3 depends on two values from the _dbbc3.ctl_ control file:

* The board number to use for measuring the time.
+

There can be up to eight to choose from. Board `1` will be in all systems and
should be adequate for the purpose, but which board is used can be changed in
the control file if need be.

* The delay of the multicast
+

The amount of time that the multicast arrives after the 1 PPS seems to be
stable. For the DDC_U v125 firmware, it is about 60 centiseconds. If it is
different for other versions, the value in _dbbc3.ctl_ can be adjusted. It should
be easy to measure it for a given firmware when NTP _is_ available using the
output of the `mcast_time` command.

In any event, using _setcl_ to set the FS time this way will only be useful to
level of stability of the delay of the multicast. Network conjestion may also
cause variations, but hopefully will be minimal in situations where this method
is needed.

Even if there are significant variations, even a significant fraction of a
second (which seems unlikely), in the arrival of the multicast, the clock model
determined should be useful.  Individual offset measurements should be fairly
accurate. If the clock model is determined over a significant amount of time, a
day or more, the fractional error in the model rate should be small. The use of
`adjust` option of _setcl_ in each `midob` should keep the FS close to the
correct time. It should be good enough to run a schedule. In any event, it
should better than any other approach without NTP. Since the DBBC3 will be
running on the correct time, small variations in the FS time should typically
not matter.

=== Multicast logging

Logging of DBBC3 multi-cast recording is controlled by the `tpicd` command.
When logging is enabled, for each multicast message received (nominal 1 Hz
rate), the following information is logged:

* `time` -- for each Core3H board in the system
* `pps2dot` -- (`pps_delay`) in nanoseconds for each Core3H board
* `tpcont`  -- Only if continuous cal is in use -- TPI counts for each BBC and IF configured for recording.
+
The counts are given in the order of cal _on_ then _off_
* `tpi`  -- Only if continuous cal is _not_ in use -- TPI counts for each BBC and IF configured for recording.
* `tsys` -- Only if continuous cal is in use -- Tsys for each BBC and IF configured for recording.

[NOTE]
====

Even when not being logged, multicast data is normally being received. A subset
can be seen in the <<Tsys monitor display>>. When the DBBC3 is busy processing
commands, it may suppress multicast messages. The FS will complain once every
20 seconds if it is not receiving multicast. When manually commanding the
DBBC3, e.g., for troubleshooting, these errors can be suppressed by using the
command:

    tpicd=stop

When _drudg_ generated setup procedures are executing they will suppress these
errors because they also use this command as they start. As a setup procedure
finishes, it will restart _tpicd_. This can also be done manually with the
command:

#TO DO: Check that is works when _tpicd_ is not configured.#

    tpicd

====

== Related Features

=== Minimizing the use of setup procedures

Normally, the FS sets the mode for each scan (unless there is continuous
recording). If this takes too long or makes the equipment unstable, the _drudg_
option `use_setup_proc yes` in _skedf.ctl_ can be used to minimize the
execution of the setup procedure.

WARNING: Not executing the setup each scan may not be robust if the equipment
sometimes loses it configuration. It is up to the individual stations to
determine whether minimizing its use is better than always using it.

With this enabled, _drudg_ will replace the calls to setup procedures (e.g.,
`setup01`) in the _.snp_ file with, e.g.:

 setup_proc=setup01

When the FS encounters this command, it will conditionally execute the setup
procedure if either of the following is true:

* This is first setup since the schedule was last started.
+

This will make sure the setup is run at the start and any restart of the
schedule.

* If there was a mode change, i.e., the name of the setup procedure changed.

The `use_setup_proc` option in _skedf.ctl_ has three possible settings:

* `yes` -- use the `setup_proc` command

* `no`  -- do not use the `setup_proc` command

* `ask` -- to prompt for `yes` or `no` for each schedule

If the option is not used, it defaults to `no`.

NOTE: The `use_setup_proc` option applies to all systems, not just ones using a
DBBC3.

Thanks to Jon Quick (HartRAO) and Harro Verkouter (JIVE) for suggesting this
option. They also suggested that it may be utilized as part of future features
for additional checking and resetting of the system.

=== Thread procedure

When a Mark 5C or FlexBuff recorder is in use, _drudg_ can optionally insert a
`thread__suffix__` procedure in each setup procedure (where `__suffix__` is a
mode specific suffix). This can be used to control whether the recordings for an
experiment is multi-threaded or single thread per file.

The contents of the procedure is same for every mode in the schedule. This
feature is controlled by the `vdif_single_thread_per_file` option in
_skedf.ctl_ control file. The option only needs to be used by stations that
need to always use a single thread per file or switch between experiments. If
the option is not present, no ``thread__suffix__`` procedure is inserted.  If
it is present, the possible setting are:

* `yes` -- to store a single thread per file, in which case, the
``thread__suffix__`` procedure contents are:

+
....
jive5ab=datastream=clear
jive5ab=datastream=add:{thread}:*
jive5ab=datastream=reset
....

* `no` -- for normal multi-threaded recordings, in which case, the
``thread__suffix__`` procedure contents are:

+
....
jive5ab=datastream=clear
jive5ab=datastream=reset
....


* `ask` -- to be prompted once per schedule for what to do

=== jive5ab_cnfg procedure

NOTE: This also applies to any system using a Mark 5C or FlexBuff recorder.

Each mode SNAP procedure produced by _drudg_ for Mark 5C and FlexBuff recorders
includes a call to the `jive5ab_cnfg` SNAP procedure. This procedure call is
inserted immediately after the `mk5c_mode`/`fb_mode` command (_or_ immediately
after the optional <<Thread procedure>> call). The procedure is mode independent,
i.e., the same procedure is used for all modes.

This procedure is a local `station` library procedure to allow tuning of the
configuration of _jive5ab_ for the specifics of the recorder, including
overriding the "`default`" configuration given by the `mk5c_mode`/`fb_mode`
command and a `thread__suffix__` procedure.

==== Default configuration

The `mk5c_mode`/`fb_mode` command sends the follow commands depending on
whether the recorder selected in _equip.ctl_ is `mk5c` or `flexbuff`. It does
_not_ depend on which command is used; `fb_mode` is just an alias for
`mk5c_mode`. It does depend on the data type, VDIF or 5B/Ethernet. Thus there
are two options for each recorder type. These are given below.

===== FlexBuff recorder

For FlexBuff recorders, there is a variable field `_socketbuffer_` in the
`net_protocol` command sent to the recorder.

. VDIF data
+

[subs="+quotes"]
....
mtu = 9000 ;
net_protocol = udpsnor : _socketbuffer_ : 256000000 : 4 ;
....

. 5B/Ethernet data
+

[subs="+quotes"]
....
mtu = 6000 ;
net_protocol = udpsnor : _socketbuffer_ : 256000000 : 4 ;
....

Where the _socketbuffer_ field depends on the total data rate:

*   32000000 -- data rate < 1 Gbps
*   64000000 -- 1 Gbps < data rate <= 4 Gbps
*  128000000 -- data rate > 4 Gbps

The _socketbuffer_ parameter is an important setting for trying to minimize
risk of packet loss when starting the recording. For (very) high data rates,
the `jive5ab_cnfg` procedure can be used to increase the _socketbuffer_ size to
values appropriate for that. This assumes that the FlexBuff has been tuned
(especially the kernel network buffer sizes) along the lines of the FlexBuff
tuning documentation at
https://www.jive.eu/~verkout/flexbuff/flexbuf.recording.txt.

===== Mark 5C recorder

. VDIF data
+
....
net_protocol = : 128k : 2M : 4;
packet = 36 : 0 : 8032 : 0 : 0 ;
....

. 5B/Ethernet data
+

....
net_protocol = : 128k : 2M : 4;
packet = 36 : 0 : 5008 : 0 : 0 ;
....

==== Overriding the defaults

You can override the commands sent by the `mk5c_mode`/`fb_mode` command or add
more by putting them in your local `jive5ab_cnfg`. This works because
`jive5ab_cnfg` is called after `mk5c_mode`/`fb_mode` command (_and_ after the
call to the optional <<Thread procedure>>) in the setup procedure. An example
of local customizations is given in the sub-sections below.

CAUTION: If put any commands in `jive5ab_cnfg` that depend on the data type,
VDIF or 5B/Ethernet, you would need to change them if there is a change in the
data type. This is not a concern for most stations.

===== Changing net_protocol

If you use different values for `net_protocol`, you can leave any field blank
that your don't need to change from what the FS has already sent. For example
to only set the _socketbuffer_ size to `64000000`, use:

....
net_protocol = : 64000000
....

====

Questions:

[start=9]
. Is the description correct for the above?
+

Harro: Yes

. Should we add guidelines for tuning parameters depending on the recorder?
+

Harro: I've put in a link to the FlexBuff tuning document

. Are there other examples we should give?

. Should `net_protocol` for Mark 5C have a value?
+

Harro: No, Mark5C recording ignores the `net_protocol` (the current command is
just to clear out any possible stale settings) - all is configured through
`packet=...`

. I know we decided to put this single file per thread option in
`jive5ab_cnfg`, but I can't remember now if we thought it was because it would
not be changed very often or if I was reluctant to ask for a _drudg_ option. I
am now thinking we might be able to add it as an option. A question is whether
it is worthwhile. I don't know how many stations would use it. I guess Eskil
would, but if so, is it better than commenting/un-commenting the relevant line
in `jive5ab_cnfg`?
+

Harro: Actually - having it as a _drudg_ option wouldn't be too bad! I think
there is wider interest in this feature. And it would make it more predictable
and convednient: stations can change as per experiment's request.
+

Ed: If we made it an option, it might be controlled by a _skedf.ctl_ option
`vdif_single_thread_per_file`:

* If the option is not present _drudg_ does nothing.

* If the option is set to `yes`, _drudg_ produces a `thread` procedure with the
commands above.

* If the option is set to `no`,  _drudg_ produces a `thread` procedure without
the `jive5ab=datastream=add:{thread}:*` command.

* If the option is set to `ask`, it will prompt for `yes` or `no` for each
experiment.
+

Maybe we could have `skip` option (do nothing) for `ask` as well if it would be
helpful.

* The `thread` procedure would come after `mk5c_mode`/`fb_mode` and before
`jive5ab_cnfg`.
+

Harro: Yup, that would allow stations to still override things the FS and
_drudg_ have done so far

====

=== drudg support

_drudg_ supports:

* Up to 128 dual side-band channels and eight IFs for VEX (_.vex_) schedule files.

* Up to 16 dual side-band BBCs (`1`-`16`) and two IFs (`a` and `b`) for Mark IV
(_.skd_) schedule files.

* The new <<DBBC3 commands>> that are used in setup procedures.

* The new _skedf.ctl_ options for <<Minimizing the use of setup procedures>>
and the <<Thread procedure>>.

* The following previously DBBC2 specific _skedf.ctl_ options can also be used
for DBBC3s:

** `cont_cal`
** `cont_cal_polarity`
** `dbbc_if_targets`
** `dbbc_bbc_target`
** `default_dbbc_if_inputs`
