//
// Copyright (c) 2020 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= FS 10.0.0-beta2 Update Notes
E. Himwich, D. Horsley, J. Gipson, J. Quick
Version 0.5 - November 2020

//:hide-uri-scheme:
:sectnums:
:sectnumlevels: 4
:experimental:

:toc:
:toclevels: 4

== Introduction

This update is intended as a test version for all stations using the
FS. This includes both stations using the main (non-VGOS) branch
(latest version _9.13.2_) and the VGOS branch (latest versions
_9.12.10_-_9.12.13_). Installing the new version as update for these
cases is fairly simple but has several steps, see the
<<Upgrading from an FS9 version to 10.0.0-beta2>>
section below.
It is also an update for stations that have been
testing _10.0.0-beta1_. The update from
_-beta1_ is less involved, see
<<Upgrading from 10.0.0-beta1 to 10.0.0-beta2>>.
Instructions are also included for updating from _-beta2_ to
the latest commit as described in
<<Upgrading from 10.0.0-beta2 to the latest commit>>.

The most significant changes in _10.0.0_ are:

. One unified version for all FS users.

+

Both non-VGOS and VGOS operations are supported by the new version.
Previous users of the main (non-VGOS) branch will need to add some new
local control files.

+

The most significant change is that previous main branch users will
find that in the new FS input is case sensitive, as it was already
in the VGOS branch.

. Support for use on both 32- and 64-bit systems.

+

The new version should run on 32-bit systems that currently support
the FS (we expect to support as far back as FSL8, but currently FSL9
is the limit), as well as on 64-bit systems. The update notice
includes instructions for transitioning to a 64-bit system, which may
require some relatively simple changes to station software. See the
<<Converting to a 64-bit system>> section below for more details.

+

A new FS Linux distribution, FSL10 (based on Debian _Stretch_), is now
available for 64-bit (and 32-bit) use. We recommend using this
distribution if you would like to move to using a 64-bit OS or need a
32-bit OS that is still under support (the base Debian distribution,
_Wheezy_, used for FSL9, and those for older FSLx versions, is no longer under
support). This also may be an alternative for users with distributions
(such as FSL7) that are too old to support the current FS.  Installation
instructions for FSL10 can be found at
<https://nvi-inc.github.io/fsl10>.

+

. Version control with _git_.

+

The FS source is now managed using _git_ and _github_ is used as
the distribution method.

+

The details of the model used for FS releases under _git_ are
described in _/usr2/fs/misc/release_model.txt_.

+

This change increases the importance of not modifying the
_/usr2/fs_ directory tree since such changes will make it more
difficult to simply `pull` updates to install bug fixes and new
features.

. Use of the FS display server is now recommended for normal use.

+

This change is new as of the _-beta2_ release.

Please also see the section <<Changes from previous versions>> below,
and its sub-sections, for details of the changes compared to the
latest FS9 versions.

Very significant contributions, in fact essential, were made by Dave
Horsley (UTAS, Australia and NVI/GSFC) and Tetsuro Kondo (NICT, Japan
and SHAO, China). Kondo-san pioneered 64-bit support in the FS with
his 64-bit implementations for the Sejong and Ishioka stations. Dave
built on his work in developing a version that would support 32- and
64-bit systems.

Dave also single-handedly imported the entire existent history of FS
source code into _git_. This includes over 130 FS9 versions (under
Linux), 17 FS8 versions (under VENIX), and two older versions (under HP
RTE-1000/A) going back to version 5.5 in 1988.  Having the source code
in _git_ greatly simplified the task of merging the non-VGOS and VGOS
versions. Dave also did the most critical work on that and provided
excellent guidance on using _git_. Having the historical code in _git_
is a great resource for understanding the evolution of the code.

As always, we are deeply indebted to Jonathan Quick (HartRAO, South
Africa) for his many significant contributions that go far beyond what
is explicitly mentioned below. In this particular case, his
contributions include testing and insights for adapting the code for
64-bit use, patiently solving various problems, developing FSL10, and
working out support for older FSLx distributions, particularly FSL8.

An appendix, <<Appendix A. Reference Appendix for Installation>>, is provided at
the end of this document.  It includes seven sub-sections:

. <<Upgrading from FS versions before the previous stable>>
. <<Example standard procedure libraries>>
. <<Cut-and-paste installation tips>>
. <<Making a back-up before installing>>
. <<Disk space requirements>>
. <<Set operations file permissions>>
. <<Fix .prc file define lines>>

If you haven't upgraded or installed the FS before, you may want to
review the appendix.  It is _strongly_ recommended that you back-up your
operational system before upgrading.

== Upgrading from 10.0.0-beta2 to the latest commit

This section covers updating from the _-beta2_ release if you
choose to install the latest commit. You must have already upgraded to
_-beta2_.

The latest commit is somewhat experimental.  We make ever effort to
keep the latest commit usable. However commits that are not tagged for
release are not intended for operations.

=== Fetch and make the latest commit

If you are using _git_, as is recommended, then as _prog_
execute:

             cd /usr2/fs-git
             git fetch
             git checkout master
             make -s

=== Updates

. If you are using _fesh_ to pull schedules from _cddis_, it is
recommend that you set the `FESH_EMAIL` environment variable with a
working email address to use as the password for _anonymous_ FTP-SSL
access (which is new in this release); this will remove the need to
enter it manually for each use.
+

If you have FSL8 or other old distribution that does not support
_curl_ SSL connections to _cddis_, it is possible to restore
the previous non-SSL FTP access. That can only be a temporary solution
since _cddis_ is planning to end non-SSL FTP access at the end of
October 2020.
+

Please see `*fesh -h*` for the details on how to use all of these
features.

. If you use RDBEs in your back-end and want to use the _rdbemsg_
utility to send operations messages, please customize your
_/usr2/control/rdbemsg.ctl_ control file by adding the _name_ line to
the file if you haven't already.  Full instructions are provided in
sub-step <<Update rdbemsg.ctl>>.

=== Review other changes

Please see the sub-section <<Changes since 10.0.0-beta2>> below
for details of the changes in the latest commit compared to the
_10.0.0-beta2_ release.

== Upgrading from 10.0.0-beta1 to 10.0.0-beta2

If you made it through the _-beta1_ update despite the errors and
omissions in the instructions (now corrected, we apologize), the
update instructions from the _-beta1_ are much simpler. The overall
method is described here:

=== Fetch and make the release

If you are using _git_ as is recommended, then as _prog_
execute:

             cd /usr2/fs-git
             git fetch
             git checkout -q 10.0.0-beta2
             make -s

=== Recompile station code

Recompile your station code. If your _/usr2/st/Makefile_ is
set-up in the usual way, then as _prog_ execute:

             cd /usr2/st
             make rmdoto rmexe all

=== Reboot upgrading from -beta1

IMPORTANT: Reboot the computer.  This is important for initializing shared
memory for the new version.

=== Login in as oper

The remaining steps assume you are logged in as _oper_.

=== Update control files from 10.0.0-beta1

. If your old version before the _-beta1_ update was _9.12.12_, you
should review the steps in <<Update control files>>. In particular,
there were two changes related to that old version to review:

.. In <<Copy control files>>, your _clpgm.ctl_ file may have been
needlessly overwritten. We think is is unlikely that any local
customizations were lost, but if they were, we apologize. Hopefully
you made a backup before trying the update. In which case, you should
be able to recover the file from the backup. Otherwise, hopefully the
changes needed are small. Additional changes to _clpgm.ctl_ are
covered farther below.

.. In <<Update equip.ctl>>, you may have ended up with extra lines
at the end of _equip.ctl_ because, according to the
_-beta1_ installation instruction, the FiLa10G input
select lines (including the comment line) were added
after the BBC3 configuration lines (including the
comment line) and extra DBBC3 configuration lines were
added. Presumably you have already sorted this out
because the FS would probably not have run if the file
was changed as previously described. If you have not
sorted this out, the change that is needed is to move
the FiLa10G input select lines before the DBBC3
configuration lines and to delete any additional lines
after the DBBC3 configurations lines. In case it is
helpful, more detail is provided in sub-step <<Review control files>>.

. There were two changes to the _clpgm.ctl_ control file:

.. The flags for the _monX_ programs in _clpgm.ctl_ have
changed from `a` to `d`.
+
Please check the file to see if those lines are present. If so, and the second field is `a`, please change it to `d` for each occurrence.

.. The line for the _scnch_ window has been generalized to
cover Mark 5 recorders as well as Mark 6.
+

Please update your file accordingly after comparing to the
new default:

             cd /usr2/control
             diff clpgm.ctl /usr2/fs/st.default/control

. In the _stpgm.ctl_ control file, the line for
the _scnch_ window has been generalized to cover Mark 5
recorders as well as Mark 6.
+
Please update your file accordingly after comparing to the
new default:

             cd /usr2/control
             diff stpgm.ctl /usr2/fs/st.default/control

. If you use RDBEs in your back-end and want to use the
_rdbemsg_ utility to send operations messages, please
customize your _/usr2/control/rdbemsg.ctl_ control file.
In particular, you should add the _station_ line to the
file.  Full instructions are provided in sub-step <<Update rdbemsg.ctl>>,
which is a new sub-step since _-beta1_.
+

NOTE: The instructions at <<Update rdbemsg.ctl>> also include setting
the `name` line in _rdbemsg.ctl_. That setting is not available as of
_-beta2_; it is provided in a later update. However, setting it for
_-beta2_ is benign and forward compatible.

=== Update .prc files from 10.0.0-beta1

If you initially upgraded from _9.13.2_, there is an optional
clean-up of your `calonnf`, `calonfp`, `caloffnf`, and
`calofffp` procedures, probably located in your _point_
procedure library in sub-step <<Remove extra if commands>>.

=== Other updates

. Please review sub-step <<Set FS_DISPLAY_SERVER>>. This sub-step did not exist for the
_-beta1_ release.  It contains information about making use
of the display server the default, which is strongly
recommended.

. Please review sub-step <<Update .Xresources>>. This sub-step did not exist for the
_-beta1_ release.  It contains information about updates
needed to the _~/.Xresources_ files for _oper_ and _prog_.
Please follow those directions.

. If you have installed the _-beta1_ as part of installing
FSL10, you can optionally rearrange your _.bashrc_ and _.profile_
files to agree with the new default.
+
As _oper_, you can find the differences between your
_~/.bashrc_ and _~/.profile_ files and the new defaults using, e.g.,:
+

             cd
             diff .bashrc  /usr2/fs/st.default/oper
+
The main changes are:

.. Move certain commands within _~/.bashrc_ so they are only used by interactive shells.
.. Move `unset TMOUT` from _~/.profile_ to _~/.bashrc_.
.. Enable the display server in _~/.profile_, as also mentioned above.

+
Likewise you can do this similarly for _prog_ (and any AUID
accounts if you are using those).

. If you updated to a 64-bit platform and installed the _go_
language as part of that, according to sub-step
<<Installing latest go language>>, then
you should register for _golang_ announcements as is now
described in that sub-step.

=== Review other changes

Please see the sub-section <<Changes since 10.0.0-beta1>> below
for details of the changes in 10.0.0-beta2 compared to the
10.0.0-beta1 release.

== Upgrading from an FS9 version to 10.0.0-beta2

This section covers upgrading from FS9, which was always 32-bit
only, to _10.0.0-beta2_.  However, this section is also utilized when
converting to a 64-bit system, as described in
<<Converting to a 64-bit system>>.
To accommodate that, there are few embedded
references to handle 64-bit systems. Otherwise the instructions are
completely independent of which type of system they are being used for.

There are two possible paths for upgrading:

. Upgrading from a main branch version. The main branch versions
are numbered _9.13.x_ and _9.11.x_ or older.  Specifically, versions
_9.12.x_ are not part of the main branch.  If you are upgrading
from a main branch version, it is assumed that upgrade is from
_9.13.2_, the previous stable release.  If you have a main branch
version older than version _9.13.2_ you should upgrade to _9.13.2_
first, please refer to appendix sub-section
<<Upgrading from FS versions before the previous stable>>
for more information.

. Upgrading from a VGOS branch version.  The VGOS branch versions
are numbered _9.12.x_.  The instructions provided in this section,_
below, are for installing as an upgrade to versions
_9.12.10_-_9.12.13_, the latest VGOS branch releases. As far as we
know, no other VGOS versions are in use.  If you have a different
version, please email Ed for more information.

The upgrade instructions for the update from the old main branch and
the old VGOS branch differ only in the step
<<Update control files>>. The
installation steps for upgrading are:

=== Back-up your operational system

Having a back-up to return to
will allow you to continue operations in case something goes
wrong with the installation.  For more details, please see
appendix sub-section <<Making a back-up before installing>>.

NOTE: If you are using FSL10 with a RAID, that sub-section points you to the
improved backup and test procedure that is available with
that distribution.

NOTE: That sub-section also includes a description of how to
preserve your operational files and switch back and forth
between an operational and a test set-up by changing
symbolic links.

=== Login as root

Login as _root_.

=== Download the FS

Place a copy of the FS _git_ repository to the _/usr2_ directory on
your computer. For example, you might do the following:

       cd /usr2
       git clone https://github.com/nvi-inc/fs.git fs-git

or alternatively, if you are using FSL8 or other old Linux
distribution, or otherwise need to use _ssh_ instead:

       cd /usr2
       git clone git@github.com:nvi-inc/fs fs-git

NOTE: Using _ssh_ requires you to have a _gitub_ account and for you
to add an _ssh_ public key from your machine's _root_ account to your _github_ account. For more information, go to
https://github.com/join and
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account.

=== Checkout the release

Checkout the _-beta2_ release from the local repository:

       cd fs-git
       git checkout -q 10.0.0-beta2

=== Set the /usr2/fs link

Set the link for the new FS version:

       cd /usr2/fs-git
       make install

Answer `*y*` to confirm installation.

NOTE: This step will change your _/usr2/fs_ symbolic link to point to
           _/usr2/fs-git_. To switch back to your old version, you
           will need to change the link manually.

The `make install` command may create and possibly rename some
existing directories if the FS was never installed on this system
before.  However, if you are using this step as part of upgrading
on your 32-bit system (this step is not used on a 64-bit system
you may be converting to), this should not be an issue.

=== Fix file permissions

Having the wrong ownership and/or permissions on the operational
files (procedure libraries, control files, schedules, and logs)
can cause errors during FS operations.  For a full discussion,
please refer to appendix sub-section <<Set operations file permissions>>.
For stations where all the operational files are
expected to owned by user _oper_ in group _rtx_, with permissions
(`ug+rw,o+r,o-w`) the following command will enforce this (note
that the _execute_/_search_ bits are not changed):

       /usr2/fs/misc/fix_perm

Answer `*y*` to the prompt if you wish to proceed. It is recommended for most stations.

=== Login as prog

IMPORTANT: Logout as _root_, and login as _prog_.

=== Set compiler

Starting with version 10.0.0, the standard
FORTRAN compiler for use with the FS is _f95_ (_gfortran_) and
we recommend that you use it. On the 32-bit systems you can
still use _fort77_, but you should only use it if you either
you don't have _f95_ or if you have FORTRAN station code that
is too difficult to convert to _f95_, see step <<Update station programs>> for more
details.

To select _f95_ as your compiler, you will need to set the
`FC` variable to this value. If your shell is _tcsh_ you can
use:

          setenv FC f95

If your shell is _bash_, you can use:

          export FC=f95

NOTE: For beta testing on a 32-bit system, you may not want to
make this change permanent since it is incompatible with
pre-_10.0.0_ versions.

To make this change permanent, you should add the appropriate
command to the appropriate _rc_ file depending on your login
shell: _~prog/.login_ for _tcsh_ or probably _~prog/.profile_
for _bash_.

=== Make the FS

          cd /usr2/fs
          make >& /dev/null

and then

          make -s

to confirm that everything compiled correctly (no news is good
news).

=== Update station programs

This step is for modifying your station programs in _/usr2/st_.  There
are two possible issues:

==== Case sensitive strings in antenna= commands

In FS9 versions, the strings used in `antenna=...` commands were always
converted to uppercase before being sent to _antcn_.  An part of the FS
input being case sensitive that this no longer happens.  If your
antenna, or your side of the antenna interface, requires that the
strings passed by the `antenna=...` command are uppercase, you have
two options:

. Convert your code. For simple backward compatibility,
change you _antcn_ program to always convert the
`antenna=...` strings to upper case. Alternatively, make
your code case insensitive.

. Convert the strings in your `antenna=...` commands
wherever they occur: SNAP procedures, SNAP schedules,
external programs, or scripts, to upper case. Field system
input is now case sensitive.

The former choice is probably the easier, but in some
cases the second  may be better. If you have questions about which to
use and how to do it, please email Ed.

==== Conversion of FORTRAN code

If you have station programs in
FORTRAN, please email Ed so he is
aware, but basically you have two options (also see step <<Set compiler>>):

. Change to using _f95_ for both the FS and your station
FORTRAN programs.   It is recommended that
you follow this approach for 32-bit systems and it is
necessary when moving to a 64-bit system.
+

You will need to adapt your __Makefile__-s
to use the same compiler options as the FS, which can be
found in _/usr2/fs/include.mk_.
As a first cut, it may work to add the following two lines
to your __Makefile__-s for FORTRAN programs:

    FFLAGS  += -ff2c -I../../fs/include -fno-range-check -finit-local-zero -fno-automatic -fbackslash
    FLIBS   += -lgfortran -lm

. Continue to use _fort77_ for both the
FS and your station programs. You should follow this approach _only_ if
you are on a 32-bit system and it is too difficult to convert to
_f95_.

=== Make local software

If _/usr2/st/Makefile_ is set-up in the standard way, you can do this with:

       cd /usr2/st
       make rmdoto rmexe all

NOTE: At this point, you are only trying to verify the code will _make_
successfully.  You may still need to debug it in the step <<Test the FS>>
below.

=== Reboot

IMPORTANT: Reboot the computer.  This is important for initializing shared
memory for the new version.

=== Login as oper

The remaining steps assume you are logged in as _oper_.

=== Update control files

This step is for updates to the local control files. There are five
sub-sections.  Differences for updating from different versions are
noted.  Please read all cases in each sub-section carefully to make
sure you find all the cases for your old version; sometimes an old
version is included in more than one case in a sub-section.

==== Update stcmd.ctl

The non-comments lines need another digit added to the
subroutine number. This sub-step is only need for updates from
_9.13.2_. You can fix your file with the commands:

  cd /usr2/control
  /usr2/fs/misc/cmdctlfix6 stcmd.ctl

You may also want to expand the (typically) second comment
line to correspond to the new format by adding a `U` after
character 18 to read as:

    *COMMAND     SEG SUBPA BO

==== Copy control files

You will need to execute the following commands to copy new
files that are needed (cut-and-paste is your friend). There
are three cases depending on what your old version was:

. Old versions _9.12.10_ and _9.12.11_:

               cd /usr2/control
               cp /usr2/fs/st.default/control/clpgm.ctl .
               cp /usr2/fs/st.default/control/rdbemsg.ctl .

. Old versions _9.12.12_ and _9.12.13_:

               cd /usr2/control
               cp /usr2/fs/st.default/control/rdbemsg.ctl .

. Old version _9.13.2_:

               cd /usr2/control
               cp /usr2/fs/st.default/control/dbba2.ctl .
               cp /usr2/fs/st.default/control/mk6c?.ctl .
               cp /usr2/fs/st.default/control/monit6.ctl .
               cp /usr2/fs/st.default/control/rdbc?.ctl .
               cp /usr2/fs/st.default/control/rdbe.ctl .
               cp /usr2/fs/st.default/control/rdbemsg.ctl .

==== Update equip.ctl

Add lines at the end: the
FiLa10G input select and the DBBC3 configuration lines.  There
are three cases, please check which applies for you.  In any
event, you should compare your _equip.ctl_ to the example as
described when you get to sub-step <<review-control-files,Review control files>>, to make sure there are
no duplicated lines or other problems caused by the commands
in this current sub-step, i.e., <<update-equip.ctl,Update equip.ctl>>.

. If your old version was _9.12.10_ or _9.12.11_, you will need
to add the final four lines of the example _equip.ctl_
file to yours:

  cd /usr2/control
  tail -n 4 /usr2/fs/st.default/control/equip.ctl >>equip.ctl

. If your old version was _9.12.12_ or _9.12.13_, you will need
to insert two lines before the final two lines.  This is
covered in sub-step <<Review control files>> below.

. If your old version was _9.13.2_, you will need to add the
final two lines of the example _equip.ctl_ file to yours:

  cd /usr2/control
  tail -n 2 /usr2/fs/st.default/control/equip.ctl >>equip.ctl

==== Review control files

You should compare your versions of the following files:

. _clpgm.ctl_
. _equip.ctl_
. _stpgm.ctl_

to the examples, e.g., using:

          cd /usr2/control
          diff clpgm.ctl /usr2/fs/st.default/control/ | less

and consider whether and what changes you should make to your
copies.

The following is a list of changes in these files. You will
need to make the corresponding changes to your copies of the
files.

===== Review clpgm.ctl

You may be able to just replace your copy with the new one.

. Old versions _9.12.10_ and _9.12.11_:
+
This file was not present so the new default version (copied by
commands in sub-step <<Copy control files>> above) should not
require modification.

. Old versions _9.12.12_, _9.12.13_, and _9.13.2_:
+
The `-title ...`  parameter for each
window was removed so that it is uniquely
supplied by the _.Xresources_ file. The _xterm_
program was added. The value of the `-name`
parameter for _erchk_ was changed from `ERRORS`
to `erchk`.
+
New lines were added for the useful
display window _scnch_, and the useful RDBE
display windows: _monit6_, and _monX_
(_X_=[_a_-_d_]). The _xterm_ program was added. The
_monan_ program was added to the default since
it is used at several sites. The value of the
`-name` parameter for _erchk_ was changed from
`ERRORS` to `erchk`.

===== Review equip.ctl

This file has the most complicated changes.
Please read all clauses to make sure you see
all that apply to your old version. The first
sub-section covers changes to non-comment lines; the
second, comments. The former are essential. The
later are in some sense optional, especially
when they refer to equipment you don't (or
never will) have. However, changing them now
may help avoid confusion at a later date.

======  Non-comment lines

.  Old versions _9.12.10_-_9.12.13_:
+
The line for DBBC PFB version was changed to have a
minimum version number of `v15_1`. The line is
shown here with the typical preceding comment:

    *DBBC PFB version
    v15_1    v15_1 or later
+
The line that defines the DBBC2 CoMo configuration was changed. Please
see item (12) in the installation instructions in _/usr2/fs/misc/fs91119up.txt_ for
full details on handling this. However, the following commands will
probably make the needed change if you don't have a DBBC2 or if your
DBBC2 configuration is four CoMos with one Core per CoMo:

  cd /usr2/control
  /usr2/fs/misc/dbbc_equip '1 1 1 1' equip.ctl
+
If the script prints a warning about the number
of IF power conversions being incorrect, the
issue must be resolved before continuing,
either by adjusting the number of power
conversions, adjusting the CoMo configuration,
or both.

. Old versions _9.12.10_ and _9.12.11_:
+
A FiLa10G input select line was added, but
sub-step <<Update equip.ctl>> above should have handled that.

. Old versions _9.12.12_ and _9.12.13_:
+
A "stanza" (actually one comment and one FiLa10G
input select line) was inserted before the
final "stanza" (typically one comment and one
DBBC3 configuration line). An example of the
lines inserted can be found near the end of the
default example _/usr2/fs/st.default/control/equip.ctl_ file. They are
listed here as well (one comment and one
FiLa10G input select line):

    *FiLa10G input select, one of: vsi1, vsi2, vsi1-2, vsi1-2-3-4, gps, tvg
    vsi1-2

. Old versions _9.12.10_, _9.12.11_, and _9.13.2_:
+
A new line for the DBBC3 configuration was added at the end, but sub-step
<<Update equip.ctl>>  above should have handled that.

====== Comment lines

. All old versions:
+
Compared to all old versions, comment lines
were added or modified for new equipment type
options.
+
. Old versions _9.12.10_-_9.12.13_:
+
The trailing comment on the line for the met. device was
reworded.

. Old versions _9.12.10_-_9.12.13_:
+
The comment lines describing the available clock
rates was completely rewritten and greatly
expanded, and an additional clock rate (`128`)
was appended to the end of the comment on
the clock rate line itself.

===== Review stpgm.ctl

. All old versions
+
The line for _erchk_ line was updated and new lines were
added for _monit2_, and _scnch_ for when the
display server is in use. Using the display
server is now the default and strongly
recommended.
+
IMPORTANT: If you are _not_ planning to use the FS display
server, we recommend you comment out the lines
for _erchk_, _mont2_, and _scnch_. If they are
used without the display server and they are
accidentally closed, the FS will be killed.
+
The new line for _erchk_ differs from the previous
commented version with the addition of the
`-name erchk` parameter and removal of the
`-title ...` and `-geom ...` parameters, so
that the latter two are uniquely supplied by
the _.Xresources_ file.
+
If you are using the display server you may
want to add other _monitX_ programs. If so, you
may also want to add resources for them (if
 they aren't already there) in the
_~/.Xresources_ files for _oper_ and _prog_.

==== Update rdbemsg.ctl

If you have RDBEs for your back-end and will use the _rdbemsg_
utility to send operations messages, you will need to
customize your _/usr2/control/rdbemsg.ctl_.

. You will need to update the `station` two letter code (lower
case) and the `name` station name to your station's values. The
station name is usually defined in the
_/usr2/control/location.ctl_ file.

. If you don't have a _HubPC_ (_mci_) node for front end monitor
and control, you should comment out that line.

. You should set the addresses for the RBDE-A (`R-A`) through RDBE-D
(`R-D`). The example file uses aliases, _rdbea_ through _rdbed_, that
you can define in _/etc/hosts_.  Likewise, if you have an _mci_ node,
you should set its alias, _hubpc_, in _/etc/hosts_. (It is usually
necessary to have _root_ access to modify _/etc/hosts_.)  Alternatively
of course, you can use any scheme you prefer for defining these
addresses in _rdbemsg.ctl_.

. The default email address `to` is for the `ivs-vgos-ops` mail
list. You can of course change that to whatever you like. You
can also temporarily over-ride the address in the _rdbemsg_
utility itself.

=== Update .prc files

This step is for updates to your SNAP _.prc_ procedure libraries.
Only one change is required: converting from using the _go_
FS program to _rte_go_. A second change is
optional and only relevant if upgrading from _9.13.2_: removing
`if=cont_cal,,` from the `fivpt` and `onoff` procedures for
`calon` and `caloff` procedures. These two changes are described next:

==== Convert from go to rte_go

Convert use of the old FS _go_ program to use _rte_go_. This
change came about because the compiler for the _go_ language
conflicts with the old program name _go_. This change is necessary even if
you do not have the _go_ language compiler installed.

To make this change for all your _.prc_ procedure libraries,
execute:

           cd /usr2/proc
           /usr2/fs/misc/go_fix *.prc

Files that are changed will have a pre-change back-up copy
with the extension _.bak_.

==== Remove extra if commands

This sub-step is optional and only relevant if you are upgrading
from _9.13.2_. You can remove the `if=cont_cal,,` as a prefix from before the
`calon` and `caloff` commands in you `calonnf`, `calonfp`,
`caloffnf`, and `calofffp` procedures, probably located in your
_point_ procedure library. This is just a clean-up and not
making this change will have no impact.

=== Miscellaneous FS related changes

There are two changes: set the `FS_DISPLAY_SERVER` environment variable
for _oper_ and _prog_ (this is only needed if you were not running the
FS display server before) and update the _~/.Xresources_ file for the
_oper_ and _prog_ accounts.

==== Set FS_DISPLAY_SERVER

Set the `FS_DISPLAY_SERVER` environment variable for _oper_ and
_prog_.  This will make using the display server the default for
your system.  We strongly recommend this, but if it is not suitable
for you for some reason you can skip this.  If you are
already using the display server, you can also skip this sub-step.

IMPORTANT: If you don't use the
display server, you will probably need to update the _stpgm.ctl_ file for that
case as described in sub-step <<Review stpgm.ctl>> above.

If _oper_ uses the _bash_ shell then in the _~oper/.profile_
file, you can uncomment or insert

          export FS_DISPLAY_SERVER=on

If _oper_ uses the _tcsh_ shell then in the _~oper/.login_
file, you can uncomment or insert

          setenv  FS_DISPLAY_SERVER on

You should logout and login again after making this change.

Please make the corresponding change for _prog_ while logged
in as _prog_.

==== Update .Xresources

Update the _~/.Xresources_ file for the _oper_ and _prog_
accounts.  The main change was to add values for the `erchk`,
`scnch`, and _helpsh_  windows.  There were some minor changes
for other windows, but what to use for the changed values may
depend on the resolution of your display.  The example values
worked well for an FSL10 installation on a system with a
non-GPU CPU.

As _oper_, you can find the differences between your file and
the example file with:

  cd
  diff .Xresources /usr2/fs/st.default/oper

Please make any changes to your file that you find
appropriate, but at a minimum you should probably add the
lines for _erchk_, _scnch_, and _helpsh_ if not already
present. You will need to logout and login again (or reload
the X-resources a different way) for the changes to become
effective.

All the new lines are at the end of the file, if need to add
lines for _monit6_, _erchk_, _scnch_, and _helpsh_, you can
use:

  cd
  tail -n 24 /usr2/fs/st.default/st.default/oper/.Xresources >>.Xresources

To add lines for just _erchk_, _scnch_, and _helpsh_, you can
use:

  cd
  tail -n 20 /usr2/fs/st.default/st.default/oper/.Xresources >>.Xresources

To add lines for just _helpsh_, you can
use:

  cd
  tail -n 6 /usr2/fs/st.default/st.default/oper/.Xresources >>.Xresources

You can update _prog_'s _.Xresources_ file similarly, but you
will need to be logged in as _prog_.

=== Miscellaneous FSLx changes

None are required for this update.

===  Test the FS

NOTE: If you are following the process in this step on your
32-bit system as part of converting to 64-bit (section <<Converting to a 64-bit system>>
below), you may prefer to only do a quick check now and
save extensive testing until you are verifying the 64-bit
installation. You could always go back and do more testing
on the 32-bit system to help resolve the origin of problems
that are noticed on the 64-bit system.

Generally speaking, a fairly thorough test is to run a test
experiment.  Start with using _drudg_ to rotate a schedule,
_drudg_-ing it to make _.snp_ and _.prc_ files, making listings,
and any other pre-experiment preparation and tests you normally
do, then execute part of schedule, and perform any normal
post-experiment plotting and clean-up that you do.  The idea here
is to verify that everything works as you expect for normal
operations.

=== Consider when to update your back-ups

NOTE: This step may not be appropriate if you are beta testing
since the beta test versions are not intended for
operations.

It would be prudent to wait until you have successfully run an
experiment or two and preferably received word that the
experiment(s) produced good data.  The chances of needing to use
your back-up should be small.  If something does happen, you can
copy the back-up to the (now assumed bad) updated disk.  You can
then either use the restored disk or apply the FS update again.
The FSL10 test procedure has more options for recovery.  Managing
this is a lot easier and safer if you have a third disk.

== Converting to a 64-bit system

To upgrade your installation to 64-bit, the easiest approach is
probably to first upgrade the FS installation on your 32-bit system to
run FS _10.0_, then transfer it to a 64-bit system. This will allow you
verify the upgrade before trying to transfer it.

An alternate method is to copy the station files from your 32-bit
system and then perform the upgrade. This will allow you to upgrade
without modifying your existing system.  These two methods only differ
in when the files are copied to the new machine, as described in
<<Transferring files>> below, and when the update instructions in
in <<Upgrading from an FS9 version to 10.0.0-beta2>>
above are used, in
<<Copying files>> or <<Finishing up>>.

The instructions below assume that the existing system you are using
has a standard FS configuration in terms of symbolic links and
directories.  If your system is different, you will need to adjust
what you do accordingly, but you may still find the outline of steps
useful.

Please follow these steps:

=== Install a 64-bit system

Install a 64-bit system on a different (hopefully new) computer. We
recommend https://nvi-inc.github.io/fsl10/, which is based on Debian _Stretch_ and tuned for FS use.

NOTE: Despite what the URL above says about which version of the FS to
check-out, at this time you should check-out _10.0.0-beta2_,

You can install a different distribution. However, we can't
provide as much support in that case. The FSL10 distribution is
tuned to provide a complete platform for running the FS. For other
distributions you may have to make adjusts for several things that
an FSL10 installation provides, including:

- which packages are installed
- required user accounts and groups

=== Rename default directories

. Rename the existing default station specific FS related directories
on the 64-bit computer to get them out of the way:

      cd /usr2
      mv control   control.DEFAULT
      mv sched     sched.DEFAULT
      mv proc      proc.DEFAULT

. If you use the _/usr2/tle_files_ directory on your old computer,
you should rename the one on the 64-bit computer:

      cd /usr2
      mv tle_files tle_files.DEFAULT

. If your station software is in _/usr2/st-0.0.0_ on your old computer,
you should rename the one on the 64-bit computer:

      cd /usr2
      mv st-0.0.0  st-0.0.0.DEFAULT

. The _log_ directory were not included above, since it should
essentially be empty on the new computer, but could also be
renamed if you prefer:

      cd /usr2
      mv log       log.DEFAULT

=== Transferring files

For transferring your files, there are two options:

. If you are upgrading your installation on your old computer
first, please follow the directions in section
<<Upgrading from an FS9 version to 10.0.0-beta2>> above for
your old system. Then return here and follow the steps in
<<Copying files>> below.

. If you are not upgrading your old computer first, proceed
directly to <<Copying files>> below.

In either case, proceed to <<Handling station code>> after copying your files.

==== Copying files

Your station specific FS related files can be copied from the old
computer using any convenient method.  If both systems are on the
network this can be particularly easy. The following example sub-steps use
this approach. You should replace the example host name _old_ (and in
file names) with your old system's host name. You may need to provide
the appropriate password for each _scp_ command (if so, you can
simplify the process by coping your 64-bit computer's _root_ _ssh_
keys to the old machine with _ssh-copy-id_ first). These commands must
be executed as _root_, and except where noted, from the 64-bit system.

. Transfer operations directories:

.. Transfer _control_, _sched_, and _proc_:

       cd /usr2
       scp -pqr oper@old:/usr2/control .
       scp -pqr oper@old:/usr2/sched .
       scp -pqr oper@old:/usr2/proc .
+
Note that your _sched_ and _proc_ directories could be
large and take a significant amount of time to transfer.

.. Transfer _log_:
+
It can be useful to have your old log files on the new
computer, but that transfer could be even larger:

  cd /usr2
  scp -pqr oper@old:/usr2/log .

.. Transfer _tle_files_:
+
If you use the _/usr2/tle_files_ directory on your old
computer, you can also transfer it:

  cd /usr2
  scp -pqr oper@old:/usr2/tle_files .

. Fix the permissions on the operations directories/files you
transferred. You can fix their permissions and ownerships
to the standard with:

  /usr2/fs/misc/fix_perm
+
Answer `*y*` to confirm.
+
If you don't have a _/usr2/tle_files_ directory, you will
get a message that there is no such directory. That is
benign unless you expect such a directory to be there.

. Make back-up copies of the operational directories. This
sub-step is optional but may be useful so that there are
unmodified copies of the directories from the old machine
to use for reference:

  cd /usr2
  cp -a proc      proc-old
  cp -a control   control-old
  cp -a sched     sched-old
+
and possibly:

  cd /usr2
  cp -a log       log-old
  cp -a tle_files tle_files-old

. Transfer your station software directory (and make a
reference copy). This is usually the target directory
pointed to by the _/usr2/st_ symbolic link. On your old
computer, you can find its name with:

  ls -l /usr2/st
+
In the rest of this sub-step, the target _st-1.0.0_ will be used as an
example, but you should replace it with your actual target. If your
target is _st-0.0.0_ you should rename the default on the new
computer first as described in sub-step <<Rename default directories>> above.

.. On the new computer, copy the target from the old computer to the
new computer, e.g.:

  cd /usr2
  scp -pqr oper@old:/usr2/st-1.0.0 .

.. On the new computer, set the _/usr2/st_ symbolic link to point to
the target directory:

  cd /usr2
  ln -fsn st-1.0.0 st

.. You can set its permissions and ownership for _prog_ with:

  cd /usr2
  chown -R prog.rtx st-1.0.0
  chmod -R a+r,u+w,go-w st-1.0.0

.. You can make a reference copy with:

  cd /usr2
  cp -a st-1.0.0 st-1.0.0-old

. Copy your _oper_ and _prog_ directories to the new
computer. This sub-step is optional. The FSL10 installation
made default home directories for these users on _/usr2_.
If you did not have customized content for the users on
the old computer, you could just use the versions on the
new computer. Still it may be useful to have a copy of
your old directories on the new system for reference,
especially if you realize later that there were additional
programs and files you want to use on the new system.

.. You can accomplish the transfers as _root_ using:

  cd /usr2
  scp -pqr oper@old:~ oper-old
  scp -pqr prog@old:~ prog-old

.. You probably want to set their permission and ownership so the
appropriate users are allow to access them:

  chown -R oper.rtx /usr2/oper-old
  chmod -R u+rw,go-rw /usr2/oper-old

  chown -R prog.rtx /usr2/prog-old
  chmod -R u+rw,go-rw /usr2/prog-old

+
You can customize the home directories on the new computer
to include any features you want from the old system.


. At this point you are principle done transferring files.
However, it is also possible that you may need or want
other changes such as:

.. Copy other files or programs from the old system
.. Install additional Debian packages
.. Copy/set-up additional configuration files, such as:

    /etc/hosts
    /etc/hosts.allow
    /etc/hosts.deny
    /etc/ntp.conf

+
You can use a similar process to the one above to transfer
and/or make reference copies of more files and directories.

=== Handling station code

If you have already converted your old system to FS _10.0_, you have
should have followed the directions in <<Update station programs>>.

There is one general issue, handling string passed by the `antenna=...` command.
Then you may need to use one or both of the additional sub-steps below
depending on whether you have FORTRAN and/or C station
code. You may have already handled the first two issues if you
updated on a 32-bit system first (for FORTRAN if you did not
convert to using _f95_, you will still need to do that).  In any
event, make sure your code _make_-s successfully before proceeding
to step <<Finishing up>> below. You may still need to debug it later.

==== Handling strings used in antenna=... commands

If you pass strings to your antenna, or your side of the
antenna interface, with `antenna=...` commands, you may need to
change how those strings are handled. If you have not already
done this, please see sub-step <<Case sensitive strings in antenna= commands>>
above for the details.

==== Handling FORTRAN code

. If you have FORTRAN station code, it will need to be converted
to use _f95_. If you have not already done so, please see sub-step
<<Conversion of FORTRAN code>> above for the details.  Please email
Ed if you have FORTRAN station code,
regardless of whether you have a problem converting it or not.

==== Handling C code

If you have C station code, it should work as written unless
you have declared integers that interface to the FS as `long`.
For a start at fixing those, please see
https://github.com/dehorsley/unlongify.

The following sub-steps describe how to install the _unlongify_ tool.

===== Install go language

If you haven't already, you will need to first install the _go_
language. If you are using FSL10, you can install the _go_ language in
one of two ways listed below: <<Installing golang package>> or
<<Installing latest go language>>. We recommend the first way for
those that are only using _go_ for the _unlongify_ tool. After
installing the _go_ language, continue the _unlongify_ installation
instructions starting at <<Configure prog account for go language>>.


====== Installing golang package

You can use the Debian package management system to
install _go_.  This will give you an older version of _go_
that is perfectly adequate for the task at hand and is
supported by the normal security mechanism. To install it
this way, as _root_ use:

  apt-get install golang

====== Installing latest go language

You can install the latest version of _go_, but this is
outside the normal security mechanism. In this case, you
will need to manage your own updates, which may not be
suitable for an operational environment. If you use this
method it is recommended that you sign-up for _go_
language announcements so that you will be informed when a
security update is available.  You can sign-up at
https://groups.google.com/forum/#!forum/golang-announce.

Another alternative is to delete the latest _go_ (`*rm -rf
/usr/local/go*`) after you have made _unlongify_. You can
always re-install it if you need it again.

Both the initial install and updates are handled by the
_fsadapt_ script, as _root_:

  cd /root/fsl10
  ./fsadapt

In the first window select _only_ the option (i.e., only that line has a `*`):

  goinst    Install (or 'Update') Go programming language

Then press kbd:[Enter] while `OK` is highlighted. On the next screen, press kbd:[Tab]
to highlight `Cancel` and the press kbd:[Enter].

===== Configure prog account for go language

Once you have the _go_ language installed, you need to define
the `GOPATH` environment variable and include it in _prog_'s
path.  The default _~prog/.profile_ file includes two commands
(commented out by default) to accomplish these things:

 #export GOPATH=~/go
 #PATH="$GOPATH/bin:/usr/local/bin/go:$PATH"

You will need to uncomment these two lines and then logout
and log back in again as _prog_ or, in a current login session
for _prog_, re-execute the file:

....
  . ~/.profile
....

===== Install unlongify

Then you should be able to execute the installation step given
at the URL above (as _prog_):

  cd
  go get github.com/dehorsley/unlongify

Please read the _README.md_ file, which is displayed at the
URL above. Alternatively, it can be viewed at
_~/prog/go/src/github.com/dehorsley/unlongify/README.md_ where
it was installed by the above command. Please pay particular
attention to the `Note` about system calls.

Once your code _make_-s successfully proceed to step <<Finishing up>>
below. You may still need to debug the code.

=== Finishing up

As mentioned previously in <<Transferring files>>,
there are two possible paths at this point:

. If you upgraded to FS10 on your old system before copying your files
to the new systems and have made any needed changes in your station
code as described in step <<Handling station code>> above, you should
re-test your system, using the <<Test the FS>> step as a guide (from
<<Upgrading from an FS9 version to 10.0.0-beta2>>).

. If you did not upgrade your old system before copying your files,
but have now copied them and have made any needed changes in your
station code as described in step <<Handling station code>> above, you should complete
the upgrade by starting with step <<Reboot>> (from
<<Upgrading from an FS9 version to 10.0.0-beta2>>),
completing it and all the following steps.

== Changes from previous versions

Each sub-section covers both FS and _drudg_ changes since specific
versions. The changes are listed incrementally. Thus the cumulative
changes are constructed by combining the changes for the relevant
versions. A summary of the changes is given in each sub-section,
followed by a more detailed description. References such as
https://github.com/nvi-inc/fs/issues/36[#36] refer to specific issues
reported at https://github.com/nvi-inc/fs/issues.

The contents of this section are:

. <<Changes since 10.0.0-beta2>>
. <<Changes since 10.0.0-beta1>>
. <<Changes since 9.13.2>>
. <<Changes since VGOS versions>>

A complete history of changes can be found using the `git log`
command.

The file _/usr2/fs/misc/changes.txt_ contains the old history of
changes in FS9. The file _/usr2/fs/misc/VENIX_changes.txt_ contains
the old history of changes in FS8. However these two files have been
merged into the history given by `git log`.

The history of _drudg_ is also described in more detail in
_/usr2/fs/drudg/change_log.txt_.


=== Changes since 10.0.0-beta2

This sub-section covers changes in the latest commit since _-beta2_.

==== Summary of FS changes since 10.0.0-beta2

. Add _new_ifdbb_ script for (RDBE) VGOS stations.

. _fesh_ uses FTP-SSL (closes https://github.com/nvi-inc/fs/issues/36[#36]).

. The station name in _rdbemsg_ is no longer hard coded (closes
https://github.com/nvi-inc/fs/issues/62[#62]).

. Restore `help` for DBBC3 commands.
. Improvements in _fsserver_ (includes tentatively closing https://github.com/nvi-inc/fs/issues/69[#69]).
. Improvements in _gnplt_ (closes https://github.com/nvi-inc/fs/issues/72[#72] and https://github.com/nvi-inc/fs/issues/73[#73]).
. Improvements in `help` files (includes closing https://github.com/nvi-inc/fs/issues/75[#75]).
. Improvements to update notes (this document):

==== Details of FS changes since 10.0.0-beta2

. Add _new_ifdbb_ script for (RDBE) VGOS stations. This script is
intended as a tool to allow stations, and schedule writers, a way
to update schedules for changes in the _ifdbb_ procedure used by
VGOS stations, particularly those with RDBE back-ends. For RDBE
stations, the attenuation used in the signal chain, which is set
by the schedule, depends on the observing mode being used and the
conditions at the station. The provides a way to incorporate
needed changes into schedules. If the script is run without other
command line arguments, it will output "help" information.

. _fesh_ uses FTP-SSL (closes
https://github.com/nvi-inc/fs/issues/36[#36]). The use of FTP-SSL for
_cddis_ access will allow use of _cddis_ after non-SSL FTP access is
disabled there, expected at the end of October 2020. It is
recommended that the `FESH_EMAIL` environment variable be set to
avoid the need to provide an email address each time use as the
_anonymous_ FTP-SSL password.
+

If you have FSL8 or other old distribution that does not support
_curl_ SSL connections to _cddis_, it is possible to restore the
previous non-SSL FTP access by setting the `FESH_CDDIS_METHOD`
environment variable to `ftp`.  However, this method will no longer work
once non-SSL FTP access ends.
+
Please see `*fesh -h*` for the details on using these features.

. The station name in _rdbemsg_ is no longer hard coded (closes
https://github.com/nvi-inc/fs/issues/62[#62]). The station name is now
set in _rdbemsg.ctlr_ control file. Thanks to Chevo Terraza (MGO) for
reporting this.

. Restore `help` for DBBC3 commands. The selection of DBBC3 specific commands
was lost in the merge of the VGOS and main branches. It is now restored.

. Improvements in _fsserver_ (includes tentatively closing https://github.com/nvi-inc/fs/issues/69[#69]).

.. _spub_/_ssub_ occasionally froze (tentatively closing
https://github.com/nvi-inc/fs/issues/69[#69]). This may have been
caused be the byte order being wrong in buffered stream `cb` This
situation is still being monitored to verify that it is fixed.

.. Fixed `clean` function in _Makefile_.
.. Fixed _sspub_ to support more than 2^32^ messages.

. Improvements in _gnplt_ (closes https://github.com/nvi-inc/fs/issues/72[#72] and https://github.com/nvi-inc/fs/issues/73[#73]).

.. _gnplt_ now updates the date in updated _.rxg_ files (closes
https://github.com/nvi-inc/fs/issues/72[#72]).  The original developer,
(Tomas Gille), did very good work developing this second version of
_gnplt_, but ran out of time in his internship and was unable to include
this minor but important feature.

.. _gnplt now works on FSL8 (Lenny) again (closes
https://github.com/nvi-inc/fs/issues/73[#73]).  Some reccent
improvements in _gnplt_ made it fail for FSL8.

. Improvements in `help` files (includes closing https://github.com/nvi-inc/fs/issues/75[#75]).

.. The `help` file for the `ddbc` command was expanded to also support
the `dbbc2` and `dbbc3` commands and now includes a description of the
output for multi-line responses for these commands (closes
https://github.com/nvi-inc/fs/issues/75[#75]). The `help` command now
works for the `dbbc2` and `dbbc3` commands.

.. The `help` file for the `fila10g` command was expanded to also
support the `fila10g2` command. The `help` command now works for the
`fila10g2` command.


. Improvements to update notes (this document).

.. Modify steps for updating to a specific commit after _-beta2_ to
use the latest commit instead. As well as being
simpler, this is part of a new approach to try to keep the update
notes current with the latest commit. It is important
to be aware that the latest commit is not a version
intended for operations. We make every effort to make sure it is
bug free, but problems may occur. Since it represents the
"bleeding edge" of development, features may not be as stable nor
use as reliable as released (tagged) versions.

.. Add missing _rdbemsg.ctl_ customization.
.. Include items added since _-beta2_.

.. Reorganized as an _.adoc_ file and now available as a web page at:
https://nvi-inc.github.io/fs/.
.. Improve structure and correct some errors from original _.txt_ version.
.. Some typo/wording fixes.

==== Summary of drudg changes since 10.0.0-beta2

_drudg_ opening message date is `2020Sep14`.

. Fix crash if `$HEAD` is the last block in a `.skd` file.

==== Details of drudg changes since 10.0.0-beta2

. Fix crash if `$HEAD` is the last block in a `.skd` file. Fixed bug in _reads.f_.

=== Changes since 10.0.0-beta1

This sub-section covers changes in _-beta2_ since _-beta1_.

==== Summary of FS changes since 10.0.0-beta1

The following is a summary of FS changes since _10.0.0-beta1_ but not
included in _10.0.0-beta2_ or later.

. Improve _fesh_ (includes closing https://github.com/nvi-inc/fs/issues/34[#34]).
. Update example _equip.ctl_ (includes closing https://github.com/nvi-inc/fs/issues/35[#35]).
. Fix some error messages (includes closing https://github.com/nvi-inc/fs/issues/43[#43] & https://github.com/nvi-inc/fs/issues/22[#22]).
. Improve _plog_.
. Restore `if` command.
. Update GPL in files.
. Remove usage of `system()` call to find _help_ file_(closes https://github.com/nvi-inc/fs/issues/40[#40] & https://github.com/nvi-inc/fs/issues/3[#3]).
. No longer set _/usr2/fs_ and _/usr2/st_ to be owned by _prog_.
. Add checking for a procedure or schedule file before attempting to open it (closes https://github.com/nvi-inc/fs/issues/45[#45]).
. Add more log header lines.
. Fix year wrap error message in procedure logging (closes https://github.com/nvi-inc/fs/issues/23[#23]).
. Fix remaining case of a closed procedure library causing a crash if
there was an attempt to execute a procedure from the library was fixed.
. Move X resources for _helpsh_ to _~/.Xresources_.
. Move unsetting of `TMOUT` environment variable for _oper_ to
    _~/.bashrc_ in the default files.
. Improve error logging for _dbbcn_.
. Improve `help` page for _tpicd_.
. Add `popen` time-out feature.
. Make use of the FS display server the default.
. Make _fsclient_ honor the `-n` flag properly (closes https://github.com/nvi-inc/fs/issues/48[#48]).
. Make _fsclient_ ignore prompt in no-X11 mode (closes https://github.com/nvi-inc/fs/issues/49[#49]).
. Add _fsserver_ improvements and log support (includes closing https://github.com/nvi-inc/fs/issues/29[#29] & https://github.com/nvi-inc/fs/issues/25[#25]).
. Eliminate `cls_chk` error from `inject_snap -w ...` command when
    an error occurs (partly closes https://github.com/nvi-inc/fs/issues/50[#50]).
. Fix labels in _gnplt_ windows that display the gain curve
    coefficients (closes https://github.com/nvi-inc/fs/issues/51[#51]).
. Improve holog/MASK.
. Fix _onoff_ for the DBBC3 rack (closes https://github.com/nvi-inc/fs/issues/52[#52]).
. Add support for DBBC3 to `if=cont_cal,...` (closes https://github.com/nvi-inc/fs/issues/54[#54]).
. Update `help` pages for _onoff_ and _fivpt_.
. Always check for day 248 problem in _setcl_ (closes https://github.com/nvi-inc/fs/issues/56[#56]).
. Change the flags for the _monX_ programs in _clpgm.ctl_ from `a`
    to `d`.
. Generalize the _scnch_ window to cover Mark 5 recorders (closes
    https://github.com/nvi-inc/fs/issues/61[#61]).
. Update _misc/release_model.txt_.
. Improve update notes (this document).

==== Details of FS changes since 10.0.0-beta1

. Improve _fesh_ (includes closing https://github.com/nvi-inc/fs/issues/34[#34]).

.. A typo in the error message for when
the schedule is already downloaded was fixed (closes https://github.com/nvi-inc/fs/issues/34[#34]). Thanks to
Morgan Goodrich (KPGO) for reporting this.

.. The internal version number was replaced with the FS version.

. Update example _equip.ctl_ (includes closing https://github.com/nvi-inc/fs/issues/35[#35]).

.. The example DBBC3
firmware is now more sensible (closes https://github.com/nvi-inc/fs/issues/35[#35]). Thanks to Eskil Varenius (Onsala)
for reporting this.

.. The minimum DBBC3 firmware version required was added in a comment.

. Fix some error messages (includes closing https://github.com/nvi-inc/fs/issues/43[#43] & https://github.com/nvi-inc/fs/issues/22[#22]).

.. Fixed errors in
_control/fserr.ctl_.  Errors in some double double-quotes (`""`)
lines and some incorrectly reused error codes were fixed (closes
https://github.com/nvi-inc/fs/issues/43[#43]).  Thanks to Alexander Neidhardt (Wettzell) for reporting
these.

.. The errors for a `tnx` command not being found when
attempting to manipulate its display setting were clarified
(closes https://github.com/nvi-inc/fs/issues/22[#22]).  Thanks to Jon Quick (HartRAO) for reporting this.

.. Error messages that should refer to the (not yet implemented)
`active_rdbes` and `active_mk6s` commands were corrected to no
longer incorrectly refer to the `rdbe_active` and `mk5_active`
commands, respectively.

.. Obsolete errors for the, no longer used, _sw.ctl_ control file
were removed.

. Improve _plog_.

.. Use of an environment variable `NETRC_DIR` was
added to support not having the _.netrc_ file in the user's home
directory was added. Please see `*plog -h*` for details on how to
use this.

.. The internal version number was replaced with the FS version.

. Restore `if` command. It had accidentally been overlooked in
_-beta1_. Thanks to Beppe Maccaferri (Medicina) for reporting
this.

. Update GPL in files. The GPL header was added to the
_holog/MASK/*.m_ and _misc/mk6in*_ scripts and removed from
_fserver/tests/convey.*_.

. Remove usage of `system()` call to find `help` files (closes https://github.com/nvi-inc/fs/issues/40[#40] &
https://github.com/nvi-inc/fs/issues/3[#3]). The `help` command no longer uses the `system()` to find the
correct `help` file to display.

. No longer set _/usr2/fs_ and _/usr2/st_ to be owned by _prog_. This
was an error in the _misc/fsinstall_ script.

. Add checking for a procedure or schedule file before attempting to
open it (closes https://github.com/nvi-inc/fs/issues/45[#45]). This change is to avoid accidentally closing
an active procedure or schedule file if the new one specified in
the `proc=...` or `schedule=...` commands, respectively, does not
exist (or has incorrect permissions).  Previously, if the files
did not exist (or did not have the correct permission), the old
file would be closed. Thanks to Jon Quick (HartRAO) for pointing
out this inconsistency.
+
The old behavior was partly a consequence of how the original file
handling worked on the HP-RTE, but is not sensible for how the
SNAP commands should work.  Note that this is a non-backward
compatible change in how the SNAP commands seem to behave.
Previously supplying a non-existent procedure or schedule file
name would cause the closure of the corresponding file. Now to
close an open procedure or schedule without opening a new one, a
null parameter must be supplied, i.e., `proc=` or `schedule=`.  As
before, the latter will not close an open schedule procedure
library.

. Add more log header lines. Log header lines were added for
`uname()` system information and the compile time value of the
`FC` environment variable were added.

. Fix year wrap error message in procedure logging (closes https://github.com/nvi-inc/fs/issues/23[#23]).
This fixed a benign and spurious error message if a log was kept
open past the end of the year and any procedures that had last
been logged in the previous year were executed again.  Thanks to
Eskil Varenius (Onsala) and Alexander Neidhardt (Wettzell) for
reporting this.

. Fix remaining case of a closed procedure library causing a crash if
there was an attempt to execute a procedure from the library was
fixed. This case could happen if the schedule that was opened was
named _station_, which would lead to the closure of an already
open schedule procedure library (there cannot be _station_
schedule procedure library since _station_ can only be opened
once).

. Move X resources for _helpsh_ to _~/.Xresources_. This allows the
geometry and other parameter of the FS `help` display _xterm_ to be
controlled locally.

. Move unsetting of `TMOUT` environment variable for _oper_ to
_~/.bashrc_ in the default files. This allows all interactive
shells to disable the time-out. Additionally, some settings were
rearranged in _~/.bashrc_ to make them only apply to interactive
shells (this was also done for _prog_ and AUID accounts). This
change is only relevant for stations using FSL10.

. Improve error logging for _dbbcn_. The name of the program is now
correctly displayed.

. Improve `help` page for _tpicd_. Made it clearer that when in the
`no` mode, `data_valid=on` will only start logging of _tpicd_ data
when a schedule is running and not-blocked.  This behavior was
inherited from the VGOS branch where accidentally leaving _tpicd_
logging RDBE multi-cast data after closing a schedule or halting
it creates a lot of extra log entries. This is probable beneficial
for all back-ends. The fact that is changed from _9.13.2_ is now
noted in <<Changes since 9.13.2>> below.

. Add _popen_ time-out feature. There is a now a `-t ...` time-out
option. If the command being run has a time-out feature, it is
generally better to use the command's feature. See `help=sy` for
more details.

. Make use of the FS display server the default. This was changed as
of the _-beta2_ release.

. Make _fsclient_ honor the `-n` flag properly (closes https://github.com/nvi-inc/fs/issues/48[#48]). This
eliminates opening "double" windows if _fsclient_ is run with `-n`
under an already running _fsclient_.

. Make _fsclient_ ignore prompt in no-X11 mode (closes https://github.com/nvi-inc/fs/issues/49[#49]). If FS
client is in no-X11 mode, it created a _fs.prompt_ when instructed
by the server. This change removes that behaviour, though it may
cause an issue if no other clients exist to dismiss the prompt,
see issue https://github.com/nvi-inc/fs/issues/49[#49]. If this is a problem for anyone's use case we will
need a new feature here.

. Add _fsserver_ improvements and log support (includes closing https://github.com/nvi-inc/fs/issues/29[#29] & https://github.com/nvi-inc/fs/issues/25[#25]).
These changes introduce new functionality to _fsserver_, as well as
simplifies some use cases.

.. The first major change is that the server now only needs to use
one socket when using _websockets_ -- address which start with
"ws://" (closes https://github.com/nvi-inc/fs/issues/29[#29]). The new default base URL for all _fsserver_
streams and control channels is now:

    ws://127.0.0.1:7083
+
(70 83 are decimal ASCII encoding of `F` and `S`.)
+
This can be changed by editing `FS_SERVER_URL_BASE` in
_include/params.h_; however, we will likely introduce command-line
flag and/or environment variable to set this in the future.
+
This is should be safe to expose on the network (rather than just
the loop-back), but users may wish to use an HTTP(S) as a proxy to
provide some authentication/authorisation.
+
This was enabled by factoring out functionality _spub_ into a
reusable "buffered stream" library, which has been incorporated
into _fsserver_. All the behaviour of streams are now managed
within the _fsserver_ process rather than an external _spub_
instance.

.. The second major change of this patch is the addition of the FS
log to the streams available from the server (closes https://github.com/nvi-inc/fs/issues/25[#25]).
(Previously only the "display" was available, which has a reduced
time-stamp format and filters some output.)
+
This is available at

    FS_SERVER_URL_BASE/log
+
that is, by default

    ws://127.0.0.1:7083/log

.. A third change is that the server now continues running after the
FS is terminated. This allows clients to detect the FS termination
and prevents a socket conflict if the FS is terminated and
restarted in quick succession. The only user visible impact will
be a slight delay if the FS is restarted quickly after termination
while the old session is finishing up. This also means, after an
FS upgrade, it's important to either shutdown the server
(`*fsserver stop*`) or restart the system.

.. Fourth, the server can now accept snap commands to be sent to FS,
e.g.:

   fsserver fs snap "terminate"
+
This allows clients to interact with the FS directly through
fsserver rather than needing access to _inject_snap_.
+
No filtering or authorisation is implemented on this command
channel, so it effectively allows complete command execution
privileges in the FS context to anyone with access to the socket.
Note this is also true for _inject_snap_ on a standard system. If
a station wishes to limit local access they can use
iptables/nftables, or use the server in UNIX socket mode and use
file system permissions. Stations that would like to enable remote
access should implement their own authentication/authorisation
that suits their needs, e.g. SSH port forwarding or HTTP proxying.

.. Finally, this patch also upgrades the included messaging library
_nng_ to version _1.3.0_, which brings with it some performance
improvements and bug fixes, the most obvious to FS users caused
some _ssub_ instances in "wait" mode to use a high amount of CPU
time.

. Eliminate `cls_chk` error from `inject_snap -w ...` command when
an error occurs (partly closes https://github.com/nvi-inc/fs/issues/50[#50]). This was caused by
_inject_snap_ not implementing the new linkage that was added for
_fserr_. This is covered in issue https://github.com/nvi-inc/fs/issues/50[#50]. To correctly retrieve the
error message would have required making a new interface to
_fserr_ or subsuming it into library routine that both _ddout_
and _inject_snap_ could use. It was not possible to do either in the
available time. Instead _inject_snap_ was modified to output the error
without the message, but pointing out that the message can be
found in the log and display. Thanks to Dave Horsley (Hobart) for
reporting this.

. Fix labels in _gnplt_ windows that display the gain curve
coefficients (closes https://github.com/nvi-inc/fs/issues/51[#51]). Previously the labels, when displayed
were in reverse order. In one window, there were no coefficient
labels at all. Thanks to Beppe Maccaferri (Medicina) for reporting
this and testing the solution.

. Improve _holog/MASK_. The elevation spacing was corrected for the
example in step (3), using _holog.m_. Axis titles were added to
_plot_mask.m_.

. Fix _onoff_ for the DBBC3 rack (closes https://github.com/nvi-inc/fs/issues/52[#52]). A code block from
_9.12.13_ in _onoff/get_samples.c_ had been omitted, preventing
sampling of the TPI values and causing _onoff_ to crash. Thanks to
Eskil Varenius (Onsala) for reporting that this caused a crash.

. Add support for DBBC3 to `if=cont_cal,...` (closes https://github.com/nvi-inc/fs/issues/54[#54]).  Thanks
to Eskil Varenius (Onsala) for reporting that this was missing.

. Update `help` pages for _onoff_ and _fivpt_. Added a section on
switching between continuous and non-continuous cal.  Removed
`if=cont_cal,,` in `calon`/`off`-`nf`/`fp` procedures.  Add
recovery method for misconfigured cal.

. Always check for day 248 problem in _setcl_ (closes https://github.com/nvi-inc/fs/issues/56[#56]).
Previously _setcl_ only checked for the day 248 problem (due to
use of 32-bit arithmetic in the time handling code), if the time
model was _not_ `computer`. In principle, when the model is
`computer` there is no need to check for this issue.  However,
since the time is still managed with the same 32-bit arithmetic as
for the non-`computer` models, it is still necessary to check.
Not doing so was an oversight. The result was that there were no
warnings of an impending 248 day time problem if the model was
`computer`.  This is now fixed. Thanks to Richard Blaauw (WSRT),
and subsequently Jon Quick (HartRAO) for reporting this.

. Change the flags for the _monX_ programs in _clpgm.ctl_ from `a`
to `d`.  Since they do not depend on the FS, they can continue
running after the client is closed.

. Generalize the _scnch_ window to cover Mark 5 recorders (closes
https://github.com/nvi-inc/fs/issues/61[#61]).  The _scnch_ window was initially developed for Mark 6
recorders. The form has now been generalized to cover Mark 5
recorders as wekk

. Update _misc/release_model.txt_. The release steps were
clarified.

. Improve update notes (this document).

.. The `-q` option was added to
the `pull` to suppress the detached HEAD warning.

.. A sentence was added to the description of the change to using
_git_ that it now even more important to not change the contents
of the _/usr2/fs_ source tree.  Changing the source tree will make
it harder to install bug fixes and updates.

.. The paths to the example control files now include the needed
intermediate directory _fs/_.

.. Some conditional changes in step <<Update control files>> were corrected to properly
depend or not depend on the old version being _9.12.12_. If you
installed the _-beta1_ version and your old version was _9.12.12_
you should review the instructions in step <<Update control files>> to verify
everything has been covered.

.. A sub-step was added to make using the FS display server the default.
If you installed _-beta1_ you should check sub-step <<Set FS_DISPLAY_SERVER>> for
changes that are needed.

.. A sub-step was added for updating the _~/.Xresources_ file for _oper_
and _prog_. If you installed _-beta1_ you should check sub-step
<<Update .Xresources>> for changes that are needed.

.. A sub-step to update where the `TMOUT` environment variable is unset
for stations using FSL10 was added in
<<Upgrading from 10.0.0-beta1 to 10.0.0-beta2>>.
 If this applies to you to
please check sub-step <<Other updates>> in that section above.

.. A recommendation was added to sign-up for the _go_ language
announcements to be informed of security updates if you are
installing the latest version of _go_ as described in sub-step
<<Installing latest go language>>. If you used that method it is recommended that you
sign-up for the announcements.

.. The update instructions now include advice on updating from
_-beta1_ to _-beta2_, in <<Upgrading from 10.0.0-beta1 to 10.0.0-beta2>>.

.. This sub-section on changes in release _-beta2_ was added.

==== Summary of drudg changes since 10.0.0-beta1

_drudg_ opening message date is `2020Jun30`.

The following is a summary of _drudg_ changes since _10.0.0-beta1_, but
not include in _10.0.0-beta2_ or later.

. Fix uninitialized variables
. Fix missing `preob` when `EARLY` start non-zero.
. Add support for additional wait at the end of recording for broadband.
. Update comment on line three of _.snp_ files.

==== Details of drudg changes since 10.0.0-beta1

. Fix uninitialized variables. Several previously uninitialized variables are
    now initialized. As part of this `implicit none` was added to all FORTRAN
    routines that did not have it before, except for _xat.f_.

. Fix missing `preob` when `EARLY` start non-zero. This was broken
    in the implementation of staggered start for FS _9.13.0_ and has been
    restored.

. Add support for additional wait at the end of recording for
    broadband. This allows schedules to include a fixed amount of
    additional wait for buffering per station. This seems to be needed
    for Mark 6 recorders in configurations that otherwise would
    require no buffer time for disks that are slower than nominal.

. Update comment on line three of _.snp_ files. Previously at the
    end of line, the number of passes and the tape length were
    listed. Since there is no tape support, these fields were replaced
    with the recorder type.

=== Changes since 9.13.2

This sub-section covers changes in _beta1_ since _9.13.2_, the last
version of the FS9 main branch.

==== Summary of FS changes since 9.13.2

#TODO: Complete this sub-section.#

. Source version control is maintained with _git_.
. Source code now works on 32- and 64-bit platforms.
. Input is now case sensitive.
. `tpicd=no` requires a running (not halted) schedule to log data.

==== Details of FS changes since 9.13.2

#TODO: Complete this sub-section.#

==== Summary of drudg changes since 9.13.2

#TODO: Write this sub-section.#

. Source version control is maintained with _git_.
. Source code now works on 32- and 64-bit platforms.

==== Details of drudg changes since 9.13.2

#TODO: Write this sub-section.#

=== Changes since VGOS versions

This sub-section covers changes in _beta1_ since the FS9 VGOS branch, last version _9.12.13_.

==== Summary of FS changes since VGOS versions

#TODO: Write this sub-section.#

 1. Source version control is maintained with _git_.
 2. Source code now works on 32- and 64-bit platforms.

==== Details of FS changes since VGOS versions

#TODO: Write this sub-section.#

==== Summary of drudg changes since VGOS versions

#TODO: Write this sub-section.#

. Source version control is maintained with _git_.
. Source code now works on 32- and 64-bit platforms.

==== Details of drudg changes since VGOS versions

#TODO: Write this sub-section.#

== Known Bugs

(There have been no changes in this section since the previous version.)

The following is a summary list of known bugs. They are described in more
detail after the list. (Please also check the github issues at:
https://github.com/nvi-inc/fs/issues)

. Do not run _fmset_ for extended periods.
. `odd` and `even` head types not supported for Mark IV & VLBA4.
. `odd`/`even` head types not supported for VLBA style tapeforms.
. _chekr_ does not check the status of the Mark IV formatter or Mark 5 recorder.
. Extraneous errors when tape is stopped by low tape sensor.
. `comm=` command in _logex_ extracts only the first command.
. S2 error scheme clumsy.
. No extra spaces allowed in _ibad.ctl_ file.
. _onoff_ and _fivpt_ programs hang.
. FS SNAP command pages don't list tape drive suffix numbers.
. LBA rack TPI detector is not usable.
. `mk5b_mode` and `bit_stream` commands only report the expected sample rate.
. Some _fmpsee_ routines do not report file I/O error through the log system.
. Some systems calls, particularly in _mk5cn_ and _dbbcn_, use separate
`UN` errors to elaborate on errors in system calls.

A more detailed discussion of these bugs follows.

. Do not run _fmset_ for extended periods.  For stations that have
formatter that can be set with _fmset_, the program should not be
run for extended periods of time.  The _fmset_ program should be
used only to set or briefly verify that the formatter time is
correct.  Do not leave _fmset_ running after completing either of
these tasks, especially during an experiment.
+
The _fmset_ program dominates the Field System when it is running
and this is likely to interfere with the running of an experiment
or other activities.  The only way to detect the time from the
VLBA formatter with greater precision than one second it to wait
for the seconds response from the formatter to change.  This
requires the FS to communicate with the formatter almost
continuously.  A similar problem exists for the S2 recorder.  This
problem is less severe for other formatters, but extended use of
_fmset_ in this case should be avoided as well.  A reminder about
this is included in the _fmset_ menu.

. `odd`/`even` head types not supported for Mark IV & VLBA4.  The
Mark IV and VLBA4 rack version of the `form` command and the Mark
IV and VLBA4 recorder versions of the `repro` and `parity`
commands do not support the `odd` and `even` parameters for the
read and write head types and reproduce electronics in the
_head.ctl_ control file.  This means that automatic substitution
of odd or even head in passes that use only even or odd heads
respectively does not occur.  The only correct settings for the
read and write head parameters and reproduce electronics is `all`.
This will be fixed in a future revision.  Please email Ed if
you are missing some tracks and need to work around this
limitation.

. `odd`/`even` head types not supported for VLBA style tapeforms.
For any mode recorded with VLBA style tapeform (14 index
positions), the only correct setting of the read and write head
types on the _head.ctl_ is `all`.  This will be fixed in a future
revision.  Please email Ed if you are missing some tracks and
need to work around this limitation.

. _chekr_ does not check the status of the Mark IV formatter or Mark
5 recorder.  Now that most communication problems with the Mark IV
formatter have been solved, this will be possible and will be done
in the future.  _chekr_ support will be implemented for Mark 5
despite communication problems, they will have to be ignored
unless they extend beyond a certain amount of time.

. Extraneous errors when tape is stopped by low tape sensor.  When a
tape drive has been commanded to move the tape and then stops
because it hit the low tape sensor (or when S2 recorders hit the
BOT or EOT), _chekr_ will complain periodically that the tape
drive is not in the correct state.  In principle the FS should be
smarter about this.  However, if the tape is managed correctly by
the schedule this error message should never occur.  If it does,
then it it an indication that there is either a problem with: (1)
the schedule, (2) the check procedures, (3) the recorder, or (4)
the tape is too short.  If any of these cases apply they should be
corrected.  It is more likely that this error message will occur
when the tape is being controlled manually.  In this case, issuing
an `et` command will convince the FS that the tape drive should be
stopped and the error message will cease.

. `comm=` command in _logex_ extracts only the first command.  The
`comm=` command in _logex_ extracts only the first command
commanded and displayed.  This problem was noted by Giuseppe
Maccaferri (Medicina).

. S2 error scheme clumsy.  The error and status response number
reporting scheme for S2 recorders is clumsy.  FS errors that have
mnemonic `rl` are mostly error responses from the recorder or the
RCL interface library that is used to communicate with the
recorder.  If the numeric part of an `rl` error is greater than
-130, then it is the error code returned by the recorder.  If the
numeric part is less than -130, but greater than -300, then add
130 to the value, the absolute value of the result is the error
response code from the RCL library.  For values less than or equal
to -300, a FS error has been detected.  Status response codes are
all reported with mnemonic `rz` and the numeric value is the
negative of the status response code.  In all cases an appropriate
error or status message is displayed.  These messages are retained
in the log.

. No extra spaces allowed in _ibad.ctl_ file.  The format of the
_ibad.ctl_ must not contain any leading or embedded spaces.  In
systems that use the LLP AT-GPIB driver (pre-FS Linux 4), if
either the option `no_untalk/unlisten_after` is misspelled or an
incorrect device name is supplied, the driver will cause a
segmentation violation when it is initialized and the FS will
terminate.  Unfortunately there is no way to prevent this problem
in a general way; it reflects a limitation in the driver.

. _onoff_ and _fivpt_ programs hang.  The _onoff_ and _fivpt_ programs
have been known to _hang_ mysteriously.  This seems to be caused by
some problem with the _rte_go_ mechanism that is used to restart the
program when it pauses to allow a SNAP procedure, such as `calon` or
`caloff` to execute.  The _rte_go_ that is used to restart the program
fails for some reason.  This has been exceedingly difficult to debug
because it is intermittent and fairly rare.  There is however a good
work around for it.  The `calon` and `caloff` procedures are called by
procedures `calonfp` and `calofffp` for _fivpt_ and `calonnf` and
`caloffnf` for _onoff_.  _fivpt_ and _onoff_ may hang during (or
actually just after) the execution of one these procedures that
_fivpt_ and _onoff_ will typically hang.  Using `sy=rte_go fivpt &` or
`sy=rte_go onoff &`, as appropriate, may help get the FS unstuck, but
the measurement results should probably be discarded.  If that doesn't
help, you will have to terminate the FS to recover. You can prevent it
from happening again (for this procedure) by adding the lines:

  !+1s
  sy=rte_go fivpt &
+
to the end of `calonfp` and `calonfffp`.  For `calonnf` and
`caloffnf`, please add:

  !+1s
  sy=rte_go onoff &
+
If you see other situations where _fivpt_ and _onoff_ hang, please
email Ed about it.

. FS SNAP command pages don't list tape drive suffix numbers.  The
FS SNAP manual pages and the `help` pages available through the
`help=` command do not reflect when multiple versions are
available with different suffixes depending on the number of drive
specified in the control files.  For example, there is only a
`tape` page, no `tape1` or `tape2` page.  However, the `help`
facility will display the version of the command with no suffix
when an available command with a suffix is used.  For example, if
two drives are defined, then `help=tape1` and `help=tape2` will
work, but `help=tape` will not and vice-versa if only one drive is
defined.

. LBA rack TPI detector is not usable.  The Australian LBA Data
Acquisition System currently lacks a functional total power
detector though support has been included.  To allow approximate
system temperature calibration, all the setup commands and the TPI
detectors of the modules of a co-existing Mark IV rack are
currently also available when the rack type is specified to be
LBA4.

. `mk5b_mode` and `bit_streams` commands only report the expected
sample rate.  The value of the actual clock rate is not read back
from the recorder in order to calculate the actual effective
sample rate.  Consequently, the query log output includes
parenthesis around the sample rate as indication that it is not
read, but expected.  The `mk5c_mode` command does report the
actual sample rate.

. Some _fmpsee_ routines do not generally report file I/O error
through the log system for programs within the FS, specifically
_boss_, _incom_, and _aquir_.  The `fmpopen()` routine does use
the log system to report errors.  Those are the most common
errors.  However other routines report errors with terminal
output.  These other routines should eventually use the log
system.

. Some systems calls, particularly in _mk5cn_ and _dbbcn_, use
separate UN errors to elaborate on errors in system calls.  These
should eventually be integrated into the main error message, but
whether this makes the errors messages too long (maximum 120
characters) should be considered.

== Appendix A. Reference Appendix for Installation

This appendix collects several topics that are useful for installation
in general, but are usually not needed for routine updates. There are seven sub-sections:

. <<Upgrading from FS versions before the previous stable>>
. <<Example standard procedure libraries>>
. <<Cut-and-paste installation tips>>
. <<Making a back-up before installing>>
. <<Disk space requirements>>
. <<Set operations file permissions>>
. <<Fix .prc file define lines>>

=== Upgrading from FS versions before the previous stable

This sub-section only covers upgrading from "main" branch versions,
i.e., versions _9.12.x_ are excluded.

For reference, the list of the most recent _critical updates_, since
version _9.3.13_, is given below.  These are updates that must be
applied sequentially.  Please start with the next update with a later
version number than what you have and apply it and the following
listed versions before upgrading to the new version.  You can find the
latest versions of installation notes for these FS versions in the
_/usr2/fs/misc_ directory.  The list of critical updates is:

  9.4.0
  9.5.3
  9.5.12
  9.6.9
  9.7.7
  9.9.2
  9.10.4
  9.11.6
  9.11.8
  9.11.19
  9.13.2

Strictly speaking you do not need to actually use the source archives
(_.tgz_ files) of the previous versions.  You can just follow the steps
in the upgrade notices for your local files for the corresponding FS
versions.  However, it can be very helpful to actually install each
version to help make sure that all of the upgrade steps have been
completed and that the FS will run _and_ to test it as described.
This can be particularly helpful when the upgrade requires some
modifications to your local programs.  So it probably best to actually
install _and_ test each version along the way.  This is especially
true if you have to upgrade through more than one previous version.
Otherwise if a step was overlooked, it might be hard to identify for
which version the error was made.

You can find the archives for old versions at: http://www.metsahovi.fi/fs/dist/old/

They can also be extracted from a local FS _git_ repo with, e.g.:

  git checkout 9.11.19

If you have a version older than _9.3.13_, please email
Ed for more information.

=== Example standard procedure libraries

For reference purposes, information about the example station
libraries for different equipment configurations is given here.  The
files are found in _/usr2/fs/st.default/proc_.  They can be referred to
and compared to what you have in _/usr2/proc/station.prc_.

_Only_ for new installations (or complete re-installs), you can copy
the default version for your equipment to _/usr2/proc_ renaming it to
_station.prc_ in the process, e.g.:

  cd /usr2/proc
  cp -i /usr2/fs/st.default/proc/3station.prc station.prc
  chmod a+rw station.prc

The `-i` option will prompt before overwriting an existing
_station.prc_ to give you a chance to recover if you did not realize
you already had a _station.prc_ file.  The table of correspondence
between equipment types and default library names is given next.

.Example station.prc libraries
|=============================================================
|Equipment - Rack/Drive1/Drive2 |Prefix letters |Station Library
|k42/k42             |k42        |k42station.prc
|k42k3/vlba          |k42k3v     |k42k3vstation.prc
|k42mk4/vlba         |k42mk4v    |k42mk4vstation.prc
|k42mk4/vlbab/vlbab  |k42mk4vb   |k42mk4vstation2.prc
|k42/k5              |k42k5      |k42k5station.prc
|lba/s2              |ls2        |ls2station.prc
|lba4/s2             |l4s2       |l4s2station.prc
|mk3/mk3a            |3          |3station.prc
|mk4/mk4             |4          |4station.prc
|mk4/mk5a            |45         |45station.prc
|mk4/vlba4           |4v4        |4v4station.prc
|mk5/mk5b            |5          |5station.prc
|none/s2             |s2         |s2station.prc
|vlba/s2             |vs2        |vs2station.prc
|vlba/vlba           |v          |vstation.prc
|vlba/vlba2          |v2         |v2station.prc
|vlba/vlba/vlba      |v          |vstation2.prc
|vlba4/vlba4         |v4         |v4station.prc
|vlba4/mk5a          |v45        |v45station.prc
|vlba4/vlba42        |v42        |v42station.prc
|vlba5/mk5b          |v5         |v5station.prc
|dbbc/mk5b           |d          |dstation.prc
|=============================================================

If an example for your equipment type is listed, please email
Ed about it so that it can be added.

=== Cut-and-paste installation tips

You can use cut-and-paste to reduce the amount of typing involved in
the installation.  This reduces the chances of missing required spaces
and other easily missed characters (like `.`) in the commands.  The
basic idea is to have two different terminals open, _either_ (preferred)
two different xterm terminals either on the local X display or
remotely logged in _or_ (more cumbersome) two different VT text
terminals (kbd:[Control+Alt+Fn]) on the FS computer you are
upgrading.  You can then switch back and forth between the terminals,
reading the instructions as you scroll through them (with _more_ or
_less_) on one terminal and entering commands on the other.  You can
cut-and-paste complicated commands from the terminal with the
instructions to the terminal where you are entering commands as
needed.  You can use _ssh_ or _su_ to switch users as needed on
the terminal where you are entering commands. For example, you can
change to being _prog_ by executing:

 ssh -X prog@localhost

or

 su - prog

Please don't forget to log back out when you need to change users
again or you may develop a series of _nested_ logins.  Any steps that
require rebooting will of course completely log out all of your
terminals; you will need to re-login again from scratch to continue.
At the end of the update, it is recommended that you login as _oper_
on the local X display for the final testing.  Please also note that
in order to paste into the X display login shell window for _oper_ and
_prog_, you typically must use kbd:[Shift+Insert].  If you have any
questions about how to cut-and-paste please email Ed.

=== Making a back-up before installing

This sub-section has two parts. The first covers back-ups. The second
covers using symbolic links to switch between operational and test
set-ups.

==== Back-ups

Before you begin the upgrade make sure you have a current back-up of
your system in case something goes wrong. If you are using one of the
FSLx distributions, there are options for each below

If you have SCSI disks, Section 5.7 of the FS9 _Computer Reference_
manual has a discussion of drive ID numbers if you are unsure about
these.

Except for FSL10 (which uses a different scheme), you would normally
choose to install the update on your primary disk after having made
and verified your back-up.  Once the installation is complete, has
been tested, and used for a little while, you can copy over your
back-up with the upgraded primary.  If the upgrade fails, you should
restore the back-up to the primary for operations.  You can then try
to upgrade again when it is convenient.  In a desperate situation, you
can use the back-up for operations.  You may choose to install the FS
on your back-up disk for testing and then later copy the back-up onto
the primary once you are satisfied with the new version.  In any
event, please be sure to make a fresh back-up (and put it safely away)
before attempting an update installation.

=====  FSL10 (stretch)

See the procedure at: https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing

=====  FSL9 (wheezy)

If the system is configured as a RAID, please see
_/usr2/fs/misc/FSL9_RAID.pdf_ section "APPLYING AN UPDATE" for directions
for applying an update.

=====  FSL8 (lenny), FSL7, (etch), and FSL6 (sarge)

If the system is configured as a RAID, please see http://www.metsahovi.fi/fs/docs/pre_FSL9_RAID.pdf
section "APPLYING AN UPDATE" for directions for
applying an update.

=====  FSL5 (woody)

We recommend you use the _tar_ based back-up that is part of the
rotating disk back-up scheme.  A draft document that describes this
method is available in http://www.metsahovi.fi/fs/docs/backups2.pdf.

=====  FSL4 (potato) and earlier

If you have an even older FS Linux distribution, please use the
disk-to-disk back scheme described in Section 5.8 of the FS9 _Computer
Reference_ manual.

If you are running one of these FSLx distributions and do not have
documentation on how to make a back-up, please email
Ed for advice.

==== Using symbolic links

_After_ you have made a backup (to allow recovery in case something
bad should happen), you can use symbolic links to your directories to
change between your operational and test directories.  This may allow
you to more easily switch between an operational and testing
configuration.

In the following examples, it is assumed that _/usr2/fs-9.13.2_ is
your operational FS version and the FS you want to test is in
_/usr2/fs-git_ and that _/usr2/st-1.0.0_ is the directory with your
station software; you should substitute the correct directories if
they are different. All commands must be entered as _root_. Extra
white space has been added only to improve legibility.

If you have aliased `rm` to `rm -i` and `mv` to `mv -i` and `cp` to
`cp -i`, you will prompted to confirm before anything destructive
occurs. If so, and if everything is set-up properly below, the only
cases where you should only be asked to confirm is for deleting the
symbolic links in examples for <<Switch permanently to new version>>
and <<Switch permanently to old operational version>>.

===== To set-up initially for testing:

Your operational station software is assumed to be in _/usr2/st-1.0.0_. Make appropriate adjustments if they are different.

. Make sure the FS is not running.

. Enter the command:

  cd /usr2
+
Make sure there are no existing directories: _control-ops_,
_proc-ops_, _st-1.0.0-ops_, _control-test_, _proc-test_,
_st-1.0.0-test_, or use different names and adjust this and
other examples accordingly.

. Enter the commands:
+
....
mv control   control-ops
mv proc      proc-ops
mv st-1.0.0  st-1.0.0-ops

cp -a control-ops   control-test
cp -a proc-ops      proc-test
cp -a st-1.0.0-ops  st-1.0.0-test

ln -sfn control-test  control
ln -sfn proc-test     proc
ln -sfn st-1.0.0-test st
....

. Then follow the installation instructions, you will be
modifying the _-test_ versions.

===== Switch temporarily to operational version

Your operational FS version is assumed here to be in _/usr2/fs-9.13.2_
and your operational station software is assumed to be in
_/usr2/st-1.0.0_.  Make appropriate adjustments if they are different.

. Make sure the FS is not running.

. Enter the commands:
+
....
cd /usr2
ln -sfn control-ops   control
ln -sfn proc-ops      proc
ln -sfn st-1.0.0-ops  st
ln -sfn fs-9.13.2     fs
....

. Reboot.

The above commands (even rebooting if you like) can be put in
a script if you need to do this multiple times.

===== Switch temporarily to test version

Your test FS version is assumed here to be in _/usr2/fs-git_
and your test station software is assumed to be in
_/usr2/st-1.0.0-test_.  Make appropriate adjustments if they are different.

. Make sure the FS is not running.

. Enter the commands:
+
....
cd /usr2
ln -sfn control-test   control
ln -sfn proc-test      proc
ln -sfn st-1.0.0-test  st
ln -sfn fs-git         fs
....

. Reboot.

The above commands (even rebooting if you like) can be put in
a script if you need to do this multiple times.

===== Switch permanently to new version

When you are satisfied with the testing of the new system
you can switch permanently.

Your test FS version is assumed here to be in _/usr2/fs-git_
and your test station software is assumed to be in
_/usr2/st-1.0.0-test_.  Make appropriate adjustments if they are different.

. Make sure the FS is not running.

. Enter the commands:
+
....
cd /usr2

rm  control
rm  proc

mv control-test   control
mv proc-test      proc
mv st-1.0.0-test  st-1.0.0

ln -sfn st-1.0.0  st
ln -sfn fs-git    fs
....

. Reboot.

Your old operational directories (named _*-ops_) are left for possible future
reference.

===== Switch permanently to old operational version

Follow these steps if you need to switch back permanently, perhaps
because the installation failed.

Your operational FS version is assumed here to be in _/usr2/fs-9.13.2_
and your operational station software is assumed to be in
_/usr2/st-1.0.0_.  Make appropriate adjustments if they are different.

. Make sure the FS is not running.

. Enter the commands:
+
....
cd /usr2

rm control
rm proc

mv control-ops   control
mv proc-ops      proc
mv st-1.0.0-ops  st-1.0.0

ln -sfn st-1.0.0  st
ln -sfn fs-9.13.2 fs
....

. Reboot.

Your old test directories (named _*-test_) are left for possible future reference.

=== Disk space requirements

Please be sure that you have at least 50 MB of free space (use the
_df_ UNIX command to check free space) on your _/usr2_ partition
before starting the upgrade.  This would probably only be an issue for
stations with 200 MB disks.  If you are tight on space, you may want
to delete old log files and old versions of the FS (except your most
recent one if you can avoid it of course).  Since you should have
backed-up your system, you can even delete the _*.[oas]_ and
executable files of your old versions with no risk.  You might want to
keep the source of the previous versions around for reference if you
have room.  You can eliminate the non-source files by _cd_-ing to each
of the old FS directories in turn as _prog_ and executing:

  make rmdoto rmexe

as a shell command.  If you have any questions about how to do this,
please email Ed.

=== Set operations file permissions

It is recommended that your local files for operations (_control_, _proc_,
_log_, _sched_, _tle_files_ directories and their contents) have the default
ownership (`oper.rtx`) and permissions (for regular files `rw-rw-r-`,
for directories `rwxrwxr-x`).  To force this (however, this will not
change the "execute/search" permissions), please execute the script (as
_root_):

  /usr2/fs/misc/fix_perm

Answer `*y*` to the prompt if you wish to proceed.  It is a good idea to
do this, unless you have purposely changed the ownership and
permissions to some other values.  If you don't want to restore the
defaults, answer `*n*` (this is the last chance to abort the execution
of the script). If you don't have a _/usr2/tle_files_ directory,
you will get a message that there is no such directory.

=== Fix .prc file define lines

Sometimes due to errors (possibly caused during manual editing,
instead of using _pfmed_), the `define` statements in _.prc_ files can
be damaged.  This can lead to other problems including causing the
contents of procedures being logged every time they are executed
rather than just the first time they are used in a given log file.
You can use the utility, _/usr2/fs/misc/fix_define_, to fix this. You
can run it when the FS is _not active_ (as _oper_):

  cd /usr2/proc
  /usr2/fs/misc/fix_define -t *.prc

in _test_ mode to see if there any `define` statements that need to be
fixed.  If there are, they will be displayed.  If you choose to fix
them, you can re-run the second command above without the `-t` flag to
apply the fix.  An original of each _.prc_ file that is changed is
retained with an added _.bak_ extension.
