OBJECTS=\
fmpappend.o fmpclose.o fmpopen.o fmpposition.o fmppost.o fmppurge.o\
fmpreadstr.o fmprewind.o fmpsetline.o fmpsetpos.o fmpwritestr.o fmpread.o\
fmperror_standalone_set.o
fmpsee.a: $(OBJECTS)

include ../include.mk
