= Making man pages

. _asciidoctor_ version

.. Works pretty well with _asciidoctor_ 2.0.15 (Mac)

.. Does not work so well with _asciidoctor_ 1.5.4 (Debian Stretch)

. Uses _snapcmd.adoc_ as source

.. Reviewing the _.html_ and _man_ page output after making changes is
recommended to help locate issues.

.. Level two section is command name/description/equip

.. Level three sections: `Syntax`, `Response`, `Settable Parameters`,
`Monitor-only Parameters` (which is optional), and `Comments`.

.. Place a horizontal ruler, a page break, and four blank lines, at
the end of each command (and before the first):

+

----
---
<<<
{nbsp}
{nbsp}
{nbsp}
{nbsp}
----

+

The `---` makes a horizontal ruler so that the separation between
commands in the _.html_ is a little more prominent. It is filter out
by _adoc2help_ for the _man_ pages, but other horizontal ruler forms
(`- - -`,`+++***+++`,`* * *`) can still used if needed.

+

The `<<<` forces a page break when the _.html_ is printed to _.pdf_.

+

.. Syntax and Response use code blocks, with parameters italic

... Bold is very rare, if ever

... Bold italic is never used

... Each example syntax and response line is its own code block,
because _adoc2help_ converts these code blocks to regular text to
reduce indenting

.. Settable Parameters and Monitor-only parameters use tables with two columns, no grid or frame

... Those do not translate well to man pages, so _adoc2help_ converts these to description lists

... First cell in a row (parameter) are defined with `pass:[a| ]`{nbsp} at the start of each line

... Vertical bar separating first and second cells has spaces on each
side

... Second cell in a row are descriptions

... Second cell lines can end with a space followed by `+` to force
new-lines.

... Code blocks should not be used in these sections. If they are,
they are converted to regular text by _adoc2help_ (that could be
changed).

..  In general for inline (non-code block) fonts:

...  The only combined fonts are italics _or_ bold with monospace,
e.g, `pass:[`_a_`]` _or_ `pass:[`*a*`]`. These are converted by _adoc2help_ to
italics(underline)/bold since the _asciidoc_ `manpage` backend does
not support them (with monospace).

... Bold italics does not work correctly with the _asciidoc_ `manpage`
backend; _adoc2help_ converts bold italics to bold for safety.

... Monospace is converted to bold by _adoc2help_.

... Bold monospace should be avoided. It does not translate to _man_
pages as visually different from bold. However, it can be used if it
makes the HTML output better.

...  No unconstrained font settings, e.g., no `pass:[__a__b]`,
`pass:[**a**b]`, or `pass:[``a``b]`, except:

.... Monospace with constrained italics can be used if the entire
token is enclosed in double back ticks and the unconstrained italics
are at the end, e.g, `pass:[``lo__X__``]`. There may be only be one of
these per line of text (but additional ones can go on separate lines).
This is converted to bold _then_ italics (underline). It may be
possible to add more cases.

.. Equations

+

+

There is limited supported for equations using `latexmath`. There are
some further restrictions to make sure the _man_ page versions will be
acceptable:

... If the `\mathit{...}` command is used (helps with long variable
names), it must span the entire equation, e.g.,
`+++stem:[\mathit{...}]+++`. There should be no extra spaces between
the `[...]` and the `\mathit{...}`. The entire equation must be within
one line.

... The `\frac{...}{...}` command is translated to a slash `/` for the
_man_ page. The command must appear entirely on one line. It cannot be
nested because that won't translate to _man_ pages. It should work to
use slashes `/` in either or both of the numerator or denominator to
provide more levels, but this will sacrifice some readability in both
the _.html_ and _man_ page.

... Experimentation may be required for other LaTeX commands.

.. Internal cross references can be used. It is recommended that the
anchor text be italicized so that it will standout in the _man_ pages.
If the anchor text is the table title, the cross reference in the
.html will agree with the italics of the table title.

.. Tables translate to _man_ pages pretty well but spanning cells
don't seem to work. Consider putting a row spanning cell in a *NOTE*
after the table.

. _adoc2help_

.. Extracts  command description from main document

.. Generates _.adoc_ source for man page _troff_ source generation

... Adds required boiler plate

... Fixes up certain font/formatting issues for manpage output

.. Runs _asciidoctor_ on generated _.adoc_ source

.. Changes manual section to `FS` in _troff_ man page source

.. Removes intermediate files

. Man pages

.. Syntax and Response sections are considered code blocks

.. In general italics are replaced with underline.

.. man pages are all monospace, so for _.adoc_ source that is:

... Inline monospace -- is replaced with bold

... Monospace and italics/bold --  is converted to underline/bold
