LIBES = ../clib/clib.a ../rtelb/rtelb.a
#
class: class.o $(OBJECTS)
	cc  -o class class.o $(OBJECTS) $(LIBES)
	strip class
#
class2: class2.o $(OBJECTS)
	cc  -o class2 class2.o $(OBJECTS) $(LIBES)
	strip class2
#
class3: class3.o $(OBJECTS)
	cc  -o class3 class3.o $(OBJECTS) $(LIBES)
	strip class4
#
class4: class4.o $(OBJECTS)
	cc  -o class4 class4.o $(OBJECTS) $(LIBES)
	strip class4
#
